import type { APIRoute } from "astro";

export const GET: APIRoute = async () => {
  // 1. Fetch Firebase config from API
  let publicConfig: Record<string, string> = {};
  try {
    const response = await fetch("/api/v1/auth/firebase-config");
    if (response.ok) {
      const body = (await response.json()) as any;
      // API returns { success: true, data: { ...config } }
      publicConfig = body?.data || {};
    }
  } catch (e: unknown) {
    console.error("Error reading Firebase config from API for SW:", e);
  }

  // 2. Fallback to Env Vars
  if (!publicConfig.apiKey) {
    publicConfig = {
      apiKey: import.meta.env.PUBLIC_FIREBASE_API_KEY || "",
      authDomain: import.meta.env.PUBLIC_FIREBASE_AUTH_DOMAIN || "",
      projectId: import.meta.env.PUBLIC_FIREBASE_PROJECT_ID || "",
      storageBucket: import.meta.env.PUBLIC_FIREBASE_STORAGE_BUCKET || "",
      messagingSenderId:
        import.meta.env.PUBLIC_FIREBASE_MESSAGING_SENDER_ID || "",
      appId: import.meta.env.PUBLIC_FIREBASE_APP_ID || "",
      measurementId: import.meta.env.PUBLIC_FIREBASE_MEASUREMENT_ID || "",
    };
  }

  // 3. Construct the script
  const scriptContent = `// Firebase Cloud Messaging Service Worker
// Dynamically generated by /src/pages/firebase-messaging-sw.js.ts

importScripts("https://www.gstatic.com/firebasejs/9.15.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/9.15.0/firebase-messaging-compat.js");

const firebaseConfig = ${JSON.stringify(publicConfig, null, 2)};

firebase.initializeApp(firebaseConfig);

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  console.log("[firebase-messaging-sw.js] Received background message", payload);

  const notificationTitle = payload.data?.customerName
    ? \`\${payload.data.customerName} placed a new order\`
    : payload.notification?.title || "New Order Received";

  const notificationOptions = {
    body: payload.data?.orderId
      ? \`Order ID: \${payload.data.orderId}. Click to view.\`
      : payload.notification?.body || "A new order has been placed on your store.",
    icon: "/favicon.svg",
    badge: "/favicon.svg",
    tag: "order-notification",
    requireInteraction: true,
    data: {
      url: payload.data?.link || "/admin/orders",
    },
  };

  self.registration.showNotification(notificationTitle, notificationOptions);
});

self.addEventListener("notificationclick", (event) => {
  console.log("[firebase-messaging-sw.js] Notification click received.");
  event.notification.close();

  const urlToOpen = event.notification.data?.url || "/admin/orders";

  event.waitUntil(
    clients
      .matchAll({
        type: "window",
        includeUncontrolled: true,
      })
      .then((clientList) => {
        for (const client of clientList) {
          if (client.url.includes("/admin") && "focus" in client) {
            return client.focus();
          }
        }
        if (clients.openWindow) {
          return clients.openWindow(urlToOpen);
        }
      }),
  );
});
`;

  return new Response(scriptContent, {
    status: 200,
    headers: {
      "Content-Type": "application/javascript",
      "Cache-Control": "no-cache, no-store, must-revalidate",
    },
  });
};
