// Reviewed snapshot of the authenticated Admin OpenAPI surface. The drift test
// compares this inventory to the live contract so every capability change is deliberate.

export type AdminHttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export const ADMIN_OPENAPI_PATH_INVENTORY = [
  ["/api/v1/admin/abandoned-checkouts", ["GET", "DELETE"]],
  ["/api/v1/admin/abandoned-checkouts/bulk-delete", ["POST"]],
  ["/api/v1/admin/ai-context/batch-details", ["POST"]],
  ["/api/v1/admin/ai-prompts", ["GET"]],
  ["/api/v1/admin/ai/chat", ["POST"]],
  ["/api/v1/admin/ai/generate", ["POST"]],
  ["/api/v1/admin/ai/generate-staged", ["POST"]],
  ["/api/v1/admin/ai/models", ["GET"]],
  ["/api/v1/admin/analytics", ["GET", "POST"]],
  ["/api/v1/admin/analytics/{id}", ["GET", "PUT", "DELETE"]],
  ["/api/v1/admin/analytics/{id}/toggle", ["POST"]],
  ["/api/v1/admin/analytics/health", ["GET"]],
  ["/api/v1/admin/attributes", ["GET", "POST"]],
  ["/api/v1/admin/attributes/{id}", ["PUT", "DELETE"]],
  ["/api/v1/admin/attributes/{id}/permanent", ["DELETE"]],
  ["/api/v1/admin/attributes/{id}/restore", ["POST"]],
  ["/api/v1/admin/attributes/{id}/values", ["GET", "POST", "PUT", "DELETE"]],
  ["/api/v1/admin/attributes/bulk-delete", ["POST"]],
  ["/api/v1/admin/attributes/bulk-restore", ["POST"]],
  ["/api/v1/admin/auth/2fa/complete-verification", ["POST"]],
  ["/api/v1/admin/auth/2fa/info", ["GET"]],
  ["/api/v1/admin/auth/2fa/method", ["POST"]],
  ["/api/v1/admin/auth/2fa/verify", ["POST"]],
  ["/api/v1/admin/auth/account-security", ["GET"]],
  ["/api/v1/admin/auth/change-password", ["POST"]],
  ["/api/v1/admin/auth/update-profile", ["POST"]],
  ["/api/v1/admin/auth/users", ["GET", "POST"]],
  ["/api/v1/admin/auth/users/{id}", ["DELETE"]],
  ["/api/v1/admin/categories", ["GET", "POST"]],
  ["/api/v1/admin/categories/{id}", ["GET", "PUT", "DELETE"]],
  ["/api/v1/admin/categories/{id}/permanent", ["DELETE"]],
  ["/api/v1/admin/categories/{id}/restore", ["POST"]],
  ["/api/v1/admin/categories/bulk-delete", ["POST"]],
  ["/api/v1/admin/categories/bulk-restore", ["POST"]],
  ["/api/v1/admin/categories/form-options", ["GET"]],
  ["/api/v1/admin/collections", ["GET", "POST"]],
  ["/api/v1/admin/collections/{id}", ["GET", "PUT", "DELETE"]],
  ["/api/v1/admin/collections/{id}/permanent", ["DELETE"]],
  ["/api/v1/admin/collections/{id}/restore", ["POST"]],
  ["/api/v1/admin/collections/bulk-activate", ["POST"]],
  ["/api/v1/admin/collections/bulk-deactivate", ["POST"]],
  ["/api/v1/admin/collections/bulk-delete", ["POST"]],
  ["/api/v1/admin/collections/bulk-restore", ["POST"]],
  ["/api/v1/admin/collections/by-ids", ["GET"]],
  ["/api/v1/admin/collections/category-options", ["GET"]],
  ["/api/v1/admin/collections/form-options", ["GET"]],
  ["/api/v1/admin/collections/reorder", ["POST"]],
  ["/api/v1/admin/customers", ["GET", "POST"]],
  ["/api/v1/admin/customers/{id}", ["GET", "PUT", "DELETE"]],
  ["/api/v1/admin/customers/{id}/history", ["GET"]],
  ["/api/v1/admin/customers/{id}/permanent", ["DELETE"]],
  ["/api/v1/admin/customers/{id}/restore", ["POST"]],
  ["/api/v1/admin/customers/bulk-delete", ["POST"]],
  ["/api/v1/admin/customers/mcp-search", ["POST"]],
  ["/api/v1/admin/dashboard", ["GET"]],
  ["/api/v1/admin/dashboard/activity", ["GET"]],
  ["/api/v1/admin/dashboard/home-summary", ["GET"]],
  ["/api/v1/admin/dashboard/metrics-summary", ["GET"]],
  ["/api/v1/admin/dashboard/summary", ["GET"]],
  ["/api/v1/admin/discounts", ["GET", "POST"]],
  ["/api/v1/admin/discounts/{id}", ["GET", "PUT", "DELETE"]],
  ["/api/v1/admin/discounts/{id}/permanent", ["DELETE"]],
  ["/api/v1/admin/discounts/{id}/restore", ["POST"]],
  ["/api/v1/admin/discounts/{id}/toggle-status", ["POST"]],
  ["/api/v1/admin/discounts/bulk-delete", ["POST"]],
  ["/api/v1/admin/discounts/bulk-restore", ["POST"]],
  ["/api/v1/admin/fcm-token", ["POST"]],
  ["/api/v1/admin/fcm-token-cleanup", ["POST"]],
  ["/api/v1/admin/fraud-checker", ["GET", "POST", "PUT"]],
  ["/api/v1/admin/fraud-checker/{id}", ["DELETE"]],
  ["/api/v1/admin/fraud-checker/{id}/test", ["POST"]],
  ["/api/v1/admin/fraud-checker/lookup", ["POST"]],
  ["/api/v1/admin/inventory", ["GET"]],
  ["/api/v1/admin/inventory/{variantId}/adjust", ["POST"]],
  ["/api/v1/admin/inventory/alerts", ["GET", "PATCH"]],
  ["/api/v1/admin/inventory/scanner/lookup", ["GET"]],
  ["/api/v1/admin/inventory/stock-adjust", ["POST"]],
  ["/api/v1/admin/inventory/stock-set", ["POST"]],
  ["/api/v1/admin/media", ["GET"]],
  ["/api/v1/admin/media/{id}", ["PUT", "PATCH", "DELETE"]],
  ["/api/v1/admin/media/folders", ["GET", "POST"]],
  ["/api/v1/admin/media/folders/{id}", ["PUT", "DELETE"]],
  ["/api/v1/admin/media/move", ["POST"]],
  ["/api/v1/admin/media/upload", ["POST"]],
  ["/api/v1/admin/navigation", ["GET", "POST"]],
  ["/api/v1/admin/navigation/{id}", ["PUT", "DELETE"]],
  ["/api/v1/admin/navigation/items", ["GET"]],
  ["/api/v1/admin/navigation/preview-products", ["GET"]],
  ["/api/v1/admin/orders", ["GET", "POST"]],
  ["/api/v1/admin/orders/:id/invoice", ["GET"]],
  ["/api/v1/admin/orders/{id}", ["GET", "PUT", "DELETE"]],
  ["/api/v1/admin/orders/{id}/cod", ["GET", "POST"]],
  ["/api/v1/admin/orders/{id}/form-data", ["GET"]],
  ["/api/v1/admin/orders/{id}/fulfill", ["GET", "POST"]],
  ["/api/v1/admin/orders/{id}/fulfillment-status", ["PUT"]],
  ["/api/v1/admin/orders/{id}/items", ["GET"]],
  ["/api/v1/admin/orders/{id}/notifications", ["GET"]],
  ["/api/v1/admin/orders/{id}/notifications/{outboxId}/resend", ["POST"]],
  ["/api/v1/admin/orders/{id}/notifications/{outboxId}/retry", ["POST"]],
  ["/api/v1/admin/orders/{id}/payment-recovery-link", ["POST"]],
  ["/api/v1/admin/orders/{id}/payments", ["GET"]],
  ["/api/v1/admin/orders/{id}/permanent", ["DELETE"]],
  ["/api/v1/admin/orders/{id}/refund", ["POST"]],
  ["/api/v1/admin/orders/{id}/refund-attempts/{attemptId}/reconcile", ["POST"]],
  ["/api/v1/admin/orders/{id}/restore", ["POST"]],
  ["/api/v1/admin/orders/{id}/return", ["POST"]],
  ["/api/v1/admin/orders/{id}/shipments", ["GET", "POST"]],
  ["/api/v1/admin/orders/{id}/shipments/{shipmentId}", ["GET", "DELETE"]],
  ["/api/v1/admin/orders/{id}/shipments/{shipmentId}/reconcile", ["POST"]],
  ["/api/v1/admin/orders/{id}/shipments/{shipmentId}/refresh", ["POST"]],
  ["/api/v1/admin/orders/{id}/shipments/{shipmentId}/status", ["POST"]],
  ["/api/v1/admin/orders/{id}/status", ["PUT"]],
  ["/api/v1/admin/orders/{id}/support-requests/{requestId}/status", ["PUT"]],
  ["/api/v1/admin/orders/bulk-delete", ["POST"]],
  ["/api/v1/admin/orders/bulk-ship", ["POST"]],
  ["/api/v1/admin/orders/payment-recovery", ["GET"]],
  ["/api/v1/admin/orders/payment-recovery/export", ["GET"]],
  ["/api/v1/admin/pages", ["GET", "POST"]],
  ["/api/v1/admin/pages/{id}", ["GET", "PUT", "DELETE"]],
  ["/api/v1/admin/pages/{id}/permanent", ["DELETE"]],
  ["/api/v1/admin/pages/{id}/restore", ["POST"]],
  ["/api/v1/admin/pages/bulk-delete", ["POST"]],
  ["/api/v1/admin/pages/bulk-publish", ["POST"]],
  ["/api/v1/admin/pages/bulk-restore", ["POST"]],
  ["/api/v1/admin/pages/bulk-unpublish", ["POST"]],
  ["/api/v1/admin/products", ["GET", "POST"]],
  ["/api/v1/admin/products/{id}", ["GET", "PUT", "DELETE"]],
  ["/api/v1/admin/products/{id}/permanent", ["DELETE"]],
  ["/api/v1/admin/products/{id}/restore", ["POST"]],
  ["/api/v1/admin/products/{id}/variants", ["GET", "POST"]],
  ["/api/v1/admin/products/{id}/variants/{variantId}", ["PUT", "DELETE"]],
  ["/api/v1/admin/products/{id}/variants/{variantId}/duplicate", ["POST"]],
  ["/api/v1/admin/products/{id}/variants/bulk-create", ["POST"]],
  ["/api/v1/admin/products/{id}/variants/bulk-delete", ["POST"]],
  ["/api/v1/admin/products/{id}/variants/bulk-update", ["POST"]],
  ["/api/v1/admin/products/{id}/variants/sort-order", ["GET", "POST"]],
  ["/api/v1/admin/products/bulk-delete", ["POST"]],
  ["/api/v1/admin/products/by-ids", ["GET"]],
  ["/api/v1/admin/products/lookup-barcode", ["GET"]],
  ["/api/v1/admin/products/stats", ["GET"]],
  ["/api/v1/admin/rbac/my-permissions", ["GET"]],
  ["/api/v1/admin/rbac/permissions", ["GET"]],
  ["/api/v1/admin/rbac/roles", ["GET", "POST"]],
  ["/api/v1/admin/rbac/roles/{id}", ["GET", "PUT", "DELETE"]],
  ["/api/v1/admin/rbac/user-permissions", ["POST", "DELETE"]],
  ["/api/v1/admin/rbac/user-roles", ["POST", "DELETE"]],
  ["/api/v1/admin/search", ["GET"]],
  ["/api/v1/admin/search/reindex", ["POST"]],
  ["/api/v1/admin/settings/abandoned-checkouts", ["POST"]],
  ["/api/v1/admin/settings/abandoned-checkouts/cleanup", ["POST"]],
  ["/api/v1/admin/settings/allowed-countries", ["GET", "PUT"]],
  ["/api/v1/admin/settings/auth", ["GET", "POST"]],
  ["/api/v1/admin/settings/business", ["GET", "POST"]],
  ["/api/v1/admin/settings/checkout-languages", ["GET", "POST"]],
  ["/api/v1/admin/settings/checkout-languages/{id}", ["GET", "PUT", "PATCH", "DELETE"]],
  ["/api/v1/admin/settings/checkout-languages/{id}/restore", ["POST"]],
  ["/api/v1/admin/settings/checkout-languages/active", ["GET"]],
  ["/api/v1/admin/settings/checkout-readiness", ["GET"]],
  ["/api/v1/admin/settings/currency", ["GET", "POST"]],
  ["/api/v1/admin/settings/delivery-locations", ["GET", "POST", "DELETE"]],
  ["/api/v1/admin/settings/delivery-locations/{id}", ["GET", "PUT", "DELETE"]],
  ["/api/v1/admin/settings/delivery-locations/all", ["DELETE"]],
  ["/api/v1/admin/settings/delivery-providers", ["GET", "POST", "PUT"]],
  ["/api/v1/admin/settings/delivery-providers/{id}", ["GET", "POST", "DELETE"]],
  ["/api/v1/admin/settings/delivery-providers/create-test", ["POST"]],
  ["/api/v1/admin/settings/email", ["GET", "POST"]],
  ["/api/v1/admin/settings/firebase", ["GET", "POST"]],
  ["/api/v1/admin/settings/footer", ["POST"]],
  ["/api/v1/admin/settings/general", ["GET"]],
  ["/api/v1/admin/settings/header", ["POST"]],
  ["/api/v1/admin/settings/hero-sliders", ["GET", "POST"]],
  ["/api/v1/admin/settings/hero-sliders/{id}", ["GET", "PUT", "DELETE"]],
  ["/api/v1/admin/settings/mcp-summary", ["GET"]],
  ["/api/v1/admin/settings/media", ["GET", "POST"]],
  ["/api/v1/admin/settings/meta-conversions", ["GET", "POST"]],
  ["/api/v1/admin/settings/meta-conversions/logs", ["GET", "POST", "DELETE"]],
  ["/api/v1/admin/settings/notification-channels", ["GET", "PUT"]],
  ["/api/v1/admin/settings/notification-channels/admin-channels", ["GET", "PUT"]],
  ["/api/v1/admin/settings/notification-channels/mcp-summary", ["GET"]],
  ["/api/v1/admin/settings/payment-methods", ["GET", "POST"]],
  ["/api/v1/admin/settings/polar", ["GET", "POST"]],
  ["/api/v1/admin/settings/security", ["GET", "POST"]],
  ["/api/v1/admin/settings/seo", ["GET", "POST"]],
  ["/api/v1/admin/settings/seo/feed-diagnostics", ["GET"]],
  ["/api/v1/admin/settings/shipping-methods", ["GET", "POST"]],
  ["/api/v1/admin/settings/shipping-methods/{id}", ["GET", "PUT", "DELETE"]],
  ["/api/v1/admin/settings/shipping-methods/{id}/permanent-delete", ["DELETE"]],
  ["/api/v1/admin/settings/shipping-methods/{id}/restore", ["POST"]],
  ["/api/v1/admin/settings/sms", ["GET", "POST"]],
  ["/api/v1/admin/settings/sslcommerz", ["GET", "POST"]],
  ["/api/v1/admin/settings/storefront-url", ["GET", "POST"]],
  ["/api/v1/admin/settings/stripe", ["GET", "POST"]],
  ["/api/v1/admin/settings/theme", ["GET", "POST"]],
  ["/api/v1/admin/settings/widget-ai", ["GET", "POST"]],
  ["/api/v1/admin/shipments/{id}", ["GET", "DELETE"]],
  ["/api/v1/admin/shipments/{id}/check-status", ["POST"]],
  ["/api/v1/admin/widgets", ["GET", "POST"]],
  ["/api/v1/admin/widgets/{id}", ["GET", "PUT", "DELETE"]],
  ["/api/v1/admin/widgets/{id}/history", ["GET", "POST"]],
  ["/api/v1/admin/widgets/{id}/history/{versionId}", ["DELETE"]],
  ["/api/v1/admin/widgets/{id}/history/restore", ["POST"]],
  ["/api/v1/admin/widgets/{id}/permanent", ["DELETE"]],
  ["/api/v1/admin/widgets/{id}/restore", ["POST"]],
  ["/api/v1/admin/widgets/{id}/toggle-status", ["PATCH"]],
  ["/api/v1/admin/widgets/bulk-activate", ["POST"]],
  ["/api/v1/admin/widgets/bulk-deactivate", ["POST"]],
  ["/api/v1/admin/widgets/bulk-delete", ["POST"]],
  ["/api/v1/admin/widgets/bulk-restore", ["POST"]],
  ["/api/v1/admin/widgets/placement-targets", ["GET"]],
] as const satisfies readonly (readonly [string, readonly AdminHttpMethod[]])[];

export const ADMIN_OPENAPI_PATH_COUNT = 209;
export const ADMIN_OPENAPI_OPERATION_COUNT = 306;
