/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./src/env.d.ts` (hash: d147e1a709498f42b631dfa4abe9dabb)
interface __BaseEnv_Env {
	AGENT_NAME: "scalius-admin-agent";
	AGENT_VERSION: "0.1.0";
	ADMIN_CONVERSATIONS: DurableObjectNamespace<import("./worker").AdminConversationDurableObject>;
	API: Fetcher /* scalius-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "AdminConversationDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AGENT_NAME" | "AGENT_VERSION">> {}
}
