/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./src/env.d.ts` (hash: ef0cbd4c4c49b6828ced65e20e8c6108)
interface __BaseEnv_Env {
	STOREFRONT_URL: "https://storefront.scalius.com";
	AGENT_PROFILE_URL: "https://agent.scalius.com/.well-known/ucp";
	AGENT_NAME: "scalius-storefront-catalog-agent";
	AGENT_VERSION: "0.1.0";
	STOREFRONT_CONVERSATIONS: DurableObjectNamespace<import("./worker").StorefrontConversationDurableObject>;
	API: Fetcher /* scalius-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "StorefrontConversationDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "STOREFRONT_URL" | "AGENT_PROFILE_URL" | "AGENT_NAME" | "AGENT_VERSION">> {}
}
