// Agent operation registry rows for the dashboard content, media, navigation, hero and theme routes.
import type { OperationRegistryEntry } from "./entry";

export const DASHBOARD_CONTENT_OPERATIONS = {
  "dashboard.content.bulk_delete": {
    risk: "destructive",
    revision: "required",
    limits: { response: 16_384 },
  },
  "dashboard.content.bulk_publish": {
    revision: "required",
    limits: { response: 16_384 },
  },
  "dashboard.content.bulk_restore": {
    revision: "required",
    limits: { response: 16_384 },
  },
  "dashboard.content.bulk_unpublish": {
    revision: "required",
    limits: { response: 16_384 },
  },
  "dashboard.content.create": {},
  "dashboard.content.get": {},
  "dashboard.content.list": {},
  "dashboard.content.permanently_delete": {
    risk: "destructive",
    revision: "required",
    limits: { response: 16_384 },
  },
  "dashboard.content.restore": {
    revision: "required",
    limits: { response: 16_384 },
  },
  "dashboard.content.trash": {
    risk: "destructive",
    revision: "required",
    limits: { response: 16_384 },
  },
  "dashboard.content.update": { revision: "required" },
  "dashboard.hero_sliders.create": {},
  "dashboard.hero_sliders.get": {},
  "dashboard.hero_sliders.list": {},
  "dashboard.hero_sliders.trash": {
    risk: "destructive",
    revision: "required",
    limits: { response: 16_384 },
  },
  "dashboard.hero_sliders.update": { revision: "required" },
  "dashboard.media_folders.create": {},
  "dashboard.media_folders.delete": {
    risk: "destructive",
    revision: "required",
    limits: { response: 16_384 },
  },
  "dashboard.media_folders.list": {},
  "dashboard.media_folders.update": { revision: "required" },
  "dashboard.media.import_url": {
    openWorld: true,
    batch: "forbidden",
  },
  "dashboard.media.list": {},
  "dashboard.media.move": { revision: "required" },
  "dashboard.media.original": {
    exposure: "excluded",
    reason: "Binary original read for the dashboard's browser rendition pipeline; agents use the public media URL.",
  },
  "dashboard.media.permanently_delete": {
    risk: "destructive",
    revision: "required",
    limits: { response: 16_384 },
  },
  "dashboard.media.restore": { revision: "required" },
  "dashboard.media.trash": {
    risk: "destructive",
    revision: "required",
    limits: { response: 16_384 },
  },
  "dashboard.media.update": { revision: "required" },
  "dashboard.media.usage": {},
  "dashboard.media.upload_abort": { limits: { response: 16_384 } },
  "dashboard.media.upload_complete": {},
  "dashboard.media.upload_get": { limits: { response: 16_384 } },
  "dashboard.media.upload_initiate": { limits: { response: 16_384 } },
  "dashboard.media.upload_part": {
    batch: "forbidden",
    transport: "octet-stream",
    limits: { request: 5_242_880, response: 16_384 },
    clientAction: "direct-upload",
  },
  "dashboard.media.upload_reconcile": {
    exposure: "excluded",
    reason: "Internal expired-upload maintenance is not a merchant capability.",
  },
  "dashboard.media.variants_save": {
    exposure: "excluded",
    reason: "Browser-generated renditions from the dashboard; agent uploads get server-generated renditions at completion.",
  },
  "dashboard.navigation.authority_shadow": {
    exposure: "excluded",
    reason: "Internal normalized-authority migration parity report.",
  },
  "dashboard.navigation.items_create": { revision: "required" },
  "dashboard.navigation.items_delete": {
    risk: "destructive",
    revision: "required",
    limits: { response: 16_384 },
  },
  "dashboard.navigation.items_get": {},
  "dashboard.navigation.items_list": {},
  "dashboard.navigation.items_move": { revision: "required" },
  "dashboard.navigation.items_move_options": {},
  "dashboard.navigation.items_search": {},
  "dashboard.navigation.items_update": { revision: "required" },
  "dashboard.navigation.legacy_items_list": {
    exposure: "excluded",
    reason: "Superseded by normalized reusable-menu and item operations.",
  },
  "dashboard.navigation.menus_create": {},
  "dashboard.navigation.menus_get": {},
  "dashboard.navigation.menus_list": {},
  "dashboard.navigation.menus_publish": { revision: "required" },
  "dashboard.navigation.menus_restore": { revision: "required" },
  "dashboard.navigation.menus_rollback": { revision: "required" },
  "dashboard.navigation.menus_trash": {
    risk: "destructive",
    revision: "required",
    limits: { response: 16_384 },
  },
  "dashboard.navigation.menus_update": { revision: "required" },
  "dashboard.navigation.placements_list": {},
  "dashboard.navigation.placements_manifest": {},
  "dashboard.navigation.placements_save": { revision: "required" },
  "dashboard.navigation.products_preview_count": { limits: { response: 16_384 } },
  "dashboard.navigation.publications_list": {},
  "dashboard.navigation.resources_search": {},
  "dashboard.theme.draft_rebase": { revision: "required" },
  "dashboard.theme.draft_save": { revision: "required" },
  "dashboard.theme.get": {},
  "dashboard.theme.preview_session_create": {
    exposure: "continuation",
    risk: "read",
    transport: "continuation",
    limits: { request: 65_536, response: 8_192 },
    sensitive: true,
    continuation: {
      method: "POST",
      urlJsonPointer: "/data/continuation/url",
      fieldsJsonPointer: "/data/continuation/fields",
      sensitiveFields: ["continuationCode"],
    },
  },
  "dashboard.theme.publish": { revision: "required" },
  "dashboard.theme.rollback": { revision: "required" },
  "dashboard.theme.save_legacy": {
    exposure: "excluded",
    reason: "Superseded by durable draft, preview, publish, version, and rollback workflow.",
  },
  "dashboard.theme.versions_list": {},
  "dashboard.theme.workspace_get": {},
} satisfies Record<string, OperationRegistryEntry>;
