// Agent operation registry rows for the dashboard settings routes.
import type { OperationRegistryEntry } from "./entry";

export const DASHBOARD_SETTINGS_OPERATIONS = {
  "dashboard.cache.purge_all": { limits: { request: 16_384, response: 8_192 } },
  "dashboard.checkout_languages.active_get": {},
  "dashboard.checkout_languages.create": { limits: { request: 65_536, response: 16_384 } },
  "dashboard.checkout_languages.delete_permanently": {
    risk: "destructive",
    batch: "forbidden",
    limits: { request: 16_384, response: 8_192 },
  },
  "dashboard.checkout_languages.get": { limits: { request: 16_384, response: 16_384 } },
  "dashboard.checkout_languages.list": { limits: { request: 16_384 } },
  "dashboard.checkout_languages.restore": { limits: { request: 16_384, response: 8_192 } },
  "dashboard.checkout_languages.trash": {
    risk: "destructive",
    limits: { request: 16_384, response: 8_192 },
  },
  "dashboard.checkout_languages.update": { revision: "required", limits: { request: 65_536, response: 16_384 } },
  "dashboard.checkout.flow_get": {},
  "dashboard.checkout.flow_update": { revision: "required" },
  "dashboard.checkout.readiness_get": {},
  "dashboard.customer_requests.policy_get": {},
  "dashboard.customer_requests.policy_update": { revision: "required" },
  "dashboard.delivery_locations.bulk_delete": {
    risk: "destructive",
    batch: "forbidden",
  },
  "dashboard.delivery_locations.create": {},
  "dashboard.delivery_locations.delete_all": {
    risk: "destructive",
    batch: "forbidden",
  },
  "dashboard.delivery_locations.get": {},
  "dashboard.delivery_locations.list": {},
  "dashboard.delivery_locations.pathao_import_chunk": {
    openWorld: true,
    batch: "forbidden",
  },
  "dashboard.delivery_locations.pathao_import_reset": { batch: "forbidden" },
  "dashboard.delivery_locations.pathao_import_status": {},
  "dashboard.delivery_locations.trash": { risk: "destructive" },
  "dashboard.delivery_locations.update": {},
  "dashboard.delivery_providers.create": {
    risk: "security",
    batch: "forbidden",
    limits: { response: 16_384 },
  },
  "dashboard.delivery_providers.delete": {
    risk: "destructive",
    limits: { response: 16_384 },
  },
  "dashboard.delivery_providers.get": { limits: { response: 16_384 } },
  "dashboard.delivery_providers.list": {},
  "dashboard.delivery_providers.test": {
    risk: "security",
    openWorld: true,
    batch: "forbidden",
    limits: { response: 16_384 },
  },
  "dashboard.delivery_providers.test_credentials": {
    risk: "security",
    openWorld: true,
    batch: "forbidden",
    limits: { response: 16_384 },
  },
  "dashboard.delivery_providers.update": {
    risk: "security",
    batch: "forbidden",
    limits: { response: 16_384 },
  },
  "dashboard.fraud_lookup.run": {
    risk: "read",
    openWorld: true,
    batch: "forbidden",
    limits: { response: 16_384 },
  },
  "dashboard.fraud_providers.create": {
    risk: "security",
    batch: "forbidden",
    limits: { response: 16_384 },
  },
  "dashboard.fraud_providers.delete": {
    risk: "destructive",
    limits: { response: 16_384 },
  },
  "dashboard.fraud_providers.list": {},
  "dashboard.fraud_providers.test": {
    risk: "security",
    openWorld: true,
    batch: "forbidden",
    limits: { response: 16_384 },
  },
  "dashboard.fraud_providers.update": {
    risk: "security",
    batch: "forbidden",
    limits: { response: 16_384 },
  },
  "dashboard.notifications.admin_rules_update": { revision: "required" },
  "dashboard.notifications.customer_rules_get": {},
  "dashboard.notifications.customer_rules_update": { revision: "required" },
  "dashboard.notifications.fcm_device_register": {
    exposure: "device",
    risk: "security",
    limits: { request: 16_384, response: 8_192 },
  },
  "dashboard.notifications.fcm_token_cleanup": {
    exposure: "excluded",
    risk: "destructive",
    limits: { request: 65_536, response: 8_192 },
    reason:
      "Provider-delivery maintenance consumes raw FCM registration tokens and deactivates stale device rows; sends already deactivate provider-invalid tokens automatically, so this is not a merchant agent capability.",
  },
  "dashboard.notifications.firebase_get": {},
  "dashboard.notifications.firebase_update": {
    revision: "required",
    risk: "security",
    batch: "forbidden",
  },
  "dashboard.notifications.template_test_send": { openWorld: true, batch: "forbidden" },
  "dashboard.notifications.templates_get": {},
  "dashboard.notifications.templates_update": { revision: "required" },
  "dashboard.payments.methods_get": {},
  "dashboard.payments.methods_update": { revision: "required" },
  "dashboard.payments.sslcommerz_get": {},
  "dashboard.payments.sslcommerz_remove": {
    revision: "required",
    risk: "destructive",
    batch: "forbidden",
  },
  "dashboard.payments.sslcommerz_update": {
    revision: "required",
    risk: "security",
    batch: "forbidden",
  },
  "dashboard.payments.stripe_get": {},
  "dashboard.payments.stripe_remove": {
    revision: "required",
    risk: "destructive",
    batch: "forbidden",
  },
  "dashboard.payments.stripe_update": {
    revision: "required",
    risk: "security",
    batch: "forbidden",
  },
  "dashboard.policies.get": {},
  "dashboard.policies.update": { revision: "required" },
  "dashboard.seo.feed_diagnostics": { limits: { request: 16_384 } },
  "dashboard.seo.feed_row_preview": {
    batch: "sequential",
    limits: { request: 16_384, response: 47_104 },
  },
  "dashboard.seo.live_probe": {
    openWorld: true,
    batch: "sequential",
    limits: { request: 16_384 },
  },
  "dashboard.seo.settings_get": { limits: { request: 16_384 } },
  "dashboard.seo.settings_update": { revision: "required", limits: { request: 65_536, response: 16_384 } },
  "dashboard.settings_abandoned_checkouts_cleanup.cleanup": {
    exposure: "excluded",
    risk: "destructive",
    limits: { response: 8_192 },
    reason:
      "Legacy dashboard-prefix mount of the service-authenticated post-order housekeeping callback; use explicit merchant deletion or scheduled retention cleanup.",
  },
  "dashboard.settings_abandoned_checkouts.abandoned_checkouts": {
    exposure: "excluded",
    limits: { response: 8_192 },
    reason:
      "Legacy dashboard-prefix mount of storefront abandoned-checkout snapshot persistence; no merchant UI invokes it, and agents must use protected context and cart operations rather than manufacture browser recovery snapshots.",
  },
  "dashboard.settings_footer.footer": {
    revision: "required",
    limits: { request: 65_536, response: 8_192 },
  },
  "dashboard.settings_footer.get_footer": { limits: { request: 16_384 } },
  "dashboard.settings_header.get_header": { limits: { request: 16_384 } },
  "dashboard.settings_header.header": {
    revision: "required",
    limits: { request: 65_536, response: 8_192 },
  },
  "dashboard.settings_homepage_presentation.get_homepage_presentation": { limits: { request: 16_384, response: 8_192 } },
  "dashboard.settings_homepage_presentation.homepage_presentation": {
    revision: "required",
    limits: { request: 16_384, response: 8_192 },
  },
  "dashboard.settings_sms.get_sms": {
    risk: "security",
    limits: { request: 16_384, response: 8_192 },
  },
  "dashboard.settings_sms.sms": {
    risk: "security",
    revision: "required",
    limits: { request: 16_384, response: 8_192 },
  },
  "dashboard.settings.business_get": { limits: { request: 16_384, response: 16_384 } },
  "dashboard.settings.business_update": { revision: "required", limits: { request: 16_384, response: 8_192 } },
  "dashboard.settings.currency_get": { limits: { request: 16_384, response: 8_192 } },
  "dashboard.settings.currency_update": { revision: "required", limits: { request: 16_384, response: 8_192 } },
  "dashboard.settings.customer_auth_get": {
    risk: "security",
    limits: { request: 16_384, response: 8_192 },
  },
  "dashboard.settings.customer_auth_update": {
    revision: "required",
    risk: "security",
    limits: { request: 16_384, response: 8_192 },
  },
  "dashboard.settings.customer_countries_get": { limits: { request: 16_384, response: 16_384 } },
  "dashboard.settings.customer_countries_update": { revision: "required", limits: { request: 16_384, response: 8_192 } },
  "dashboard.settings.email_get": {
    risk: "security",
    limits: { request: 16_384, response: 8_192 },
  },
  "dashboard.settings.email_update": {
    revision: "required",
    risk: "security",
    limits: { request: 16_384, response: 8_192 },
  },
  "dashboard.settings.general_get": {
    exposure: "excluded",
    limits: { request: 16_384 },
    reason:
      "Legacy aggregate of independently managed header and footer documents; excluded until those documents are exposed as bounded semantic read projections.",
  },
  "dashboard.settings.media_delivery_get": { limits: { request: 16_384, response: 16_384 } },
  "dashboard.settings.media_delivery_update": { revision: "required", limits: { request: 16_384, response: 16_384 } },
  "dashboard.settings.platform_get": { limits: { request: 16_384, response: 16_384 } },
  "dashboard.settings.platform_update": { revision: "required", limits: { request: 16_384, response: 16_384 } },
  "dashboard.settings.storefront_url_get": { limits: { request: 16_384, response: 8_192 } },
  "dashboard.settings.storefront_url_update": { revision: "required", limits: { request: 16_384, response: 8_192 } },
  "dashboard.shipping_methods.list": {},
  "dashboard.shipping_zones.apply_template": { revision: "required", batch: "forbidden" },
  "dashboard.shipping_zones.create": {},
  "dashboard.shipping_zones.delete": { risk: "destructive" },
  "dashboard.shipping_zones.everywhere_else_update": { revision: "required" },
  "dashboard.shipping_zones.update": { revision: "required" },
  "dashboard.taxes.classes_create": {},
  "dashboard.taxes.classes_delete": {
    risk: "destructive",
    revision: "required",
  },
  "dashboard.taxes.classes_list": {},
  "dashboard.taxes.classes_update": { revision: "required" },
  "dashboard.taxes.classifications_list": {},
  "dashboard.taxes.classifications_update": { revision: "required" },
  "dashboard.taxes.configuration_get": {
    exposure: "excluded",
    reason:
      "Legacy aggregate can exceed the 65,536-byte structured-result ceiling because it returns every active jurisdiction; use dashboard.taxes.settings_get, dashboard.taxes.classes_list, dashboard.taxes.rates_list, and dashboard.taxes.jurisdictions_list.",
  },
  "dashboard.taxes.jurisdictions_list": {},
  "dashboard.taxes.preview": { risk: "read" },
  "dashboard.taxes.rates_create": {},
  "dashboard.taxes.rates_delete": {
    risk: "destructive",
    revision: "required",
  },
  "dashboard.taxes.rates_list": {},
  "dashboard.taxes.rates_update": { revision: "required" },
  "dashboard.taxes.settings_get": {},
  "dashboard.taxes.settings_update": { revision: "required" },
} satisfies Record<string, OperationRegistryEntry>;
