/**
 * Generates migration 0091_catalogue_projection_fill (D1/Turso SQL and its
 * PostgreSQL sidecar) from `catalogProjectionFillStatements`, the same
 * statement builders every product, SKU and stock write appends to its batch.
 * The checked-in files must equal this output
 * (catalog-projection-fill.d1.test.ts), so the fill never becomes a second
 * copy of the projection rules.
 *
 *   pnpm --filter @scalius/core exec tsx scripts/catalog-projection-fill.ts --write
 */
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { drizzle } from "drizzle-orm/sqlite-proxy";
import * as schema from "../../database/src/schema";
import type { Database } from "../../database/src/types";
import { compileSqliteStatementForPostgres } from "../../database/src/postgres-sqlite-profile";
import { catalogProjectionFillStatements } from "../src/modules/products/catalog-projections";

export const CATALOG_PROJECTION_FILL_MIGRATION = {
    version: 91,
    name: "0091_catalogue_projection_fill",
} as const;

const BREAKPOINT = "--> statement-breakpoint";

const HEADER = `-- Fills the catalogue projections that 0090 created (product_facet_values,
-- product_buyer_state) for every product, so listings, the sitemap and brand
-- pages read a complete buyer state the moment the API that reads them goes
-- live: no empty window, no staff action. Generated by
-- packages/core/scripts/catalog-projection-fill.ts from
-- catalogProjectionFillStatements, the builders every product, SKU and stock
-- write appends to its batch (a test keeps this file equal to that output).
-- Idempotent: the facet rows are replaced and the buyer state is upserted.`;

/** A bound value as a SQL literal (the fill binds only strings and integers). */
function literal(value: unknown): string {
    if (value === null || value === undefined) return "NULL";
    if (typeof value === "number" && Number.isFinite(value)) return String(value);
    if (typeof value === "boolean") return value ? "1" : "0";
    if (typeof value === "string") return `'${value.replaceAll("'", "''")}'`;
    throw new Error(`Cannot inline a ${typeof value} into the fill migration.`);
}

/** Replaces each `?` outside string literals and quoted identifiers with its value. */
function inlineParameters(text: string, params: readonly unknown[]): string {
    let output = "";
    let quote: "'" | "\"" | "`" | null = null;
    let index = 0;
    for (const character of text) {
        if (quote) {
            if (character === quote) quote = null;
            output += character;
        } else if (character === "'" || character === "\"" || character === "`") {
            quote = character;
            output += character;
        } else if (character === "?") {
            if (index >= params.length) throw new Error("More placeholders than parameters.");
            output += literal(params[index++]);
        } else {
            output += character;
        }
    }
    if (index !== params.length) throw new Error("More parameters than placeholders.");
    return output;
}

/** The fill statements as plain SQLite SQL with every parameter inlined. */
export function catalogProjectionFillSql(): string[] {
    const db = drizzle(async () => ({ rows: [] }), { schema }) as unknown as Database;
    return catalogProjectionFillStatements(db).map((statement) => {
        const { sql: text, params } = (statement as unknown as { toSQL(): { sql: string; params: unknown[] } }).toSQL();
        return inlineParameters(text, params).replace(/\s+$/, "");
    });
}

function sourceSha256(statements: readonly string[]): string {
    return createHash("sha256").update(`${statements.join(`\n${BREAKPOINT}\n`)}\n`).digest("hex");
}

/** Both migration files, byte for byte. */
export function renderCatalogProjectionFillMigration(): { sqlite: string; postgres: string } {
    const fill = catalogProjectionFillSql();
    const sqliteStatements = fill.map((statement, index) => `${index === 0 ? `${HEADER}\n` : ""}${statement};`);
    const sha = sourceSha256(sqliteStatements);
    const { version, name } = CATALOG_PROJECTION_FILL_MIGRATION;
    const sqlite = [
        ...sqliteStatements,
        `INSERT INTO \`scalius_schema_migrations\` (\`version\`, \`name\`, \`source_sha256\`) VALUES (${version}, '${name}', '${sha}');`,
    ].join(`\n${BREAKPOINT}\n`) + "\n";
    const postgres = [
        ...fill.map((statement, index) =>
            `${index === 0 ? `${HEADER}\n` : ""}${compileSqliteStatementForPostgres(statement, 0).sql};`),
        `INSERT INTO "scalius_schema_migrations" ("version", "name", "source_sha256") VALUES (${version}, '${name}', '${sha}');`,
    ].join(`\n${BREAKPOINT}\n`) + "\n";
    return { sqlite, postgres };
}

export const CATALOG_PROJECTION_FILL_PATHS = {
    sqlite: fileURLToPath(new URL(`../../database/migrations/${CATALOG_PROJECTION_FILL_MIGRATION.name}.sql`, import.meta.url)),
    postgres: fileURLToPath(new URL(`../../database/migrations/postgres/${CATALOG_PROJECTION_FILL_MIGRATION.name}.sql`, import.meta.url)),
};

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
    if (!process.argv.includes("--write")) {
        console.error("Usage: tsx scripts/catalog-projection-fill.ts --write");
        process.exit(1);
    }
    const rendered = renderCatalogProjectionFillMigration();
    writeFileSync(CATALOG_PROJECTION_FILL_PATHS.sqlite, rendered.sqlite);
    writeFileSync(CATALOG_PROJECTION_FILL_PATHS.postgres, rendered.postgres);
    console.log(`Wrote ${CATALOG_PROJECTION_FILL_MIGRATION.name} (D1/Turso and PostgreSQL).`);
}
