import {
  AGENT_PRODUCT_CONSTRUCTION_RULES,
  type AgentWorkflowCard,
  type AgentWorkflowStepPolicies,
} from "./types";

const readPolicies: AgentWorkflowStepPolicies = {
  revision: "none",
  idempotency: "none",
  confirmation: "none",
  stopConditions: ["Stop on auth/read failure."],
  nonInferenceRules: ["Treat missing data as unknown."],
};

const createPolicies: AgentWorkflowStepPolicies = {
  revision: "none",
  idempotency: "none",
  confirmation: "required",
  stopConditions: ["Stop on conflict or uncertain write; reread."],
  nonInferenceRules: ["Use resolved or merchant facts only."],
};

export const OPTIONED_PRODUCT_WORKFLOW: AgentWorkflowCard = {
  id: "catalog.optioned-product.v1",
  surface: "dashboard",
  title: "Create a configurable product",
  summary: "Resolve, atomically create, publish, and verify an exact option/SKU matrix.",
  examples: [
    "Create a Size × Color T-shirt and verify SKU, image, stock, and discovery truth.",
  ],
  tags: ["catalog", "media", "variants"],
  constructionRules: AGENT_PRODUCT_CONSTRUCTION_RULES,
  requiredFacts: [
    {
      id: "productSpec",
      title: "Product facts",
      description: "Name, slug, rich text, price, SEO, condition, visibility.",
      required: true,
      source: { kind: "merchant" },
      nonInferenceRule: "Never invent claims, brand, price, condition, or copy.",
    },
    {
      id: "categoryId",
      title: "Resolved category",
      description: "Existing category ID or conditional-create result.",
      required: true,
      source: {
        kind: "operation",
        operationId: "dashboard.categories.form_options",
        responsePointer: "/data/categories",
        alternatives: [
          { operationId: "dashboard.categories.create", responsePointer: "/data/id" },
        ],
      },
      nonInferenceRule: "Resolve by name; never guess or substitute an ID.",
    },
    {
      id: "attributeAssignments",
      title: "Attributes",
      description: "Active IDs and truthful merchant values.",
      required: true,
      source: {
        kind: "operation",
        operationId: "dashboard.attributes.list_summaries",
        responsePointer: "/data/attributes",
      },
      nonInferenceRule: "Never duplicate or fabricate attributes.",
    },
    {
      id: "mediaSources",
      title: "Usable media sources",
      description: "Primary and secondary public URLs or client-readable files.",
      required: true,
      source: { kind: "merchant" },
      nonInferenceRule: "Only committed assets are media authority.",
    },
    {
      id: "optionMatrix",
      title: "Exact option matrix",
      description: "Ordered axes/values and complete SKU price, stock, and pmed image rows.",
      required: true,
      source: { kind: "merchant" },
      nonInferenceRule: "Never add, omit, collapse, or reorder combinations.",
    },
  ],
  phases: [
    {
      id: "resolve",
      surface: "dashboard",
      title: "Resolve identities and policy",
      summary: "Use bounded reads once before constructing any mutation.",
      dependsOn: [],
      stopConditions: ["Stop on ambiguity, collision, missing facts, or grants."],
      steps: [
        {
          id: "categories",
          title: "Resolve category options",
          operationId: "dashboard.categories.form_options",
          mutation: "read",
          input: { template: {}, dependencies: [], defaults: [] },
          policies: readPolicies,
        },
        {
          id: "attributes",
          title: "Resolve attribute summaries",
          operationId: "dashboard.attributes.list_summaries",
          mutation: "read",
          condition: "Repeat only for requested attribute names.",
          input: {
            template: { query: { page: 1, limit: 20, search: null } },
            dependencies: [],
            defaults: [
              { templatePointer: "/query/page", value: 1 },
              { templatePointer: "/query/limit", value: 20 },
            ],
          },
          policies: readPolicies,
        },
        {
          id: "seo",
          title: "Read discovery settings",
          operationId: "dashboard.seo.settings_get",
          mutation: "read",
          input: { template: {}, dependencies: [], defaults: [] },
          policies: readPolicies,
        },
        {
          id: "productCollision",
          title: "Check product slug and name",
          operationId: "dashboard.products.list_summaries",
          mutation: "read",
          input: {
            template: { query: { page: 1, limit: 10, search: null } },
            dependencies: [
              {
                templatePointer: "/query/search",
                source: { kind: "fact", factId: "productSpec", factPointer: "/name" },
              },
            ],
            defaults: [
              { templatePointer: "/query/page", value: 1 },
              { templatePointer: "/query/limit", value: 10 },
            ],
          },
          policies: readPolicies,
        },
        {
          id: "skuCollision",
          title: "Check active SKU namespace",
          operationId: "dashboard.inventory.list",
          mutation: "read",
          input: {
            template: { query: { section: "variants", search: null, status: "all", page: 1, limit: 100 } },
            dependencies: [
              {
                templatePointer: "/query/search",
                source: { kind: "fact", factId: "optionMatrix", factPointer: "/skuPrefix" },
              },
            ],
            defaults: [
              { templatePointer: "/query/page", value: 1 },
              { templatePointer: "/query/limit", value: 100 },
            ],
          },
          policies: readPolicies,
        },
      ],
    },
    {
      id: "prepare",
      surface: "dashboard",
      title: "Create missing prerequisites",
      summary: "Create missing prerequisites and only approved discovery fields.",
      dependsOn: ["resolve"],
      stopConditions: ["On concurrent create, reread; never duplicate."],
      steps: [
        {
          id: "categoryCreate",
          title: "Create draft category",
          operationId: "dashboard.categories.create",
          mutation: "create",
          condition: "Only when no unambiguous reusable category exists.",
          input: {
            template: { body: { name: null, slug: null, description: null, metaTitle: null, metaDescription: null, image: null } },
            dependencies: [],
            defaults: [],
          },
          policies: createPolicies,
        },
        {
          id: "attributeCreate",
          title: "Create missing attribute",
          operationId: "dashboard.attributes.create",
          mutation: "create",
          condition: "Repeat for each approved missing attribute.",
          input: {
            template: { body: { name: null, slug: null, filterable: true, options: [] } },
            dependencies: [],
            defaults: [{ templatePointer: "/body/filterable", value: true }],
          },
          policies: createPolicies,
        },
        {
          id: "discoveryUpdate",
          title: "Enable requested discovery fields",
          operationId: "dashboard.seo.settings_update",
          mutation: "partial",
          condition: "Only after explicit store-wide approval.",
          input: { template: { body: { discovery: {} } }, dependencies: [], defaults: [] },
          policies: createPolicies,
        },
      ],
    },
    {
      id: "media",
      surface: "dashboard",
      title: "Commit product media",
      summary: "Import each source and retain its committed media ID.",
      dependsOn: ["resolve"],
      stopConditions: ["Stop on inaccessible, invalid, or oversized media."],
      steps: [
        {
          id: "primary",
          title: "Import primary media",
          operationId: "dashboard.media.import_url",
          mutation: "create",
          condition: "Use the reviewed direct-upload client action for a local file.",
          input: {
            template: { body: { sourceUrl: null } },
            dependencies: [
              {
                templatePointer: "/body/sourceUrl",
                source: { kind: "fact", factId: "mediaSources", factPointer: "/primary/sourceUrl" },
              },
            ],
            defaults: [],
          },
          policies: createPolicies,
        },
        {
          id: "secondary",
          title: "Import secondary media",
          operationId: "dashboard.media.import_url",
          mutation: "create",
          condition: "Use the reviewed direct-upload client action for a local file.",
          input: {
            template: { body: { sourceUrl: null } },
            dependencies: [
              {
                templatePointer: "/body/sourceUrl",
                source: { kind: "fact", factId: "mediaSources", factPointer: "/secondary/sourceUrl" },
              },
            ],
            defaults: [],
          },
          policies: createPolicies,
        },
      ],
    },
    {
      id: "create",
      surface: "dashboard",
      title: "Create atomically",
      summary: "Submit media, attributes, axes, and all SKUs atomically.",
      dependsOn: ["prepare", "media"],
      stopConditions: ["Stop on conflict; never fall back to per-SKU creation."],
      steps: [
        {
          id: "product",
          title: "Create atomic optioned product",
          operationId: "dashboard.products.create",
          mutation: "create",
          input: {
            template: {
              body: {
                name: null,
                description: null,
                price: null,
                categoryId: null,
                isActive: true,
                freeDelivery: false,
                metaTitle: null,
                metaDescription: null,
                canonicalPath: null,
                noIndex: false,
                excludeFromSitemap: false,
                excludeFromProductFeed: false,
                productCondition: null,
                slug: null,
                media: [
                  { id: "pmed_primary", mediaId: null, altText: null, isPrimary: true },
                  { id: "pmed_secondary", mediaId: null, altText: null, isPrimary: false },
                ],
                attributes: null,
                optionMatrix: null,
              },
            },
            dependencies: [
              { templatePointer: "/body/name", source: { kind: "fact", factId: "productSpec", factPointer: "/name" } },
              { templatePointer: "/body/slug", source: { kind: "fact", factId: "productSpec", factPointer: "/slug" } },
              { templatePointer: "/body/categoryId", source: { kind: "fact", factId: "categoryId" } },
              { templatePointer: "/body/attributes", source: { kind: "fact", factId: "attributeAssignments" } },
              { templatePointer: "/body/optionMatrix", source: { kind: "fact", factId: "optionMatrix" } },
              {
                templatePointer: "/body/media/0/mediaId",
                source: { kind: "step", phaseId: "media", stepId: "primary", responsePointer: "/data/file/id" },
              },
              {
                templatePointer: "/body/media/1/mediaId",
                source: { kind: "step", phaseId: "media", stepId: "secondary", responsePointer: "/data/file/id" },
              },
            ],
            defaults: [
              { templatePointer: "/body/isActive", value: true },
              { templatePointer: "/body/noIndex", value: false },
              { templatePointer: "/body/excludeFromSitemap", value: false },
              { templatePointer: "/body/excludeFromProductFeed", value: false },
            ],
          },
          policies: createPolicies,
        },
      ],
    },
    {
      id: "publish",
      surface: "dashboard",
      title: "Publish eligible category",
      summary: "Prove readiness, then publish with current revision.",
      dependsOn: ["create"],
      stopConditions: ["Stop on readiness blocker or revision conflict."],
      steps: [
        {
          id: "category",
          title: "Read fresh category revision",
          operationId: "dashboard.categories.get_section",
          mutation: "read",
          input: {
            template: { path: { id: null, section: "summary" } },
            dependencies: [{ templatePointer: "/path/id", source: { kind: "fact", factId: "categoryId" } }],
            defaults: [{ templatePointer: "/path/section", value: "summary" }],
          },
          policies: readPolicies,
        },
        {
          id: "readiness",
          title: "Read category publish readiness",
          operationId: "dashboard.categories.publish_readiness",
          mutation: "read",
          input: {
            template: { path: { id: null } },
            dependencies: [{ templatePointer: "/path/id", source: { kind: "fact", factId: "categoryId" } }],
            defaults: [],
          },
          policies: readPolicies,
        },
        {
          id: "status",
          title: "Publish category with CAS",
          operationId: "dashboard.categories.set_status",
          mutation: "lifecycle",
          condition: "Only if not published and ready.",
          input: {
            template: { path: { id: null }, body: { expectedRevision: null, status: "published" } },
            dependencies: [
              { templatePointer: "/path/id", source: { kind: "fact", factId: "categoryId" } },
              {
                templatePointer: "/body/expectedRevision",
                source: { kind: "step", phaseId: "publish", stepId: "category", responsePointer: "/data/category/revision" },
              },
            ],
            defaults: [{ templatePointer: "/body/status", value: "published" }],
          },
          policies: {
            ...createPolicies,
            revision: "required",
            stopConditions: ["On conflict, reread summary/readiness; never retry stale."],
          },
        },
      ],
    },
    {
      id: "dashboardVerify",
      surface: "dashboard",
      title: "Verify dashboard truth",
      summary: "Read composition, feed, and discovery health.",
      dependsOn: ["create", "publish"],
      stopConditions: ["Stop on SKU/image/stock drift or discovery failure."],
      steps: [
        {
          id: "sections",
          title: "Read bounded product sections",
          operationId: "dashboard.products.get_section",
          mutation: "read",
          condition: "Read base, text, media, attributes, info, options, and variants.",
          input: {
            template: { path: { id: null, section: null }, query: { offset: 0, limit: 10 } },
            dependencies: [
              {
                templatePointer: "/path/id",
                source: { kind: "step", phaseId: "create", stepId: "product", responsePointer: "/data/id" },
              },
            ],
            defaults: [
              { templatePointer: "/query/offset", value: 0 },
              { templatePointer: "/query/limit", value: 10 },
            ],
          },
          policies: readPolicies,
        },
        {
          id: "feed",
          title: "Read bounded feed diagnostics",
          operationId: "dashboard.seo.feed_diagnostics",
          mutation: "read",
          input: { template: { query: { scanLimit: 500, sampleLimit: 10 } }, dependencies: [], defaults: [{ templatePointer: "/query/scanLimit", value: 500 }, { templatePointer: "/query/sampleLimit", value: 10 }] },
          policies: readPolicies,
        },
        {
          id: "probe",
          title: "Probe public discovery resources",
          operationId: "dashboard.seo.live_probe",
          mutation: "read",
          input: { template: {}, dependencies: [], defaults: [] },
          policies: readPolicies,
        },
      ],
    },
    {
      id: "storefrontVerify",
      surface: "storefront",
      title: "Verify buyer SKU truth",
      summary: "Compare public options, prices, images, and availability bands.",
      dependsOn: ["dashboardVerify"],
      stopConditions: ["Stop on missing or mismatched buyer-visible facts."],
      steps: [
        {
          id: "sections",
          title: "Read storefront product sections",
          operationId: "storefront.products.get_section",
          mutation: "read",
          condition: "Read summary, media, options, values, and bounded variants.",
          input: {
            template: { path: { slug: null, section: null }, query: { offset: 0, limit: 10 } },
            dependencies: [
              { templatePointer: "/path/slug", source: { kind: "fact", factId: "productSpec", factPointer: "/slug" } },
            ],
            defaults: [
              { templatePointer: "/query/offset", value: 0 },
              { templatePointer: "/query/limit", value: 10 },
            ],
          },
          policies: readPolicies,
        },
      ],
    },
  ],
  verification: [
    {
      id: "composition",
      surface: "dashboard",
      operationId: "dashboard.products.get_section",
      responsePointers: ["/data/aggregateRevision", "/data/items", "/data/total"],
      proves: ["Exact media, attributes, axes, SKUs, prices, and stock."],
      bounds: { maxCalls: 12, maxItems: 150, maxResponseBytes: 65_536 },
    },
    {
      id: "feed",
      surface: "dashboard",
      operationId: "dashboard.seo.feed_diagnostics",
      responsePointers: ["/data/policy", "/data/totals", "/data/reasons"],
      proves: ["Feed eligibility and explicit exclusion reasons."],
      bounds: { maxCalls: 1, maxItems: 500, maxResponseBytes: 65_536 },
    },
    {
      id: "discovery",
      surface: "dashboard",
      operationId: "dashboard.seo.live_probe",
      responsePointers: ["/data/ok", "/data/resources"],
      proves: ["Sitemap/feed health and absolute-link evidence."],
      bounds: { maxCalls: 1, maxItems: 12, maxResponseBytes: 65_536 },
    },
    {
      id: "buyer",
      surface: "storefront",
      operationId: "storefront.products.get_section",
      responsePointers: ["/data/product", "/data/items"],
      proves: ["Buyer SKU price, variant image, and availability band."],
      bounds: { maxCalls: 10, maxItems: 150, maxResponseBytes: 61_440 },
    },
  ],
};

export const DAILY_OPERATING_SNAPSHOT_WORKFLOW: AgentWorkflowCard = {
  id: "operations.daily-snapshot.v1",
  surface: "dashboard",
  title: "Daily merchant snapshot",
  summary: "Report booked-gross activity, open fulfillment, alerts, and payment/delivery readiness.",
  examples: [
    "Show today's booked sales, orders to fulfill, stock alerts, and checkout readiness.",
  ],
  tags: ["daily", "operations", "readiness"],
  requiredFacts: [
    {
      id: "days",
      title: "Merchant-day window",
      description: "Use 1 today; use 2 and select the earlier key yesterday.",
      required: true,
      defaultValue: 1,
      source: { kind: "constant", value: 1 },
      nonInferenceRule: "Keep Asia/Dhaka date keys; ignore host timezone.",
    },
    {
      id: "currency",
      title: "Currency",
      description: "Currency returned by store currency settings.",
      required: true,
      source: { kind: "operation", operationId: "dashboard.settings.currency_get", responsePointer: "/data/currencyCode" },
      nonInferenceRule: "Never guess or mix currency labels.",
    },
  ],
  phases: [
    {
      id: "activity",
      surface: "dashboard",
      title: "Activity and work queue",
      summary: "Read the merchant-day aggregate, currency, and bounded fulfillment queue.",
      dependsOn: [],
      stopConditions: ["Never total partial pages or use host-local dates."],
      steps: [
        {
          id: "daily",
          title: "Read booked-gross activity",
          operationId: "dashboard.home.activity",
          mutation: "read",
          input: {
            template: { query: { days: 1 } },
            dependencies: [{ templatePointer: "/query/days", source: { kind: "fact", factId: "days" } }],
            defaults: [{ templatePointer: "/query/days", value: 1 }],
          },
          output: {
            selectors: [{
              pointer: "/data/dailyActivityData",
              alias: "activity",
              maxItems: 2,
              fields: [
                { pointer: "/date", alias: "date" },
                { pointer: "/orders", alias: "orders" },
                { pointer: "/revenue", alias: "revenue" },
                { pointer: "/newCustomers", alias: "newCustomers" },
              ],
            }],
          },
          policies: readPolicies,
        },
        {
          id: "currency",
          title: "Read store currency",
          operationId: "dashboard.settings.currency_get",
          mutation: "read",
          input: { template: {}, dependencies: [], defaults: [] },
          output: {
            selectors: [
              { pointer: "/data/currencyCode", alias: "currencyCode" },
              { pointer: "/data/currencySymbol", alias: "currencySymbol" },
            ],
          },
          policies: readPolicies,
        },
        {
          id: "fulfillment",
          title: "Read orders awaiting fulfillment",
          operationId: "dashboard.orders.list",
          mutation: "read",
          input: {
            template: {
              query: {
                page: 1,
                limit: 10,
                statusGroup: "open",
                fulfillmentStatus: "pending",
                sort: "createdAt",
                order: "desc",
              },
            },
            dependencies: [],
            defaults: [
              { templatePointer: "/query/page", value: 1 },
              { templatePointer: "/query/limit", value: 10 },
              { templatePointer: "/query/statusGroup", value: "open" },
              { templatePointer: "/query/fulfillmentStatus", value: "pending" },
              { templatePointer: "/query/sort", value: "createdAt" },
              { templatePointer: "/query/order", value: "desc" },
            ],
          },
          output: {
            selectors: [
              {
                pointer: "/data/orders",
                alias: "orderQueue",
                maxItems: 10,
                fields: [
                  { pointer: "/id", alias: "id" },
                  { pointer: "/totalAmount", alias: "totalAmount" },
                  { pointer: "/status", alias: "status" },
                  { pointer: "/paymentStatus", alias: "paymentStatus" },
                  { pointer: "/paymentMethod", alias: "paymentMethod" },
                  { pointer: "/fulfillmentStatus", alias: "fulfillmentStatus" },
                  { pointer: "/createdAt", alias: "createdAt" },
                  { pointer: "/itemCount", alias: "itemCount" },
                  { pointer: "/totalQuantity", alias: "totalQuantity" },
                ],
              },
              {
                pointer: "/data/pagination",
                alias: "pagination",
                fields: [
                  { pointer: "/page", alias: "page" },
                  { pointer: "/limit", alias: "limit" },
                  { pointer: "/total", alias: "total" },
                  { pointer: "/totalPages", alias: "totalPages" },
                ],
              },
            ],
          },
          policies: readPolicies,
        },
      ],
    },
    {
      id: "readiness",
      surface: "dashboard",
      title: "Operating readiness",
      summary: "Distinguish saved settings, active rows, and buyer-usable readiness.",
      dependsOn: ["activity"],
      stopConditions: ["Report unavailable projections; never guess providers."],
      steps: [
        {
          id: "alerts",
          title: "Read inventory alerts",
          operationId: "dashboard.inventory_alerts.list",
          mutation: "read",
          input: { template: { query: { status: "active" } }, dependencies: [], defaults: [{ templatePointer: "/query/status", value: "active" }] },
          output: {
            selectors: [{
              pointer: "/data/alerts",
              alias: "inventoryAlerts",
              maxItems: 20,
              fields: [
                { pointer: "/productId", alias: "productId" },
                { pointer: "/productName", alias: "productName" },
                { pointer: "/variantId", alias: "variantId" },
                { pointer: "/variantSku", alias: "sku" },
                { pointer: "/variantLabel", alias: "variant" },
                { pointer: "/currentQty", alias: "quantity" },
                { pointer: "/threshold", alias: "threshold" },
                { pointer: "/alertStatus", alias: "status" },
              ],
            }],
          },
          policies: readPolicies,
        },
        {
          id: "checkout",
          title: "Read checkout readiness",
          operationId: "dashboard.checkout.readiness_get",
          mutation: "read",
          condition: "Use this first-class projection for blockers; never assume COD, gateway, or delivery fallback.",
          input: { template: {}, dependencies: [], defaults: [] },
          output: {
            selectors: [
              { pointer: "/data/ready", alias: "ready" },
              {
                pointer: "/data/hasActiveShippingMethod",
                alias: "hasActiveShippingMethod",
              },
              {
                pointer: "/data/hasActiveDeliveryHierarchy",
                alias: "hasActiveDeliveryHierarchy",
              },
              {
                pointer: "/data/customerSignInRequired",
                alias: "customerSignInRequired",
              },
              {
                pointer: "/data/hasUsableCustomerSignIn",
                alias: "hasUsableCustomerSignIn",
              },
              { pointer: "/data/issues", alias: "issues", maxItems: 20 },
            ],
          },
          policies: readPolicies,
        },
        {
          id: "payments",
          title: "Read payment configuration",
          operationId: "dashboard.payments.methods_get",
          mutation: "read",
          condition: "Enabled/configured is not usable; report gatewayStatus usability and checkout visibility.",
          input: { template: {}, dependencies: [], defaults: [] },
          output: {
            selectors: [
              {
                pointer: "/data/enabledMethods",
                alias: "enabledMethods",
                maxItems: 4,
              },
              {
                pointer: "/data/activeMethods",
                alias: "activeMethods",
                maxItems: 4,
              },
              { pointer: "/data/defaultMethod", alias: "defaultMethod" },
              { pointer: "/data/activeDefaultMethod", alias: "activeDefaultMethod" },
              {
                pointer: "/data/gatewayStatus",
                alias: "gatewayStatus",
                fields: [
                  { pointer: "/stripe/configured", alias: "stripeConfigured" },
                  { pointer: "/stripe/usable", alias: "stripeUsable" },
                  { pointer: "/stripe/checkoutVisible", alias: "stripeVisible" },
                  { pointer: "/sslcommerz/configured", alias: "sslConfigured" },
                  { pointer: "/sslcommerz/usable", alias: "sslUsable" },
                  { pointer: "/sslcommerz/checkoutVisible", alias: "sslVisible" },
                  { pointer: "/polar/configured", alias: "polarConfigured" },
                  { pointer: "/polar/usable", alias: "polarUsable" },
                  { pointer: "/polar/checkoutVisible", alias: "polarVisible" },
                  { pointer: "/cod/configured", alias: "codConfigured" },
                  { pointer: "/cod/usable", alias: "codUsable" },
                  { pointer: "/cod/checkoutVisible", alias: "codVisible" },
                ],
              },
            ],
          },
          policies: readPolicies,
        },
        {
          id: "delivery",
          title: "Read saved shipping methods",
          operationId: "dashboard.shipping_methods.list",
          mutation: "read",
          condition: "Rows are saved definitions; only isActive rows are active, and readiness owns buyer usability.",
          input: {
            template: { query: { page: 1, limit: 100, sort: "sortOrder", order: "asc" } },
            dependencies: [],
            defaults: [
              { templatePointer: "/query/page", value: 1 },
              { templatePointer: "/query/limit", value: 100 },
              { templatePointer: "/query/sort", value: "sortOrder" },
              { templatePointer: "/query/order", value: "asc" },
            ],
          },
          output: {
            selectors: [
              {
                pointer: "/data/shippingMethods",
                alias: "shippingMethods",
                maxItems: 100,
                fields: [
                  { pointer: "/id", alias: "id" },
                  { pointer: "/name", alias: "name" },
                  { pointer: "/fee", alias: "fee" },
                  { pointer: "/isActive", alias: "isActive" },
                  { pointer: "/sortOrder", alias: "sortOrder" },
                ],
              },
              {
                pointer: "/data/pagination",
                alias: "pagination",
                fields: [
                  { pointer: "/page", alias: "page" },
                  { pointer: "/limit", alias: "limit" },
                  { pointer: "/total", alias: "total" },
                  { pointer: "/totalPages", alias: "totalPages" },
                ],
              },
            ],
          },
          policies: readPolicies,
        },
      ],
    },
  ],
  verification: [
    {
      id: "activity",
      surface: "dashboard",
      operationId: "dashboard.home.activity",
      responsePointers: ["/data"],
      proves: ["Booked gross uses merchant-day keys; it is not collected cash or net settlement."],
      bounds: { maxCalls: 1, maxItems: 2, maxResponseBytes: 32_768 },
    },
    {
      id: "fulfillment",
      surface: "dashboard",
      operationId: "dashboard.orders.list",
      responsePointers: ["/data/orders", "/data/pagination"],
      proves: ["A bounded open/pending fulfillment queue; never a total of a partial page."],
      bounds: { maxCalls: 1, maxItems: 10, maxResponseBytes: 65_536 },
    },
    {
      id: "readiness",
      surface: "dashboard",
      operationId: "dashboard.checkout.readiness_get",
      responsePointers: ["/data"],
      proves: ["First-class payment and delivery blockers."],
      bounds: { maxCalls: 1, maxItems: 20, maxResponseBytes: 65_536 },
    },
    {
      id: "payment",
      surface: "dashboard",
      operationId: "dashboard.payments.methods_get",
      responsePointers: ["/data/enabledMethods", "/data/gatewayStatus"],
      proves: ["Saved selection versus configured, usable, and checkout-visible status."],
      bounds: { maxCalls: 1, maxItems: 4, maxResponseBytes: 65_536 },
    },
    {
      id: "delivery",
      surface: "dashboard",
      operationId: "dashboard.shipping_methods.list",
      responsePointers: ["/data/shippingMethods", "/data/pagination"],
      proves: ["Bounded saved methods with explicit active flags."],
      bounds: { maxCalls: 1, maxItems: 100, maxResponseBytes: 65_536 },
    },
  ],
};

export const CURATED_AGENT_WORKFLOW_CARDS: readonly AgentWorkflowCard[] = [
  OPTIONED_PRODUCT_WORKFLOW,
  DAILY_OPERATING_SNAPSHOT_WORKFLOW,
];
