import type {
  AgentWorkflowControl,
  AgentWorkflowControlTriggerBranch,
} from "./types";

const BANGLADESH_SETUP_SAFE_READS = [
  "dashboard.settings.currency_get",
  "dashboard.checkout.flow_get",
  "dashboard.checkout.readiness_get",
  "dashboard.payments.methods_get",
  "dashboard.shipping_methods.list",
  "storefront.checkout.get_config",
] as const;

const BANGLADESH_SETUP_FORBIDDEN_WRITES = [
  "dashboard.settings.currency_update",
  "dashboard.payments.sslcommerz_update",
  "dashboard.payments.methods_update",
  "dashboard.shipping_methods.update",
  "dashboard.shipping_methods.create",
  "dashboard.shipping_methods.trash",
  "dashboard.shipping_methods.delete_permanently",
  "dashboard.checkout.flow_update",
  "dashboard.seo.settings_update",
  "dashboard.analytics.create",
  "dashboard.analytics.update",
  "dashboard.analytics.set_active",
] as const;

const OWNER_BRIEF_TIME_ANCHORS = ["30 days"] as const;

const OWNER_BRIEF_SAFE_READS = [
  "dashboard.home.activity",
  "dashboard.settings.currency_get",
  "dashboard.inventory.list",
  "dashboard.abandoned_checkouts.summaries_list",
  "dashboard.orders.payment_recovery_list",
] as const;

const OWNER_BRIEF_UNSUPPORTED_BRANCHES: AgentWorkflowControlTriggerBranch[] = [
  {
    allOf: [[
      "cash",
      "profit",
      "net revenue",
      "aov",
      "ltv",
      "cac",
      "repeat customer",
    ]],
  },
  {
    allOf: [
      ["top", "best selling", "best-selling"],
      ["product", "sku"],
    ],
  },
  {
    allOf: [[
      "margin",
      "roas",
      "traffic",
      "conversion",
      "ad spend",
      "impression",
      "click",
      "session",
    ]],
  },
  {
    allOf: [
      ["status", "aging", "stuck", "refund", "chargeback", "return", "cancel", "cancellation"],
      ["count", "total", "amount", "rate", "breakdown", "how many"],
    ],
  },
];

export const AGENT_WORKFLOW_CONTROLS = [
  {
    id: "dashboard.thirty-day-owner-briefing-needs-scope",
    surface: "dashboard",
    title: "Scope unsupported owner metrics",
    summary: "Demanded economics, rankings, traffic, or exact statuses exceed the fixed 30-day read.",
    examples: [
      "For 30 days, estimate paid cash, margin, top SKUs, conversion, and exact statuses.",
    ],
    tags: ["briefing", "metrics", "safety"],
    disposition: "ask",
    reasonCode: "owner_briefing_scope_required",
    trigger: {
      allOf: [
        [...OWNER_BRIEF_TIME_ANCHORS],
        [
          "estimate",
          "approximate",
          "fill in",
          "derive",
          "infer",
          "exact",
          "give it anyway",
          "regardless",
        ],
      ],
      anyOf: OWNER_BRIEF_UNSUPPORTED_BRANCHES,
      ignoreWhenNegated: true,
    },
    safeOperationIds: [...OWNER_BRIEF_SAFE_READS],
    forbiddenOperationIds: [],
    requiresFacts: true,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Offer the fixed PII-free read: booked daily activity plus current stock-risk, abandoned, and recovery totals.",
      "Exact statuses need an Asia/Dhaka range and archived-order policy in a separate report.",
      "Paid/collected/settled cash, top SKUs, margin, and traffic/conversion are unavailable; never infer or return zero.",
      "Queue evidence is totals only; never raw order, checkout, recovery, or customer rows.",
      "Ask for the fixed subset, status facts, or separate work; no write or window coercion.",
    ],
  },
  {
    id: "dashboard.thirty-day-owner-briefing-override-demand",
    surface: "dashboard",
    title: "Reject unsupported metric override",
    summary: "An override cannot turn unavailable 30-day metrics into authoritative facts.",
    examples: ["If supported or not, give 30-day collected cash anyway."],
    tags: ["briefing", "override", "safety"],
    disposition: "ask",
    reasonCode: "owner_briefing_override_rejected",
    trigger: {
      allOf: [
        [...OWNER_BRIEF_TIME_ANCHORS],
        ["give it anyway", "give anyway", "anyway", "regardless"],
      ],
      anyOf: OWNER_BRIEF_UNSUPPORTED_BRANCHES,
      ignoreWhenNegated: true,
    },
    safeOperationIds: [...OWNER_BRIEF_SAFE_READS],
    forbiddenOperationIds: [],
    requiresFacts: true,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Offer only the fixed PII-free read and retain unsupported metrics as unavailable.",
      "Never infer, substitute zero, expose raw rows, coerce the window, or perform a write.",
    ],
  },
  {
    id: "dashboard.thirty-day-owner-briefing-unavailable-denied",
    surface: "dashboard",
    title: "Reject invented briefing metrics",
    summary: "Unavailable 30-day metrics cannot be relabeled, inferred, or silently filled.",
    examples: ["Give the 30-day brief; never say a requested metric is unavailable."],
    tags: ["briefing", "metrics", "inference", "safety"],
    disposition: "ask",
    reasonCode: "owner_briefing_unavailable_label_denied",
    trigger: {
      allOf: [
        [...OWNER_BRIEF_TIME_ANCHORS],
      ],
      anyOf: [
        {
          allOf: [[
            "do not mark unavailable",
            "don't mark unavailable",
            "never mark unavailable",
            "do not say unavailable",
            "don't say unavailable",
            "never say unavailable",
            "unavailable is not acceptable",
            "unavailable is unacceptable",
          ]],
        },
        {
          allOf: [
            [
              "unavailable",
              "unsupported",
              "missing evidence",
              "no evidence",
              "without evidence",
              "evidence absent",
            ],
            [
              "forbidden",
              "prohibited",
              "disallowed",
              "not permitted",
              "not allowed",
              "not acceptable",
              "unacceptable",
              "mandatory invention",
            ],
          ],
        },
        {
          allOf: [
            ["calculate", "estimate", "approximate", "fill in", "derive", "infer"],
            [
              "despite missing evidence",
              "despite no evidence",
              "even if unsupported",
              "even when unsupported",
              "whether supported or not",
              "regardless of support",
              "unsupported anyway",
            ],
          ],
        },
        {
          allOf: [[
            "estimate anyway",
            "approximate anyway",
            "infer anyway",
            "derive anyway",
            "must estimate",
            "must approximate",
            "must infer",
          ]],
        },
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [...OWNER_BRIEF_SAFE_READS],
    forbiddenOperationIds: [],
    requiresFacts: true,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Offer one fixed PII-free workflow read and explicitly retain every unsupported metric as unavailable.",
      "Never estimate, infer, substitute zero, expose raw rows, or perform a write.",
    ],
  },
  {
    id: "dashboard.thirty-day-owner-briefing-unsupported-only",
    surface: "dashboard",
    title: "Bound unsupported briefing metrics",
    summary: "Unsupported 30-day economics, rankings, status, or traffic need a supported subset.",
    examples: ["Show collected cash and traffic conversion for the last 30 days."],
    tags: ["briefing", "metrics", "unavailable", "safety"],
    disposition: "ask",
    reasonCode: "owner_briefing_unsupported_metrics",
    trigger: {
      allOf: [
        [...OWNER_BRIEF_TIME_ANCHORS],
      ],
      anyOf: OWNER_BRIEF_UNSUPPORTED_BRANCHES,
      noneOf: ["if known", "if supported", "if available", "unavailable", "do not estimate", "don't estimate"],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [...OWNER_BRIEF_SAFE_READS],
    forbiddenOperationIds: [],
    requiresFacts: true,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Offer the fixed PII-free 30-day subset: booked daily activity plus current stock-risk, abandoned-checkout, and recovery totals.",
      "Paid, collected, or settled cash, status counts, top-SKU ranking, gross margin, and traffic/conversion are unavailable in this fixed workflow read.",
      "Never infer missing metrics, return raw rows, coerce another window, or perform a write.",
    ],
  },
  {
    id: "dashboard.thirty-day-owner-briefing-pii-expansion",
    surface: "dashboard",
    title: "Reject briefing PII expansion",
    summary: "A fixed PII-free brief cannot expose customer identities or contact details.",
    examples: ["Give the 30-day owner brief and include every abandoned shopper email address."],
    tags: ["briefing", "pii", "compound", "safety"],
    disposition: "ask",
    reasonCode: "owner_briefing_pii_expansion",
    trigger: {
      allOf: [
        [...OWNER_BRIEF_TIME_ANCHORS],
      ],
      anyOf: [
        {
          allOf: [
            ["buyer", "customer", "shopper"],
            ["contact", "identity", "name", "email", "phone", "address", "detail"],
          ],
        },
        { allOf: [["name"], ["email"]] },
        { allOf: [["export"], ["buyer", "customer", "shopper"]] },
        {
          allOf: [
            ["buyer", "customer", "shopper"],
            ["phonebook", "directory", "contact list", "roster"],
          ],
        },
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [...OWNER_BRIEF_SAFE_READS],
    forbiddenOperationIds: [],
    requiresFacts: true,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Keep the briefing PII-free and count-only; never expose customer identities or contact details.",
      "Offer only the fixed 30-day read subset; customer export or raw-customer work needs a separate authorized request.",
    ],
  },
  {
    id: "dashboard.thirty-day-owner-briefing-row-expansion",
    surface: "dashboard",
    title: "Reject raw briefing rows",
    summary: "A bounded briefing returns aggregate totals, never raw operational rows.",
    examples: ["Give the 30-day brief plus raw checkout, order, and recovery rows."],
    tags: ["briefing", "rows", "pii", "safety"],
    disposition: "ask",
    reasonCode: "owner_briefing_raw_rows",
    trigger: {
      allOf: [
        [...OWNER_BRIEF_TIME_ANCHORS],
      ],
      anyOf: [
        {
          allOf: [
            ["raw", "every", "all", "each", "underlying", "individual"],
            ["customer", "order", "checkout", "recovery"],
            ["row", "rows", "record", "detail", "object", "source row"],
          ],
        },
        {
          allOf: [[
            "customer row",
            "customer record",
            "order row",
            "order record",
            "checkout row",
            "checkout record",
            "recovery row",
            "recovery record",
          ]],
        },
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [...OWNER_BRIEF_SAFE_READS],
    forbiddenOperationIds: [],
    requiresFacts: true,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Return projections and totals only; never expose raw checkout, order, recovery, or customer records.",
      "Offer only the fixed PII-free 30-day subset and perform no write.",
    ],
  },
  {
    id: "dashboard.thirty-day-owner-briefing-mutation-expansion",
    surface: "dashboard",
    title: "Separate briefing from mutations",
    summary: "A fixed read must not absorb SEO, product, shipping, export, or homepage changes.",
    examples: ["Give the 30-day brief, then update the homepage hero and global SEO."],
    tags: ["briefing", "compound", "write", "safety"],
    disposition: "ask",
    reasonCode: "owner_briefing_write_expansion",
    trigger: {
      allOf: [
        [...OWNER_BRIEF_TIME_ANCHORS],
      ],
      anyOf: [{
        allOf: [
          ["update", "change", "rewrite", "delete", "trash"],
          ["seo", "product", "shipping", "homepage", "hero"],
        ],
      }],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [...OWNER_BRIEF_SAFE_READS],
    forbiddenOperationIds: [],
    requiresFacts: true,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Do not absorb SEO, product, shipping, homepage, deletion, export, or any other mutation into the briefing.",
      "Ask for a separate supported write request; offer only the fixed 30-day read subset now.",
    ],
  },
  {
    id: "dashboard.shipping-threshold-unsupported",
    surface: "dashboard",
    title: "Clarify unsupported delivery thresholds",
    summary:
      "Flat-fee labels cannot enforce geography, and order-value free-delivery thresholds are unsupported.",
    examples: [
      "Add Dhaka and nationwide delivery with fees and a free-shipping threshold.",
    ],
    tags: ["shipping", "delivery", "threshold"],
    disposition: "ask",
    reasonCode: "shipping_threshold_or_scope_unsupported",
    trigger: {
      allOf: [
        ["shipping", "delivery"],
        [
          "free shipping",
          "free delivery",
          "delivery free",
          "waive shipping fee",
          "waive delivery fee",
        ],
        ["threshold", "minimum spend", "minimum cart", "cart value", "order value"],
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [
      "dashboard.settings.currency_get",
      "dashboard.checkout.flow_get",
      "dashboard.checkout.readiness_get",
      "dashboard.payments.methods_get",
      "dashboard.shipping_methods.list",
      "storefront.checkout.get_config",
    ],
    forbiddenOperationIds: [
      "dashboard.settings.currency_update",
      "dashboard.payments.methods_update",
      "dashboard.payments.stripe_update",
      "dashboard.payments.sslcommerz_update",
      "dashboard.payments.polar_update",
      "dashboard.shipping_methods.create",
      "dashboard.shipping_methods.update",
      "dashboard.shipping_methods.trash",
      "dashboard.shipping_methods.restore",
      "dashboard.shipping_methods.delete_permanently",
      "dashboard.checkout.flow_update",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Flat-fee names are global labels; they do not enforce Dhaka, nationwide, zone, or other geography.",
      "Order-value free-delivery thresholds are unsupported; do not encode them in labels or fees.",
      "Ask whether the merchant accepts global flat-fee methods without thresholds as a supported subset.",
      "Require exact fees and intent for keeping or disabling other payment and shipping methods.",
      "Until facts and subset acceptance are explicit, perform reads only and make no settings write.",
    ],
  },
  {
    id: "dashboard.campaign-layout-needs-review",
    surface: "dashboard",
    title: "Clarify campaign page presentation limits",
    summary:
      "Campaign page, navigation, and shared-layout changes need reviewed HTML and homepage fallback choices.",
    examples: [
      "Publish a campaign landing page, add it to navigation and the homepage, and announce it in the header.",
    ],
    tags: ["campaign", "content", "navigation", "homepage", "header", "unsupported"],
    disposition: "ask",
    reasonCode: "campaign_layout_requires_reviewed_facts",
    trigger: {
      allOf: [
        ["campaign page", "landing page", "cms page"],
        ["navigation", "main menu", "menu"],
        ["homepage", "layout", "announcement", "announce"],
        ["create", "build", "publish", "launch"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: [
      "dashboard.content.list",
      "dashboard.navigation.placements_manifest",
      "dashboard.navigation.menus_list",
      "dashboard.settings_header.get_header",
      "dashboard.settings_homepage_presentation.get_homepage_presentation",
      "dashboard.hero_sliders.list",
    ],
    forbiddenOperationIds: [
      "dashboard.products.create",
      "dashboard.products.update_section",
      "dashboard.categories.create",
      "dashboard.categories.set_status",
      "dashboard.attributes.create",
      "dashboard.inventory.adjust_stock",
      "dashboard.inventory.set_stock",
      "dashboard.seo.settings_update",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Do not substitute product, category, attribute, inventory, or global SEO writes for page-scoped campaign work.",
      "Explain that CMS pages accept sanitized HTML, not semantic hero, collection, or FAQ blocks.",
      "Ask whether an untyped HTML page and desktop/mobile hero-slide fallback are acceptable.",
      "Require exact page SEO, media, menu placement, announcement, hero images, order, and publish facts.",
      "Keep theme and unrelated layout unchanged; perform discovery reads only until the reviewed facts are confirmed.",
    ],
  },
  {
    id: "dashboard.campaign-global-seo-overreach",
    surface: "dashboard",
    title: "Separate campaign and global SEO writes",
    summary: "Page-scoped campaign SEO does not authorize store-wide discovery changes.",
    examples: [
      "Create an Eid campaign page, then rewrite global SEO, robots, and structured-data settings.",
    ],
    tags: ["campaign", "content", "seo", "robots", "structured-data", "safety"],
    disposition: "ask",
    reasonCode: "campaign_global_seo_requires_separate_intent",
    trigger: {
      allOf: [
        ["campaign page", "landing page", "sale page", "cms page", "eid page"],
        ["global seo", "store-wide seo", "sitewide seo", "robots", "structured data"],
        ["change", "configure", "install", "rewrite", "set", "update"],
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [
      "dashboard.content.list",
      "dashboard.seo.settings_get",
      "storefront.seo.get",
    ],
    forbiddenOperationIds: ["dashboard.seo.settings_update"],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Global SEO, robots, and structured-data settings are store-wide and outside this page workflow.",
      "Keep SEO page-scoped; do bounded reads and ask for a separate explicit global-discovery request.",
      "Do not perform page, navigation, presentation, catalog, or global SEO writes from this compound request.",
    ],
  },
  {
    id: "dashboard.shipping-geography-unsupported",
    surface: "dashboard",
    title: "Reject geographic flat-fee enforcement",
    summary: "Flat-fee method names are global labels and cannot enforce a buyer location or delivery zone.",
    examples: ["Make Dhaka and Nationwide method labels enforce buyer geography."],
    tags: ["shipping", "geography", "zones", "safety"],
    disposition: "ask",
    reasonCode: "shipping_geography_is_not_enforced",
    trigger: {
      allOf: [
        ["shipping", "delivery", "flat fee", "flat-fee", "method"],
        ["geography", "geographic location", "delivery zone", "zone"],
        ["enforce", "act as", "encode", "labels act"],
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [...BANGLADESH_SETUP_SAFE_READS],
    forbiddenOperationIds: [...BANGLADESH_SETUP_FORBIDDEN_WRITES],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Explain that flat-fee names are display labels, not geographic predicates or delivery zones.",
      "Make no setup write; ask for explicit acceptance of globally offered labels without geography enforcement.",
    ],
  },
  {
    id: "dashboard.shipping-fees-must-be-supplied",
    surface: "dashboard",
    title: "Require exact delivery fees",
    summary: "Delivery fees are merchant facts and cannot be selected by the resolver.",
    examples: ["Create Dhaka and Nationwide methods but choose suitable fees for me."],
    tags: ["shipping", "fees", "facts"],
    disposition: "ask",
    reasonCode: "shipping_fees_missing",
    trigger: {
      allOf: [
        ["shipping", "delivery", "method", "methods"],
        ["choose suitable fee", "choose suitable fees", "choose fees", "set fees for me", "decide fees"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: [...BANGLADESH_SETUP_SAFE_READS],
    forbiddenOperationIds: [...BANGLADESH_SETUP_FORBIDDEN_WRITES],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Require an exact merchant-supplied label, fee, active intent, and optional sort order for each method.",
      "Never choose or infer a delivery fee; make no setup write until every method spec is complete.",
    ],
  },
  {
    id: "dashboard.shipping-method-match-ambiguous",
    surface: "dashboard",
    title: "Stop on ambiguous delivery matches",
    summary: "A shipping update needs exactly one active exact-name match; the resolver cannot choose a duplicate.",
    examples: ["If several Dhaka methods exist, choose whichever seems best."],
    tags: ["shipping", "duplicates", "identity"],
    disposition: "ask",
    reasonCode: "shipping_method_match_ambiguous",
    trigger: {
      allOf: [
        ["multiple existing methods", "duplicate method", "several methods", "more than one method"],
        ["choose whichever", "seems best", "pick one"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: [...BANGLADESH_SETUP_SAFE_READS],
    forbiddenOperationIds: [...BANGLADESH_SETUP_FORBIDDEN_WRITES],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Require exactly one active exact-name match for update; create only when no active, trashed, near, or duplicate match exists.",
      "Make no setup write; return the bounded matches and ask the merchant to resolve identity ambiguity.",
    ],
  },
  {
    id: "dashboard.shipping-unrelated-delete",
    surface: "dashboard",
    title: "Reject unrelated delivery deletion",
    summary: "The supported setup preserves unrelated shipping methods and never deletes them implicitly.",
    examples: ["Create these methods and delete every other shipping method."],
    tags: ["shipping", "deletion", "preservation"],
    disposition: "ask",
    reasonCode: "unrelated_shipping_delete_requires_separate_intent",
    trigger: {
      allOf: [
        ["delete", "remove", "trash"],
        ["every other", "all other", "unrelated"],
        ["shipping method", "shipping methods", "delivery method", "delivery methods"],
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [...BANGLADESH_SETUP_SAFE_READS],
    forbiddenOperationIds: [...BANGLADESH_SETUP_FORBIDDEN_WRITES],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Preserve every unrelated shipping method; deletion is not part of the reviewed setup.",
      "Make no setup write; ask for a separate exact destructive request after current-method review.",
    ],
  },
  {
    id: "dashboard.payment-policy-must-be-explicit",
    surface: "dashboard",
    title: "Require payment preservation and default intent",
    summary: "The resolver cannot choose which existing methods to disable or which method becomes default.",
    examples: ["Choose for me which payment methods to keep and which should be default."],
    tags: ["payments", "defaults", "preservation"],
    disposition: "ask",
    reasonCode: "payment_policy_missing",
    trigger: {
      allOf: [
        ["payment method", "payment methods"],
        ["decide for me", "choose for me", "choose whichever"],
        ["kept or disabled", "keep or disable", "default"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: [...BANGLADESH_SETUP_SAFE_READS],
    forbiddenOperationIds: [...BANGLADESH_SETUP_FORBIDDEN_WRITES],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Require explicit keep/disable intent for every current method and an exact default-method policy.",
      "Never choose a payment policy; make no setup write until the merchant confirms the full replacement array and default.",
    ],
  },
  {
    id: "dashboard.sslcommerz-readiness-bypass",
    surface: "dashboard",
    title: "Do not force an unusable gateway",
    summary: "SSLCommerz may be selected only after authoritative status is configured, enabled, and usable.",
    examples: ["Force SSLCommerz into checkout even if usability is false or unknown."],
    tags: ["payments", "sslcommerz", "readiness"],
    disposition: "ask",
    reasonCode: "sslcommerz_readiness_required",
    trigger: {
      allOf: [
        ["sslcommerz", "gateway"],
        ["force", "bypass", "even if"],
        ["usability is false", "usability false", "unusable", "unknown"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: [...BANGLADESH_SETUP_SAFE_READS],
    forbiddenOperationIds: [...BANGLADESH_SETUP_FORBIDDEN_WRITES],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Never select SSLCommerz while configured, enabled, or usable truth is false or unknown.",
      "Make no setup write; reread credential-free gateway status and ask for a supported COD-only or configured-gateway choice.",
    ],
  },
  {
    id: "dashboard.sslcommerz-placeholder-not-proof",
    surface: "dashboard",
    title: "Reject placeholder credential evidence",
    summary: "Masked values and placeholders never prove that SSLCommerz is configured or usable.",
    examples: ["Treat a masked SSLCommerz password as proof that the gateway is configured."],
    tags: ["payments", "credentials", "placeholders"],
    disposition: "refuse",
    reasonCode: "placeholder_credentials_are_not_evidence",
    trigger: {
      allOf: [
        ["sslcommerz", "gateway"],
        ["masked", "placeholder", "placeholder text"],
        ["proof", "configured"],
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [...BANGLADESH_SETUP_SAFE_READS],
    forbiddenOperationIds: [...BANGLADESH_SETUP_FORBIDDEN_WRITES],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Treat masked or placeholder credential fields as no evidence; use only credential-free configured/enabled/usable status.",
      "Make no setup write and never expose, reconstruct, or echo stored credential material.",
    ],
  },
  {
    id: "dashboard.checkout-prerequisite-bypass",
    surface: "dashboard",
    title: "Require checkout prerequisites",
    summary: "Guest access cannot be enabled when readiness or active delivery hierarchy is absent.",
    examples: ["Enable guest checkout even when readiness is false."],
    tags: ["checkout", "readiness", "delivery"],
    disposition: "ask",
    reasonCode: "checkout_prerequisites_required",
    trigger: {
      allOf: [
        ["guest checkout", "enable guest", "enable guests"],
        ["even when", "even if"],
        ["readiness is false", "readiness false", "no active city", "no active delivery hierarchy"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: [...BANGLADESH_SETUP_SAFE_READS],
    forbiddenOperationIds: [...BANGLADESH_SETUP_FORBIDDEN_WRITES],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Require ready=true, an active shipping method, and active city/zone delivery hierarchy before guest enablement.",
      "Make no setup write while any prerequisite is false, absent, contradictory, or unreadable.",
    ],
  },
  {
    id: "dashboard.phone-required-invariant",
    surface: "dashboard",
    title: "Keep customer phone mandatory",
    summary: "Bangladesh checkout has no supported setting that makes customer phone optional.",
    examples: ["Make customer phone optional before enabling checkout."],
    tags: ["checkout", "phone", "identity"],
    disposition: "refuse",
    reasonCode: "customer_phone_is_mandatory",
    trigger: {
      allOf: [
        ["phone", "customer phone"],
        ["optional", "not required", "disable phone requirement"],
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [...BANGLADESH_SETUP_SAFE_READS],
    forbiddenOperationIds: [...BANGLADESH_SETUP_FORBIDDEN_WRITES],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Customer phone is a mandatory platform invariant; do not invent or imply a disabling setting.",
      "Make no setup write while the request requires optional phone collection.",
    ],
  },
  {
    id: "dashboard.timezone-fixed-invariant",
    surface: "dashboard",
    title: "Do not invent a timezone setting",
    summary: "Merchant-calendar semantics are fixed to Asia/Dhaka and expose no writable timezone setting.",
    examples: ["Change the store timezone setting to Asia/Dhaka."],
    tags: ["settings", "timezone", "calendar"],
    disposition: "ask",
    reasonCode: "timezone_setting_unavailable",
    trigger: {
      allOf: [
        ["timezone", "timezone setting", "store timezone"],
        ["change", "set", "update"],
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [...BANGLADESH_SETUP_SAFE_READS],
    forbiddenOperationIds: [...BANGLADESH_SETUP_FORBIDDEN_WRITES],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "State that merchant-calendar behavior is fixed to Asia/Dhaka; no writable timezone operation exists.",
      "Make no setup write until the merchant accepts the fixed invariant without a timezone mutation.",
    ],
  },
  {
    id: "dashboard.unrelated-settings-overreach",
    surface: "dashboard",
    title: "Separate unrelated SEO and analytics work",
    summary: "The Bangladesh checkout setup never includes global SEO or analytics mutations.",
    examples: ["Configure checkout and also rewrite SEO and install an analytics snippet."],
    tags: ["settings", "seo", "analytics", "scope"],
    disposition: "ask",
    reasonCode: "unrelated_settings_require_separate_review",
    trigger: {
      allOf: [
        ["seo", "seo discovery", "global seo"],
        ["analytics", "analytics snippet"],
        ["rewrite", "install", "update", "change"],
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [...BANGLADESH_SETUP_SAFE_READS],
    forbiddenOperationIds: [...BANGLADESH_SETUP_FORBIDDEN_WRITES],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Do not add, delete, or mutate SEO, analytics, or any unrelated setting in this setup.",
      "Make no setup write; ask the merchant to keep the accepted subset isolated and resolve unrelated work separately.",
    ],
  },
  {
    id: "dashboard.non-atomic-setup-guarantee",
    surface: "dashboard",
    title: "Reject atomic rollback and blind retry claims",
    summary: "These settings writes are non-atomic and have no cross-operation rollback guarantee.",
    examples: ["Guarantee atomic setup, roll back every write, and blindly retry until success."],
    tags: ["settings", "atomicity", "retries", "safety"],
    disposition: "ask",
    reasonCode: "atomic_rollback_unavailable",
    trigger: {
      allOf: [
        ["atomic", "roll back", "rollback"],
        ["blindly retry", "retry uncertain", "until all changes", "until success"],
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [...BANGLADESH_SETUP_SAFE_READS],
    forbiddenOperationIds: [...BANGLADESH_SETUP_FORBIDDEN_WRITES],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "State that the sequence is non-atomic: no automatic rollback spans currency, payment, shipping, and checkout writes.",
      "Make no setup write; require stop, reread, partial-state reporting, and no blind retry after uncertainty.",
    ],
  },
  {
    id: "dashboard.provider-credentials-must-be-supplied",
    surface: "dashboard",
    title: "Reject invented provider credentials",
    summary: "Payment credentials must come from the merchant through the reviewed secure input.",
    examples: ["Invent SSLCommerz provider credentials and enable the gateway."],
    tags: ["payments", "providers", "credentials", "safety"],
    disposition: "refuse",
    reasonCode: "provider_credentials_cannot_be_invented",
    trigger: {
      allOf: [
        ["invent", "fabricate", "make up", "guess", "generate"],
        ["credential", "credentials", "secret", "password", "api key"],
        ["provider", "gateway", "sslcommerz", "stripe", "polar"],
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [...BANGLADESH_SETUP_SAFE_READS],
    forbiddenOperationIds: [...BANGLADESH_SETUP_FORBIDDEN_WRITES],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Never invent, guess, echo, or place provider credentials in a workflow input.",
      "Make no setup write; ask for merchant-supplied secure configuration, then reread credential-free readiness.",
    ],
  },
  {
    id: "dashboard.locked-currency-force",
    surface: "dashboard",
    title: "Do not bypass the currency lock",
    summary: "A locked currency code is authoritative and has no force or bypass operation.",
    examples: ["Force BDT even if the currency code is locked."],
    tags: ["currency", "lock", "safety"],
    disposition: "ask",
    reasonCode: "locked_currency_requires_supported_choice",
    trigger: {
      allOf: [
        ["currency", "currency code", "bdt"],
        ["locked", "currency lock"],
        ["force", "bypass", "override", "ignore"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: [...BANGLADESH_SETUP_SAFE_READS],
    forbiddenOperationIds: [...BANGLADESH_SETUP_FORBIDDEN_WRITES],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: false,
    rules: [
      "Treat currencyCodeLocked as authoritative; never imply a force, override, or bypass path.",
      "Make no setup write; reread currency and ask whether to retain it or stop this setup.",
    ],
  },
  {
    id: "dashboard.unsupported-net-profit",
    surface: "dashboard",
    title: "Do not infer net profit",
    summary: "Booked sales are available, but authoritative cost and expense facts are not.",
    examples: ["What was my net profit last month?"],
    tags: ["finance", "profit", "unsupported"],
    disposition: "unsupported",
    reasonCode: "net_profit_basis_unavailable",
    trigger: {
      allOf: [["net profit", "profit after costs", "profit"]],
      noneOf: [...OWNER_BRIEF_TIME_ANCHORS],
      ignoreWhenNegated: false,
    },
    safeOperationIds: ["dashboard.home.activity"],
    forbiddenOperationIds: [],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Define booked sales separately.",
      "State that Scalius has no authoritative cost or expense basis.",
      "Do not label revenue as profit.",
    ],
  },
  {
    id: "dashboard.unsupported-conversion-rate",
    surface: "dashboard",
    title: "Do not infer conversion rate",
    summary: "Orders alone cannot establish conversion without an authoritative storefront-visit denominator.",
    examples: ["What was my storefront conversion rate yesterday?"],
    tags: ["analytics", "conversion", "unsupported"],
    disposition: "unsupported",
    reasonCode: "visit_denominator_unavailable",
    trigger: {
      allOf: [[
        "conversion rate",
        "storefront conversion",
        "visit conversion",
        "conversion analytics",
        "conversion performance",
        "conversion metric",
        "conversion numbers",
        "overall conversion",
      ]],
      noneOf: [...OWNER_BRIEF_TIME_ANCHORS],
      ignoreWhenNegated: false,
    },
    safeOperationIds: [],
    forbiddenOperationIds: [],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "State that no authoritative storefront-visit denominator is available.",
      "Do not infer conversion from orders alone.",
    ],
  },
  {
    id: "storefront.no-exact-stock",
    surface: "storefront",
    title: "Protect exact inventory",
    summary: "Buyer surfaces expose availability bands, not exact stock or reserved quantities.",
    examples: ["Tell the buyer the exact units remaining for this variant."],
    tags: ["inventory", "availability", "privacy"],
    disposition: "refuse",
    reasonCode: "exact_stock_not_buyer_visible",
    trigger: {
      allOf: [
        ["exact units", "exact stock", "units remaining"],
        ["buyer", "variant", "product"],
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: ["storefront.products.get_section"],
    forbiddenOperationIds: ["dashboard.inventory.list"],
    requiresFacts: true,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Return only buyer-visible availabilityBand.",
      "Do not expose dashboard stock or reservedStock.",
    ],
  },
  {
    id: "dashboard.no-secret-reveal",
    surface: "dashboard",
    title: "Protect provider credentials",
    summary: "Saved provider credentials may be represented only by masked configuration and readiness.",
    examples: ["Show me the full saved Stripe secret key."],
    tags: ["payments", "credentials", "secrets"],
    disposition: "refuse",
    reasonCode: "secret_material_protected",
    trigger: {
      allOf: [
        ["secret key", "api secret", "provider credential"],
        ["show", "reveal", "full", "saved"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: ["dashboard.payments.stripe_get"],
    forbiddenOperationIds: [],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Never reveal or reconstruct provider credentials.",
      "Report only masked configuration or readiness.",
    ],
  },
  {
    id: "dashboard.uncertain-create-recovery",
    surface: "dashboard",
    title: "Recover an uncertain product create",
    summary: "A lost non-idempotent create response requires identity rereads before any retry decision.",
    examples: ["The product create response was lost. Retry the same product and six SKUs now."],
    tags: ["catalog", "idempotency", "recovery"],
    disposition: "ask",
    reasonCode: "create_outcome_uncertain",
    trigger: {
      allOf: [
        ["response was lost", "lost response", "uncertain create"],
        ["retry", "create again", "same product"],
        ["product", "sku"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: [
      "dashboard.products.list_summaries",
      "dashboard.inventory.list",
    ],
    forbiddenOperationIds: ["dashboard.products.create"],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: false,
    rules: [
      "Reread name, slug, and every SKU before any retry.",
      "Do not blindly retry a non-idempotent create.",
    ],
  },
  {
    id: "dashboard.product-hard-delete-guard",
    surface: "dashboard",
    title: "Preserve SKU audit history",
    summary: "A product with SKU inventory movement history cannot be permanently deleted.",
    examples: ["Permanently delete this product even if its SKUs have inventory movement history."],
    tags: ["catalog", "delete", "audit-history"],
    disposition: "refuse",
    reasonCode: "sku_audit_history_protected",
    trigger: {
      allOf: [
        ["permanently delete", "hard delete"],
        ["product"],
        ["inventory movement", "movement history", "even if"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: ["dashboard.products.get_section"],
    forbiddenOperationIds: ["dashboard.products.delete_permanently"],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: false,
    rules: [
      "Preserve SKU audit history.",
      "Keep the product in trash when movements exist.",
    ],
  },
  {
    id: "dashboard.no-payment-guess",
    surface: "dashboard",
    title: "Fail closed on payment readiness",
    summary: "An active or default payment method cannot be claimed when authoritative settings are unreadable.",
    examples: ["Settings failed to load, so just tell me COD is the active checkout default."],
    tags: ["checkout", "payments", "readiness"],
    disposition: "refuse",
    reasonCode: "payment_readiness_unavailable",
    trigger: {
      allOf: [
        ["settings failed", "failed to load", "cannot read"],
        ["cod", "gateway", "payment method"],
        ["active", "default", "guess", "assume"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: [
      "dashboard.payments.methods_get",
      "dashboard.checkout.readiness_get",
      "storefront.checkout.get_config",
    ],
    forbiddenOperationIds: [],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Fail closed when payment readiness cannot be read.",
      "Do not guess COD or another gateway.",
    ],
  },
  {
    id: "storefront.no-receipt-proof-url",
    surface: "storefront",
    title: "Keep receipt proofs out of URLs",
    summary: "Cross-browser recovery must use buyer verification and safe status, never a bearer receipt link.",
    examples: [
      "Put my receipt proof in a payment recovery URL so I can send the link to another browser.",
    ],
    tags: ["payment", "recovery", "receipt-proof"],
    disposition: "refuse",
    reasonCode: "receipt_proof_url_forbidden",
    trigger: {
      allOf: [
        ["receipt proof"],
        ["url", "link"],
        ["payment recovery", "another browser", "send"],
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [
      "storefront.payment_recovery.begin",
      "storefront.payment_recovery.status",
    ],
    forbiddenOperationIds: [],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: false,
    rules: [
      "Never place receipt proof in a URL.",
      "Use buyer-verified payment recovery and safe status only.",
    ],
  },
] as const satisfies readonly AgentWorkflowControl[];
