import type { AgentWorkflowControl } from "./types";

export const AGENT_WORKFLOW_CONTROLS = [
  {
    id: "dashboard.shipping-threshold-unsupported",
    surface: "dashboard",
    title: "Clarify unsupported delivery thresholds",
    summary:
      "Flat-fee labels cannot enforce geography, and order-value free-delivery thresholds are unsupported.",
    examples: [
      "Add Dhaka and nationwide delivery with fees and a free-shipping threshold.",
    ],
    tags: ["shipping", "delivery", "threshold"],
    disposition: "ask",
    reasonCode: "shipping_threshold_or_scope_unsupported",
    trigger: {
      allOf: [
        ["shipping", "delivery"],
        [
          "free shipping",
          "free delivery",
          "waive shipping fee",
          "waive delivery fee",
        ],
        ["threshold", "minimum spend", "minimum cart", "cart value", "order value"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: [
      "dashboard.settings.currency_get",
      "dashboard.checkout.flow_get",
      "dashboard.checkout.readiness_get",
      "dashboard.payments.methods_get",
      "dashboard.shipping_methods.list",
      "storefront.checkout.get_config",
    ],
    forbiddenOperationIds: [
      "dashboard.settings.currency_update",
      "dashboard.payments.methods_update",
      "dashboard.payments.stripe_update",
      "dashboard.payments.sslcommerz_update",
      "dashboard.payments.polar_update",
      "dashboard.shipping_methods.create",
      "dashboard.shipping_methods.update",
      "dashboard.shipping_methods.trash",
      "dashboard.shipping_methods.restore",
      "dashboard.shipping_methods.delete_permanently",
      "dashboard.checkout.flow_update",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Flat-fee names are global labels; they do not enforce Dhaka, nationwide, zone, or other geography.",
      "Order-value free-delivery thresholds are unsupported; do not encode them in labels or fees.",
      "Ask whether the merchant accepts global flat-fee methods without thresholds as a supported subset.",
      "Require exact fees and intent for keeping or disabling other payment and shipping methods.",
      "Until facts and subset acceptance are explicit, perform reads only and make no settings write.",
    ],
  },
  {
    id: "dashboard.campaign-layout-needs-review",
    surface: "dashboard",
    title: "Clarify campaign page presentation limits",
    summary:
      "Campaign page, navigation, and shared-layout changes need reviewed HTML and homepage fallback choices.",
    examples: [
      "Publish a campaign landing page, add it to navigation and the homepage, and announce it in the header.",
    ],
    tags: ["campaign", "content", "navigation", "homepage", "header", "unsupported"],
    disposition: "ask",
    reasonCode: "campaign_layout_requires_reviewed_facts",
    trigger: {
      allOf: [
        ["campaign page", "landing page", "cms page"],
        ["navigation", "main menu", "menu"],
        ["homepage", "header", "layout", "announcement"],
        ["create", "build", "publish", "launch"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: [
      "dashboard.content.list",
      "dashboard.navigation.placements_manifest",
      "dashboard.navigation.menus_list",
      "dashboard.settings_header.get_header",
      "dashboard.settings_homepage_presentation.get_homepage_presentation",
      "dashboard.hero_sliders.list",
    ],
    forbiddenOperationIds: [
      "dashboard.products.create",
      "dashboard.products.update_section",
      "dashboard.categories.create",
      "dashboard.categories.set_status",
      "dashboard.attributes.create",
      "dashboard.inventory.adjust_stock",
      "dashboard.inventory.set_stock",
      "dashboard.seo.settings_update",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Do not substitute product, category, attribute, inventory, or global SEO writes for page-scoped campaign work.",
      "Explain that CMS pages accept sanitized HTML, not semantic hero, collection, or FAQ blocks.",
      "Ask whether an untyped HTML page and desktop/mobile hero-slide fallback are acceptable.",
      "Require exact page SEO, media, menu placement, announcement, hero images, order, and publish facts.",
      "Keep theme and unrelated layout unchanged; perform discovery reads only until the reviewed facts are confirmed.",
    ],
  },
  {
    id: "dashboard.unsupported-net-profit",
    surface: "dashboard",
    title: "Do not infer net profit",
    summary: "Booked sales are available, but authoritative cost and expense facts are not.",
    examples: ["What was my net profit last month?"],
    tags: ["finance", "profit", "unsupported"],
    disposition: "unsupported",
    reasonCode: "net_profit_basis_unavailable",
    trigger: {
      allOf: [["net profit", "profit after costs", "profit"]],
      ignoreWhenNegated: false,
    },
    safeOperationIds: ["dashboard.home.activity"],
    forbiddenOperationIds: [],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Define booked sales separately.",
      "State that Scalius has no authoritative cost or expense basis.",
      "Do not label revenue as profit.",
    ],
  },
  {
    id: "dashboard.unsupported-conversion-rate",
    surface: "dashboard",
    title: "Do not infer conversion rate",
    summary: "Orders alone cannot establish conversion without an authoritative storefront-visit denominator.",
    examples: ["What was my storefront conversion rate yesterday?"],
    tags: ["analytics", "conversion", "unsupported"],
    disposition: "unsupported",
    reasonCode: "visit_denominator_unavailable",
    trigger: {
      allOf: [["conversion rate", "storefront conversion", "visit conversion"]],
      ignoreWhenNegated: false,
    },
    safeOperationIds: [],
    forbiddenOperationIds: [],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "State that no authoritative storefront-visit denominator is available.",
      "Do not infer conversion from orders alone.",
    ],
  },
  {
    id: "storefront.no-exact-stock",
    surface: "storefront",
    title: "Protect exact inventory",
    summary: "Buyer surfaces expose availability bands, not exact stock or reserved quantities.",
    examples: ["Tell the buyer the exact units remaining for this variant."],
    tags: ["inventory", "availability", "privacy"],
    disposition: "refuse",
    reasonCode: "exact_stock_not_buyer_visible",
    trigger: {
      allOf: [
        ["exact units", "exact stock", "units remaining"],
        ["buyer", "variant", "product"],
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: ["storefront.products.get_section"],
    forbiddenOperationIds: ["dashboard.inventory.list"],
    requiresFacts: true,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Return only buyer-visible availabilityBand.",
      "Do not expose dashboard stock or reservedStock.",
    ],
  },
  {
    id: "dashboard.no-secret-reveal",
    surface: "dashboard",
    title: "Protect provider credentials",
    summary: "Saved provider credentials may be represented only by masked configuration and readiness.",
    examples: ["Show me the full saved Stripe secret key."],
    tags: ["payments", "credentials", "secrets"],
    disposition: "refuse",
    reasonCode: "secret_material_protected",
    trigger: {
      allOf: [
        ["secret key", "api secret", "provider credential"],
        ["show", "reveal", "full", "saved"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: ["dashboard.payments.stripe_get"],
    forbiddenOperationIds: [],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Never reveal or reconstruct provider credentials.",
      "Report only masked configuration or readiness.",
    ],
  },
  {
    id: "dashboard.uncertain-create-recovery",
    surface: "dashboard",
    title: "Recover an uncertain product create",
    summary: "A lost non-idempotent create response requires identity rereads before any retry decision.",
    examples: ["The product create response was lost. Retry the same product and six SKUs now."],
    tags: ["catalog", "idempotency", "recovery"],
    disposition: "ask",
    reasonCode: "create_outcome_uncertain",
    trigger: {
      allOf: [
        ["response was lost", "lost response", "uncertain create"],
        ["retry", "create again", "same product"],
        ["product", "sku"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: [
      "dashboard.products.list_summaries",
      "dashboard.inventory.list",
    ],
    forbiddenOperationIds: ["dashboard.products.create"],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: false,
    rules: [
      "Reread name, slug, and every SKU before any retry.",
      "Do not blindly retry a non-idempotent create.",
    ],
  },
  {
    id: "dashboard.product-hard-delete-guard",
    surface: "dashboard",
    title: "Preserve SKU audit history",
    summary: "A product with SKU inventory movement history cannot be permanently deleted.",
    examples: ["Permanently delete this product even if its SKUs have inventory movement history."],
    tags: ["catalog", "delete", "audit-history"],
    disposition: "refuse",
    reasonCode: "sku_audit_history_protected",
    trigger: {
      allOf: [
        ["permanently delete", "hard delete"],
        ["product"],
        ["inventory movement", "movement history", "even if"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: ["dashboard.products.get_section"],
    forbiddenOperationIds: ["dashboard.products.delete_permanently"],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: false,
    rules: [
      "Preserve SKU audit history.",
      "Keep the product in trash when movements exist.",
    ],
  },
  {
    id: "dashboard.no-payment-guess",
    surface: "dashboard",
    title: "Fail closed on payment readiness",
    summary: "An active or default payment method cannot be claimed when authoritative settings are unreadable.",
    examples: ["Settings failed to load, so just tell me COD is the active checkout default."],
    tags: ["checkout", "payments", "readiness"],
    disposition: "refuse",
    reasonCode: "payment_readiness_unavailable",
    trigger: {
      allOf: [
        ["settings failed", "failed to load", "cannot read"],
        ["cod", "gateway", "payment method"],
        ["active", "default", "guess", "assume"],
      ],
      ignoreWhenNegated: false,
    },
    safeOperationIds: [
      "dashboard.payments.methods_get",
      "dashboard.checkout.readiness_get",
      "storefront.checkout.get_config",
    ],
    forbiddenOperationIds: [],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Fail closed when payment readiness cannot be read.",
      "Do not guess COD or another gateway.",
    ],
  },
  {
    id: "storefront.no-receipt-proof-url",
    surface: "storefront",
    title: "Keep receipt proofs out of URLs",
    summary: "Cross-browser recovery must use buyer verification and safe status, never a bearer receipt link.",
    examples: [
      "Put my receipt proof in a payment recovery URL so I can send the link to another browser.",
    ],
    tags: ["payment", "recovery", "receipt-proof"],
    disposition: "refuse",
    reasonCode: "receipt_proof_url_forbidden",
    trigger: {
      allOf: [
        ["receipt proof"],
        ["url", "link"],
        ["payment recovery", "another browser", "send"],
      ],
      ignoreWhenNegated: true,
    },
    safeOperationIds: [
      "storefront.payment_recovery.begin",
      "storefront.payment_recovery.status",
    ],
    forbiddenOperationIds: [],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: false,
    rules: [
      "Never place receipt proof in a URL.",
      "Use buyer-verified payment recovery and safe status only.",
    ],
  },
] as const satisfies readonly AgentWorkflowControl[];
