import type { AgentWorkflowIntentRoute } from "./types";

export const DASHBOARD_AGENT_WORKFLOW_ROUTES = [
  {
    id: "dashboard.daily-operations-snapshot",
    surface: "dashboard",
    kind: "read",
    title: "Daily operations snapshot",
    summary:
      "Read today's booked revenue and orders plus current fulfillment, low-stock, payment-recovery, and checkout readiness; collected cash and net settlement remain unavailable.",
    examples: [
      "How did my store do today—orders, booked revenue, collected cash, low stock, fulfillment backlog, failed-payment recovery work, and checkout readiness?",
    ],
    tags: ["operations", "sales", "daily", "payment-recovery"],
    workflowId: "operations.daily-snapshot.v1",
    operationIds: [
      "dashboard.home.activity",
      "dashboard.orders.list",
      "dashboard.orders.payment_recovery_list",
      "dashboard.inventory_alerts.list",
      "dashboard.checkout.readiness_get",
      "dashboard.payments.methods_get",
      "dashboard.shipping_methods.list",
      "dashboard.settings.currency_get",
    ],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Interpret activity.daily.bookedRevenue as Asia/Dhaka order-day booked gross, not collected cash, profit, or net settlement.",
      "No authoritative merchant-day collected-cash or net-settlement aggregate exists; report it unavailable, never zero or inferred.",
      "activity.paymentRecovery.total is all recoverable hosted-payment work; activity.paymentNeedsAttention.total is the actionable failed/stale subset; both are current non-transactional backlogs, not daily metrics.",
      "Never subtract the recovery totals because their parallel reads can observe different instants.",
      "Fail closed when fulfillment, stock, checkout, payment, delivery, or currency facts cannot be read.",
    ],
  },
  {
    id: "dashboard.sales-today",
    surface: "dashboard",
    kind: "read",
    title: "Today's sales and orders",
    summary: "Read today's booked sales total and order count from dashboard activity.",
    examples: ["What are today's sales and order count? Be clear about what sales means."],
    tags: ["sales", "orders", "today"],
    operationIds: ["dashboard.home.activity"],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Report booked sales rather than profit or settled cash.",
      "Preserve the returned period and currency context.",
    ],
  },
  {
    id: "dashboard.product-counts",
    surface: "dashboard",
    kind: "read",
    title: "Product status counts",
    summary: "Read active, draft, and trashed product counts.",
    examples: ["How many active, draft, and trashed products do I have?"],
    tags: ["catalog", "products", "counts"],
    operationIds: ["dashboard.products.stats"],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: ["Use the authoritative product status aggregates without inferring missing states."],
  },
  {
    id: "dashboard.low-stock",
    surface: "dashboard",
    kind: "read",
    title: "Low-stock products",
    summary: "List bounded inventory alerts for products and SKUs that need attention.",
    examples: ["Show me the products that are low or out of stock and still need attention."],
    tags: ["inventory", "low-stock", "alerts"],
    operationIds: ["dashboard.inventory_alerts.list"],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: ["Report only returned SKU-level inventory alerts and their supplied thresholds."],
  },
  {
    id: "dashboard.customer-history",
    surface: "dashboard",
    kind: "read",
    title: "Customer order history",
    summary: "Resolve one customer and read that customer's bounded order history.",
    examples: [
      "Find this customer and summarize their order history without exposing unrelated customers.",
    ],
    tags: ["customers", "orders", "history"],
    operationIds: ["dashboard.customers.list", "dashboard.customers.history"],
    requiresFacts: true,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Resolve one exact customer before reading history.",
      "Do not expose records belonging to unrelated customers.",
    ],
  },
  {
    id: "dashboard.complex-product-create",
    surface: "dashboard",
    kind: "mixed",
    title: "Create and publish an optioned product",
    summary:
      "Create an optioned product, publish its ready category, and verify admin and buyer discovery.",
    examples: [
      "Create a two-axis T-shirt with Size S/M/L and Color Black/White, exact SKUs, different stock and prices, color-specific images, category, Brand and Material attributes, rich description, SEO, sitemap and feed visibility, then verify buyer truth.",
    ],
    tags: ["catalog", "variants", "publishing", "verification"],
    workflowId: "catalog.optioned-product.v1",
    operationIds: [
      "dashboard.seo.settings_get",
      "dashboard.settings.currency_get",
      "dashboard.categories.form_options",
      "dashboard.attributes.list_summaries",
      "dashboard.products.list_summaries",
      "dashboard.categories.create",
      "dashboard.attributes.create",
      "dashboard.seo.settings_update",
      "dashboard.media.import_url",
      "dashboard.products.create",
      "dashboard.categories.publish_readiness",
      "dashboard.categories.set_status",
      "dashboard.products.get_section",
      "dashboard.categories.get_section",
      "dashboard.seo.feed_row_preview",
      "dashboard.seo.live_probe",
      "storefront.products.get_section",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Require the merchant's exact option axes, SKU matrix, prices, and stock facts.",
      "Resolve category, attribute, media, and product collisions; product creation owns SKU uniqueness.",
      "Create the product once and publish the category only when readiness passes.",
      "Confirm writes; verify bounded admin, feed, discovery, and storefront evidence.",
    ],
  },
  {
    id: "dashboard.product-section-update",
    surface: "dashboard",
    kind: "write",
    title: "Update one product section",
    summary: "Read and update one semantic product section using its current revision.",
    examples: [
      "Change only this product's SEO title and description without overwriting its variants or media.",
    ],
    tags: ["catalog", "products", "section-update"],
    operationIds: ["dashboard.products.get_section", "dashboard.products.update_section"],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Read the current semantic section and revision first.",
      "Write only the requested section and preserve unrelated product data.",
      "Confirm the write and verify the returned section state.",
    ],
  },
  {
    id: "dashboard.category-publish",
    surface: "dashboard",
    kind: "write",
    title: "Publish a category",
    summary: "Read a category, check publish readiness, and publish with its current revision.",
    examples: ["Publish this draft category if it is ready, using its current revision."],
    tags: ["categories", "publishing", "readiness"],
    operationIds: [
      "dashboard.categories.get_section",
      "dashboard.categories.publish_readiness",
      "dashboard.categories.set_status",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Use the exact category and current monotonic revision.",
      "Stop when publish readiness reports a blocker.",
      "Confirm publication and verify the status result.",
    ],
  },
  {
    id: "dashboard.inventory-cycle-count",
    surface: "dashboard",
    kind: "write",
    title: "Set counted stock",
    summary: "Resolve a SKU, set its absolute counted stock, and verify inventory state.",
    examples: [
      "Look up SKU ABC-123, set its physical count to 27, and verify the ledger-backed stock result.",
    ],
    tags: ["inventory", "cycle-count", "stock"],
    operationIds: [
      "dashboard.inventory.lookup_sku",
      "dashboard.inventory.set_stock",
      "dashboard.inventory.list",
    ],
    requiresFacts: false,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Resolve the exact SKU before changing stock.",
      "Use an absolute stock write with the required version and ledger reason.",
      "Confirm the mutation and verify the resulting SKU inventory.",
    ],
  },
  {
    id: "dashboard.inventory-relative-adjustment",
    surface: "dashboard",
    kind: "write",
    title: "Adjust SKU stock",
    summary: "Resolve a SKU and apply a reasoned relative stock adjustment.",
    examples: [
      "Record five damaged units against this SKU rather than replacing its absolute stock.",
    ],
    tags: ["inventory", "adjustment", "stock"],
    operationIds: ["dashboard.inventory.lookup_sku", "dashboard.inventory.adjust_stock"],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Require an exact SKU, signed quantity delta, and reason.",
      "Use relative adjustment rather than replacing absolute stock.",
      "Confirm the mutation and verify its returned ledger-backed result.",
    ],
  },
  {
    id: "dashboard.barcode-labels",
    surface: "dashboard",
    kind: "read",
    title: "Generate barcode labels",
    summary: "Preview selected SKU labels and generate a bounded label artifact.",
    examples: [
      "Preview barcode labels for these exact SKUs and generate a printable PDF only after the facts match.",
    ],
    tags: ["inventory", "barcodes", "artifact"],
    operationIds: [
      "dashboard.inventory_labels.preview",
      "dashboard.inventory_labels.generate_artifact",
    ],
    requiresFacts: true,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Preview the exact selected SKUs and label settings first.",
      "Return the bounded artifact handle rather than inline binary content.",
    ],
  },
  {
    id: "dashboard.media-upload",
    surface: "dashboard",
    kind: "write",
    title: "Upload product media",
    summary: "Initiate, transfer, complete, and verify a resumable media upload.",
    examples: [
      "Upload these local product images, wait until each is committed, and return the reusable media IDs.",
    ],
    tags: ["media", "upload", "products"],
    operationIds: [
      "dashboard.media.upload_initiate",
      "dashboard.media.upload_part",
      "dashboard.media.upload_complete",
      "dashboard.media.upload_get",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Follow the resumable upload sequence and supplied part boundaries.",
      "Do not use media identifiers until completion succeeds.",
      "Confirm the write and verify the final upload status.",
    ],
  },
  {
    id: "dashboard.collection-create",
    surface: "dashboard",
    kind: "write",
    title: "Create a collection",
    summary: "Resolve collection form options, create one collection, and verify its saved section.",
    examples: [
      "Create an active collection from these categories and products, including discovery metadata, then verify its bounded sections.",
    ],
    tags: ["collections", "catalog", "create"],
    operationIds: [
      "dashboard.collections.form_options",
      "dashboard.collections.create",
      "dashboard.collections.get_section",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Resolve exact category and product identifiers before creation.",
      "Require the merchant's collection title and membership rules.",
      "Confirm creation and verify the saved collection section.",
    ],
  },
  {
    id: "dashboard.promotion-lifecycle",
    surface: "dashboard",
    kind: "write",
    title: "Create and activate a promotion",
    summary: "Create a draft promotion, preview it, activate it when eligible, and verify it.",
    examples: [
      "Create a code promotion, preview the real evaluator result, and activate it only if eligible.",
    ],
    tags: ["promotions", "discounts", "activation"],
    operationIds: [
      "dashboard.promotions.create",
      "dashboard.promotions.preview",
      "dashboard.promotions.activate",
      "dashboard.promotions.get",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Create a draft from complete merchant-supplied promotion facts.",
      "Use the production preview and stop on eligibility errors.",
      "Confirm activation with the current revision, then verify the promotion.",
    ],
  },
  {
    id: "dashboard.discount-toggle",
    surface: "dashboard",
    kind: "write",
    title: "Toggle a discount code",
    summary: "Resolve one discount code, change its active state, and verify the result.",
    examples: ["Find the SAVE10 discount and deactivate it without deleting it."],
    tags: ["discounts", "codes", "activation"],
    operationIds: [
      "dashboard.discounts.list",
      "dashboard.discounts.set_active",
      "dashboard.discounts.get",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Resolve exactly one matching discount before mutation.",
      "Toggle active state without deleting or rewriting the discount.",
      "Confirm the change and verify the resulting discount record.",
    ],
  },
  {
    id: "dashboard.page-publish",
    surface: "dashboard",
    kind: "write",
    title: "Create and publish a page",
    summary: "Create a content page, publish its current record, and verify the public slug.",
    examples: [
      "Draft an About page with canonical and sitemap settings, publish it, and verify the public page.",
    ],
    tags: ["content", "pages", "publishing"],
    operationIds: [
      "dashboard.content.create",
      "dashboard.content.update",
      "storefront.pages.get_by_slug",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Require merchant-provided copy and discovery metadata.",
      "Create the draft, then publish only the current saved record.",
      "Confirm publication and verify the buyer-facing slug.",
    ],
  },
  {
    id: "dashboard.navigation-publish",
    surface: "dashboard",
    kind: "mixed",
    title: "Create and publish navigation",
    summary: "Resolve links, build and publish a menu, place it, and verify storefront navigation.",
    examples: [
      "Add a Shop menu with category and collection links, publish an immutable revision, place it in the header, and verify the storefront projection.",
    ],
    tags: ["navigation", "menus", "publishing"],
    operationIds: [
      "dashboard.navigation.resources_search",
      "dashboard.navigation.menus_create",
      "dashboard.navigation.items_create",
      "dashboard.navigation.menus_publish",
      "dashboard.navigation.placements_save",
      "storefront.navigation.placements_list",
      "storefront.navigation.menu_get_by_id",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Resolve every internal link target before creating items.",
      "Create the menu and items before producing an immutable published version.",
      "Save placement with its current revision after confirmation.",
      "Verify both placement and published menu through storefront reads.",
    ],
  },
  {
    id: "dashboard.campaign-content-supported-setup",
    surface: "dashboard",
    kind: "mixed",
    title: "Stage campaign",
    summary: "New page",
    examples: [
      "Create Eid page: slug/title/HTML/SEO/canonical/noIndex/excludeFromSitemap/media/alt, menu append, topBar, active-now desktop/mobile slides; accept sanitized draft, preserve all else, verify buyer.",
    ],
    tags: ["campaign"],
    operationIds: [
      "dashboard.content.list",
      "dashboard.navigation.placements_manifest",
      "dashboard.navigation.menus_list",
      "dashboard.navigation.items_search",
      "dashboard.settings_header.get_header",
      "dashboard.hero_sliders.list",
      "dashboard.media.list",
      "dashboard.media.import_url",
      "dashboard.content.create",
      "dashboard.content.get",
      "dashboard.content.bulk_publish",
      "dashboard.navigation.items_create",
      "dashboard.navigation.menus_publish",
      "dashboard.settings_header.header",
      "dashboard.hero_sliders.create",
      "dashboard.hero_sliders.update",
      "storefront.pages.get_by_slug",
      "storefront.navigation.get",
      "storefront.homepage.get",
      "storefront.layout.get",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Require exact page/SEO/media/menu/topBar/slides; staged non-atomic acceptance. Active now; canonical: same-store route path; absolute/query/fragment stops.",
      "Scan active/trash; any slug match stops. Create draft, accept sanitized reread, publish its revision.",
      "Clean published main menu, no page-target match anywhere: append top-level, publish returned revision; never update/move/reorder.",
      "CAS-merge topBar text/enabled only; no link. Preserve header/theme/shell.",
      "Max 3 HTTPS imports; preflight unique filename/folder. Uncertain: list and accept one unambiguous new exact match; never re-import blindly. Local/base64: upload/re-enter. Preserve full slider arrays; distinct desktop/mobile assets or approved reuse; no schedule.",
      "Non-atomic/no rollback. Conflict/uncertain create: reread/reconfirm, no retry; stop/report partial. Never catalog/global SEO or certify pixels, remote images/links, UI/head, sitemap XML.",
    ],
  },
  {
    id: "dashboard.theme-publish",
    surface: "dashboard",
    kind: "write",
    title: "Publish a theme draft",
    summary: "Read the theme workspace, save a draft, preview it, publish it, and verify layout.",
    examples: [
      "Change the storefront colors in the durable draft, preview the exact draft, and publish that revision.",
    ],
    tags: ["theme", "appearance", "publishing"],
    operationIds: [
      "dashboard.theme.workspace_get",
      "dashboard.theme.draft_save",
      "dashboard.theme.preview_session_create",
      "dashboard.theme.publish",
      "storefront.layout.get",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Read the current workspace and revision before saving a durable draft.",
      "Preview the exact saved draft before publication.",
      "Confirm publication and verify the resulting storefront layout.",
    ],
  },
  {
    id: "dashboard.checkout-readiness",
    surface: "dashboard",
    kind: "read",
    title: "Checkout readiness",
    summary: "Read saved checkout flow, readiness, active methods, and buyer-facing checkout config.",
    examples: [
      "Why is checkout not ready? Include the saved flow, active gateways, delivery options, and buyer-visible config.",
    ],
    tags: ["checkout", "payments", "shipping", "readiness"],
    operationIds: [
      "dashboard.checkout.flow_get",
      "dashboard.checkout.readiness_get",
      "dashboard.payments.methods_get",
      "dashboard.shipping_methods.list",
      "storefront.checkout.get_config",
    ],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Fail closed when any authoritative checkout setting cannot be read.",
      "Distinguish saved flow, admin readiness, and buyer-visible configuration.",
      "Never guess a payment or delivery method.",
    ],
  },
  {
    id: "dashboard.guest-checkout-conditional-enable",
    surface: "dashboard",
    kind: "write",
    title: "Conditionally enable guest access",
    summary:
      "Validate prerequisites, merge only the guest-access switch into the versioned flow, and verify buyer config.",
    examples: [
      "Turn on guest checkout only if payment and shipping are genuinely usable, without changing any other checkout setting.",
    ],
    tags: ["guest-access", "conditional-enable", "only-if", "preserve-settings"],
    operationIds: [
      "dashboard.checkout.flow_get",
      "dashboard.checkout.readiness_get",
      "dashboard.payments.methods_get",
      "dashboard.shipping_methods.list",
      "dashboard.checkout.flow_update",
      "storefront.checkout.get_config",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Read the complete versioned checkout flow and authoritative readiness before editing.",
      "Require at least one active buyer-usable payment method plus active shipping and delivery hierarchy.",
      "Fail closed without a change when readiness or method evidence is missing or contradictory.",
      "Merge only the guest-checkout field and preserve every unrelated flow setting.",
      "Confirm the exact diff, then reread saved flow and verify the separate buyer-facing checkout config.",
    ],
  },
  {
    id: "dashboard.checkout-flow-replace",
    surface: "dashboard",
    kind: "write",
    title: "Update checkout flow",
    summary: "Read the versioned checkout flow, merge requested changes, and verify buyer config.",
    examples: [
      "Require email and delivery instructions at checkout while preserving every other flow setting.",
    ],
    tags: ["checkout", "guest-checkout", "settings"],
    operationIds: [
      "dashboard.checkout.flow_get",
      "dashboard.checkout.flow_update",
      "storefront.checkout.get_config",
    ],
    requiresFacts: false,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Read the complete versioned checkout flow before editing.",
      "Merge only requested fields and preserve all unrelated settings.",
      "Confirm the write and verify the buyer-facing checkout config.",
    ],
  },
  {
    id: "dashboard.bangladesh-checkout-supported-setup",
    surface: "dashboard",
    kind: "mixed",
    title: "Bangladesh checkout setup",
    summary: "Apply reviewed Bangladesh payment, flat-fee, and guest setup; verify buyer truth.",
    examples: [
      "Configure accepted Bangladesh setup: supplied BDT symbol/rate; keep Dhaka time/phone fixed; preserve payments/default; add COD/proven SSLCommerz; active global Dhaka Delivery 80, Nationwide 150; accept no geography/threshold enforcement; turn on guests only after readiness; verify buyer checkout.",
    ],
    tags: ["bangladesh", "bdt", "checkout", "flat-fee"],
    operationIds: [
      "dashboard.settings.currency_get",
      "dashboard.payments.methods_get",
      "dashboard.shipping_methods.list",
      "dashboard.checkout.flow_get",
      "dashboard.settings.currency_update",
      "dashboard.payments.sslcommerz_update",
      "dashboard.payments.methods_update",
      "dashboard.shipping_methods.update",
      "dashboard.shipping_methods.create",
      "dashboard.checkout.readiness_get",
      "dashboard.checkout.flow_update",
      "storefront.checkout.get_config",
      "storefront.shipping_methods.list",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Require global labels accepted without geography/threshold; Dhaka time and mandatory phone stay fixed.",
      "BDT needs unlocked code, explicit symbol, positive USD rate; write/reread all or stop.",
      "Set only {enabled:true} after configured/no-error SSLCommerz status; no secrets/sandbox. Reread usable; no charge proof.",
      "Require keep/disable intent per payment and exact default; union COD/usable SSLCommerz into fresh enabledMethods. Never choose.",
      "Require merchant name/fee/active/optional sort. One active exact match: update; none: create; near/duplicate/trashed: ask; never delete.",
      "Require readiness + active shipping/delivery hierarchy; revision-merge guest only. Failure: stop/reread/report partial; no rollback/retry. Never touch SEO/analytics; verify both audiences.",
    ],
  },
  {
    id: "dashboard.payment-methods",
    surface: "dashboard",
    kind: "write",
    title: "Configure payment methods",
    summary: "Read payment configuration, update enabled and default methods, and verify checkout.",
    examples: [
      "Make COD active and default only if it is actually configured, then verify the buyer sees it.",
    ],
    tags: ["payments", "checkout", "configuration"],
    operationIds: [
      "dashboard.payments.methods_get",
      "dashboard.payments.methods_update",
      "storefront.checkout.get_config",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Read the complete payment-method configuration first.",
      "Activate or default only a method that is truthfully configured.",
      "Confirm the write, fail closed on missing settings, and verify checkout.",
    ],
  },
  {
    id: "dashboard.business-seo-settings",
    surface: "dashboard",
    kind: "write",
    title: "Update business identity and SEO",
    summary: "Read and safely merge business and SEO settings, then verify public discovery.",
    examples: [
      "Update the legal business name and product-feed title without replacing unrelated business or SEO settings, then verify public schema and feeds.",
    ],
    tags: ["business", "seo", "identity", "settings"],
    operationIds: [
      "dashboard.settings.business_get",
      "dashboard.seo.settings_get",
      "dashboard.settings.business_update",
      "dashboard.seo.settings_update",
      "dashboard.seo.live_probe",
      "storefront.seo.get",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Read business and SEO settings as separate current documents.",
      "Merge only supplied identity and discovery fields; preserve unrelated settings.",
      "Confirm both writes, then verify public SEO and bounded live-probe evidence.",
    ],
  },
  {
    id: "dashboard.shipping-method",
    surface: "dashboard",
    kind: "write",
    title: "Create a shipping method",
    summary: "Create a globally offered flat-fee shipping method and verify admin and storefront visibility.",
    examples: [
      "Add a Dhaka delivery method with the merchant-provided price and make sure it appears at checkout.",
    ],
    tags: ["shipping", "delivery", "checkout"],
    operationIds: [
      "dashboard.shipping_methods.create",
      "dashboard.shipping_methods.list",
      "storefront.shipping_methods.list",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Require the merchant-supplied label, fee, active state, and sort order.",
      "Treat the label as display text; flat-fee methods do not enforce a geographic service area.",
      "Confirm creation before the write.",
      "Verify the method in bounded admin and buyer-facing lists.",
    ],
  },
  {
    id: "dashboard.tax-configuration",
    surface: "dashboard",
    kind: "mixed",
    title: "Configure a tax rate",
    summary: "Read tax references, create a rate, preview a calculation, and verify configured rates.",
    examples: [
      "Configure a VAT rate for the supplied jurisdiction and class, preview a real cart calculation, then verify versioned settings.",
    ],
    tags: ["tax", "rates", "jurisdictions", "configuration"],
    operationIds: [
      "dashboard.taxes.settings_get",
      "dashboard.taxes.jurisdictions_list",
      "dashboard.taxes.classes_list",
      "dashboard.taxes.rates_create",
      "dashboard.taxes.preview",
      "dashboard.taxes.rates_list",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Resolve exact jurisdiction and tax-class identifiers.",
      "Require merchant-supplied rate, scope, and effective facts.",
      "Confirm the rate write, then preview a real calculation and verify the list.",
    ],
  },
  {
    id: "dashboard.delivery-provider",
    surface: "dashboard",
    kind: "write",
    title: "Connect a delivery provider",
    summary: "Test supplied credentials, create the provider connection, and test the saved connection.",
    examples: [
      "Test these courier credentials before saving a provider, then verify the saved connection without logging credentials.",
    ],
    tags: ["delivery", "provider", "credentials"],
    operationIds: [
      "dashboard.delivery_providers.test_credentials",
      "dashboard.delivery_providers.create",
      "dashboard.delivery_providers.test",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Never log or return raw provider credentials.",
      "Test credentials before saving the connection.",
      "Confirm creation, then test the saved provider record.",
    ],
  },
  {
    id: "dashboard.delivery-location-import",
    surface: "dashboard",
    kind: "write",
    title: "Import delivery locations",
    summary: "Read Pathao import status and advance the import by one bounded chunk.",
    examples: [
      "Resume the Pathao location import in bounded chunks and report progress until it reaches a terminal state.",
    ],
    tags: ["delivery", "locations", "import"],
    operationIds: [
      "dashboard.delivery_locations.pathao_import_status",
      "dashboard.delivery_locations.pathao_import_chunk",
    ],
    requiresFacts: false,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Read import status before dispatching a chunk.",
      "Process only one bounded chunk at a time.",
      "Stop on terminal or failed state and verify returned progress.",
    ],
  },
  {
    id: "dashboard.order-fulfill",
    surface: "dashboard",
    kind: "write",
    title: "Fulfill an order",
    summary: "Read an order, record fulfillment with supplied tracking facts, and verify it.",
    examples: [
      "Manually fulfill this paid order with the supplied tracking facts and verify shipment state.",
    ],
    tags: ["orders", "fulfillment", "tracking"],
    operationIds: [
      "dashboard.orders.get",
      "dashboard.orders.fulfill",
      "dashboard.orders.fulfillment_get",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Read the exact order and current fulfillment state first.",
      "Require merchant-supplied shipment and tracking facts.",
      "Confirm fulfillment and verify the resulting shipment record.",
    ],
  },
  {
    id: "dashboard.order-provider-shipment",
    surface: "dashboard",
    kind: "write",
    title: "Create a provider shipment",
    summary: "Read an order, create its external provider shipment, and verify provider state.",
    examples: [
      "Create a courier shipment for this order using its configured provider and verify the provider tracking record.",
    ],
    tags: ["orders", "shipping", "provider"],
    operationIds: [
      "dashboard.orders.get",
      "dashboard.orders.create_shipment",
      "dashboard.orders.shipments",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Read the exact current order and selected provider first.",
      "Confirm before creating an external shipment side effect.",
      "Verify the returned provider shipment record without blind retries.",
    ],
  },
  {
    id: "dashboard.order-refund",
    surface: "dashboard",
    kind: "write",
    title: "Refund an order payment",
    summary: "Resolve a captured payment, issue an exact refund, and reconcile provider state.",
    examples: [
      "Refund the exact supplied amount for this captured payment and reconcile any uncertain provider result.",
    ],
    tags: ["orders", "payments", "refund"],
    operationIds: [
      "dashboard.orders.payments",
      "dashboard.orders.refund",
      "dashboard.orders.refund_reconcile",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Resolve the exact captured payment and validate the refund amount.",
      "Require confirmation immediately before the financial action.",
      "Reconcile uncertain provider results instead of retrying a refund blindly.",
    ],
  },
  {
    id: "dashboard.order-return",
    surface: "dashboard",
    kind: "write",
    title: "Process an order return",
    summary: "Create, approve, receive, and verify an item-level order return.",
    examples: [
      "Create, approve, and receive an item-level return, restoring stock only through the return workflow.",
    ],
    tags: ["orders", "returns", "inventory"],
    operationIds: [
      "dashboard.orders.return_create",
      "dashboard.orders.return_approve",
      "dashboard.orders.return_receive",
      "dashboard.orders.return_get",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Require exact order items, quantities, reason, and disposition.",
      "Confirm each lifecycle mutation against the current return state.",
      "Change stock only through receipt, then verify the completed return.",
    ],
  },
  {
    id: "dashboard.invoice-issue",
    surface: "dashboard",
    kind: "write",
    title: "Issue an order invoice",
    summary: "Review the draft invoice, issue it once, and return its verified print artifact.",
    examples: [
      "Preview this order's draft invoice, issue its immutable number once, and generate the printable artifact.",
    ],
    tags: ["orders", "invoice", "artifact"],
    operationIds: [
      "dashboard.orders.invoice_get",
      "dashboard.orders.invoice_issue",
      "dashboard.orders.invoice_print",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Review the exact draft invoice before issuing it.",
      "Confirm the one-time issue action against current authority.",
      "Do not retry uncertain issuance; print only the verified immutable invoice.",
    ],
  },
  {
    id: "dashboard.order-export",
    surface: "dashboard",
    kind: "read",
    title: "Export filtered orders",
    summary: "Export orders using explicit bounded status and date filters.",
    examples: ["Export last month's completed orders as the bounded CSV artifact."],
    tags: ["orders", "export", "artifact"],
    operationIds: ["dashboard.orders.export"],
    requiresFacts: true,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Require explicit bounded filters and an exact date range.",
      "Return the artifact handle rather than embedding export bytes.",
    ],
  },
  {
    id: "dashboard.notification-rules",
    surface: "dashboard",
    kind: "write",
    title: "Update customer notification rules",
    summary: "Read complete notification rules, change one event channel, and verify the settings.",
    examples: [
      "Enable customer SMS for shipped orders but keep every other notification rule unchanged.",
    ],
    tags: ["notifications", "customers", "sms"],
    operationIds: [
      "dashboard.notifications.customer_rules_get",
      "dashboard.notifications.customer_rules_update",
    ],
    requiresFacts: false,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Read the complete current rule set before editing.",
      "Change only the requested event and channel; preserve all other rules.",
      "Confirm the write and verify the returned settings.",
    ],
  },
  {
    id: "dashboard.analytics-provider",
    surface: "dashboard",
    kind: "write",
    title: "Configure an analytics provider",
    summary: "Create an inactive analytics configuration, activate it, and verify provider health.",
    examples: [
      "Create a Cloudflare Web Analytics draft with a real token, activate it with revision protection, and verify readiness.",
    ],
    tags: ["analytics", "provider", "activation"],
    operationIds: [
      "dashboard.analytics.create",
      "dashboard.analytics.set_active",
      "dashboard.analytics.health",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Reject placeholder tokens and snippets before creating configuration.",
      "Create an inactive draft before activation.",
      "Confirm activation with current revision, then verify bounded health evidence.",
    ],
  },
  {
    id: "dashboard.meta-capi",
    surface: "dashboard",
    kind: "write",
    title: "Configure Meta Conversions API",
    summary: "Read and update Meta conversion settings, then inspect bounded safe delivery logs.",
    examples: [
      "Configure Meta Conversions API with supplied credentials and verify settings without provider payload logs.",
    ],
    tags: ["analytics", "meta", "capi", "credentials"],
    operationIds: [
      "dashboard.meta_conversions.get",
      "dashboard.meta_conversions.update",
      "dashboard.meta_conversions.logs_list",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Never log or return credentials, buyer data, or raw provider payloads.",
      "Merge only supplied fields into the current settings.",
      "Confirm the security-sensitive write and verify with bounded safe log metadata.",
    ],
  },
  {
    id: "dashboard.fraud-check",
    surface: "dashboard",
    kind: "read",
    title: "Check a phone for fraud signals",
    summary: "Run a bounded fraud lookup for one merchant-supplied phone number.",
    examples: [
      "Check this buyer phone against the configured fraud provider and return only the bounded result.",
    ],
    tags: ["fraud", "customers", "lookup"],
    operationIds: ["dashboard.fraud_lookup.run"],
    requiresFacts: true,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Use only the exact phone number supplied for the lookup.",
      "Return bounded provider evidence without unrelated personal data or inference.",
    ],
  },
  {
    id: "dashboard.team-invite",
    surface: "dashboard",
    kind: "write",
    title: "Invite a team member",
    summary: "Resolve an existing role, invite one team member, and verify membership state.",
    examples: [
      "Invite a support administrator with the least-privilege existing role and verify the assignment.",
    ],
    tags: ["team", "roles", "invite", "security"],
    operationIds: [
      "dashboard.team.roles.list",
      "dashboard.team.users.invite",
      "dashboard.team.users.list",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Resolve an existing least-privilege role for the stated duties.",
      "Confirm the security-sensitive invite before dispatch.",
      "Verify the pending member and assigned role in the team list.",
    ],
  },
  {
    id: "dashboard.account-sessions",
    surface: "dashboard",
    kind: "write",
    title: "Revoke an account session",
    summary: "List account sessions, resolve one non-current session, and revoke it.",
    examples: [
      "List my active sessions and revoke the one I identify, not the current session.",
    ],
    tags: ["account", "sessions", "security"],
    operationIds: ["dashboard.account.sessions.list", "dashboard.account.sessions.revoke"],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "List sessions and resolve the exact non-current target first.",
      "Never revoke the current session unless explicitly and safely supported.",
      "Confirm revocation and verify the operation result.",
    ],
  },
  {
    id: "dashboard.agent-grant-narrow",
    surface: "dashboard",
    kind: "write",
    title: "Narrow an agent grant",
    summary: "Read one agent connection and reduce its granted operation scope.",
    examples: ["Show this agent connection and narrow its grant to read-only catalog access."],
    tags: ["agent-access", "grants", "security"],
    operationIds: [
      "dashboard.agent_access.connections.get",
      "dashboard.agent_access.grants.update",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Read the exact connection and its current authority first.",
      "Apply only a narrowing change; never broaden authority through this route.",
      "Confirm the security write and verify its returned grant state.",
    ],
  },
  {
    id: "dashboard.header-footer-homepage",
    surface: "dashboard",
    kind: "mixed",
    title: "Update storefront presentation settings",
    summary: "Read, safely update, and verify header, footer, and homepage presentation settings.",
    examples: [
      "Update the header logo, footer support links, and homepage category order while preserving each current revision, then verify layout and homepage.",
    ],
    tags: ["storefront", "header", "footer", "homepage"],
    operationIds: [
      "dashboard.settings_header.get_header",
      "dashboard.settings_footer.get_footer",
      "dashboard.settings_homepage_presentation.get_homepage_presentation",
      "dashboard.settings_header.header",
      "dashboard.settings_footer.footer",
      "dashboard.settings_homepage_presentation.homepage_presentation",
      "storefront.layout.get",
      "storefront.homepage.get",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Read each current settings document and revision independently.",
      "Merge only requested fields and preserve unrelated presentation settings.",
      "Confirm the writes, then verify storefront layout and homepage projections.",
    ],
  },
  {
    id: "dashboard.storefront-origin",
    surface: "dashboard",
    kind: "write",
    title: "Update storefront origin",
    summary: "Read and update the canonical storefront URL, then probe public discovery.",
    examples: [
      "Change the canonical storefront origin only after validating it is absolute HTTPS, then probe discovery resources.",
    ],
    tags: ["storefront", "url", "seo", "origin"],
    operationIds: [
      "dashboard.settings.storefront_url_get",
      "dashboard.settings.storefront_url_update",
      "dashboard.seo.live_probe",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Read the current storefront URL before replacement.",
      "Require an absolute HTTPS URL for the merchant's intended origin.",
      "Confirm the write, then probe canonical discovery surfaces.",
    ],
  },
  {
    id: "dashboard.cache-purge-selected",
    surface: "dashboard",
    kind: "write",
    title: "Purge selected cache groups",
    summary: "List valid cache groups and purge only the selected product and feed groups.",
    examples: [
      "List cache domains and purge only product and feed caches, not every public cache.",
    ],
    tags: ["cache", "products", "feeds", "operations"],
    operationIds: ["dashboard.cache.groups_list", "dashboard.cache.purge_groups"],
    requiresFacts: false,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Resolve valid cache group names before mutation.",
      "Select only the requested product and feed groups; never expand to purge-all.",
      "Confirm the selected purge and verify the bounded operation result.",
    ],
  },
] satisfies readonly AgentWorkflowIntentRoute[];
