import type { AgentWorkflowIntentRoute } from "./types";

export const AGENT_STOREFRONT_INTENT_ROUTES = [
  {
    id: "storefront.product-research",
    surface: "storefront",
    kind: "read",
    title: "Research a product",
    summary: "Find products and inspect exact buyer-visible option, image, price, and availability projections.",
    examples: [
      "Find a black cotton shirt under 1200, show its options, images, price, and availability without claiming exact stock.",
    ],
    tags: ["catalog", "search", "availability"],
    operationIds: [
      "storefront.search.predict",
      "storefront.products.list",
      "storefront.products.get_section",
    ],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Treat buyer-visible availabilityBand as stock truth; never claim an exact quantity.",
      "Resolve exact product and variant identities from bounded public results.",
    ],
  },
  {
    id: "storefront.category-filter",
    surface: "storefront",
    kind: "read",
    title: "Browse a filtered category",
    summary: "Read a category's declared filters and continue its bounded product listing.",
    examples: [
      "Browse this category and show only its valid filterable attributes and the next product page.",
    ],
    tags: ["catalog", "categories", "filters"],
    operationIds: [
      "storefront.categories.get_section",
      "storefront.attributes.list_for_category",
      "storefront.categories.list_product_summaries",
    ],
    requiresFacts: true,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: [
      "Use the resolved category ID, returned filter definitions, and declared pagination only.",
      "Never invent a filter or total a partial page.",
    ],
  },
  {
    id: "storefront.homepage-layout",
    surface: "storefront",
    kind: "read",
    title: "Summarize storefront presentation",
    summary: "Read the published homepage and shared buyer-visible layout projection.",
    examples: [
      "Summarize the buyer-visible homepage, header, navigation, currency, theme, and store policies.",
    ],
    tags: ["homepage", "layout", "presentation"],
    operationIds: ["storefront.homepage.get", "storefront.layout.get"],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: ["Report only values present in the published buyer projection."],
  },
  {
    id: "storefront.checkout-journey",
    surface: "storefront",
    kind: "mixed",
    title: "Complete a buyer checkout",
    summary: "Create a buyer context, build and validate its cart, submit once, and read a safe receipt.",
    examples: [
      "Start a buyer context, add this exact variant, set delivery, apply the supplied code, quote, validate, place the order idempotently, and return a safe receipt.",
    ],
    tags: ["cart", "checkout", "receipt"],
    operationIds: [
      "storefront.context.create",
      "storefront.cart.add",
      "storefront.delivery.set",
      "storefront.discount.apply",
      "storefront.checkout.quote",
      "storefront.checkout.validate",
      "storefront.checkout.submit",
      "storefront.receipt.get",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Resolve exact variant and delivery IDs, then thread the current context revision through each write.",
      "Review the quote and validation result before confirmed checkout submission with one canonical idempotency key.",
      "Keep receipt proofs, payment secrets, and continuation fields out of model-visible output.",
    ],
  },
  {
    id: "storefront.cart-edit",
    surface: "storefront",
    kind: "write",
    title: "Edit a cart quantity",
    summary: "Set one resolved cart variant quantity and return the recalculated cart.",
    examples: [
      "Change the quantity of the identified cart variant to three and return the revalidated cart.",
    ],
    tags: ["cart", "quantity"],
    operationIds: ["storefront.cart.set_quantity", "storefront.cart.get"],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Use the exact variant and current context revision; never submit a client price or stock value.",
      "Verify with the returned and reread cart projection.",
    ],
  },
  {
    id: "storefront.delivery-search",
    surface: "storefront",
    kind: "read",
    title: "Resolve a delivery location",
    summary: "Search city, then zone, then area summaries without selecting a delivery option.",
    examples: [
      "Find the buyer's city, zone, and area with bounded searches before selecting delivery.",
    ],
    tags: ["delivery", "locations", "search"],
    operationIds: [
      "storefront.locations.city_summaries",
      "storefront.locations.zone_summaries",
      "storefront.locations.area_summaries",
    ],
    requiresFacts: true,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: ["Resolve each parent ID before the next bounded search; never infer location IDs."],
  },
  {
    id: "storefront.customer-login",
    surface: "storefront",
    kind: "write",
    title: "Authorize a customer",
    summary: "Begin the reviewed customer authorization handoff and read only its safe status.",
    examples: [
      "Start secure customer authorization, let the buyer complete the browser step, then report safe status.",
    ],
    tags: ["customer", "authentication", "continuation"],
    operationIds: [
      "storefront.customer_auth.begin",
      "storefront.customer_auth.status",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Use only the fixed reviewed browser continuation and safe status operation.",
      "Never expose credentials, OTPs, customer cookies, or continuation fields.",
    ],
  },
  {
    id: "storefront.customer-profile",
    surface: "storefront",
    kind: "write",
    title: "Update a customer profile",
    summary: "Read, update, and verify the current authorized customer's delivery profile.",
    examples: [
      "Update my authorized delivery profile after showing the current values, then verify it.",
    ],
    tags: ["customer", "profile", "delivery"],
    operationIds: [
      "storefront.customer_profile.get",
      "storefront.customer_profile.update",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Require a live customer-bound context and preserve any current values the buyer did not change.",
      "Verify only the authorized customer's profile.",
    ],
  },
  {
    id: "storefront.order-support",
    surface: "storefront",
    kind: "write",
    title: "Request order support",
    summary: "Read one authorized customer order and submit a support request against it.",
    examples: [
      "Show my order, submit this support request against it, and do not expose any other buyer's order.",
    ],
    tags: ["orders", "customer", "support"],
    operationIds: [
      "storefront.orders.get",
      "storefront.orders.support_request.create",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Require customer-bound authority for the exact order and never expose another buyer's data.",
      "Treat the created support request result as bounded verification evidence.",
    ],
  },
  {
    id: "storefront.hosted-payment",
    surface: "storefront",
    kind: "mixed",
    title: "Complete hosted payment",
    summary: "Begin payment for an authorized order and poll only its safe status after browser handoff.",
    examples: [
      "Start secure payment for my authorized order and poll only the safe payment status after I finish the browser step.",
    ],
    tags: ["orders", "payment", "continuation"],
    operationIds: [
      "storefront.orders.payment.begin",
      "storefront.payment.status",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Require customer-bound order authority and use only the fixed reviewed browser continuation.",
      "Poll only the safe status operation; never expose payment secrets or provider payloads.",
    ],
  },
  {
    id: "storefront.payment-recovery",
    surface: "storefront",
    kind: "mixed",
    title: "Recover payment access",
    summary: "Use buyer verification to recover payment access and report only safe recovery status.",
    examples: [
      "Recover payment access for my order through buyer verification; never put a receipt proof in a URL.",
    ],
    tags: ["payment", "recovery", "buyer-verification"],
    operationIds: [
      "storefront.payment_recovery.begin",
      "storefront.payment_recovery.status",
    ],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: true,
    rules: [
      "Use buyer-verified recovery and its safe status only.",
      "Never place receipt proof, OTP, or bearer material in a URL or model-visible output.",
    ],
  },
  {
    id: "storefront.content-discovery",
    surface: "storefront",
    kind: "read",
    title: "Discover public content",
    summary: "Find and read published pages and articles through bounded public content operations.",
    examples: [
      "Find the returns page and the newest help article, using only published public content.",
    ],
    tags: ["content", "pages", "articles"],
    operationIds: [
      "storefront.pages.list",
      "storefront.pages.get_by_slug",
      "storefront.articles.list",
      "storefront.articles.get_by_slug",
    ],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: ["Use only published public results and resolve the exact slug before detail reads."],
  },
  {
    id: "storefront.navigation-tree",
    surface: "storefront",
    kind: "read",
    title: "Read published navigation",
    summary: "Read current placements and expand one requested branch of a published menu.",
    examples: [
      "Show the current published header navigation and expand one menu branch without loading the entire tree.",
    ],
    tags: ["navigation", "menus", "layout"],
    operationIds: [
      "storefront.navigation.placements_list",
      "storefront.navigation.items_list",
    ],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: ["Resolve the placed menu and request only the needed bounded branch."],
  },
  {
    id: "storefront.checkout-options",
    surface: "storefront",
    kind: "read",
    title: "Read buyer checkout options",
    summary: "Read buyer-visible checkout, language, payment, authentication, and delivery configuration.",
    examples: [
      "What payment gateways, customer-auth rules, language, and shipping methods can this buyer actually use?",
    ],
    tags: ["checkout", "payment", "delivery"],
    operationIds: [
      "storefront.checkout.get_config",
      "storefront.checkout_language.get_active",
      "storefront.shipping_methods.list",
    ],
    requiresFacts: false,
    requiresConfirmation: false,
    requiresVerification: false,
    rules: ["Report only active buyer-visible options and fail closed when configuration cannot be read."],
  },
  {
    id: "storefront.close-context",
    surface: "storefront",
    kind: "write",
    title: "Close a buyer context",
    summary: "Close one identified buyer context and clear its bound cart and session authority.",
    examples: ["Close this buyer context and clear its bound cart/session authority."],
    tags: ["context", "cart", "session"],
    operationIds: ["storefront.context.close"],
    requiresFacts: true,
    requiresConfirmation: true,
    requiresVerification: false,
    rules: [
      "Resolve the exact context ID and confirm closure because its cart/session authority is discarded.",
    ],
  },
] as const satisfies readonly AgentWorkflowIntentRoute[];
