// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type _Error = {
    success?: boolean;
    error?: string;
    message?: string;
};

export type Success = {
    success?: boolean;
    data?: {
        [key: string]: unknown;
    };
};

export type OrderPostRequest = {
    customerName: string;
    customerPhone: string;
    customerEmail?: string | null;
    shippingAddress: string;
    /**
     * City ID from /locations/cities.
     */
    city: string;
    /**
     * Zone ID from /locations/zones.
     */
    zone: string;
    /**
     * Area ID from /locations/areas (optional).
     */
    area?: string | null;
    /**
     * Name of the city (for record-keeping). Optional, as it can be looked up from the city ID, but providing it can be a useful fallback.
     */
    cityName?: string | null;
    /**
     * Name of the zone (for record-keeping). Optional, can be looked up from zone ID.
     */
    zoneName?: string | null;
    /**
     * Name of the area (for record-keeping). Optional, can be looked up from area ID.
     */
    areaName?: string | null;
    notes?: string | null;
    items: Array<{
        productId: string;
        variantId?: string | null;
        quantity: number;
        /**
         * The final price per unit for this item, after any product-level discounts but before order-level discounts.
         */
        price: number;
    }>;
    /**
     * The total amount of discount applied to the order.
     */
    discountAmount?: number | null;
    /**
     * The discount code used, if any. This is used for logging usage.
     */
    discountCode?: string | null;
    shippingCharge: number;
    /**
     * The final total amount of the order. If not provided, it will be calculated on the server as: (items total) + shippingCharge - discountAmount.
     */
    totalAmount?: number | null;
};

export type GetAuthTokenData = {
    body?: never;
    headers: {
        /**
         * The static, pre-shared API token for your service.
         */
        'X-API-Token': string;
    };
    path?: never;
    query?: never;
    url: '/auth/token';
};

export type GetAuthTokenErrors = {
    /**
     * Unauthorized. The provided `X-API-Token` was missing or invalid.
     */
    401: _Error;
};

export type GetAuthTokenError = GetAuthTokenErrors[keyof GetAuthTokenErrors];

export type GetAuthTokenResponses = {
    /**
     * Successfully generated and returned a JWT.
     */
    200: {
        success?: boolean;
        data?: {
            /**
             * The JWT to be used for authenticating subsequent requests.
             */
            token?: string;
        };
    };
};

export type GetAuthTokenResponse = GetAuthTokenResponses[keyof GetAuthTokenResponses];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeErrors = {
    /**
     * Unauthorized. The provided JWT was missing, invalid, or expired.
     */
    401: _Error;
};

export type GetAuthMeError = GetAuthMeErrors[keyof GetAuthMeErrors];

export type GetAuthMeResponses = {
    /**
     * Successfully retrieved identity information.
     */
    200: {
        success?: boolean;
        data?: {
            user?: {
                id?: string;
                email?: string;
                name?: string;
                role?: string;
            };
        };
    };
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type PostAuthRevokeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/revoke';
};

export type PostAuthRevokeErrors = {
    400: unknown;
    500: unknown;
};

export type PostAuthRevokeResponses = {
    /**
     * Successfully revoked the token.
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type PostAuthRevokeResponse = PostAuthRevokeResponses[keyof PostAuthRevokeResponses];

export type GetAuthTokenStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/token-stats';
};

export type GetAuthTokenStatsErrors = {
    401: unknown;
    /**
     * Forbidden. The authenticated user does not have sufficient permissions.
     */
    403: _Error;
};

export type GetAuthTokenStatsError = GetAuthTokenStatsErrors[keyof GetAuthTokenStatsErrors];

export type GetAuthTokenStatsResponses = {
    /**
     * Token system statistics.
     */
    200: {
        success?: boolean;
        data?: {
            blacklistedTokensCount?: number;
            /**
             * A partially redacted view of the JWT secret.
             */
            jwtSecret?: string;
            /**
             * Indicates if the insecure default secret is being used.
             */
            isUsingDefaultSecret?: boolean;
        };
    };
};

export type GetAuthTokenStatsResponse = GetAuthTokenStatsResponses[keyof GetAuthTokenStatsResponses];

export type GetProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination.
         */
        page?: number;
        /**
         * Number of products per page.
         */
        limit?: number;
        /**
         * Filter by a specific category ID.
         */
        category?: string;
        /**
         * Search term to filter products by name.
         */
        search?: string;
        /**
         * Sort order for the products.
         */
        sort?: 'newest' | 'price-asc' | 'price-desc' | 'name-asc' | 'name-desc' | 'discount';
        /**
         * Filter by a minimum price.
         */
        minPrice?: number;
        /**
         * Filter by a maximum price.
         */
        maxPrice?: number;
        /**
         * Filter for products that have free delivery.
         */
        freeDelivery?: 'true' | 'false';
        /**
         * Filter for products that have a discount.
         */
        hasDiscount?: 'true' | 'false';
        /**
         * Fetch a specific set of products by their comma-separated IDs.
         */
        ids?: string;
        /**
         * Dynamically filter by any attribute slug (e.g., `brand=Samsung`, `warranty=2-year`). Obtain available attribute slugs from the `/attributes/filterable` endpoint. Multiple attribute filters can be combined.
         */
        '[attribute_slug]'?: string;
    };
    url: '/products';
};

export type GetProductsErrors = {
    /**
     * Server Error - Failed to fetch products
     */
    500: _Error;
};

export type GetProductsError = GetProductsErrors[keyof GetProductsErrors];

export type GetProductsResponses = {
    /**
     * A paginated list of products.
     */
    200: {
        products?: Array<{
            id?: string;
            name?: string;
            price?: number;
            slug?: string;
            /**
             * Type of discount applied to the product
             */
            discountType?: 'percentage' | 'flat';
            /**
             * Discount percentage (0-100) when discountType is 'percentage'
             */
            discountPercentage?: number | null;
            /**
             * Flat discount amount when discountType is 'flat'
             */
            discountAmount?: number | null;
            freeDelivery?: boolean;
            categoryId?: string;
            /**
             * URL of the product's primary image.
             */
            imageUrl?: string | null;
            category?: {
                id?: string;
                name?: string;
                slug?: string;
            } | null;
            /**
             * The price after the discount percentage has been applied. Equal to `price` if no discount.
             */
            discountedPrice?: number;
            /**
             * Indicates if the product has multiple variants (e.g., by size or color).
             */
            hasVariants?: boolean;
            createdAt?: string;
            updatedAt?: string;
        }>;
        pagination?: {
            page?: number;
            limit?: number;
            total?: number;
            totalPages?: number;
        };
    };
};

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses];

export type GetProductsBySlugData = {
    body?: never;
    path: {
        /**
         * The URL-friendly slug of the product to retrieve.
         */
        slug: string;
    };
    query?: never;
    url: '/products/{slug}';
};

export type GetProductsBySlugErrors = {
    /**
     * Product not found
     */
    404: _Error;
    /**
     * Server Error - Failed to fetch product
     */
    500: _Error;
};

export type GetProductsBySlugError = GetProductsBySlugErrors[keyof GetProductsBySlugErrors];

export type GetProductsBySlugResponses = {
    /**
     * Detailed information for the requested product.
     */
    200: {
        product?: {
            id?: string;
            name?: string;
            /**
             * The main HTML description of the product.
             */
            description?: string | null;
            price?: number;
            categoryId?: string;
            slug?: string;
            metaTitle?: string | null;
            metaDescription?: string | null;
            /**
             * Type of discount applied to the product
             */
            discountType?: 'percentage' | 'flat';
            /**
             * Discount percentage (0-100) when discountType is 'percentage'
             */
            discountPercentage?: number | null;
            /**
             * Flat discount amount when discountType is 'flat'
             */
            discountAmount?: number | null;
            freeDelivery?: boolean;
            isActive?: boolean;
            /**
             * A list of key features extracted from the product description.
             */
            features?: Array<string>;
            discountedPrice?: number;
            /**
             * Indicates if the product has multiple variants (e.g., by size or color).
             */
            hasVariants?: boolean;
            createdAt?: string;
            updatedAt?: string;
            deletedAt?: string | null;
            /**
             * A list of filterable attributes assigned to the product.
             */
            attributes?: Array<{
                name?: string;
                value?: string;
                slug?: string;
            }>;
            /**
             * Rich content sections for the product, often used for detailed specifications or feature callouts.
             */
            additionalInfo?: Array<{
                id?: string;
                title?: string;
                content?: string;
            }>;
        };
        /**
         * The category the product belongs to.
         */
        category?: {
            id?: string;
            name?: string;
            slug?: string;
            description?: string | null;
            imageUrl?: string | null;
            metaTitle?: string | null;
            metaDescription?: string | null;
        } | null;
        /**
         * A list of all images for the product, sorted by `sortOrder`.
         */
        images?: Array<{
            id?: string;
            productId?: string;
            url?: string;
            alt?: string;
            isPrimary?: boolean;
            sortOrder?: number;
            createdAt?: string;
        }>;
        /**
         * A list of all available variants for the product (e.g., by color, size).
         */
        variants?: Array<{
            id?: string;
            productId?: string;
            size?: string | null;
            color?: string | null;
            weight?: number | null;
            sku?: string | null;
            /**
             * The specific price for this variant. If null, it inherits the parent product's price.
             */
            price?: number | null;
            stock?: number;
            /**
             * Type of discount applied to this variant
             */
            discountType?: 'percentage' | 'flat';
            /**
             * Discount percentage for this variant
             */
            discountPercentage?: number | null;
            /**
             * Flat discount amount for this variant
             */
            discountAmount?: number | null;
            /**
             * Sort order for color-based grouping (used for variant image mapping)
             */
            colorSortOrder?: number;
            /**
             * Sort order for size-based grouping (used for storefront display)
             */
            sizeSortOrder?: number;
            createdAt?: string;
            updatedAt?: string;
            deletedAt?: string | null;
        }>;
        /**
         * A list of related products, typically from the same category.
         */
        relatedProducts?: Array<{
            id?: string;
            name?: string;
            price?: number;
            slug?: string;
            discountType?: 'percentage' | 'flat';
            discountPercentage?: number | null;
            discountAmount?: number | null;
            freeDelivery?: boolean | null;
            imageUrl?: string | null;
            discountedPrice?: number;
        }>;
    };
};

export type GetProductsBySlugResponse = GetProductsBySlugResponses[keyof GetProductsBySlugResponses];

export type GetProductsByProductIdVariantsData = {
    body?: never;
    path: {
        /**
         * ID of the product to get variants for.
         */
        productId: string;
    };
    query?: never;
    url: '/products/{productId}/variants';
};

export type GetProductsByProductIdVariantsErrors = {
    /**
     * Server Error - Failed to fetch product variants
     */
    500: _Error;
};

export type GetProductsByProductIdVariantsError = GetProductsByProductIdVariantsErrors[keyof GetProductsByProductIdVariantsErrors];

export type GetProductsByProductIdVariantsResponses = {
    /**
     * A list of product variants.
     */
    200: {
        variants?: Array<{
            id?: string;
            productId?: string;
            size?: string | null;
            color?: string | null;
            weight?: number | null;
            sku?: string | null;
            price?: number | null;
            stock?: number;
            /**
             * Sort order for color-based grouping
             */
            colorSortOrder?: number;
            /**
             * Sort order for size-based grouping
             */
            sizeSortOrder?: number;
            createdAt?: string;
            updatedAt?: string;
        }>;
    };
};

export type GetProductsByProductIdVariantsResponse = GetProductsByProductIdVariantsResponses[keyof GetProductsByProductIdVariantsResponses];

export type GetProductsSearchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search term to find products by name.
         */
        search?: string;
        /**
         * Page number for pagination.
         */
        page?: number;
        /**
         * Number of products per page.
         */
        limit?: number;
    };
    url: '/products/search';
};

export type GetProductsSearchErrors = {
    /**
     * Bad Request - Invalid query parameters
     */
    400: _Error;
    /**
     * Server Error - Failed to search products
     */
    500: _Error;
};

export type GetProductsSearchError = GetProductsSearchErrors[keyof GetProductsSearchErrors];

export type GetProductsSearchResponses = {
    /**
     * Successfully searched products.
     */
    200: {
        success?: boolean;
        data?: Array<{
            id?: string;
            name?: string;
            price?: number;
            discountType?: 'percentage' | 'flat';
            discountPercentage?: number | null;
            discountAmount?: number | null;
            primaryImageUrl?: string | null;
            variants?: Array<{
                id?: string;
                productId?: string;
                size?: string | null;
                color?: string | null;
                weight?: number | null;
                sku?: string | null;
                price?: number | null;
                stock?: number;
                discountType?: 'percentage' | 'flat';
                discountPercentage?: number | null;
                discountAmount?: number | null;
                /**
                 * Sort order for color-based grouping
                 */
                colorSortOrder?: number;
                /**
                 * Sort order for size-based grouping
                 */
                sizeSortOrder?: number;
            }>;
        }>;
        pagination?: {
            page?: number;
            limit?: number;
            total?: number;
            totalPages?: number;
            hasNextPage?: boolean;
            hasPrevPage?: boolean;
        };
    };
};

export type GetProductsSearchResponse = GetProductsSearchResponses[keyof GetProductsSearchResponses];

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories';
};

export type GetCategoriesResponses = {
    /**
     * Successfully retrieved categories
     */
    200: {
        categories?: Array<{
            id?: string;
            name?: string;
            slug?: string;
            description?: string;
            imageUrl?: string | null;
            createdAt?: string;
            metaTitle?: string | null;
            metaDescription?: string | null;
        }>;
    };
};

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses];

export type GetCategoriesBySlugData = {
    body?: never;
    path: {
        /**
         * Slug of the category to retrieve
         */
        slug: string;
    };
    query?: never;
    url: '/categories/{slug}';
};

export type GetCategoriesBySlugErrors = {
    /**
     * Category not found
     */
    404: _Error;
};

export type GetCategoriesBySlugError = GetCategoriesBySlugErrors[keyof GetCategoriesBySlugErrors];

export type GetCategoriesBySlugResponses = {
    /**
     * Successfully retrieved category
     */
    200: {
        category?: {
            id?: string;
            name?: string;
            slug?: string;
            description?: string;
            imageUrl?: string | null;
            createdAt?: string;
            metaTitle?: string | null;
            metaDescription?: string | null;
        };
    };
};

export type GetCategoriesBySlugResponse = GetCategoriesBySlugResponses[keyof GetCategoriesBySlugResponses];

export type GetCategoriesBySlugProductsData = {
    body?: never;
    path: {
        /**
         * Slug of the category
         */
        slug: string;
    };
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of products per page
         */
        limit?: number;
        /**
         * Sort order for products
         */
        sort?: 'newest' | 'price-asc' | 'price-desc' | 'name-asc' | 'name-desc' | 'discount';
        /**
         * Search term to filter products by name
         */
        search?: string;
        /**
         * Minimum price filter
         */
        minPrice?: number;
        /**
         * Maximum price filter
         */
        maxPrice?: number;
        /**
         * Filter by free delivery availability
         */
        freeDelivery?: 'true' | 'false';
        /**
         * Filter by discount availability
         */
        hasDiscount?: 'true' | 'false';
        /**
         * Example: Filter by Samsung attribute value (dynamic attribute filtering)
         */
        samsung?: string;
        /**
         * Example: Filter by warranty attribute value (dynamic attribute filtering)
         */
        warranty?: string;
    };
    url: '/categories/{slug}/products';
};

export type GetCategoriesBySlugProductsErrors = {
    /**
     * Category not found
     */
    404: _Error;
    500: unknown;
};

export type GetCategoriesBySlugProductsError = GetCategoriesBySlugProductsErrors[keyof GetCategoriesBySlugProductsErrors];

export type GetCategoriesBySlugProductsResponses = {
    /**
     * Successfully retrieved category products
     */
    200: {
        category?: {
            id?: string;
            name?: string;
            slug?: string;
            description?: string;
            imageUrl?: string | null;
            metaTitle?: string | null;
            metaDescription?: string | null;
        };
        products?: Array<{
            id?: string;
            name?: string;
            price?: number;
            slug?: string;
            discountPercentage?: number | null;
            freeDelivery?: boolean;
            imageUrl?: string | null;
            discountedPrice?: number;
            createdAt?: string | null;
            updatedAt?: string | null;
            category?: {
                id?: string;
                name?: string;
                slug?: string;
            };
        }>;
        pagination?: {
            page?: number;
            limit?: number;
            total?: number;
            totalPages?: number;
        };
        appliedFilters?: {
            attributes?: Array<{
                slug?: string;
                value?: string;
            }>;
            search?: string | null;
            minPrice?: number | null;
            maxPrice?: number | null;
            freeDelivery?: string | null;
            hasDiscount?: string | null;
            sort?: string;
        };
    };
};

export type GetCategoriesBySlugProductsResponse = GetCategoriesBySlugProductsResponses[keyof GetCategoriesBySlugProductsResponses];

export type GetCollectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/collections';
};

export type GetCollectionsErrors = {
    /**
     * Server error
     */
    500: _Error;
};

export type GetCollectionsError = GetCollectionsErrors[keyof GetCollectionsErrors];

export type GetCollectionsResponses = {
    /**
     * Successfully retrieved collections
     */
    200: {
        collections?: Array<{
            id?: string;
            name?: string;
            /**
             * UI rendering style only. collection1 = grid with featured product, collection2 = horizontal scroll
             */
            type?: 'collection1' | 'collection2';
            /**
             * JSON object defining the collection's behavior and product selection
             */
            config?: {
                /**
                 * Array of category IDs to pull products from
                 */
                categoryIds?: Array<string>;
                /**
                 * Array of specific product IDs to include
                 */
                productIds?: Array<string>;
                /**
                 * Optional featured product for collection1 style
                 */
                featuredProductId?: string | null;
                /**
                 * Maximum number of products to display (1-24)
                 */
                maxProducts?: number;
                /**
                 * Custom display title
                 */
                title?: string | null;
                /**
                 * Custom display subtitle
                 */
                subtitle?: string | null;
            };
            sortOrder?: number;
            isActive?: boolean;
            createdAt?: string;
            updatedAt?: string;
        }>;
    };
};

export type GetCollectionsResponse = GetCollectionsResponses[keyof GetCollectionsResponses];

export type GetCollectionsByIdData = {
    body?: never;
    path: {
        /**
         * ID of the collection to retrieve.
         */
        id: string;
    };
    query?: never;
    url: '/collections/{id}';
};

export type GetCollectionsByIdErrors = {
    /**
     * Collection not found
     */
    404: _Error;
};

export type GetCollectionsByIdError = GetCollectionsByIdErrors[keyof GetCollectionsByIdErrors];

export type GetCollectionsByIdResponses = {
    /**
     * Successfully retrieved collection
     */
    200: {
        success?: boolean;
        collection?: {
            id?: string;
            name?: string;
            /**
             * UI rendering style only
             */
            type?: 'collection1' | 'collection2';
            config?: {
                /**
                 * Category IDs this collection pulls from
                 */
                categoryIds?: Array<string>;
                /**
                 * Specific product IDs included
                 */
                productIds?: Array<string>;
                featuredProductId?: string | null;
                maxProducts?: number;
                title?: string | null;
                subtitle?: string | null;
            };
            sortOrder?: number;
            isActive?: boolean;
            createdAt?: string;
            updatedAt?: string;
            deletedAt?: string | null;
            /**
             * CHANGED: Now an array of category objects (was single 'category' object)
             */
            categories?: Array<{
                id?: string;
                name?: string;
                slug?: string;
            }>;
            /**
             * Products in this collection (from categories and/or specific products)
             */
            products?: Array<{
                id?: string;
                name?: string;
                price?: number;
                slug?: string;
                discountPercentage?: number | null;
                imageUrl?: string | null;
                discountedPrice?: number;
            }>;
            /**
             * Featured product for collection1 style (optional)
             */
            featuredProduct?: {
                id?: string;
                name?: string;
                price?: number;
                discountPercentage?: number | null;
                slug?: string;
                imageUrl?: string | null;
                discountedPrice?: number;
            } | null;
        };
    };
};

export type GetCollectionsByIdResponse = GetCollectionsByIdResponses[keyof GetCollectionsByIdResponses];

export type GetOrdersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination.
         */
        page?: number;
        /**
         * Number of orders per page.
         */
        limit?: number;
        /**
         * Filter orders by a specific status.
         */
        status?: 'pending' | 'processing' | 'confirmed' | 'shipped' | 'delivered' | 'cancelled' | 'returned';
        /**
         * Search query for order ID, customer name, or customer phone.
         */
        search?: string;
        /**
         * The field to sort the orders by.
         */
        sort?: 'customerName' | 'totalAmount' | 'status' | 'createdAt' | 'updatedAt';
        /**
         * The sort direction.
         */
        order?: 'asc' | 'desc';
        /**
         * Set to 'true' to list soft-deleted orders instead of active ones.
         */
        trashed?: 'true' | 'false';
    };
    url: '/orders';
};

export type GetOrdersErrors = {
    401: unknown;
    500: unknown;
};

export type GetOrdersResponses = {
    /**
     * A paginated list of orders.
     */
    200: {
        orders?: Array<{
            id?: string;
            customerName?: string;
            customerPhone?: string;
            customerEmail?: string | null;
            customerId?: string | null;
            totalAmount?: number;
            shippingCharge?: number;
            discountAmount?: number;
            status?: string;
            city?: string;
            zone?: string;
            area?: string | null;
            cityName?: string;
            zoneName?: string;
            areaName?: string | null;
            createdAt?: string;
            updatedAt?: string;
            /**
             * The number of unique line items in the order.
             */
            itemCount?: number;
            /**
             * The total number of all units in the order.
             */
            totalQuantity?: number;
        }>;
        pagination?: {
            page?: number;
            limit?: number;
            total?: number;
            totalPages?: number;
            hasNextPage?: boolean;
            hasPrevPage?: boolean;
        };
    };
};

export type GetOrdersResponse = GetOrdersResponses[keyof GetOrdersResponses];

export type PostOrdersData = {
    body: {
        customerName: string;
        /**
         * Must be a valid Bangladeshi phone number.
         */
        customerPhone: string;
        customerEmail?: string | null;
        shippingAddress: string;
        /**
         * City ID from `/locations/cities`.
         */
        city: string;
        /**
         * Zone ID from `/locations/zones`.
         */
        zone: string;
        /**
         * Area ID from `/locations/areas` (optional).
         */
        area?: string | null;
        /**
         * Name of the city (for display/record-keeping).
         */
        cityName?: string;
        /**
         * Name of the zone (for display/record-keeping).
         */
        zoneName?: string;
        /**
         * Name of the area (for display/record-keeping).
         */
        areaName?: string | null;
        notes?: string | null;
        items: Array<{
            productId: string;
            variantId?: string | null;
            quantity: number;
            /**
             * The final price per unit for this line item.
             */
            price: number;
        }>;
        discountAmount?: number | null;
        /**
         * If a discount was applied, include its code to log usage.
         */
        discountCode?: string | null;
        shippingCharge: number;
    };
    path?: never;
    query?: never;
    url: '/orders';
};

export type PostOrdersErrors = {
    /**
     * Bad Request - Caused by either a validation error or insufficient stock.
     */
    400: {
        success?: boolean;
        error?: {
            code?: string;
            message?: string;
            details?: Array<{
                [key: string]: unknown;
            }>;
        };
    } | {
        success?: boolean;
        error?: {
            code?: string;
            message?: string;
            variantId?: string;
            available?: number;
            requested?: number;
        };
    };
    401: unknown;
    500: unknown;
};

export type PostOrdersError = PostOrdersErrors[keyof PostOrdersErrors];

export type PostOrdersResponses = {
    /**
     * Order created successfully.
     */
    201: {
        success?: boolean;
        data?: {
            /**
             * The unique ID of the newly created order.
             */
            id?: string;
        };
    };
};

export type PostOrdersResponse = PostOrdersResponses[keyof PostOrdersResponses];

export type DeleteOrdersByIdData = {
    body?: never;
    path: {
        /**
         * The unique ID of the order to soft delete.
         */
        id: string;
    };
    query?: never;
    url: '/orders/{id}';
};

export type DeleteOrdersByIdErrors = {
    401: unknown;
    404: unknown;
    500: unknown;
};

export type DeleteOrdersByIdResponses = {
    /**
     * Order soft-deleted successfully.
     */
    204: void;
};

export type DeleteOrdersByIdResponse = DeleteOrdersByIdResponses[keyof DeleteOrdersByIdResponses];

export type GetOrdersByIdData = {
    body?: never;
    path: {
        /**
         * The unique ID of the order.
         */
        id: string;
    };
    query?: never;
    url: '/orders/{id}';
};

export type GetOrdersByIdErrors = {
    401: unknown;
    404: unknown;
    500: unknown;
};

export type GetOrdersByIdResponses = {
    /**
     * Detailed information for the requested order.
     */
    200: {
        order?: {
            id?: string;
            customerName?: string;
            customerPhone?: string;
            customerEmail?: string | null;
            customerId?: string | null;
            shippingAddress?: string;
            totalAmount?: number;
            shippingCharge?: number;
            discountAmount?: number;
            notes?: string | null;
            city?: string;
            zone?: string;
            area?: string | null;
            cityName?: string;
            zoneName?: string;
            areaName?: string | null;
            status?: string;
            createdAt?: string;
            updatedAt?: string;
            items?: Array<{
                id?: string;
                productId?: string;
                variantId?: string | null;
                quantity?: number;
                price?: number;
                productName?: string;
                productImage?: string | null;
                variantSize?: string | null;
                variantColor?: string | null;
            }>;
            /**
             * A list of delivery shipments associated with this order.
             */
            shipments?: Array<{
                id?: string;
                providerId?: string;
                providerType?: string;
                trackingId?: string | null;
                status?: string;
                createdAt?: string;
            }>;
            /**
             * A list of currently active delivery providers that a shipment can be created with.
             */
            deliveryProviders?: Array<{
                id?: string;
                name?: string;
                type?: string;
                isActive?: boolean;
            }>;
        };
    };
};

export type GetOrdersByIdResponse = GetOrdersByIdResponses[keyof GetOrdersByIdResponses];

export type PutOrdersByIdData = {
    body: OrderPostRequest;
    path: {
        /**
         * The unique ID of the order to update.
         */
        id: string;
    };
    query?: never;
    url: '/orders/{id}';
};

export type PutOrdersByIdErrors = {
    400: unknown;
    401: unknown;
    404: unknown;
    500: unknown;
};

export type PutOrdersByIdResponses = {
    /**
     * Order updated successfully.
     */
    200: {
        id?: string;
    };
};

export type PutOrdersByIdResponse = PutOrdersByIdResponses[keyof PutOrdersByIdResponses];

export type GetOrdersByIdItemsData = {
    body?: never;
    path: {
        /**
         * The unique ID of the order.
         */
        id: string;
    };
    query?: never;
    url: '/orders/{id}/items';
};

export type GetOrdersByIdItemsErrors = {
    401: unknown;
    500: unknown;
};

export type GetOrdersByIdItemsResponses = {
    /**
     * A list of items in the order.
     */
    200: Array<{
        id?: string;
        productId?: string;
        variantId?: string | null;
        quantity?: number;
        price?: number;
        productName?: string;
        productImage?: string | null;
        variantSize?: string | null;
        variantColor?: string | null;
    }>;
};

export type GetOrdersByIdItemsResponse = GetOrdersByIdItemsResponses[keyof GetOrdersByIdItemsResponses];

export type GetOrdersProductsForFormData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/orders/products-for-form';
};

export type GetOrdersProductsForFormErrors = {
    401: unknown;
    500: unknown;
};

export type GetOrdersProductsForFormResponses = {
    /**
     * A list of products with their nested variants.
     */
    200: {
        products?: Array<{
            id?: string;
            name?: string;
            price?: number;
            discountPercentage?: number | null;
            variants?: Array<{
                id?: string;
                productId?: string;
                size?: string | null;
                color?: string | null;
                weight?: number | null;
                sku?: string | null;
                price?: number | null;
                stock?: number;
            }>;
        }>;
    };
};

export type GetOrdersProductsForFormResponse = GetOrdersProductsForFormResponses[keyof GetOrdersProductsForFormResponses];

export type PostOrdersBulkDeleteData = {
    body: {
        orderIds: Array<string>;
        /**
         * If true, permanently deletes the orders from the database. If false (default), orders are soft-deleted.
         */
        permanent?: boolean;
    };
    path?: never;
    query?: never;
    url: '/orders/bulk-delete';
};

export type PostOrdersBulkDeleteErrors = {
    400: unknown;
    401: unknown;
    500: unknown;
};

export type PostOrdersBulkDeleteResponses = {
    /**
     * Orders deleted successfully.
     */
    204: void;
};

export type PostOrdersBulkDeleteResponse = PostOrdersBulkDeleteResponses[keyof PostOrdersBulkDeleteResponses];

export type PostOrdersByIdRestoreData = {
    body?: never;
    path: {
        /**
         * The unique ID of the order to restore.
         */
        id: string;
    };
    query?: never;
    url: '/orders/{id}/restore';
};

export type PostOrdersByIdRestoreErrors = {
    /**
     * Bad Request - The order is not deleted.
     */
    400: unknown;
    401: unknown;
    404: unknown;
    500: unknown;
};

export type PostOrdersByIdRestoreResponses = {
    /**
     * Order restored successfully.
     */
    204: void;
};

export type PostOrdersByIdRestoreResponse = PostOrdersByIdRestoreResponses[keyof PostOrdersByIdRestoreResponses];

export type PutOrdersByIdStatusData = {
    body: {
        status: 'pending' | 'processing' | 'confirmed' | 'shipped' | 'delivered' | 'cancelled' | 'returned';
    };
    path: {
        /**
         * The unique ID of the order.
         */
        id: string;
    };
    query?: never;
    url: '/orders/{id}/status';
};

export type PutOrdersByIdStatusErrors = {
    400: unknown;
    401: unknown;
    500: unknown;
};

export type PutOrdersByIdStatusResponses = {
    /**
     * Order status updated successfully.
     */
    200: {
        success?: boolean;
        data?: {
            message?: string;
        };
    };
};

export type PutOrdersByIdStatusResponse = PutOrdersByIdStatusResponses[keyof PutOrdersByIdStatusResponses];

export type DeleteOrdersByIdPermanentData = {
    body?: never;
    path: {
        /**
         * The unique ID of the order to permanently delete.
         */
        id: string;
    };
    query?: never;
    url: '/orders/{id}/permanent';
};

export type DeleteOrdersByIdPermanentErrors = {
    401: unknown;
    404: unknown;
    500: unknown;
};

export type DeleteOrdersByIdPermanentResponses = {
    /**
     * Order permanently deleted successfully.
     */
    204: void;
};

export type DeleteOrdersByIdPermanentResponse = DeleteOrdersByIdPermanentResponses[keyof DeleteOrdersByIdPermanentResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * API is healthy
     */
    200: {
        status?: string;
        timestamp?: string;
        version?: string;
        environment?: string;
        uptime?: number;
        cache?: {
            type?: string;
            redisAvailable?: boolean;
            size?: number;
            memory?: string;
            hitRate?: string;
            missRate?: string;
            uptime?: string;
        };
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetHeroSlidersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by slider type (desktop or mobile)
         */
        type?: 'desktop' | 'mobile';
    };
    url: '/hero/sliders';
};

export type GetHeroSlidersErrors = {
    /**
     * Server error
     */
    500: _Error;
};

export type GetHeroSlidersError = GetHeroSlidersErrors[keyof GetHeroSlidersErrors];

export type GetHeroSlidersResponses = {
    /**
     * Successfully retrieved hero sliders
     */
    200: {
        desktop?: {
            id?: string;
            type?: string;
            images?: Array<{
                url?: string;
                alt?: string;
                link?: string | null;
            }>;
            isActive?: boolean;
            createdAt?: string | null;
            updatedAt?: string | null;
        } | null;
        mobile?: {
            id?: string;
            type?: string;
            images?: Array<{
                url?: string;
                alt?: string;
                link?: string | null;
            }>;
            isActive?: boolean;
            createdAt?: string | null;
            updatedAt?: string | null;
        } | null;
        images?: Array<{
            url?: string;
            alt?: string;
            link?: string | null;
        }>;
        isMobile?: boolean;
    };
};

export type GetHeroSlidersResponse = GetHeroSlidersResponses[keyof GetHeroSlidersResponses];

export type GetHeroSlidersByIdData = {
    body?: never;
    path: {
        /**
         * Slider ID
         */
        id: string;
    };
    query?: never;
    url: '/hero/sliders/{id}';
};

export type GetHeroSlidersByIdErrors = {
    /**
     * Hero slider not found
     */
    404: _Error;
    /**
     * Server error
     */
    500: _Error;
};

export type GetHeroSlidersByIdError = GetHeroSlidersByIdErrors[keyof GetHeroSlidersByIdErrors];

export type GetHeroSlidersByIdResponses = {
    /**
     * Successfully retrieved hero slider
     */
    200: {
        slider?: {
            id?: string;
            type?: string;
            images?: Array<{
                url?: string;
                alt?: string;
                link?: string | null;
            }>;
            isActive?: boolean;
            createdAt?: string | null;
            updatedAt?: string | null;
        };
    };
};

export type GetHeroSlidersByIdResponse = GetHeroSlidersByIdResponses[keyof GetHeroSlidersByIdResponses];

export type GetSearchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search query string
         */
        q?: string;
        /**
         * Filter products by category ID
         */
        categoryId?: string;
        /**
         * Minimum price for product results
         */
        minPrice?: number;
        /**
         * Maximum price for product results
         */
        maxPrice?: number;
        /**
         * Maximum number of results to return per content type
         */
        limit?: number;
        /**
         * Whether to include pages in search results
         */
        searchPages?: 'true' | 'false';
        /**
         * Whether to include categories in search results
         */
        searchCategories?: 'true' | 'false';
    };
    url: '/search';
};

export type GetSearchErrors = {
    /**
     * Too Many Requests - Rate limit exceeded
     */
    429: _Error;
    /**
     * Server Error - Failed to perform search
     */
    500: _Error;
};

export type GetSearchError = GetSearchErrors[keyof GetSearchErrors];

export type GetSearchResponses = {
    /**
     * Successfully performed search
     */
    200: {
        products?: Array<{
            id?: string;
            name?: string;
            description?: string | null;
            price?: number;
            slug?: string;
            imageUrl?: string | null;
            categoryId?: string;
            categoryName?: string | null;
            type?: string;
        }>;
        categories?: Array<{
            id?: string;
            name?: string;
            slug?: string;
            description?: string | null;
            type?: string;
        }>;
        pages?: Array<{
            id?: string;
            title?: string;
            slug?: string;
            content?: string;
            type?: string;
        }>;
        success?: boolean;
        query?: string;
        timestamp?: string;
    };
};

export type GetSearchResponse = GetSearchResponses[keyof GetSearchResponses];

export type PostSearchReindexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/search/reindex';
};

export type PostSearchReindexErrors = {
    /**
     * Unauthorized - Invalid authorization
     */
    401: _Error;
    /**
     * Server Error - Failed to reindex content
     */
    500: _Error;
};

export type PostSearchReindexError = PostSearchReindexErrors[keyof PostSearchReindexErrors];

export type PostSearchReindexResponses = {
    /**
     * Successfully reindexed content
     */
    200: {
        productsCount?: number;
        categoriesCount?: number;
        pagesCount?: number;
        success?: boolean;
        message?: string;
        timestamp?: string;
    };
};

export type PostSearchReindexResponse = PostSearchReindexResponses[keyof PostSearchReindexResponses];

export type GetHeaderData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/header';
};

export type GetHeaderErrors = {
    /**
     * Header configuration not found
     */
    404: _Error;
    /**
     * Server Error - Failed to fetch header data
     */
    500: _Error;
};

export type GetHeaderError = GetHeaderErrors[keyof GetHeaderErrors];

export type GetHeaderResponses = {
    /**
     * Successfully retrieved header data
     */
    200: {
        header?: {
            topBar?: {
                text?: string;
            };
            logo?: {
                src?: string;
                alt?: string;
            };
            favicon?: {
                src?: string;
                alt?: string;
            } | null;
            contact?: {
                phone?: string;
                text?: string;
            };
            social?: {
                facebook?: string;
            };
        };
        success?: boolean;
    };
};

export type GetHeaderResponse = GetHeaderResponses[keyof GetHeaderResponses];

export type GetFooterData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/footer';
};

export type GetFooterErrors = {
    /**
     * Footer configuration not found
     */
    404: _Error;
    /**
     * Server Error - Failed to fetch footer data
     */
    500: _Error;
};

export type GetFooterError = GetFooterErrors[keyof GetFooterErrors];

export type GetFooterResponses = {
    /**
     * Successfully retrieved footer data
     */
    200: {
        data?: {
            logo?: {
                src?: string;
                alt?: string;
            };
            tagline?: string;
            copyrightText?: string;
            menus?: Array<{
                id?: string;
                title?: string;
                links?: Array<{
                    title?: string;
                    href?: string;
                    subMenu?: Array<{
                        [key: string]: unknown;
                    }>;
                }>;
            }>;
            social?: Array<{
                id?: string;
                platform?: string;
                url?: string;
                icon?: string;
            }>;
            description?: string;
        };
        success?: boolean;
    };
};

export type GetFooterResponse = GetFooterResponses[keyof GetFooterResponses];

export type GetNavigationData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Type of navigation to retrieve
         */
        type?: 'header' | 'footer' | 'all';
    };
    url: '/navigation';
};

export type GetNavigationErrors = {
    /**
     * Navigation configuration not found
     */
    404: _Error;
    /**
     * Server Error - Failed to fetch navigation data
     */
    500: _Error;
};

export type GetNavigationError = GetNavigationErrors[keyof GetNavigationErrors];

export type GetNavigationResponses = {
    /**
     * Successfully retrieved navigation data
     */
    200: {
        navigation?: {
            header?: Array<{
                title?: string;
                href?: string;
                subMenu?: Array<{
                    [key: string]: unknown;
                }>;
            }>;
            footer?: Array<{
                id?: string;
                title?: string;
                links?: Array<{
                    [key: string]: unknown;
                }>;
            }>;
        };
        success?: boolean;
    };
};

export type GetNavigationResponse = GetNavigationResponses[keyof GetNavigationResponses];

export type GetNavigationByIdData = {
    body?: never;
    path: {
        /**
         * ID of the navigation menu to retrieve (header, footer, or a specific menu ID)
         */
        id: string;
    };
    query?: never;
    url: '/navigation/{id}';
};

export type GetNavigationByIdErrors = {
    /**
     * Navigation menu not found
     */
    404: _Error;
    /**
     * Server Error - Failed to fetch navigation menu
     */
    500: _Error;
};

export type GetNavigationByIdError = GetNavigationByIdErrors[keyof GetNavigationByIdErrors];

export type GetNavigationByIdResponses = {
    /**
     * Successfully retrieved navigation menu
     */
    200: {
        menu?: {
            id?: string;
            name?: string;
            items?: Array<{
                title?: string;
                href?: string;
                subMenu?: Array<{
                    [key: string]: unknown;
                }>;
            }>;
        };
        success?: boolean;
    };
};

export type GetNavigationByIdResponse = GetNavigationByIdResponses[keyof GetNavigationByIdResponses];

export type GetPagesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of pages to return
         */
        limit?: number;
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Sort field and direction (prefix with - for descending)
         */
        sort?: 'title' | 'createdAt' | '-title' | '-createdAt';
        /**
         * Only return published pages
         */
        publishedOnly?: boolean;
    };
    url: '/pages';
};

export type GetPagesErrors = {
    /**
     * Server Error - Failed to fetch pages
     */
    500: _Error;
};

export type GetPagesError = GetPagesErrors[keyof GetPagesErrors];

export type GetPagesResponses = {
    /**
     * Successfully retrieved pages
     */
    200: {
        pages?: Array<{
            id?: string;
            title?: string;
            slug?: string;
            content?: string;
            metaTitle?: string | null;
            metaDescription?: string | null;
            isPublished?: boolean;
            createdAt?: number;
            updatedAt?: number;
        }>;
        pagination?: {
            page?: number;
            limit?: number;
            total?: number;
            totalPages?: number;
        };
        success?: boolean;
    };
};

export type GetPagesResponse = GetPagesResponses[keyof GetPagesResponses];

export type GetPagesSlugBySlugData = {
    body?: never;
    path: {
        /**
         * Slug of the page to retrieve
         */
        slug: string;
    };
    query?: never;
    url: '/pages/slug/{slug}';
};

export type GetPagesSlugBySlugErrors = {
    /**
     * Page not found
     */
    404: _Error;
    /**
     * Server Error - Failed to fetch page
     */
    500: _Error;
};

export type GetPagesSlugBySlugError = GetPagesSlugBySlugErrors[keyof GetPagesSlugBySlugErrors];

export type GetPagesSlugBySlugResponses = {
    /**
     * Successfully retrieved page
     */
    200: {
        page?: {
            id?: string;
            title?: string;
            slug?: string;
            content?: string;
            metaTitle?: string | null;
            metaDescription?: string | null;
            isPublished?: boolean;
            createdAt?: number;
            updatedAt?: number;
        };
        success?: boolean;
    };
};

export type GetPagesSlugBySlugResponse = GetPagesSlugBySlugResponses[keyof GetPagesSlugBySlugResponses];

export type GetAnalyticsConfigurationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/analytics/configurations';
};

export type GetAnalyticsConfigurationsErrors = {
    500: unknown;
};

export type GetAnalyticsConfigurationsResponses = {
    /**
     * Successfully retrieved analytics configurations.
     */
    200: {
        analytics?: Array<{
            id?: string;
            name?: string;
            /**
             * e.g., 'google_analytics', 'facebook_pixel'
             */
            type?: string;
            /**
             * The processed configuration or script content, ready for use.
             */
            config?: {
                [key: string]: unknown;
            };
            isActive?: boolean;
            usePartytown?: boolean;
            /**
             * The recommended location to inject the script in the HTML.
             */
            location?: 'head' | 'body_start' | 'body_end';
            createdAt?: string;
            updatedAt?: string;
        }>;
    };
};

export type GetAnalyticsConfigurationsResponse = GetAnalyticsConfigurationsResponses[keyof GetAnalyticsConfigurationsResponses];

export type GetCacheStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cache/stats';
};

export type GetCacheStatsErrors = {
    401: unknown;
    500: unknown;
};

export type GetCacheStatsResponses = {
    /**
     * Cache statistics retrieved successfully.
     */
    200: {
        success?: boolean;
        stats?: {
            /**
             * Number of keys in the cache.
             */
            size?: number;
            /**
             * Approximate memory usage.
             */
            memory?: string;
            hitRate?: string | null;
            missRate?: string | null;
            /**
             * Cache server uptime.
             */
            uptime?: string;
            cacheType?: 'redis' | 'memory';
        };
    };
};

export type GetCacheStatsResponse = GetCacheStatsResponses[keyof GetCacheStatsResponses];

export type PostCacheClearData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cache/clear';
};

export type PostCacheClearErrors = {
    401: unknown;
    500: unknown;
};

export type PostCacheClearResponses = {
    /**
     * Cache cleared successfully.
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type PostCacheClearResponse = PostCacheClearResponses[keyof PostCacheClearResponses];

export type PostCacheClearProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cache/clear-products';
};

export type PostCacheClearProductsErrors = {
    401: unknown;
    500: unknown;
};

export type PostCacheClearProductsResponses = {
    /**
     * Product cache cleared successfully.
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type PostCacheClearProductsResponse = PostCacheClearProductsResponses[keyof PostCacheClearProductsResponses];

export type PostCacheClearCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cache/clear-categories';
};

export type PostCacheClearCategoriesErrors = {
    401: unknown;
    500: unknown;
};

export type PostCacheClearCategoriesResponses = {
    /**
     * Category cache cleared successfully.
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type PostCacheClearCategoriesResponse = PostCacheClearCategoriesResponses[keyof PostCacheClearCategoriesResponses];

export type PostCacheClearCollectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cache/clear-collections';
};

export type PostCacheClearCollectionsErrors = {
    401: unknown;
    500: unknown;
};

export type PostCacheClearCollectionsResponses = {
    /**
     * Collections cache cleared successfully.
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type PostCacheClearCollectionsResponse = PostCacheClearCollectionsResponses[keyof PostCacheClearCollectionsResponses];

export type PostCacheClearFooterData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cache/clear-footer';
};

export type PostCacheClearFooterErrors = {
    401: unknown;
    500: unknown;
};

export type PostCacheClearFooterResponses = {
    /**
     * Footer cache cleared successfully.
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type PostCacheClearFooterResponse = PostCacheClearFooterResponses[keyof PostCacheClearFooterResponses];

export type PostCacheClearHeaderData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cache/clear-header';
};

export type PostCacheClearHeaderErrors = {
    401: unknown;
    500: unknown;
};

export type PostCacheClearHeaderResponses = {
    /**
     * Header cache cleared successfully.
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type PostCacheClearHeaderResponse = PostCacheClearHeaderResponses[keyof PostCacheClearHeaderResponses];

export type PostCacheClearHeroData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cache/clear-hero';
};

export type PostCacheClearHeroErrors = {
    401: unknown;
    500: unknown;
};

export type PostCacheClearHeroResponses = {
    /**
     * Hero cache cleared successfully.
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type PostCacheClearHeroResponse = PostCacheClearHeroResponses[keyof PostCacheClearHeroResponses];

export type PostCacheClearNavigationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cache/clear-navigation';
};

export type PostCacheClearNavigationErrors = {
    401: unknown;
    500: unknown;
};

export type PostCacheClearNavigationResponses = {
    /**
     * Navigation cache cleared successfully.
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type PostCacheClearNavigationResponse = PostCacheClearNavigationResponses[keyof PostCacheClearNavigationResponses];

export type PostCacheClearPagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cache/clear-pages';
};

export type PostCacheClearPagesErrors = {
    401: unknown;
    500: unknown;
};

export type PostCacheClearPagesResponses = {
    /**
     * Pages cache cleared successfully.
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type PostCacheClearPagesResponse = PostCacheClearPagesResponses[keyof PostCacheClearPagesResponses];

export type PostCacheClearSearchData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cache/clear-search';
};

export type PostCacheClearSearchErrors = {
    401: unknown;
    500: unknown;
};

export type PostCacheClearSearchResponses = {
    /**
     * Search cache cleared successfully.
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type PostCacheClearSearchResponse = PostCacheClearSearchResponses[keyof PostCacheClearSearchResponses];

export type GetDiscountsValidateData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The discount code to validate.
         */
        code: string;
        /**
         * The current order total (subtotal + shipping).
         */
        total?: number;
        /**
         * A JSON string of cart items. Required for product-specific and collection-based discounts. Collections are automatically expanded to their products. Example: `[{"id":"prod_123","price":100,"quantity":1}]`
         */
        items?: string;
        /**
         * The current shipping cost. Required for `free_shipping` discounts.
         */
        shippingCost?: number;
        /**
         * Customer's phone number, used for 'limit one per customer' validation.
         */
        customerPhone?: string;
    };
    url: '/discounts/validate';
};

export type GetDiscountsValidateErrors = {
    400: unknown;
    500: unknown;
};

export type GetDiscountsValidateResponses = {
    /**
     * The result of the discount validation.
     */
    200: {
        valid?: boolean;
        discount?: {
            id?: string;
            code?: string;
            type?: string;
            valueType?: string;
            discountValue?: number;
            /**
             * Rules for combining this discount with others.
             */
            combinable?: {
                withProductDiscounts?: boolean;
                withOrderDiscounts?: boolean;
                withShippingDiscounts?: boolean;
            };
        };
        /**
         * The calculated discount value.
         */
        discountAmount?: number;
    } | {
        valid?: boolean;
        /**
         * Reason why the discount is invalid.
         */
        error?: string;
        /**
         * The minimum purchase amount required, if applicable.
         */
        minPurchaseAmount?: number | null;
        /**
         * The minimum item quantity required, if applicable.
         */
        minQuantity?: number | null;
    };
};

export type GetDiscountsValidateResponse = GetDiscountsValidateResponses[keyof GetDiscountsValidateResponses];

export type PostDiscountsUsageData = {
    body: {
        discountId: string;
        orderId: string;
        customerId?: string | null;
        amountDiscounted: number;
    };
    path?: never;
    query?: never;
    url: '/discounts/usage';
};

export type PostDiscountsUsageErrors = {
    400: unknown;
    500: unknown;
};

export type PostDiscountsUsageResponses = {
    /**
     * Successfully recorded discount usage.
     */
    201: {
        success?: boolean;
        /**
         * The ID of the new discount usage record.
         */
        id?: string;
    };
};

export type PostDiscountsUsageResponse = PostDiscountsUsageResponses[keyof PostDiscountsUsageResponses];

export type GetLocationsCitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/locations/cities';
};

export type GetLocationsCitiesErrors = {
    500: unknown;
};

export type GetLocationsCitiesResponses = {
    /**
     * A list of active cities.
     */
    200: {
        success?: boolean;
        data?: Array<{
            id?: string;
            name?: string;
            type?: string;
            parentId?: string | null;
            isActive?: boolean;
            sortOrder?: number;
        }>;
    };
};

export type GetLocationsCitiesResponse = GetLocationsCitiesResponses[keyof GetLocationsCitiesResponses];

export type GetLocationsZonesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The ID of the parent city.
         */
        cityId: string;
    };
    url: '/locations/zones';
};

export type GetLocationsZonesErrors = {
    400: unknown;
    500: unknown;
};

export type GetLocationsZonesResponses = {
    /**
     * A list of active zones for the specified city.
     */
    200: {
        success?: boolean;
        data?: Array<{
            id?: string;
            name?: string;
            type?: string;
            parentId?: string;
            isActive?: boolean;
            sortOrder?: number;
        }>;
    };
};

export type GetLocationsZonesResponse = GetLocationsZonesResponses[keyof GetLocationsZonesResponses];

export type GetLocationsAreasData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The ID of the parent zone.
         */
        zoneId: string;
    };
    url: '/locations/areas';
};

export type GetLocationsAreasErrors = {
    400: unknown;
    500: unknown;
};

export type GetLocationsAreasResponses = {
    /**
     * A list of active areas for the specified zone.
     */
    200: {
        success?: boolean;
        data?: Array<{
            id?: string;
            name?: string;
            type?: string;
            parentId?: string;
            isActive?: boolean;
            sortOrder?: number;
        }>;
    };
};

export type GetLocationsAreasResponse = GetLocationsAreasResponses[keyof GetLocationsAreasResponses];

export type GetCheckoutLanguagesActiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/checkout-languages/active';
};

export type GetCheckoutLanguagesActiveErrors = {
    500: unknown;
};

export type GetCheckoutLanguagesActiveResponses = {
    /**
     * The active checkout language configuration.
     */
    200: {
        language?: {
            id?: string;
            name?: string;
            code?: string;
            /**
             * All text labels and messages for the checkout page.
             */
            languageData?: {
                pageTitle?: string;
                checkoutSectionTitle?: string;
                cartSectionTitle?: string;
                customerNameLabel?: string;
                customerNamePlaceholder?: string;
                customerPhoneLabel?: string;
                customerPhonePlaceholder?: string;
                customerPhoneHelp?: string;
                customerEmailLabel?: string;
                customerEmailPlaceholder?: string;
                shippingAddressLabel?: string;
                shippingAddressPlaceholder?: string;
                cityLabel?: string;
                zoneLabel?: string;
                areaLabel?: string;
                shippingMethodLabel?: string;
                orderNotesLabel?: string;
                orderNotesPlaceholder?: string;
                subtotalText?: string;
                shippingText?: string;
                discountText?: string;
                totalText?: string;
                discountCodePlaceholder?: string;
                applyDiscountText?: string;
                removeDiscountText?: string;
                placeOrderText?: string;
                processingText?: string;
                emptyCartText?: string;
                continueShoppingText?: string;
                termsText?: string;
                processingOrderTitle?: string;
                processingOrderMessage?: string;
                requiredFieldIndicator?: string;
            };
            /**
             * Rules for showing or hiding optional form fields.
             */
            fieldVisibility?: {
                showEmailField?: boolean;
                showOrderNotesField?: boolean;
                showAreaField?: boolean;
            };
            isActive?: boolean;
            isDefault?: boolean;
        };
    };
};

export type GetCheckoutLanguagesActiveResponse = GetCheckoutLanguagesActiveResponses[keyof GetCheckoutLanguagesActiveResponses];

export type GetWidgetsByIdData = {
    body?: never;
    path: {
        /**
         * The unique ID of the widget.
         */
        id: string;
    };
    query?: never;
    url: '/widgets/{id}';
};

export type GetWidgetsByIdErrors = {
    404: unknown;
    500: unknown;
};

export type GetWidgetsByIdResponses = {
    /**
     * The requested widget.
     */
    200: {
        success?: boolean;
        widget?: {
            id?: string;
            /**
             * Internal name for the widget.
             */
            name?: string;
            /**
             * The raw HTML content of the widget.
             */
            htmlContent?: string;
            /**
             * Optional CSS for the widget.
             */
            cssContent?: string | null;
            isActive?: boolean;
            displayTarget?: 'homepage';
            placementRule?: 'before_collection' | 'after_collection' | 'fixed_top_homepage' | 'fixed_bottom_homepage' | 'standalone';
            /**
             * The ID of the collection this widget is placed relative to.
             */
            referenceCollectionId?: string | null;
            sortOrder?: number;
            createdAt?: string | null;
            updatedAt?: string | null;
        };
    };
};

export type GetWidgetsByIdResponse = GetWidgetsByIdResponses[keyof GetWidgetsByIdResponses];

export type GetWidgetsActiveHomepageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/widgets/active/homepage';
};

export type GetWidgetsActiveHomepageErrors = {
    500: unknown;
};

export type GetWidgetsActiveHomepageResponses = {
    /**
     * A list of active widgets for the homepage.
     */
    200: {
        widgets?: Array<{
            id?: string;
            name?: string;
            htmlContent?: string;
            cssContent?: string | null;
            isActive?: boolean;
            displayTarget?: 'homepage';
            placementRule?: 'before_collection' | 'after_collection' | 'fixed_top_homepage' | 'fixed_bottom_homepage' | 'standalone';
            referenceCollectionId?: string | null;
            sortOrder?: number;
            createdAt?: string | null;
            updatedAt?: string | null;
        }>;
    };
};

export type GetWidgetsActiveHomepageResponse = GetWidgetsActiveHomepageResponses[keyof GetWidgetsActiveHomepageResponses];

export type GetSeoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/seo';
};

export type GetSeoErrors = {
    500: unknown;
};

export type GetSeoResponses = {
    /**
     * Global SEO settings.
     */
    200: {
        /**
         * The general title for the entire site, used as a suffix or default.
         */
        siteTitle?: string | null;
        /**
         * The specific SEO title for the homepage.
         */
        homepageTitle?: string | null;
        /**
         * The specific meta description for the homepage.
         */
        homepageMetaDescription?: string | null;
        /**
         * The raw content for the `robots.txt` file.
         */
        robotsTxt?: string | null;
        success?: boolean;
    };
};

export type GetSeoResponse = GetSeoResponses[keyof GetSeoResponses];

export type GetAttributesFilterableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/attributes/filterable';
};

export type GetAttributesFilterableErrors = {
    500: unknown;
};

export type GetAttributesFilterableResponses = {
    /**
     * Successfully retrieved filterable attributes.
     */
    200: {
        filters?: Array<{
            id?: string;
            name?: string;
            slug?: string;
            values?: Array<string>;
        }>;
    };
};

export type GetAttributesFilterableResponse = GetAttributesFilterableResponses[keyof GetAttributesFilterableResponses];

export type GetAttributesCategoryByCategoryIdData = {
    body?: never;
    path: {
        /**
         * The ID of the category
         */
        categoryId: string;
    };
    query?: never;
    url: '/attributes/category/{categoryId}';
};

export type GetAttributesCategoryByCategoryIdErrors = {
    500: unknown;
};

export type GetAttributesCategoryByCategoryIdResponses = {
    /**
     * Successfully retrieved category attributes.
     */
    200: {
        filters?: Array<{
            id?: string;
            name?: string;
            slug?: string;
            values?: Array<string>;
        }>;
    };
};

export type GetAttributesCategoryByCategoryIdResponse = GetAttributesCategoryByCategoryIdResponses[keyof GetAttributesCategoryByCategoryIdResponses];

export type GetAttributesCategorySlugByCategorySlugData = {
    body?: never;
    path: {
        /**
         * The slug of the category
         */
        categorySlug: string;
    };
    query?: never;
    url: '/attributes/category-slug/{categorySlug}';
};

export type GetAttributesCategorySlugByCategorySlugErrors = {
    /**
     * Category not found
     */
    404: {
        error?: string;
    };
    500: unknown;
};

export type GetAttributesCategorySlugByCategorySlugError = GetAttributesCategorySlugByCategorySlugErrors[keyof GetAttributesCategorySlugByCategorySlugErrors];

export type GetAttributesCategorySlugByCategorySlugResponses = {
    /**
     * Successfully retrieved category attributes.
     */
    200: {
        filters?: Array<{
            id?: string;
            name?: string;
            slug?: string;
            values?: Array<string>;
        }>;
    };
};

export type GetAttributesCategorySlugByCategorySlugResponse = GetAttributesCategorySlugByCategorySlugResponses[keyof GetAttributesCategorySlugByCategorySlugResponses];

export type GetAttributesSearchFiltersData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search query to find matching products
         */
        q: string;
        /**
         * Optional: Limit search to a specific category
         */
        categoryId?: string;
    };
    url: '/attributes/search-filters';
};

export type GetAttributesSearchFiltersErrors = {
    500: unknown;
};

export type GetAttributesSearchFiltersResponses = {
    /**
     * Successfully retrieved search filters.
     */
    200: {
        filters?: Array<{
            id?: string;
            name?: string;
            slug?: string;
            values?: Array<string>;
        }>;
    };
};

export type GetAttributesSearchFiltersResponse = GetAttributesSearchFiltersResponses[keyof GetAttributesSearchFiltersResponses];

export type PostAbandonedCheckoutsData = {
    body: {
        /**
         * A unique identifier for the user's checkout session, generated by the storefront.
         */
        checkoutId: string;
        /**
         * The customer's phone number, if entered.
         */
        customerPhone?: string;
        /**
         * A JSON object containing all data captured from the checkout form, including cart items, customer details, etc.
         */
        checkoutData: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/abandoned-checkouts';
};

export type PostAbandonedCheckoutsErrors = {
    400: unknown;
    500: unknown;
};

export type PostAbandonedCheckoutsResponses = {
    /**
     * Successfully saved the abandoned checkout data.
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type PostAbandonedCheckoutsResponse = PostAbandonedCheckoutsResponses[keyof PostAbandonedCheckoutsResponses];

export type DeleteAbandonedCheckoutsByCheckoutIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier for the checkout session to be deleted.
         */
        checkoutId: string;
    };
    query?: never;
    url: '/abandoned-checkouts/{checkoutId}';
};

export type DeleteAbandonedCheckoutsByCheckoutIdErrors = {
    500: unknown;
};

export type DeleteAbandonedCheckoutsByCheckoutIdResponses = {
    /**
     * Successfully deleted the abandoned checkout record.
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type DeleteAbandonedCheckoutsByCheckoutIdResponse = DeleteAbandonedCheckoutsByCheckoutIdResponses[keyof DeleteAbandonedCheckoutsByCheckoutIdResponses];

export type PostMetaEventsData = {
    body: {
        /**
         * A standard or custom event name (e.g., 'Purchase', 'ViewContent').
         */
        eventName: string;
        /**
         * The URL of the page where the event occurred.
         */
        eventSourceUrl: string;
        /**
         * Where the conversion occurred. Defaults to 'website' if not provided.
         */
        actionSource?: 'website' | 'app' | 'offline' | 'chat' | 'physical_store' | 'system_generated' | 'business_messaging' | 'other';
        /**
         * User identification data. Provide as many fields as possible to improve Event Match Quality. PII (like email, phone, name) will be hashed by the server automatically according to Meta's requirements.
         */
        userData: {
            /**
             * User's email address (unhashed).
             */
            em?: string;
            /**
             * User's phone number (unhashed). Should include country code if possible.
             */
            ph?: string;
            /**
             * User's first name (unhashed).
             */
            fn?: string;
            /**
             * User's last name (unhashed).
             */
            ln?: string;
            /**
             * User's gender. 'f' for female or 'm' for male.
             */
            ge?: 'f' | 'm';
            /**
             * User's date of birth in YYYYMMDD format.
             */
            db?: string;
            /**
             * User's city (unhashed).
             */
            ct?: string;
            /**
             * User's state (unhashed). 2-letter ANSI code for US.
             */
            st?: string;
            /**
             * User's zip code.
             */
            zp?: string;
            /**
             * User's country. 2-letter ISO 3166-1 alpha-2 code.
             */
            country?: string;
            /**
             * A unique ID from your system for the user.
             */
            external_id?: string;
            /**
             * User's IP address.
             */
            client_ip_address?: string;
            /**
             * User's browser user agent string.
             */
            client_user_agent?: string;
            /**
             * The Facebook browser ID (_fbp cookie).
             */
            fbp?: string;
            /**
             * The Facebook click ID (_fbc cookie). Generated from fbclid URL parameter.
             */
            fbc?: string;
            /**
             * The subscription ID for the user in a transaction.
             */
            subscription_id?: string;
            /**
             * The ID associated with a lead generated from a Meta Lead Ad.
             */
            lead_id?: number;
        };
        /**
         * Event-specific data like value, currency, or contents.
         */
        customData?: {
            /**
             * Monetary value of the event.
             */
            value?: number;
            /**
             * ISO 4217 currency code.
             */
            currency?: string;
            /**
             * Array of product SKUs or IDs.
             */
            content_ids?: Array<string>;
            /**
             * Detailed information about products in the event.
             */
            contents?: Array<{
                id?: string;
                quantity?: number;
                item_price?: number;
            }>;
            content_type?: 'product' | 'product_group';
            /**
             * The order or transaction ID. Important for purchase events.
             */
            order_id?: string;
            /**
             * The user's search query.
             */
            search_string?: string;
        };
    };
    path?: never;
    query?: never;
    url: '/meta/events';
};

export type PostMetaEventsErrors = {
    /**
     * Bad Request - The provided payload was invalid.
     */
    400: _Error;
    /**
     * Service Unavailable - The Conversions API is not configured or enabled on the server.
     */
    503: _Error;
};

export type PostMetaEventsError = PostMetaEventsErrors[keyof PostMetaEventsErrors];

export type PostMetaEventsResponses = {
    /**
     * Event successfully received and queued for processing.
     */
    200: {
        success?: boolean;
        message?: string;
        /**
         * The unique ID assigned to this event for server-side deduplication.
         */
        eventId?: string;
    };
};

export type PostMetaEventsResponse = PostMetaEventsResponses[keyof PostMetaEventsResponses];
