ALTER TABLE "settings" ADD COLUMN "revision" integer DEFAULT 1 NOT NULL;
--> statement-breakpoint
UPDATE "settings" SET "key" = 'document', "type" = 'json', "value" = (CASE WHEN json_valid("value") THEN "value"::jsonb ELSE '{}'::jsonb END || jsonb_build_object('storefrontUrl', coalesce((SELECT "storefront_url" FROM "site_settings" LIMIT 1), '')))::text WHERE "category" = 'platform' AND "key" = 'config';
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category") SELECT gen_random_uuid()::text, 'document', jsonb_build_object('storefrontUrl', coalesce((SELECT "storefront_url" FROM "site_settings" LIMIT 1), ''), 'apiUrl', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'platform' AND "key" = 'api_url'), ''), 'dashboardUrl', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'platform' AND "key" = 'dashboard_url'), ''), 'mediaUrl', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'platform' AND "key" = 'media_url'), ''), 'customerAuthCookieDomain', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'platform' AND "key" = 'customer_auth_cookie_domain'), ''), 'corsAllowedOrigins', coalesce((SELECT CASE WHEN (CASE WHEN json_valid("value") THEN jsonb_typeof("value"::jsonb) END) = 'array' THEN "value"::jsonb ELSE to_jsonb("value") END FROM "settings" WHERE "category" = 'platform' AND "key" IN ('cors_allowed_origins')), '[]'::jsonb))::text, 'json', 'platform' WHERE NOT EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'platform' AND "key" IN ('document')) AND (EXISTS (SELECT 1 FROM "site_settings") OR EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'platform'));
--> statement-breakpoint
UPDATE "settings" SET "key" = 'document', "type" = 'json' WHERE "category" IN ('email', 'firebase') AND "key" = 'config';
--> statement-breakpoint
UPDATE "settings" SET "key" = 'document', "type" = 'json' WHERE "category" = 'media' AND "key" = 'image_optimization';
--> statement-breakpoint
UPDATE "settings" SET "key" = 'document', "type" = 'json', "value" = jsonb_build_object('cspAllowedDomains', "value")::text WHERE "category" = 'security' AND "key" = 'csp_allowed_domains';
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category") SELECT gen_random_uuid()::text, 'document', jsonb_build_object('provider', CASE WHEN (SELECT "value" FROM "settings" WHERE "category" = 'email' AND "key" = 'email_provider') IN ('cloudflare', 'resend') THEN (SELECT "value" FROM "settings" WHERE "category" = 'email' AND "key" = 'email_provider') ELSE '' END, 'sender', trim(coalesce((SELECT "value" FROM "settings" WHERE "category" = 'email' AND "key" = 'email_sender'), '')), 'resendApiKey', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'email' AND "key" = 'resend_api_key'), ''))::text, 'json', 'email' WHERE NOT EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'email' AND "key" IN ('document')) AND EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'email' AND "key" IN ('email_provider', 'email_sender', 'resend_api_key'));
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category") SELECT gen_random_uuid()::text, 'document', jsonb_build_object('serviceAccount', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'firebase' AND "key" = 'service_account'), ''), 'publicConfig', coalesce((SELECT "value"::jsonb FROM "settings" WHERE "category" = 'firebase' AND "key" = 'public_config' AND (CASE WHEN json_valid("value") THEN jsonb_typeof("value"::jsonb) END) = 'object'), '{}'::jsonb))::text, 'json', 'firebase' WHERE NOT EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'firebase' AND "key" IN ('document')) AND EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'firebase' AND "key" IN ('service_account', 'public_config'));
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category") SELECT gen_random_uuid()::text, 'document', jsonb_build_object('accessToken', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'whatsapp' AND "key" = 'access_token'), trim((SELECT "whatsapp_access_token" FROM "site_settings" LIMIT 1)), ''), 'phoneNumberId', coalesce((SELECT "whatsapp_phone_number_id" FROM "site_settings" LIMIT 1), ''), 'authTemplateName', coalesce((SELECT "whatsapp_template_name" FROM "site_settings" LIMIT 1), ''))::text, 'json', 'whatsapp' WHERE EXISTS (SELECT 1 FROM "site_settings") OR EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'whatsapp' AND "key" IN ('access_token'));
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category") SELECT gen_random_uuid()::text, 'document', jsonb_build_object('activeProvider', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'sms' AND "key" = 'active_provider'), ''), 'bdbulksmsToken', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'sms' AND "key" = 'bdbulksms_token'), ''), 'mimsmsUsername', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'sms' AND "key" = 'mimsms_username'), ''), 'mimsmsApiKey', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'sms' AND "key" = 'mimsms_api_key'), ''), 'mimsmsSenderName', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'sms' AND "key" = 'mimsms_sender_name'), ''), 'smsnetbdApiKey', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'sms' AND "key" = 'smsnetbd_api_key'), ''), 'smsnetbdSenderId', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'sms' AND "key" = 'smsnetbd_sender_id'), ''), 'gennetApiToken', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'sms' AND "key" = 'gennet_api_token'), ''), 'gennetBaseUrl', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'sms' AND "key" = 'gennet_base_url'), ''), 'gennetSid', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'sms' AND "key" = 'gennet_sid'), ''))::text, 'json', 'sms' WHERE EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'sms');
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category") SELECT gen_random_uuid()::text, 'document', jsonb_build_object('companyName', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'business_info' AND "key" = 'company_name'), ''), 'legalName', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'business_info' AND "key" = 'legal_name'), ''), 'addressLine1', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'business_info' AND "key" = 'address_line1'), ''), 'addressLine2', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'business_info' AND "key" = 'address_line2'), ''), 'city', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'business_info' AND "key" = 'city'), ''), 'stateRegion', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'business_info' AND "key" = 'state_region'), ''), 'postalCode', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'business_info' AND "key" = 'postal_code'), ''), 'country', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'business_info' AND "key" = 'country'), 'Bangladesh'), 'phone', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'business_info' AND "key" = 'phone'), ''), 'email', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'business_info' AND "key" = 'email'), ''), 'taxId', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'business_info' AND "key" = 'tax_id'), ''), 'invoicePrefix', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'business_info' AND "key" = 'invoice_prefix'), 'INV'), 'invoiceFooterText', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'business_info' AND "key" = 'invoice_footer_text'), ''), 'invoiceLogoUrl', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'business_info' AND "key" = 'invoice_logo_url'), ''))::text, 'json', 'business' WHERE EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'business_info');
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category") SELECT gen_random_uuid()::text, 'document', jsonb_build_object('currencyCode', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'currency' AND "key" = 'currency_code'), ''), 'currencySymbol', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'currency' AND "key" = 'currency_symbol'), '৳'), 'usdExchangeRate', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'currency' AND "key" = 'usd_exchange_rate'), '1'))::text, 'json', 'currency' WHERE EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'currency' AND "key" IN ('currency_code'));
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category") SELECT gen_random_uuid()::text, 'document', jsonb_build_object('allowedCountries', (CASE WHEN (CASE WHEN json_valid("value") THEN jsonb_typeof("value"::jsonb) END) = 'array' THEN "value"::jsonb WHEN (CASE WHEN json_valid("value") THEN jsonb_typeof("value"::jsonb) END) = 'object' AND jsonb_typeof("value"::jsonb -> 'countries') = 'array' THEN "value"::jsonb -> 'countries' ELSE '[]'::jsonb END), 'allowedCountriesMode', (CASE WHEN (CASE WHEN json_valid("value") THEN jsonb_typeof("value"::jsonb) END) = 'object' AND ("value"::jsonb ->> 'mode') = 'exclude' THEN 'exclude' ELSE 'include' END))::text, 'json', 'customer_countries' FROM "settings" WHERE "category" = 'phone' AND "key" IN ('allowed_countries');
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category", "revision") SELECT gen_random_uuid()::text, 'document', jsonb_build_object('guestCheckoutEnabled', ("guest_checkout_enabled" <> 0), 'checkoutMode', "checkout_mode", 'partialPaymentEnabled', ("partial_payment_enabled" <> 0), 'partialPaymentAmount', "partial_payment_amount")::text, 'json', 'checkout', "checkout_flow_revision" FROM "site_settings";
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category") SELECT gen_random_uuid()::text, 'document', jsonb_build_object('authVerificationMethod', coalesce((SELECT "auth_verification_method" FROM "site_settings" LIMIT 1), 'email'), 'policy', coalesce((SELECT "value"::jsonb FROM "settings" WHERE "category" = 'customer_auth' AND "key" = 'policy' AND (CASE WHEN json_valid("value") THEN jsonb_typeof("value"::jsonb) END) = 'object'), 'null'::jsonb))::text, 'json', 'customer_auth' WHERE EXISTS (SELECT 1 FROM "site_settings") OR EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'customer_auth' AND "key" IN ('policy'));
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category") SELECT gen_random_uuid()::text, 'document', "value"::jsonb::text, 'json', 'customer_requests' FROM "settings" WHERE "category" = 'order_support' AND "key" IN ('customer_request_policy') AND (CASE WHEN json_valid("value") THEN jsonb_typeof("value"::jsonb) END) = 'object';
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category", "revision") SELECT gen_random_uuid()::text, 'document', (CASE WHEN (CASE WHEN json_valid("header_config") THEN jsonb_typeof("header_config"::jsonb) END) = 'object' THEN "header_config"::jsonb ELSE '{}'::jsonb END)::text, 'json', 'header', "header_config_revision" FROM "site_settings";
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category", "revision") SELECT gen_random_uuid()::text, 'document', (CASE WHEN (CASE WHEN json_valid("footer_config") THEN jsonb_typeof("footer_config"::jsonb) END) = 'object' THEN "footer_config"::jsonb ELSE '{}'::jsonb END)::text, 'json', 'footer', "footer_config_revision" FROM "site_settings";
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category", "revision") SELECT gen_random_uuid()::text, 'document', (CASE WHEN (CASE WHEN json_valid("homepage_config") THEN jsonb_typeof("homepage_config"::jsonb) END) = 'object' THEN "homepage_config"::jsonb ELSE '{}'::jsonb END)::text, 'json', 'homepage', "homepage_config_revision" FROM "site_settings";
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category") SELECT gen_random_uuid()::text, 'document', jsonb_build_object('siteTitle', coalesce((SELECT "site_title" FROM "site_settings" LIMIT 1), ''), 'homepageTitle', coalesce((SELECT "homepage_title" FROM "site_settings" LIMIT 1), ''), 'homepageMetaDescription', coalesce((SELECT "homepage_meta_description" FROM "site_settings" LIMIT 1), ''), 'robotsTxt', coalesce((SELECT "robots_txt" FROM "site_settings" LIMIT 1), ''), 'discovery', coalesce((SELECT "value"::jsonb FROM "settings" WHERE "category" = 'seo' AND "key" = 'discovery' AND json_valid("value")), 'null'::jsonb), 'returnPolicy', coalesce((SELECT "value"::jsonb FROM "settings" WHERE "category" = 'seo' AND "key" = 'return_policy' AND json_valid("value")), 'null'::jsonb))::text, 'json', 'seo' WHERE EXISTS (SELECT 1 FROM "site_settings") OR EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'seo');
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category") SELECT gen_random_uuid()::text, 'document', jsonb_build_object('orderChannels', coalesce((SELECT "value"::jsonb FROM "settings" WHERE "category" = 'notifications' AND "key" = 'order_channels' AND json_valid("value")), 'null'::jsonb), 'adminChannels', coalesce((SELECT "value"::jsonb FROM "settings" WHERE "category" = 'notifications' AND "key" = 'admin_channels' AND json_valid("value")), 'null'::jsonb), 'whatsappOrderTemplateName', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'notifications' AND "key" = 'whatsapp_order_template_name'), 'order_status_update'), 'whatsappOrderTemplateLanguage', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'notifications' AND "key" = 'whatsapp_order_template_language'), 'en_US'))::text, 'json', 'notifications' WHERE EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'notifications');
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category") SELECT gen_random_uuid()::text, 'document', jsonb_build_object('secretKey', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'stripe' AND "key" = 'secret_key'), ''), 'publishableKey', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'stripe' AND "key" = 'publishable_key'), ''), 'webhookSecret', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'stripe' AND "key" = 'webhook_secret'), ''), 'enabled', (CASE WHEN (SELECT "value" FROM "settings" WHERE "category" = 'stripe' AND "key" = 'enabled') IS NOT NULL THEN (SELECT "value" FROM "settings" WHERE "category" = 'stripe' AND "key" = 'enabled') <> 'false' ELSE coalesce((SELECT "value" FROM "settings" WHERE "category" = 'stripe' AND "key" = 'secret_key'), '') <> '' AND coalesce((SELECT "value" FROM "settings" WHERE "category" = 'stripe' AND "key" = 'publishable_key'), '') <> '' AND coalesce((SELECT "value" FROM "settings" WHERE "category" = 'stripe' AND "key" = 'webhook_secret'), '') <> '' END))::text, 'json', 'stripe' WHERE EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'stripe' AND (("key" IN ('secret_key', 'publishable_key', 'webhook_secret') AND "value" <> '') OR "key" = 'enabled'));
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category") SELECT gen_random_uuid()::text, 'document', jsonb_build_object('storeId', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'sslcommerz' AND "key" = 'store_id'), ''), 'storePassword', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'sslcommerz' AND "key" = 'store_password'), ''), 'sandbox', (coalesce((SELECT "value" FROM "settings" WHERE "category" = 'sslcommerz' AND "key" = 'sandbox'), 'true') <> 'false'), 'enabled', (CASE WHEN (SELECT "value" FROM "settings" WHERE "category" = 'sslcommerz' AND "key" = 'enabled') IS NOT NULL THEN (SELECT "value" FROM "settings" WHERE "category" = 'sslcommerz' AND "key" = 'enabled') <> 'false' ELSE trim(coalesce((SELECT "value" FROM "settings" WHERE "category" = 'sslcommerz' AND "key" = 'store_id'), '')) <> '' AND trim(coalesce((SELECT "value" FROM "settings" WHERE "category" = 'sslcommerz' AND "key" = 'store_password'), '')) <> '' END))::text, 'json', 'sslcommerz' WHERE EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'sslcommerz' AND (("key" IN ('store_id', 'store_password') AND "value" <> '') OR "key" IN ('sandbox', 'enabled')));
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category") SELECT gen_random_uuid()::text, 'document', jsonb_build_object('enabledMethods', (CASE WHEN EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'payment_methods' AND "key" IN ('enabled_methods')) THEN coalesce((SELECT "value"::jsonb FROM "settings" WHERE "category" = 'payment_methods' AND "key" = 'enabled_methods' AND (CASE WHEN json_valid("value") THEN jsonb_typeof("value"::jsonb) END) = 'array'), '[]'::jsonb) ELSE 'null'::jsonb END), 'defaultMethod', coalesce((SELECT "value" FROM "settings" WHERE "category" = 'payment_methods' AND "key" = 'default_method'), 'cod'))::text, 'json', 'payment_methods' WHERE EXISTS (SELECT 1 FROM "settings" WHERE "category" = 'payment_methods');
--> statement-breakpoint
INSERT INTO "settings" ("id", "key", "value", "type", "category") SELECT gen_random_uuid()::text, 'document', jsonb_build_object('pixelId', coalesce("pixel_id", ''), 'accessToken', coalesce("access_token", ''), 'testEventCode', coalesce("test_event_code", ''), 'isEnabled', ("is_enabled" <> 0), 'logRetentionDays', "log_retention_days")::text, 'json', 'meta_conversions' FROM "meta_conversions_settings" WHERE "singleton_key" = 'default';
--> statement-breakpoint
DELETE FROM "settings" WHERE "key" <> 'document' AND "category" NOT IN ('notification_provider_health', 'fraud-checker');
--> statement-breakpoint
DROP TABLE "site_settings";
--> statement-breakpoint
DROP TABLE "meta_conversions_settings";
--> statement-breakpoint
INSERT INTO "scalius_schema_migrations" ("version", "name", "source_sha256") VALUES (67, '0067_settings_documents', 'cdf999ee82cb87fb8811552eb1d76d87a99d36eecf0508c4ac742699504f0205');
