-- Fills the catalogue projections that 0090 created (product_facet_values,
-- product_buyer_state) for every product, so listings, the sitemap and brand
-- pages read a complete buyer state the moment the API that reads them goes
-- live: no empty window, no staff action. Generated by
-- packages/core/scripts/catalog-projection-fill.ts from
-- catalogProjectionFillStatements, the builders every product, SKU and stock
-- write appends to its batch (a test keeps this file equal to that output).
-- Idempotent: the facet rows are replaced and the buyer state is upserted.
delete from "product_facet_values" where 1 = 1;
--> statement-breakpoint
insert into "product_facet_values" ("owner_id", "product_id", "variant_id", "facet_kind", "facet_key", "value_key", "value_label", "value_number", "sort_order") select "product_attribute_values"."product_id", "product_attribute_values"."product_id", NULL as "facet_variant_id", 'attribute' as "facet_kind_value", "product_attributes"."id", CASE "product_attributes"."value_type"
        WHEN 'enum' THEN "product_attribute_values"."value_id"
        WHEN 'number' THEN CASE WHEN "product_attribute_values"."value_number" IS NULL THEN NULL
            ELSE (CASE WHEN CAST(round("product_attribute_values"."value_number" * 1000000) AS bigint) < 0 THEN '-' ELSE '' END
        || CAST(abs(CAST(round("product_attribute_values"."value_number" * 1000000) AS bigint)) / 1000000 AS TEXT)
        || CASE WHEN (abs(CAST(round("product_attribute_values"."value_number" * 1000000) AS bigint)) % 1000000) = 0 THEN ''
            ELSE '.' || rtrim(substr(CAST(1000000 + (abs(CAST(round("product_attribute_values"."value_number" * 1000000) AS bigint)) % 1000000) AS TEXT), 2), '0') END) END
        WHEN 'boolean' THEN CASE WHEN "product_attribute_values"."value_number" IS NULL THEN NULL
            ELSE CAST(CAST("product_attribute_values"."value_number" AS bigint) AS TEXT) END
        ELSE substr(lower(trim("product_attribute_values"."value")), 1, 200)
    END as "facet_value_key", COALESCE(NULLIF(substr(trim("product_attribute_values"."value"), 1, 200), ''), CASE "product_attributes"."value_type"
        WHEN 'enum' THEN "product_attribute_values"."value_id"
        WHEN 'number' THEN CASE WHEN "product_attribute_values"."value_number" IS NULL THEN NULL
            ELSE (CASE WHEN CAST(round("product_attribute_values"."value_number" * 1000000) AS bigint) < 0 THEN '-' ELSE '' END
        || CAST(abs(CAST(round("product_attribute_values"."value_number" * 1000000) AS bigint)) / 1000000 AS TEXT)
        || CASE WHEN (abs(CAST(round("product_attribute_values"."value_number" * 1000000) AS bigint)) % 1000000) = 0 THEN ''
            ELSE '.' || rtrim(substr(CAST(1000000 + (abs(CAST(round("product_attribute_values"."value_number" * 1000000) AS bigint)) % 1000000) AS TEXT), 2), '0') END) END
        WHEN 'boolean' THEN CASE WHEN "product_attribute_values"."value_number" IS NULL THEN NULL
            ELSE CAST(CAST("product_attribute_values"."value_number" AS bigint) AS TEXT) END
        ELSE substr(lower(trim("product_attribute_values"."value")), 1, 200)
    END) as "facet_value_label", CASE WHEN "product_attributes"."value_type" IN ('number', 'boolean')
                THEN "product_attribute_values"."value_number" ELSE NULL END as "facet_value_number", COALESCE("attribute_values"."sort_order", 0) as "facet_sort_order" from "product_attribute_values" inner join "product_attributes" on ("product_attributes"."id" = "product_attribute_values"."attribute_id" and "product_attributes"."deleted_at" is null) left join "attribute_values" on "attribute_values"."id" = "product_attribute_values"."value_id" where (1 = 1 and length("product_attributes"."id") BETWEEN 1 AND 120 and length(CASE "product_attributes"."value_type"
        WHEN 'enum' THEN "product_attribute_values"."value_id"
        WHEN 'number' THEN CASE WHEN "product_attribute_values"."value_number" IS NULL THEN NULL
            ELSE (CASE WHEN CAST(round("product_attribute_values"."value_number" * 1000000) AS bigint) < 0 THEN '-' ELSE '' END
        || CAST(abs(CAST(round("product_attribute_values"."value_number" * 1000000) AS bigint)) / 1000000 AS TEXT)
        || CASE WHEN (abs(CAST(round("product_attribute_values"."value_number" * 1000000) AS bigint)) % 1000000) = 0 THEN ''
            ELSE '.' || rtrim(substr(CAST(1000000 + (abs(CAST(round("product_attribute_values"."value_number" * 1000000) AS bigint)) % 1000000) AS TEXT), 2), '0') END) END
        WHEN 'boolean' THEN CASE WHEN "product_attribute_values"."value_number" IS NULL THEN NULL
            ELSE CAST(CAST("product_attribute_values"."value_number" AS bigint) AS TEXT) END
        ELSE substr(lower(trim("product_attribute_values"."value")), 1, 200)
    END) BETWEEN 1 AND 200) on conflict do nothing;
--> statement-breakpoint
insert into "product_facet_values" ("owner_id", "product_id", "variant_id", "facet_kind", "facet_key", "value_key", "value_label", "value_number", "sort_order") select "product_variants"."id", "product_variants"."product_id", "product_variants"."id", 'option' as "facet_kind_value", 'option.' || replace("product_option_definitions"."normalized_name", ' ', '-') as "facet_key_value", substr("product_option_values"."normalized_value", 1, 200) as "facet_value_key", COALESCE(NULLIF(substr(trim("product_option_values"."value"), 1, 200), ''), substr("product_option_values"."normalized_value", 1, 200)) as "facet_value_label", NULL as "facet_value_number", "product_option_values"."position" from "product_variants" inner join "product_variant_option_values" on "product_variant_option_values"."variant_id" = "product_variants"."id" inner join "product_option_definitions" on ("product_option_definitions"."id" = "product_variant_option_values"."option_definition_id" and "product_option_definitions"."deleted_at" is null) inner join "product_option_values" on ("product_option_values"."id" = "product_variant_option_values"."option_value_id" and "product_option_values"."deleted_at" is null) where (1 = 1 and "product_variants"."deleted_at" is null and "product_variants"."id" <> 'default' and length('option.' || replace("product_option_definitions"."normalized_name", ' ', '-')) BETWEEN 1 AND 120 and length("product_option_values"."normalized_value") >= 1) on conflict do nothing;
--> statement-breakpoint
insert into "product_buyer_state" ("product_id", "is_public", "category_id", "brand_id", "product_created_at", "sku_id", "from_minor", "to_minor", "base_minor", "discount_depth_bps", "has_discount", "available_for_sale", "has_customer_options", "availability_band", "refreshed_at") select "products"."id", CASE
                WHEN "products"."is_active" = 1
                  AND "products"."deleted_at" IS NULL
                  AND "buyer_catalog_pricing"."id" IS NOT NULL
                  AND (
        (
        EXISTS (
            SELECT 1
            FROM "product_variants" AS buyer_option_sku
            WHERE 
        buyer_option_sku.product_id = "products"."id"
        AND buyer_option_sku.deleted_at IS NULL
        AND buyer_option_sku.id <> 'default'
    
              AND buyer_option_sku.is_default = 0
              AND trim(coalesce(buyer_option_sku.option_combination_key, '')) <> ''
              
        )
        AND (SELECT count(*) FROM "product_option_definitions" AS buyer_axis
             WHERE buyer_axis.product_id = "products"."id" AND buyer_axis.deleted_at IS NULL) > 0
        AND NOT EXISTS (
            SELECT 1
            FROM "product_variants" AS buyer_shape_sku
            WHERE 
        buyer_shape_sku.product_id = "products"."id"
        AND buyer_shape_sku.deleted_at IS NULL
        AND buyer_shape_sku.id <> 'default'
    
              AND buyer_shape_sku.is_default = 0
              AND (
                SELECT count(*)
                FROM "product_variant_option_values" AS buyer_assignment
                JOIN "product_option_definitions" AS buyer_definition
                  ON buyer_definition.id = buyer_assignment.option_definition_id
                 AND buyer_definition.deleted_at IS NULL
                JOIN "product_option_values" AS buyer_value
                  ON buyer_value.id = buyer_assignment.option_value_id
                 AND buyer_value.deleted_at IS NULL
                WHERE buyer_assignment.variant_id = buyer_shape_sku.id
              ) <> (
                SELECT count(*) FROM "product_option_definitions" AS buyer_required_axis
                WHERE buyer_required_axis.product_id = "products"."id"
                  AND buyer_required_axis.deleted_at IS NULL
              )
        )
    )
        OR (
            (
                SELECT count(*)
                FROM "product_variants" AS buyer_active_sku
                WHERE 
        buyer_active_sku.product_id = "products"."id"
        AND buyer_active_sku.deleted_at IS NULL
        AND buyer_active_sku.id <> 'default'
    
            ) = 1
            AND EXISTS (
                SELECT 1
                FROM "product_variants" AS buyer_simple_sku
                WHERE 
        buyer_simple_sku.product_id = "products"."id"
        AND buyer_simple_sku.deleted_at IS NULL
        AND buyer_simple_sku.id <> 'default'
    
                  AND buyer_simple_sku.is_default = 1
            )
        )
    )
                THEN 1 ELSE 0
            END as "buyer_state_is_public", "products"."category_id", "products"."brand_id", "products"."created_at", "buyer_catalog_pricing"."id", "buyer_effective_price" as "buyer_state_from_minor", CASE
                WHEN "buyer_catalog_pricing"."id" IS NULL THEN NULL
                ELSE MAX(COALESCE("buyer_max_price", "buyer_effective_price"), "buyer_effective_price")
            END as "buyer_state_to_minor", CASE
                WHEN "buyer_catalog_pricing"."id" IS NULL THEN NULL
                ELSE MAX("buyer_catalog_pricing"."price_minor", "buyer_effective_price")
            END as "buyer_state_base_minor", CASE
                WHEN "buyer_catalog_pricing"."id" IS NOT NULL AND "buyer_catalog_pricing"."price_minor" > 0 AND "buyer_catalog_pricing"."price_minor" > "buyer_effective_price"
                    THEN MIN(("buyer_catalog_pricing"."price_minor" - "buyer_effective_price") * 10000 / "buyer_catalog_pricing"."price_minor", 10000)
                ELSE 0
            END as "buyer_state_discount_depth_bps", COALESCE("buyer_has_discount", 0) as "buyer_state_has_discount", COALESCE("buyer_available_for_sale", 0) as "buyer_state_available_for_sale", COALESCE("buyer_has_customer_options", 0) as "buyer_state_has_customer_options", CASE
                WHEN "buyer_state_card_sku"."id" IS NULL THEN 'out_of_stock'
                WHEN "buyer_state_card_sku"."track_inventory" = 0 THEN 'untracked'
                WHEN ("buyer_state_card_sku"."stock" - "buyer_state_card_sku"."reserved_stock") <= 0 THEN 'out_of_stock'
                WHEN COALESCE("buyer_state_card_sku"."low_stock_threshold", (
    SELECT CASE WHEN json_valid("settings"."value")
      THEN CAST(scalius_compat.json_scalar_text(jsonb_extract_path(("settings"."value")::jsonb, 'defaultLowStockThreshold')) AS bigint) END
    FROM "settings"
    WHERE "settings"."category" = 'inventory' AND "settings"."key" = 'document'
  )) > 0 AND ("buyer_state_card_sku"."stock" - "buyer_state_card_sku"."reserved_stock") <= COALESCE("buyer_state_card_sku"."low_stock_threshold", (
    SELECT CASE WHEN json_valid("settings"."value")
      THEN CAST(scalius_compat.json_scalar_text(jsonb_extract_path(("settings"."value")::jsonb, 'defaultLowStockThreshold')) AS bigint) END
    FROM "settings"
    WHERE "settings"."category" = 'inventory' AND "settings"."key" = 'document'
  )) THEN 'low_stock'
                ELSE 'in_stock'
            END as "buyer_state_availability_band", unixepoch() as "buyer_state_refreshed_at" from "products" left join (select "product_id", "id", "price_minor", "buyer_effective_price" as "buyer_effective_price", "buyer_discount_type" as "buyer_discount_type", "buyer_discount_bps" as "buyer_discount_bps", "buyer_discount_amount" as "buyer_discount_amount", "buyer_available_for_sale" as "buyer_available_for_sale", "buyer_has_customer_options" as "buyer_has_customer_options", CASE
                WHEN "buyer_available_for_sale" = 1
                    THEN "buyer_has_available_discount"
                ELSE "buyer_has_any_discount"
            END as "buyer_has_discount", CASE
                WHEN "buyer_available_for_sale" = 1
                    THEN "buyer_max_available_effective_price"
                ELSE "buyer_max_effective_price"
            END as "buyer_max_price" from (select "buyer_pricing_sku"."product_id", "buyer_pricing_sku"."id", "buyer_pricing_sku"."price_minor", CASE
        WHEN "buyer_pricing_sku"."discount_type" = 'flat' AND "buyer_pricing_sku"."discount_amount_minor" > 0
            THEN MAX("buyer_pricing_sku"."price_minor" - "buyer_pricing_sku"."discount_amount_minor", 0)
        WHEN NOT ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) AND "buyer_pricing_product"."discount_type" = 'flat' AND "buyer_pricing_product"."discount_amount_minor" > 0
            THEN MAX("buyer_pricing_sku"."price_minor" - "buyer_pricing_product"."discount_amount_minor", 0)
        WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) OR ("buyer_pricing_product"."discount_type" = 'percentage' AND "buyer_pricing_product"."discount_bps" > 0)
            THEN MIN("buyer_pricing_sku"."price_minor", CASE coalesce((
        SELECT CASE WHEN upper(trim(coalesce(CASE WHEN json_valid("settings"."value") THEN scalius_compat.json_scalar_text(jsonb_extract_path(("settings"."value")::jsonb, 'currencyCode')) END, ''))) IN ('USD', 'EUR', 'GBP', 'JPY', 'CHF', 'CAD', 'AUD', 'NZD', 'CNY', 'HKD', 'SGD', 'SEK', 'NOK', 'DKK', 'MXN', 'BRL', 'INR', 'PKR', 'LKR', 'NPR', 'AFN', 'BTN', 'MVR', 'MYR', 'PHP', 'THB', 'IDR', 'VND', 'MMK', 'KHR', 'LAK', 'BND', 'KRW', 'TWD', 'MNT', 'KPW', 'MOP', 'AED', 'SAR', 'QAR', 'KWD', 'BHD', 'OMR', 'JOD', 'IQD', 'IRR', 'YER', 'LBP', 'SYP', 'ILS', 'KZT', 'UZS', 'KGS', 'TJS', 'TMT', 'GEL', 'AMD', 'AZN', 'TRY', 'RUB', 'UAH', 'PLN', 'CZK', 'HUF', 'RON', 'BGN', 'HRK', 'RSD', 'BAM', 'MKD', 'ALL', 'MDL', 'BYN', 'ISK', 'ARS', 'CLP', 'COP', 'PEN', 'UYU', 'PYG', 'BOB', 'VES', 'GYD', 'SRD', 'TTD', 'JMD', 'BBD', 'BSD', 'BZD', 'CRC', 'CUP', 'DOP', 'GTQ', 'HNL', 'HTG', 'NIO', 'PAB', 'AWG', 'ANG', 'KYD', 'BMD', 'XCD', 'FKP', 'NGN', 'GHS', 'XOF', 'GMD', 'GNF', 'SLL', 'LRD', 'CVE', 'MRU', 'KES', 'TZS', 'UGX', 'RWF', 'BIF', 'ETB', 'SOS', 'ERN', 'DJF', 'SDG', 'SSP', 'SCR', 'KMF', 'MGA', 'MUR', 'XAF', 'CDF', 'ZAR', 'BWP', 'LSL', 'SZL', 'NAD', 'MWK', 'ZMW', 'MZN', 'AOA', 'ZWL', 'EGP', 'DZD', 'MAD', 'TND', 'LYD', 'STN', 'FJD', 'PGK', 'WST', 'TOP', 'VUV', 'SBD', 'XPF', 'XDR', 'XAG', 'XAU') THEN 1 ELSE 100 END
        FROM "settings"
        WHERE "settings"."category" = 'currency' AND "settings"."key" = 'document'
    ), 100)
                WHEN 100 THEN ((("buyer_pricing_sku"."price_minor" * (10000 - MIN(CASE WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) THEN "buyer_pricing_sku"."discount_bps" ELSE "buyer_pricing_product"."discount_bps" END, 10000))) + 500000) / 1000000) * 100
                ELSE (("buyer_pricing_sku"."price_minor" * (10000 - MIN(CASE WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) THEN "buyer_pricing_sku"."discount_bps" ELSE "buyer_pricing_product"."discount_bps" END, 10000))) + 5000) / 10000
            END)
        ELSE "buyer_pricing_sku"."price_minor"
    END as "buyer_effective_price", CASE
            WHEN CASE
        WHEN "buyer_pricing_sku"."discount_type" = 'flat' AND "buyer_pricing_sku"."discount_amount_minor" > 0 THEN 1
        WHEN "buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0 THEN 1
        ELSE 0
    END = 1 THEN "buyer_pricing_sku"."discount_type"
            ELSE "buyer_pricing_product"."discount_type"
        END as "buyer_discount_type", CASE
            WHEN CASE
        WHEN "buyer_pricing_sku"."discount_type" = 'flat' AND "buyer_pricing_sku"."discount_amount_minor" > 0 THEN 1
        WHEN "buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0 THEN 1
        ELSE 0
    END = 1 THEN "buyer_pricing_sku"."discount_bps"
            ELSE "buyer_pricing_product"."discount_bps"
        END as "buyer_discount_bps", CASE
            WHEN CASE
        WHEN "buyer_pricing_sku"."discount_type" = 'flat' AND "buyer_pricing_sku"."discount_amount_minor" > 0 THEN 1
        WHEN "buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0 THEN 1
        ELSE 0
    END = 1 THEN "buyer_pricing_sku"."discount_amount_minor"
            ELSE "buyer_pricing_product"."discount_amount_minor"
        END as "buyer_discount_amount", MAX(CASE
        WHEN "buyer_pricing_sku"."track_inventory" = 0
          OR ("buyer_pricing_sku"."stock" - "buyer_pricing_sku"."reserved_stock") > 0
        THEN 1 ELSE 0
    END) OVER (
                PARTITION BY "buyer_pricing_sku"."product_id"
            ) as "buyer_available_for_sale", MAX(CASE
                WHEN "buyer_pricing_sku"."is_default" = 0
                  AND trim(coalesce("buyer_pricing_sku"."option_combination_key", '')) <> ''
                THEN 1 ELSE 0
            END) OVER (PARTITION BY "buyer_pricing_sku"."product_id") as "buyer_has_customer_options", MAX(CASE
                WHEN CASE
        WHEN "buyer_pricing_sku"."discount_type" = 'flat' AND "buyer_pricing_sku"."discount_amount_minor" > 0
            THEN MAX("buyer_pricing_sku"."price_minor" - "buyer_pricing_sku"."discount_amount_minor", 0)
        WHEN NOT ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) AND "buyer_pricing_product"."discount_type" = 'flat' AND "buyer_pricing_product"."discount_amount_minor" > 0
            THEN MAX("buyer_pricing_sku"."price_minor" - "buyer_pricing_product"."discount_amount_minor", 0)
        WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) OR ("buyer_pricing_product"."discount_type" = 'percentage' AND "buyer_pricing_product"."discount_bps" > 0)
            THEN MIN("buyer_pricing_sku"."price_minor", CASE coalesce((
        SELECT CASE WHEN upper(trim(coalesce(CASE WHEN json_valid("settings"."value") THEN scalius_compat.json_scalar_text(jsonb_extract_path(("settings"."value")::jsonb, 'currencyCode')) END, ''))) IN ('USD', 'EUR', 'GBP', 'JPY', 'CHF', 'CAD', 'AUD', 'NZD', 'CNY', 'HKD', 'SGD', 'SEK', 'NOK', 'DKK', 'MXN', 'BRL', 'INR', 'PKR', 'LKR', 'NPR', 'AFN', 'BTN', 'MVR', 'MYR', 'PHP', 'THB', 'IDR', 'VND', 'MMK', 'KHR', 'LAK', 'BND', 'KRW', 'TWD', 'MNT', 'KPW', 'MOP', 'AED', 'SAR', 'QAR', 'KWD', 'BHD', 'OMR', 'JOD', 'IQD', 'IRR', 'YER', 'LBP', 'SYP', 'ILS', 'KZT', 'UZS', 'KGS', 'TJS', 'TMT', 'GEL', 'AMD', 'AZN', 'TRY', 'RUB', 'UAH', 'PLN', 'CZK', 'HUF', 'RON', 'BGN', 'HRK', 'RSD', 'BAM', 'MKD', 'ALL', 'MDL', 'BYN', 'ISK', 'ARS', 'CLP', 'COP', 'PEN', 'UYU', 'PYG', 'BOB', 'VES', 'GYD', 'SRD', 'TTD', 'JMD', 'BBD', 'BSD', 'BZD', 'CRC', 'CUP', 'DOP', 'GTQ', 'HNL', 'HTG', 'NIO', 'PAB', 'AWG', 'ANG', 'KYD', 'BMD', 'XCD', 'FKP', 'NGN', 'GHS', 'XOF', 'GMD', 'GNF', 'SLL', 'LRD', 'CVE', 'MRU', 'KES', 'TZS', 'UGX', 'RWF', 'BIF', 'ETB', 'SOS', 'ERN', 'DJF', 'SDG', 'SSP', 'SCR', 'KMF', 'MGA', 'MUR', 'XAF', 'CDF', 'ZAR', 'BWP', 'LSL', 'SZL', 'NAD', 'MWK', 'ZMW', 'MZN', 'AOA', 'ZWL', 'EGP', 'DZD', 'MAD', 'TND', 'LYD', 'STN', 'FJD', 'PGK', 'WST', 'TOP', 'VUV', 'SBD', 'XPF', 'XDR', 'XAG', 'XAU') THEN 1 ELSE 100 END
        FROM "settings"
        WHERE "settings"."category" = 'currency' AND "settings"."key" = 'document'
    ), 100)
                WHEN 100 THEN ((("buyer_pricing_sku"."price_minor" * (10000 - MIN(CASE WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) THEN "buyer_pricing_sku"."discount_bps" ELSE "buyer_pricing_product"."discount_bps" END, 10000))) + 500000) / 1000000) * 100
                ELSE (("buyer_pricing_sku"."price_minor" * (10000 - MIN(CASE WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) THEN "buyer_pricing_sku"."discount_bps" ELSE "buyer_pricing_product"."discount_bps" END, 10000))) + 5000) / 10000
            END)
        ELSE "buyer_pricing_sku"."price_minor"
    END < "buyer_pricing_sku"."price_minor" THEN 1 ELSE 0
            END) OVER (PARTITION BY "buyer_pricing_sku"."product_id") as "buyer_has_any_discount", MAX(CASE
                WHEN CASE
        WHEN "buyer_pricing_sku"."track_inventory" = 0
          OR ("buyer_pricing_sku"."stock" - "buyer_pricing_sku"."reserved_stock") > 0
        THEN 1 ELSE 0
    END = 1 AND CASE
        WHEN "buyer_pricing_sku"."discount_type" = 'flat' AND "buyer_pricing_sku"."discount_amount_minor" > 0
            THEN MAX("buyer_pricing_sku"."price_minor" - "buyer_pricing_sku"."discount_amount_minor", 0)
        WHEN NOT ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) AND "buyer_pricing_product"."discount_type" = 'flat' AND "buyer_pricing_product"."discount_amount_minor" > 0
            THEN MAX("buyer_pricing_sku"."price_minor" - "buyer_pricing_product"."discount_amount_minor", 0)
        WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) OR ("buyer_pricing_product"."discount_type" = 'percentage' AND "buyer_pricing_product"."discount_bps" > 0)
            THEN MIN("buyer_pricing_sku"."price_minor", CASE coalesce((
        SELECT CASE WHEN upper(trim(coalesce(CASE WHEN json_valid("settings"."value") THEN scalius_compat.json_scalar_text(jsonb_extract_path(("settings"."value")::jsonb, 'currencyCode')) END, ''))) IN ('USD', 'EUR', 'GBP', 'JPY', 'CHF', 'CAD', 'AUD', 'NZD', 'CNY', 'HKD', 'SGD', 'SEK', 'NOK', 'DKK', 'MXN', 'BRL', 'INR', 'PKR', 'LKR', 'NPR', 'AFN', 'BTN', 'MVR', 'MYR', 'PHP', 'THB', 'IDR', 'VND', 'MMK', 'KHR', 'LAK', 'BND', 'KRW', 'TWD', 'MNT', 'KPW', 'MOP', 'AED', 'SAR', 'QAR', 'KWD', 'BHD', 'OMR', 'JOD', 'IQD', 'IRR', 'YER', 'LBP', 'SYP', 'ILS', 'KZT', 'UZS', 'KGS', 'TJS', 'TMT', 'GEL', 'AMD', 'AZN', 'TRY', 'RUB', 'UAH', 'PLN', 'CZK', 'HUF', 'RON', 'BGN', 'HRK', 'RSD', 'BAM', 'MKD', 'ALL', 'MDL', 'BYN', 'ISK', 'ARS', 'CLP', 'COP', 'PEN', 'UYU', 'PYG', 'BOB', 'VES', 'GYD', 'SRD', 'TTD', 'JMD', 'BBD', 'BSD', 'BZD', 'CRC', 'CUP', 'DOP', 'GTQ', 'HNL', 'HTG', 'NIO', 'PAB', 'AWG', 'ANG', 'KYD', 'BMD', 'XCD', 'FKP', 'NGN', 'GHS', 'XOF', 'GMD', 'GNF', 'SLL', 'LRD', 'CVE', 'MRU', 'KES', 'TZS', 'UGX', 'RWF', 'BIF', 'ETB', 'SOS', 'ERN', 'DJF', 'SDG', 'SSP', 'SCR', 'KMF', 'MGA', 'MUR', 'XAF', 'CDF', 'ZAR', 'BWP', 'LSL', 'SZL', 'NAD', 'MWK', 'ZMW', 'MZN', 'AOA', 'ZWL', 'EGP', 'DZD', 'MAD', 'TND', 'LYD', 'STN', 'FJD', 'PGK', 'WST', 'TOP', 'VUV', 'SBD', 'XPF', 'XDR', 'XAG', 'XAU') THEN 1 ELSE 100 END
        FROM "settings"
        WHERE "settings"."category" = 'currency' AND "settings"."key" = 'document'
    ), 100)
                WHEN 100 THEN ((("buyer_pricing_sku"."price_minor" * (10000 - MIN(CASE WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) THEN "buyer_pricing_sku"."discount_bps" ELSE "buyer_pricing_product"."discount_bps" END, 10000))) + 500000) / 1000000) * 100
                ELSE (("buyer_pricing_sku"."price_minor" * (10000 - MIN(CASE WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) THEN "buyer_pricing_sku"."discount_bps" ELSE "buyer_pricing_product"."discount_bps" END, 10000))) + 5000) / 10000
            END)
        ELSE "buyer_pricing_sku"."price_minor"
    END < "buyer_pricing_sku"."price_minor" THEN 1 ELSE 0
            END) OVER (PARTITION BY "buyer_pricing_sku"."product_id") as "buyer_has_available_discount", MAX(CASE
                WHEN CASE
        WHEN "buyer_pricing_sku"."track_inventory" = 0
          OR ("buyer_pricing_sku"."stock" - "buyer_pricing_sku"."reserved_stock") > 0
        THEN 1 ELSE 0
    END = 1 THEN CASE
        WHEN "buyer_pricing_sku"."discount_type" = 'flat' AND "buyer_pricing_sku"."discount_amount_minor" > 0
            THEN MAX("buyer_pricing_sku"."price_minor" - "buyer_pricing_sku"."discount_amount_minor", 0)
        WHEN NOT ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) AND "buyer_pricing_product"."discount_type" = 'flat' AND "buyer_pricing_product"."discount_amount_minor" > 0
            THEN MAX("buyer_pricing_sku"."price_minor" - "buyer_pricing_product"."discount_amount_minor", 0)
        WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) OR ("buyer_pricing_product"."discount_type" = 'percentage' AND "buyer_pricing_product"."discount_bps" > 0)
            THEN MIN("buyer_pricing_sku"."price_minor", CASE coalesce((
        SELECT CASE WHEN upper(trim(coalesce(CASE WHEN json_valid("settings"."value") THEN scalius_compat.json_scalar_text(jsonb_extract_path(("settings"."value")::jsonb, 'currencyCode')) END, ''))) IN ('USD', 'EUR', 'GBP', 'JPY', 'CHF', 'CAD', 'AUD', 'NZD', 'CNY', 'HKD', 'SGD', 'SEK', 'NOK', 'DKK', 'MXN', 'BRL', 'INR', 'PKR', 'LKR', 'NPR', 'AFN', 'BTN', 'MVR', 'MYR', 'PHP', 'THB', 'IDR', 'VND', 'MMK', 'KHR', 'LAK', 'BND', 'KRW', 'TWD', 'MNT', 'KPW', 'MOP', 'AED', 'SAR', 'QAR', 'KWD', 'BHD', 'OMR', 'JOD', 'IQD', 'IRR', 'YER', 'LBP', 'SYP', 'ILS', 'KZT', 'UZS', 'KGS', 'TJS', 'TMT', 'GEL', 'AMD', 'AZN', 'TRY', 'RUB', 'UAH', 'PLN', 'CZK', 'HUF', 'RON', 'BGN', 'HRK', 'RSD', 'BAM', 'MKD', 'ALL', 'MDL', 'BYN', 'ISK', 'ARS', 'CLP', 'COP', 'PEN', 'UYU', 'PYG', 'BOB', 'VES', 'GYD', 'SRD', 'TTD', 'JMD', 'BBD', 'BSD', 'BZD', 'CRC', 'CUP', 'DOP', 'GTQ', 'HNL', 'HTG', 'NIO', 'PAB', 'AWG', 'ANG', 'KYD', 'BMD', 'XCD', 'FKP', 'NGN', 'GHS', 'XOF', 'GMD', 'GNF', 'SLL', 'LRD', 'CVE', 'MRU', 'KES', 'TZS', 'UGX', 'RWF', 'BIF', 'ETB', 'SOS', 'ERN', 'DJF', 'SDG', 'SSP', 'SCR', 'KMF', 'MGA', 'MUR', 'XAF', 'CDF', 'ZAR', 'BWP', 'LSL', 'SZL', 'NAD', 'MWK', 'ZMW', 'MZN', 'AOA', 'ZWL', 'EGP', 'DZD', 'MAD', 'TND', 'LYD', 'STN', 'FJD', 'PGK', 'WST', 'TOP', 'VUV', 'SBD', 'XPF', 'XDR', 'XAG', 'XAU') THEN 1 ELSE 100 END
        FROM "settings"
        WHERE "settings"."category" = 'currency' AND "settings"."key" = 'document'
    ), 100)
                WHEN 100 THEN ((("buyer_pricing_sku"."price_minor" * (10000 - MIN(CASE WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) THEN "buyer_pricing_sku"."discount_bps" ELSE "buyer_pricing_product"."discount_bps" END, 10000))) + 500000) / 1000000) * 100
                ELSE (("buyer_pricing_sku"."price_minor" * (10000 - MIN(CASE WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) THEN "buyer_pricing_sku"."discount_bps" ELSE "buyer_pricing_product"."discount_bps" END, 10000))) + 5000) / 10000
            END)
        ELSE "buyer_pricing_sku"."price_minor"
    END ELSE NULL
            END) OVER (PARTITION BY "buyer_pricing_sku"."product_id") as "buyer_max_available_effective_price", MAX(CASE
        WHEN "buyer_pricing_sku"."discount_type" = 'flat' AND "buyer_pricing_sku"."discount_amount_minor" > 0
            THEN MAX("buyer_pricing_sku"."price_minor" - "buyer_pricing_sku"."discount_amount_minor", 0)
        WHEN NOT ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) AND "buyer_pricing_product"."discount_type" = 'flat' AND "buyer_pricing_product"."discount_amount_minor" > 0
            THEN MAX("buyer_pricing_sku"."price_minor" - "buyer_pricing_product"."discount_amount_minor", 0)
        WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) OR ("buyer_pricing_product"."discount_type" = 'percentage' AND "buyer_pricing_product"."discount_bps" > 0)
            THEN MIN("buyer_pricing_sku"."price_minor", CASE coalesce((
        SELECT CASE WHEN upper(trim(coalesce(CASE WHEN json_valid("settings"."value") THEN scalius_compat.json_scalar_text(jsonb_extract_path(("settings"."value")::jsonb, 'currencyCode')) END, ''))) IN ('USD', 'EUR', 'GBP', 'JPY', 'CHF', 'CAD', 'AUD', 'NZD', 'CNY', 'HKD', 'SGD', 'SEK', 'NOK', 'DKK', 'MXN', 'BRL', 'INR', 'PKR', 'LKR', 'NPR', 'AFN', 'BTN', 'MVR', 'MYR', 'PHP', 'THB', 'IDR', 'VND', 'MMK', 'KHR', 'LAK', 'BND', 'KRW', 'TWD', 'MNT', 'KPW', 'MOP', 'AED', 'SAR', 'QAR', 'KWD', 'BHD', 'OMR', 'JOD', 'IQD', 'IRR', 'YER', 'LBP', 'SYP', 'ILS', 'KZT', 'UZS', 'KGS', 'TJS', 'TMT', 'GEL', 'AMD', 'AZN', 'TRY', 'RUB', 'UAH', 'PLN', 'CZK', 'HUF', 'RON', 'BGN', 'HRK', 'RSD', 'BAM', 'MKD', 'ALL', 'MDL', 'BYN', 'ISK', 'ARS', 'CLP', 'COP', 'PEN', 'UYU', 'PYG', 'BOB', 'VES', 'GYD', 'SRD', 'TTD', 'JMD', 'BBD', 'BSD', 'BZD', 'CRC', 'CUP', 'DOP', 'GTQ', 'HNL', 'HTG', 'NIO', 'PAB', 'AWG', 'ANG', 'KYD', 'BMD', 'XCD', 'FKP', 'NGN', 'GHS', 'XOF', 'GMD', 'GNF', 'SLL', 'LRD', 'CVE', 'MRU', 'KES', 'TZS', 'UGX', 'RWF', 'BIF', 'ETB', 'SOS', 'ERN', 'DJF', 'SDG', 'SSP', 'SCR', 'KMF', 'MGA', 'MUR', 'XAF', 'CDF', 'ZAR', 'BWP', 'LSL', 'SZL', 'NAD', 'MWK', 'ZMW', 'MZN', 'AOA', 'ZWL', 'EGP', 'DZD', 'MAD', 'TND', 'LYD', 'STN', 'FJD', 'PGK', 'WST', 'TOP', 'VUV', 'SBD', 'XPF', 'XDR', 'XAG', 'XAU') THEN 1 ELSE 100 END
        FROM "settings"
        WHERE "settings"."category" = 'currency' AND "settings"."key" = 'document'
    ), 100)
                WHEN 100 THEN ((("buyer_pricing_sku"."price_minor" * (10000 - MIN(CASE WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) THEN "buyer_pricing_sku"."discount_bps" ELSE "buyer_pricing_product"."discount_bps" END, 10000))) + 500000) / 1000000) * 100
                ELSE (("buyer_pricing_sku"."price_minor" * (10000 - MIN(CASE WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) THEN "buyer_pricing_sku"."discount_bps" ELSE "buyer_pricing_product"."discount_bps" END, 10000))) + 5000) / 10000
            END)
        ELSE "buyer_pricing_sku"."price_minor"
    END) OVER (
                PARTITION BY "buyer_pricing_sku"."product_id"
            ) as "buyer_max_effective_price", ROW_NUMBER() OVER (
                PARTITION BY "buyer_pricing_sku"."product_id"
                ORDER BY CASE
        WHEN "buyer_pricing_sku"."track_inventory" = 0
          OR ("buyer_pricing_sku"."stock" - "buyer_pricing_sku"."reserved_stock") > 0
        THEN 1 ELSE 0
    END DESC, CASE
        WHEN "buyer_pricing_sku"."discount_type" = 'flat' AND "buyer_pricing_sku"."discount_amount_minor" > 0
            THEN MAX("buyer_pricing_sku"."price_minor" - "buyer_pricing_sku"."discount_amount_minor", 0)
        WHEN NOT ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) AND "buyer_pricing_product"."discount_type" = 'flat' AND "buyer_pricing_product"."discount_amount_minor" > 0
            THEN MAX("buyer_pricing_sku"."price_minor" - "buyer_pricing_product"."discount_amount_minor", 0)
        WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) OR ("buyer_pricing_product"."discount_type" = 'percentage' AND "buyer_pricing_product"."discount_bps" > 0)
            THEN MIN("buyer_pricing_sku"."price_minor", CASE coalesce((
        SELECT CASE WHEN upper(trim(coalesce(CASE WHEN json_valid("settings"."value") THEN scalius_compat.json_scalar_text(jsonb_extract_path(("settings"."value")::jsonb, 'currencyCode')) END, ''))) IN ('USD', 'EUR', 'GBP', 'JPY', 'CHF', 'CAD', 'AUD', 'NZD', 'CNY', 'HKD', 'SGD', 'SEK', 'NOK', 'DKK', 'MXN', 'BRL', 'INR', 'PKR', 'LKR', 'NPR', 'AFN', 'BTN', 'MVR', 'MYR', 'PHP', 'THB', 'IDR', 'VND', 'MMK', 'KHR', 'LAK', 'BND', 'KRW', 'TWD', 'MNT', 'KPW', 'MOP', 'AED', 'SAR', 'QAR', 'KWD', 'BHD', 'OMR', 'JOD', 'IQD', 'IRR', 'YER', 'LBP', 'SYP', 'ILS', 'KZT', 'UZS', 'KGS', 'TJS', 'TMT', 'GEL', 'AMD', 'AZN', 'TRY', 'RUB', 'UAH', 'PLN', 'CZK', 'HUF', 'RON', 'BGN', 'HRK', 'RSD', 'BAM', 'MKD', 'ALL', 'MDL', 'BYN', 'ISK', 'ARS', 'CLP', 'COP', 'PEN', 'UYU', 'PYG', 'BOB', 'VES', 'GYD', 'SRD', 'TTD', 'JMD', 'BBD', 'BSD', 'BZD', 'CRC', 'CUP', 'DOP', 'GTQ', 'HNL', 'HTG', 'NIO', 'PAB', 'AWG', 'ANG', 'KYD', 'BMD', 'XCD', 'FKP', 'NGN', 'GHS', 'XOF', 'GMD', 'GNF', 'SLL', 'LRD', 'CVE', 'MRU', 'KES', 'TZS', 'UGX', 'RWF', 'BIF', 'ETB', 'SOS', 'ERN', 'DJF', 'SDG', 'SSP', 'SCR', 'KMF', 'MGA', 'MUR', 'XAF', 'CDF', 'ZAR', 'BWP', 'LSL', 'SZL', 'NAD', 'MWK', 'ZMW', 'MZN', 'AOA', 'ZWL', 'EGP', 'DZD', 'MAD', 'TND', 'LYD', 'STN', 'FJD', 'PGK', 'WST', 'TOP', 'VUV', 'SBD', 'XPF', 'XDR', 'XAG', 'XAU') THEN 1 ELSE 100 END
        FROM "settings"
        WHERE "settings"."category" = 'currency' AND "settings"."key" = 'document'
    ), 100)
                WHEN 100 THEN ((("buyer_pricing_sku"."price_minor" * (10000 - MIN(CASE WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) THEN "buyer_pricing_sku"."discount_bps" ELSE "buyer_pricing_product"."discount_bps" END, 10000))) + 500000) / 1000000) * 100
                ELSE (("buyer_pricing_sku"."price_minor" * (10000 - MIN(CASE WHEN ("buyer_pricing_sku"."discount_type" = 'percentage' AND "buyer_pricing_sku"."discount_bps" > 0) THEN "buyer_pricing_sku"."discount_bps" ELSE "buyer_pricing_product"."discount_bps" END, 10000))) + 5000) / 10000
            END)
        ELSE "buyer_pricing_sku"."price_minor"
    END ASC, "buyer_pricing_sku"."id" ASC
            ) as "buyer_rank" from "product_variants" "buyer_pricing_sku" inner join "products" "buyer_pricing_product" on "buyer_pricing_product"."id" = "buyer_pricing_sku"."product_id" where ("buyer_pricing_sku"."product_id" IN (SELECT "products"."id" FROM "products" WHERE 1 = 1) and "buyer_pricing_sku"."deleted_at" is null and "buyer_pricing_sku"."id" <> 'default' and (
                "buyer_pricing_sku"."is_default" = 0
                OR NOT EXISTS (
                    SELECT 1
                    FROM product_variants AS buyer_option_sku
                    WHERE buyer_option_sku.product_id = "buyer_pricing_sku"."product_id"
                      AND buyer_option_sku.deleted_at IS NULL
                      AND buyer_option_sku.id <> 'default'
                      AND buyer_option_sku.is_default = 0
                      AND trim(coalesce(buyer_option_sku.option_combination_key, '')) <> ''
                )
            ))) "buyer_ranked_skus" where "buyer_rank" = 1) "buyer_catalog_pricing" on "buyer_catalog_pricing"."product_id" = "products"."id" left join "product_variants" "buyer_state_card_sku" on "buyer_state_card_sku"."id" = "buyer_catalog_pricing"."id" where 1 = 1 on conflict ("product_id") do update set "is_public" = excluded.is_public, "category_id" = excluded.category_id, "brand_id" = excluded.brand_id, "product_created_at" = excluded.product_created_at, "sku_id" = excluded.sku_id, "from_minor" = excluded.from_minor, "to_minor" = excluded.to_minor, "base_minor" = excluded.base_minor, "discount_depth_bps" = excluded.discount_depth_bps, "has_discount" = excluded.has_discount, "available_for_sale" = excluded.available_for_sale, "has_customer_options" = excluded.has_customer_options, "availability_band" = excluded.availability_band, "refreshed_at" = excluded.refreshed_at;
--> statement-breakpoint
INSERT INTO "scalius_schema_migrations" ("version", "name", "source_sha256") VALUES (91, '0091_catalogue_projection_fill', 'f517802465dd78eb25c3688f3b7dd9b0ac2ebe58dbf1b124fb4758f538ea0531');
