import type { APIRoute } from "astro";
import { db } from "@/db";
import { settings } from "@/db/schema";
import { eq, and } from "drizzle-orm";

const CATEGORY = "firebase";
const KEY_PUBLIC_CONFIG = "public_config";

export const GET: APIRoute = async () => {
  // 1. Fetch config from DB
  let publicConfig: Record<string, string> = {};
  try {
    const result = await db
      .select({ value: settings.value })
      .from(settings)
      .where(
        and(
          eq(settings.key, KEY_PUBLIC_CONFIG),
          eq(settings.category, CATEGORY),
        ),
      )
      .get();

    if (result && result.value) {
      publicConfig = JSON.parse(result.value);
    }
  } catch (e) {
    console.error("Error reading Firebase config from DB for SW:", e);
  }

  // 2. Fallback to Env Vars
  // Note: We use process.env here for compatibility, assuming Vite/Astro injects them or runtime has them.
  // In Cloudflare Workers, we might need to check if 'import.meta.env' works in this context or pass env from locals if possible.
  // However, for a static file generation or SSR endpoint, import.meta.env usually works for build-time vars,
  // but for runtime env vars in Cloudflare, we usually access them via context.

  // Since this is an Astro endpoint, we can try to use import.meta.env for build-time defaults
  if (!publicConfig.apiKey) {
    publicConfig = {
      apiKey: import.meta.env.PUBLIC_FIREBASE_API_KEY || "",
      authDomain: import.meta.env.PUBLIC_FIREBASE_AUTH_DOMAIN || "",
      projectId: import.meta.env.PUBLIC_FIREBASE_PROJECT_ID || "",
      storageBucket: import.meta.env.PUBLIC_FIREBASE_STORAGE_BUCKET || "",
      messagingSenderId:
        import.meta.env.PUBLIC_FIREBASE_MESSAGING_SENDER_ID || "",
      appId: import.meta.env.PUBLIC_FIREBASE_APP_ID || "",
      measurementId: import.meta.env.PUBLIC_FIREBASE_MEASUREMENT_ID || "",
    };
  }

  // 3. Construct the script
  const scriptContent = `// Firebase Cloud Messaging Service Worker
// Dynamically generated by /src/pages/firebase-messaging-sw.js.ts

importScripts("https://www.gstatic.com/firebasejs/9.15.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/9.15.0/firebase-messaging-compat.js");

const firebaseConfig = ${JSON.stringify(publicConfig, null, 2)};

firebase.initializeApp(firebaseConfig);

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  console.log("[firebase-messaging-sw.js] Received background message", payload);

  const notificationTitle = payload.data?.customerName
    ? \`\${payload.data.customerName} placed a new order\`
    : payload.notification?.title || "New Order Received";

  const notificationOptions = {
    body: payload.data?.orderId
      ? \`Order ID: \${payload.data.orderId}. Click to view.\`
      : payload.notification?.body || "A new order has been placed on your store.",
    icon: "/favicon.svg",
    badge: "/favicon.svg",
    tag: "order-notification",
    requireInteraction: true,
    data: {
      url: payload.data?.link || "/admin/orders",
    },
  };

  self.registration.showNotification(notificationTitle, notificationOptions);
});

self.addEventListener("notificationclick", (event) => {
  console.log("[firebase-messaging-sw.js] Notification click received.");
  event.notification.close();

  const urlToOpen = event.notification.data?.url || "/admin/orders";

  event.waitUntil(
    clients
      .matchAll({
        type: "window",
        includeUncontrolled: true,
      })
      .then((clientList) => {
        for (const client of clientList) {
          if (client.url.includes("/admin") && "focus" in client) {
            return client.focus();
          }
        }
        if (clients.openWindow) {
          return clients.openWindow(urlToOpen);
        }
      }),
  );
});
`;

  return new Response(scriptContent, {
    status: 200,
    headers: {
      "Content-Type": "application/javascript",
      "Cache-Control": "no-cache, no-store, must-revalidate", // Ensure fresh config
    },
  });
};
