/**
 * Compact sidecar inventory for semantic content parity. This deliberately
 * describes merchant/visitor scenarios instead of coupling agent contracts to
 * dashboard DOM structure.
 */
export const contentAgentScenarios = {
  contentLifecycle: [
    "dashboard.content.list",
    "dashboard.content.create",
    "dashboard.content.get",
    "dashboard.content.update",
    "dashboard.content.trash",
    "dashboard.content.restore",
    "dashboard.content.permanently_delete",
    "dashboard.content.bulk_delete",
    "dashboard.content.bulk_publish",
    "dashboard.content.bulk_unpublish",
    "dashboard.content.bulk_restore",
    "storefront.pages.list",
    "storefront.pages.get_by_slug",
    "storefront.pages.get_by_id",
    "storefront.articles.list",
    "storefront.articles.get_by_slug",
  ],
  mediaUploadSessionControl: [
    "dashboard.media.upload_initiate",
    "dashboard.media.upload_get",
    // MCP names the required direct-client action; the CLI streams this exact
    // bounded operation with the same live agent credential and session.
    "dashboard.media.upload_part",
    "dashboard.media.upload_complete",
    "dashboard.media.upload_abort",
  ],
  mediaLibrary: [
    "dashboard.media.list",
    "dashboard.media.update",
    "dashboard.media.trash",
    "dashboard.media.restore",
    "dashboard.media.permanently_delete",
    "dashboard.media.move",
    "dashboard.media_folders.list",
    "dashboard.media_folders.create",
    "dashboard.media_folders.update",
    "dashboard.media_folders.delete",
  ],
  navigationDraftPublishRollback: [
    "dashboard.navigation.resources_search",
    "dashboard.navigation.products_preview_count",
    "dashboard.navigation.menus_list",
    "dashboard.navigation.menus_create",
    "dashboard.navigation.menus_get",
    "dashboard.navigation.menus_update",
    "dashboard.navigation.menus_trash",
    "dashboard.navigation.menus_restore",
    "dashboard.navigation.items_list",
    "dashboard.navigation.items_search",
    "dashboard.navigation.items_get",
    "dashboard.navigation.items_move_options",
    "dashboard.navigation.items_create",
    "dashboard.navigation.items_update",
    "dashboard.navigation.items_move",
    "dashboard.navigation.items_delete",
    "dashboard.navigation.menus_publish",
    "dashboard.navigation.publications_list",
    "dashboard.navigation.menus_rollback",
    "dashboard.navigation.placements_manifest",
    "dashboard.navigation.placements_list",
    "dashboard.navigation.placements_save",
    "storefront.navigation.get",
    "storefront.navigation.placements_list",
    "storefront.navigation.menu_get",
    "storefront.navigation.items_list",
    "storefront.navigation.menu_get_by_id",
  ],
  heroLifecycle: [
    "dashboard.hero_sliders.list",
    "dashboard.hero_sliders.create",
    "dashboard.hero_sliders.get",
    "dashboard.hero_sliders.update",
    "dashboard.hero_sliders.trash",
    "storefront.hero_sliders.list",
    "storefront.hero_sliders.get",
  ],
  themeDraftPreviewPublishRollback: [
    "dashboard.theme.get",
    "dashboard.theme.workspace_get",
    "dashboard.theme.draft_save",
    "dashboard.theme.draft_rebase",
    "dashboard.theme.publish",
    "dashboard.theme.versions_list",
    "dashboard.theme.rollback",
    "dashboard.theme.preview_session_create",
  ],
  internalSupport: [
    "dashboard.media.upload_reconcile",
    "dashboard.navigation.legacy_items_list",
    "dashboard.navigation.authority_shadow",
    "dashboard.theme.save_legacy",
  ],
} as const;

export const contentPresentationOnlyScenarios = [
  "open or close a dialog, menu, popover, or tab",
  "select dashboard rows before a bulk command",
  "format rich text before saving content",
  "edit a hero draft locally before its update command",
  "move between media previews or pause a browser-held File upload",
  "open an external URL returned by a navigation item",
] as const;
