// src/server/openapi/abandoned-checkout-paths.ts

export const abandonedCheckoutPaths = {
  "/abandoned-checkouts": {
    post: {
      tags: ["Orders"],
      summary: "Create or update an abandoned checkout",
      description:
        "Creates or updates a record of an incomplete checkout. This endpoint is designed to be called periodically by the storefront as a user fills out the checkout form. It uses an idempotent approach, where sending the same `checkoutId` multiple times will update the same record instead of creating new ones.",
      requestBody: {
        required: true,
        content: {
          "application/json": {
            schema: {
              type: "object",
              required: ["checkoutId", "checkoutData"],
              properties: {
                checkoutId: {
                  type: "string",
                  description: "A unique identifier for the user's checkout session, generated by the storefront.",
                  example: "chk_session_12345abcde",
                },
                customerPhone: {
                  type: "string",
                  description: "The customer's phone number, if entered.",
                  example: "01712345678",
                },
                checkoutData: {
                  type: "object",
                  description: "A JSON object containing all data captured from the checkout form, including cart items, customer details, etc.",
                  example: {
                    customerName: "John Doe",
                    shippingAddress: "123 Main St",
                    items: [
                      {
                        productId: "prod_abc",
                        quantity: 1,
                        price: 1500,
                      },
                    ],
                  },
                },
              },
            },
          },
        },
      },
      responses: {
        "200": {
          description: "Successfully saved the abandoned checkout data.",
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  success: { type: "boolean", example: true },
                  message: { type: "string", example: "Abandoned checkout saved." },
                },
              },
            },
          },
        },
        "400": { $ref: "#/components/schemas/Error" },
        "500": { $ref: "#/components/schemas/Error" },
      },
    },
  },
  "/abandoned-checkouts/{checkoutId}": {
    delete: {
      tags: ["Orders"],
      summary: "Delete an abandoned checkout record",
      description:
        "Deletes an abandoned checkout record, typically after a user successfully completes their order. This prevents completed orders from appearing as abandoned.",
      parameters: [
        {
          name: "checkoutId",
          in: "path",
          required: true,
          description: "The unique identifier for the checkout session to be deleted.",
          schema: {
            type: "string",
          },
          example: "chk_session_12345abcde",
        },
      ],
      responses: {
        "200": {
          description: "Successfully deleted the abandoned checkout record.",
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  success: { type: "boolean", example: true },
                  message: { type: "string", example: "Abandoned checkout record deleted." },
                },
              },
            },
          },
        },
        "500": { $ref: "#/components/schemas/Error" },
      },
    },
  },
};