import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@scalius/database/client", () => ({ getDb: vi.fn(() => ({})) }));
vi.mock("@scalius/core/integrations/storage", () => ({
  withPublicMediaUrl: vi.fn(async (_url: string, callback: () => Promise<unknown>) => callback()),
}));
vi.mock("@scalius/shared/cors-helper", () => ({
  getCorsOriginContext: vi.fn(async () => () => "*"),
}));

import app from "../app";
import {
  OPENAPI_CONTRACT_ETAG,
  OPENAPI_CONTRACT_JSON,
} from "../generated/openapi-contract.gen";

const env = {
  PUBLIC_API_BASE_URL: "https://api.example.test",
  R2_PUBLIC_URL: "https://media.example.test",
} as Env;

describe("deploy-generated OpenAPI route", () => {
  beforeEach(() => vi.clearAllMocks());

  it("serves the exact generated bytes with a revalidatable ETag", async () => {
    const response = await app.request("https://api.example.test/api/v1/openapi.json", {}, env);
    expect(response.status).toBe(200);
    expect(response.headers.get("Content-Type")).toContain("application/json");
    expect(response.headers.get("Cache-Control")).toBe("public, max-age=0, must-revalidate");
    expect(response.headers.get("ETag")).toBe(OPENAPI_CONTRACT_ETAG);
    expect(await response.text()).toBe(OPENAPI_CONTRACT_JSON);
  });

  it("returns no body when the contract ETag is current", async () => {
    const response = await app.request("https://api.example.test/api/v1/openapi.json", {
      headers: { "If-None-Match": OPENAPI_CONTRACT_ETAG },
    }, env);
    expect(response.status).toBe(304);
    expect(await response.text()).toBe("");
  });
});
