import type { RuntimeApiApp } from "./base-app";
import { adminAuthMiddleware } from "../middleware/admin-auth";
import { cookieOriginGuardMiddleware } from "../middleware/cookie-origin-guard";
import { abandonedCheckoutsRoutes } from "../routes/abandoned-checkouts";
import { adminAgentAccessRoutes } from "../routes/admin/agent-access";
import { adminAnalyticsRoutes } from "../routes/admin/analytics";
import { adminAttributesRoutes } from "../routes/admin/attributes";
import { adminAuthManagementRoutes } from "../routes/admin/auth-management";
import { adminCategoryRoutes } from "../routes/admin/categories";
import { adminCollectionRoutes } from "../routes/admin/collections";
import { adminCustomerRoutes } from "../routes/admin/customers";
import { adminDashboardRoutes } from "../routes/admin/dashboard";
import { adminDiscountRoutes } from "../routes/admin/discounts";
import { adminFraudCheckerRoutes } from "../routes/admin/fraud-checker";
import { adminInventoryRoutes } from "../routes/admin/inventory";
import { adminMediaRoutes } from "../routes/admin/media";
import { adminNavigationRoutes } from "../routes/admin/navigation";
import { adminOrdersRoutes } from "../routes/admin/orders";
import { adminPageRoutes } from "../routes/admin/pages";
import { adminProductsRoutes } from "../routes/admin/products";
import { adminPromotionRoutes } from "../routes/admin/promotions";
import { adminRbacRoutes } from "../routes/admin/rbac";
import { adminSearchRoutes } from "../routes/admin/search";
import { adminSettingsRoutes } from "../routes/admin/settings";
import { adminLocationRoutes } from "../routes/admin/settings/delivery-locations";
import { adminShipmentRoutes } from "../routes/admin/shipments";
import { adminSystemUtilsRoutes } from "../routes/admin/system-utils";
import { adminTaxRoutes } from "../routes/admin/taxes";
import { checkoutLanguageRoutes } from "../routes/checkout-languages";

export function registerAdminRoutes(app: RuntimeApiApp): void {
  app.use("/admin/*", cookieOriginGuardMiddleware);
  app.use("/admin/*", adminAuthMiddleware);

  app.route("/admin/categories", adminCategoryRoutes);
  app.route("/admin/collections", adminCollectionRoutes);
  app.route("/admin/customers", adminCustomerRoutes);
  app.route("/admin/pages", adminPageRoutes);
  app.route("/admin/discounts", adminDiscountRoutes);
  app.route("/admin/promotions", adminPromotionRoutes);
  app.route("/admin/media", adminMediaRoutes);
  app.route("/admin/inventory", adminInventoryRoutes);
  app.route("/admin/navigation", adminNavigationRoutes);
  app.route("/admin/search", adminSearchRoutes);
  app.route("/admin/shipments", adminShipmentRoutes);
  app.route("/admin/analytics", adminAnalyticsRoutes);
  app.route("/admin/dashboard", adminDashboardRoutes);
  app.route("/admin/fraud-checker", adminFraudCheckerRoutes);
  app.route("/admin/rbac", adminRbacRoutes);
  app.route("/admin/settings", adminSettingsRoutes);
  app.route("/admin/orders", adminOrdersRoutes);
  app.route("/admin/products", adminProductsRoutes);
  app.route("/admin/auth", adminAuthManagementRoutes);
  app.route("/admin/attributes", adminAttributesRoutes);
  app.route("/admin/taxes", adminTaxRoutes);
  app.route("/admin/agent-access", adminAgentAccessRoutes);
  app.route("/admin", adminSystemUtilsRoutes);
  app.route("/admin/settings/delivery-locations", adminLocationRoutes);
  app.route("/admin/settings/checkout-languages", checkoutLanguageRoutes);
  app.route("/admin/settings/abandoned-checkouts", abandonedCheckoutsRoutes);
}
