export const ENGLISH_CHECKOUT_LANGUAGE_DATA = {
  pageTitle: "Cart & Checkout",
  checkoutSectionTitle: "Checkout information",
  cartSectionTitle: "Shopping cart",
  customerNameLabel: "Full name",
  customerNamePlaceholder: "Enter your full name",
  customerPhoneLabel: "Phone number",
  customerPhonePlaceholder: "01712-345678",
  customerPhoneHelp: "11-digit mobile number starting with 01. The courier calls this number.",
  phoneCountryLabelText: "Phone number country",
  customerEmailLabel: "Email (optional)",
  customerEmailPlaceholder: "Enter your email address",
  shippingAddressLabel: "Delivery address",
  shippingAddressPlaceholder: "Enter your full delivery address",
  cityLabel: "City",
  zoneLabel: "Thana",
  areaLabel: "Area (optional)",
  shippingMethodLabel: "Choose delivery option",
  orderNotesLabel: "Order notes (optional)",
  orderNotesPlaceholder: "Any special instructions for your order?",
  continueShoppingText: "Continue shopping",
  subtotalText: "Subtotal",
  shippingText: "Shipping",
  discountText: "Discount",
  totalText: "Total",
  discountCodePlaceholder: "Discount code",
  applyDiscountText: "Apply",
  removeDiscountText: "Remove",
  placeOrderText: "Place order",
  processingText: "Processing…",
  emptyCartText: "Your cart is empty",
  emptyCartDescriptionText: "You haven't added anything to your cart yet.",
  paymentRecoveryMessageText:
    "Your order was created before payment opened. Review its payment status before starting another checkout.",
  viewPaymentStatusText: "View payment status",
  paymentRecoveryPageTitleText: "Payment recovery",
  paymentRecoveryEyebrowText: "Hosted payment recovery",
  paymentRecoveryHeadingText: "Verify this order",
  paymentRecoveryIntroText:
    "This link does not open private receipt details by itself. Verify the buyer contact to continue payment from this browser.",
  paymentRecoverySmsChannelText: "SMS to order phone",
  paymentRecoveryWhatsappChannelText: "WhatsApp to order phone",
  paymentRecoveryEmailChannelText: "Email on order",
  paymentRecoveryOrderReferenceText: "Order reference",
  paymentRecoveryVerificationChannelText: "Verification channel",
  paymentRecoverySendCodeText: "Send code",
  paymentRecoveryVerificationCodeText: "Verification code",
  paymentRecoveryContinueToReceiptText: "Continue to receipt",
  paymentRecoveryUnavailableText:
    "Payment recovery isn't available right now. Sign in to check your account orders.",
  paymentRecoveryMissingOrderText:
    "This recovery link is missing an order reference. Ask the store to send a fresh payment recovery link.",
  paymentRecoveryViewAccountOrdersText: "View account orders",
  paymentRecoverySendingCodeText: "Sending verification code…",
  paymentRecoveryCodeSentText:
    "If this order is eligible for payment recovery, a verification code will be sent to the buyer contact.",
  paymentRecoverySendFailedText: "Could not send a verification code. Please try again.",
  paymentRecoveryEnterCodeText: "Enter the verification code to continue.",
  paymentRecoveryVerifyingCodeText: "Verifying code…",
  paymentRecoveryVerificationFailedText:
    "Verification failed. Please request a new code and try again.",
  paymentRecoveryRateLimitedText:
    "Too many verification attempts. Wait a moment and try again.",
  orderReceiptPageTitleText: "Order receipt",
  orderReceiptMissingTitleText: "We could not open this receipt",
  orderReceiptBrowserRecoveryMessageText:
    "This receipt can only be opened in the browser used at checkout. Verify your contact to recover payment.",
  orderReceiptBrowserOnlyMessageText:
    "This receipt can only be opened in the browser used at checkout. Sign in to view your orders, or return to the checkout browser.",
  orderReceiptUnavailableTitleText: "Receipt temporarily unavailable",
  orderReceiptPrivateUnavailableMessageText:
    "We could not load this receipt from the private order link. If the order was placed, it may still appear in your account history.",
  orderReceiptExpiredTitleText: "Receipt access expired",
  orderReceiptExpiredMessageText:
    "This private receipt is no longer available in this browser. Sign in to check your account orders.",
  orderReceiptUnavailableMessageText:
    "We could not load this receipt right now. Please retry or check your account order history.",
  orderReceiptReferenceText: "Reference",
  orderReceiptVerifyRecoveryText: "Verify payment recovery",
  orderReceiptRetryText: "Retry receipt",
  orderReceiptOrderDetailsText: "Order details",
  orderReceiptOrderNumberText: "Order number",
  orderReceiptPlacedText: "Placed",
  orderReceiptStatusText: "Status",
  orderReceiptPaymentText: "Payment",
  orderReceiptPaymentStatusText: "Payment status",
  orderReceiptDeliveryText: "Delivery",
  orderReceiptDeliveryWithMethodText: "Delivery · {method}",
  orderReceiptDeliveryNotRecordedText: "Delivery method was not recorded for this order.",
  orderReceiptFeeWaivedText: "{fee} fee waived",
  orderReceiptPaidText: "Paid",
  orderReceiptBalanceDueText: "Balance due",
  orderReceiptDeliveryDetailsText: "Delivery details",
  orderReceiptItemsText: "Items",
  orderReceiptProductUnavailableText: "Product unavailable",
  orderReceiptQuantityText: "Quantity: {quantity}",
  orderReceiptItemDiscountText: "Item discount: −{amount}",
  orderReceiptTaxIncludedText: "{label} included: {amount}",
  orderReceiptTaxAddedText: "{label} added: {amount}",
  orderReceiptLineTotalText: "Line total",
  orderReceiptPrintText: "Print receipt",
  orderReceiptCheckingPaymentText: "Checking payment status…",
  orderReceiptCheckPaymentText: "Check payment status",
  orderReceiptStripePaymentMethodRequiredText:
    "Stripe needs new card details. Choose Complete payment with Stripe below to continue.",
  orderReceiptStripeAuthenticationRequiredText:
    "Stripe needs additional authentication. Choose Complete payment with Stripe below to continue.",
  orderReceiptConfirmationDelayedText:
    "Confirmation is taking longer than usual. You can safely leave this receipt and return later.",
  orderReceiptStatusUpdatedText: "Payment status updated. Refreshing your receipt…",
  orderReceiptRetryWithProviderText: "Retry payment with {provider}",
  orderReceiptRetryPaymentText: "Retry payment",
  orderReceiptOpeningPaymentText: "Opening payment…",
  orderReceiptRetryUnavailableText: "Payment retry is unavailable for this order.",
  orderReceiptCardUnavailableText: "Card payment is unavailable for this order.",
  orderReceiptLoadingCardText: "Loading secure card fields…",
  orderReceiptEnterCardText: "Enter your card details to continue with this order.",
  orderReceiptCardLoadFailedText: "Could not load the secure card form. Please try another payment method.",
  orderReceiptPaymentProcessingRetryText: "Payment is still processing. Retrying in {seconds}s…",
  orderReceiptStartPaymentFailedText: "Could not start payment. Please try again.",
  orderReceiptGatewayRedirectFailedText: "The payment service did not return a safe payment page.",
  orderReceiptConfirmingCardText: "Confirming card payment for your existing order…",
  orderReceiptCardPaymentFailedText: "Card payment could not be completed. Your order is still saved.",
  orderReceiptExistingOrderCardHelpText:
    "Your existing order will be updated. This will not create another order.",
  orderReceiptPaymentIssueTitleText: "Payment not completed",
  orderReceiptPaymentIssueMessageText:
    "Order #{orderId} is saved. Choose a payment method.",
  orderReceiptPaymentPendingTitleText: "Payment pending",
  orderReceiptPaymentPendingMessageText:
    "Order #{orderId} is saved.",
  orderReceiptConfirmedTitleText: "Order confirmed",
  orderReceiptConfirmedMessageText: "Order #{orderId} is confirmed and being prepared.",
  orderReceiptProcessingTitleText: "Order processing",
  orderReceiptProcessingMessageText: "Order #{orderId} is being prepared.",
  orderReceiptShippedTitleText: "Order shipped",
  orderReceiptShippedMessageText: "Order #{orderId} is on the way.",
  orderReceiptDeliveredTitleText: "Order delivered",
  orderReceiptDeliveredMessageText: "Order #{orderId} has been delivered.",
  orderReceiptCompletedTitleText: "Order completed",
  orderReceiptCompletedMessageText: "Order #{orderId} is complete.",
  orderReceiptCancelledTitleText: "Order cancelled",
  orderReceiptCancelledMessageText: "Order #{orderId} was cancelled.",
  orderReceiptRefundedTitleText: "Order refunded",
  orderReceiptRefundedMessageText: "The refund for order #{orderId} has been recorded.",
  orderReceiptReturnedTitleText: "Order returned",
  orderReceiptReturnedMessageText: "The return for order #{orderId} has been recorded.",
  orderReceiptPartiallyRefundedTitleText: "Order partially refunded",
  orderReceiptPartiallyRefundedMessageText:
    "A partial refund for order #{orderId} has been recorded.",
  orderReceiptUpdatedTitleText: "Order updated",
  orderReceiptUpdatedMessageText: "Order #{orderId} has been updated.",
  orderReceiptPlacedTitleText: "Order placed",
  orderReceiptPlacedMessageText: "We received order #{orderId}.",
  orderReceiptStatusNotAvailableText: "Not available",
  orderReceiptStatusPendingText: "Pending",
  orderReceiptStatusIncompleteText: "Incomplete",
  orderReceiptStatusConfirmedText: "Confirmed",
  orderReceiptStatusProcessingText: "Processing",
  orderReceiptStatusShippedText: "Shipped",
  orderReceiptStatusDeliveredText: "Delivered",
  orderReceiptStatusCompletedText: "Completed",
  orderReceiptStatusCancelledText: "Cancelled",
  orderReceiptStatusRefundedText: "Refunded",
  orderReceiptStatusReturnedText: "Returned",
  orderReceiptStatusPartiallyRefundedText: "Partially refunded",
  orderReceiptStatusFailedText: "Failed",
  orderReceiptPaymentStatusPaidText: "Paid",
  orderReceiptPaymentStatusPartialText: "Partially paid",
  orderReceiptPaymentStatusUnpaidText: "Unpaid",
  orderReceiptPaymentStatusNoPaymentDueText: "No payment due",
  orderReceiptPaymentMethodCardText: "Card (Stripe)",
  orderReceiptPaymentMethodSslcommerzText: "Online payment (SSLCommerz)",
  orderReceiptSaveAccountTitleText: "Save this order to your account",
  orderReceiptSavedAccountTitleText: "Order saved to your account",
  orderReceiptSaveAccountHelpText:
    "Create an account with the phone saved on this order, or sign in with a matching phone or email.",
  orderReceiptViewInAccountText: "View in account",
  orderReceiptSaveToAccountText: "Save to my account",
  orderReceiptSavingText: "Saving…",
  orderReceiptCreateAccountText: "Create account",
  orderReceiptSignInText: "Sign in",
  orderReceiptMissingReferenceText: "This receipt is missing its order reference.",
  orderReceiptSavingToAccountText: "Saving this order to your account…",
  orderReceiptSaveFailedText: "This order could not be saved. Please try again.",
  orderReceiptAlreadySavedText: "This order is already in your account.",
  orderReceiptSavedText: "Order saved. You can now track it from any signed-in device.",
  orderReceiptCreateAccountPromptText: "Create your account with the phone number saved on this order.",
  orderReceiptSignInPromptText: "Sign in with a phone number or email that matches this order.",
  orderReceiptHelpText: "Need help?",
  orderReceiptCancelRequestActionText: "Request cancellation",
  orderReceiptCancelRequestDescriptionText: "Ask the store to review this order before it ships.",
  orderReceiptCancelRequestPickupDescriptionText: "Ask the store to review this order before it's collected.",
  orderReceiptCancelRequestServiceDescriptionText: "Ask the store to review this order before the service is done.",
  orderReceiptReturnRequestActionText: "Request return",
  orderReceiptRefundRequestActionText: "Request refund",
  orderReceiptRequestSubmittedText:
    "The store received your request and will review it before making changes.",
  orderReceiptRequestUnderReviewText: "The store team is reviewing this request.",
  orderReceiptRequestApprovedText: "The store accepted this request. Check the order status for progress.",
  orderReceiptRequestRejectedText: "The store could not accept this request.",
  orderReceiptRequestWithdrawnText: "This request was withdrawn.",
  orderReceiptRequestCompletedText: "This request is complete.",
  orderReceiptRequestSettledText: "This request is settled.",
  orderReceiptRequestStatusSubmittedText: "Submitted",
  orderReceiptRequestStatusUnderReviewText: "Under review",
  orderReceiptRequestStatusApprovedText: "Approved",
  orderReceiptRequestStatusRejectedText: "Rejected",
  orderReceiptRequestStatusWithdrawnText: "Withdrawn",
  orderReceiptRequestStatusCompletedText: "Completed",
  orderReceiptRequestLabelText: "{action} · {status}",
  orderReceiptReasonText: "Reason",
  orderReceiptReasonAriaText: "Support request reason",
  orderReceiptReasonPlaceholderText: "Why are you requesting this?",
  orderReceiptCancelText: "Cancel",
  orderReceiptSendRequestText: "Send request",
  orderReceiptMissingProofText: "This receipt is missing the browser proof needed to send a request.",
  orderReceiptReasonRequiredText: "Add a short reason before sending the request.",
  orderReceiptSupportFailedText: "Support request failed. Please try again.",
  orderReceiptRequestSentText: "Request sent. The store team can now review it from the order.",
  orderReceiptSupportUnavailableText: "Support requests are not available for this order right now.",
  orderReceiptNextStepsTitleText: "What happens next",
  orderReceiptNextStepsCodText: "We'll call you to confirm your order, then hand it to the courier.",
  orderReceiptNextStepsPaidText: "Your payment is confirmed. We'll pack your order and hand it to the courier.",
  orderReceiptNextStepsPickupCodText: "We'll call you to confirm your order, then let you know when it's ready to collect.",
  orderReceiptNextStepsPickupPaidText: "Your payment is confirmed. We'll let you know when your order is ready to collect.",
  orderReceiptNextStepsServiceCodText: "We'll call you to confirm your order and arrange the service.",
  orderReceiptNextStepsServicePaidText: "Your payment is confirmed. We'll contact you to arrange the service.",
  orderReceiptDeliveryEstimateText: "Delivery usually takes {estimate}.",
  orderReceiptAccountSavedText: "Saved to your account",
  orderReceiptViewOrderText: "View order",
  orderReceiptAccountSignInText: "Sign in to see this order in your account",
  orderReceiptAccountCreateText: "Create an account to track this order",
  orderReceiptIncompleteTitleText: "This receipt link is incomplete",
  orderReceiptTrackOrderHelpText: "You can open your order on any device with its order number and the phone number you used.",
  trackOrderText: "Track your order",
  trackOrderIntroText: "Enter your order number and the phone number used for the order.",
  trackOrderCodeSentText: "If these details match an order, we've sent a code to the phone number or email saved on it.",
  trackOrderNumberInvalidText: "Enter your order number, for example #1001.",
  trackOrderPhoneInvalidText: "Enter the phone number used for the order.",
  trackOrderUnavailableText: "Order tracking isn't available right now.",
  storeContactLabelText: "Contact the store:",
  orderCodeResendInText: "Send a new code in {time}",
  orderCodeSendNewText: "Send a new code",
  orderCodeTryAgainInText: "Try again in {time}",
  orderCodeWrongOneAttemptText: "That code isn't right. 1 attempt left.",
  orderCodeWrongAttemptsText: "That code isn't right. {count} attempts left.",
  orderCodeExpiredText: "This code can't be used anymore. Send a new code.",
  paymentRecoveryFinishTitleText: "Finish paying for your order",
  paymentRecoveryCodeIntroText: "We'll send a code to the phone number or email saved on this order.",
  paymentRecoveryCodeRequestedText: "If this order can still be paid online, we've sent a code to the phone number or email saved on it.",
  paymentRecoveryContinueToPaymentText: "Continue to payment",
  paymentRecoveryLinkIncompleteText: "This payment link is incomplete. Ask the store to send it again.",
  paymentRecoveryCodesUnavailableText: "We can't send codes right now.",
  paymentRecoverySendCodeByText: "Send the code by",
  termsText: "By placing this order, you agree to our {terms} and {privacy}.",
  termsLinkText: "Terms of Service",
  privacyLinkText: "Privacy Policy",
  processingOrderTitle: "Processing your order",
  processingOrderMessage: "Please wait while we process your order.",
  requiredFieldIndicator: "*",
  homeAriaLabel: "Go to homepage",
  secureCheckoutText: "Secure checkout",
  checkoutProgressLabel: "Checkout progress",
  informationStepText: "Information",
  paymentStepText: "Payment",
  confirmationStepText: "Confirmation",
  estimatedTotalText: "Estimated total",
  taxText: "Tax",
  freeText: "Free",
  calculatingText: "Calculating…",
  unavailableText: "Sold out",
  taxVerificationFailedText: "We couldn't update the total. Check your connection and try again.",
  cartItemChangedText: "One cart item needs attention before checkout.",
  cartAvailabilityFailedText: "Could not verify cart availability. Refresh and try again.",
  cartItemsChangedText: "{count} cart items changed before payment. Review them before checkout.",
  oneCartItemChangedText: "One cart item changed before payment. Please review it before checkout.",
  cartAvailabilityReviewText: "Could not verify cart availability. Review your cart before checkout.",
  orderSummaryText: "Order summary",
  paymentPageTitle: "Payment",
  paymentMethodsText: "Payment methods",
  paymentMethodText: "Payment method",
  loadingPaymentMethodsText: "Loading payment methods",
  testModeNoticeText: "Test mode — no real payments will be processed.",
  cardDetailsText: "Card details",
  selectPaymentMethodText: "Select a payment method",
  continueToPaymentText: "Continue to payment",
  checkoutUnavailableText: "Checkout unavailable",
  checkoutUnavailableMessage:
    "Checkout is temporarily unavailable. Please try again shortly.",
  errorPrefixText: "Error:",
  successPrefixText: "Success!",
  existingCheckoutTitle: "You already have a checkout in progress",
  existingCheckoutMessage:
    "Order {orderId} is waiting for payment. Review it before starting another checkout.",
  reviewExistingCheckoutText: "Review existing checkout",
  signInToCheckoutText: "Sign in to checkout",
  signInPromptText: "Already have an account? Sign in for faster checkout",
  noScriptText: "JavaScript is required to update your cart before checkout.",
  selectCityPlaceholder: "Select a city",
  selectZonePlaceholder: "Select a thana",
  selectAreaPlaceholder: "Select an area (optional)",
  loadingText: "Loading…",
  zonesLoadFailedText: "Could not load thanas. Try again",
  areasLoadFailedText: "Could not load areas. Try again",
  noShippingMethodsText: "No shipping methods are available at this time.",
  waivedShippingFeeText: "Normally {fee}; waived by an item in your cart.",
  phoneRequiredText: "Enter your phone number.",
  phoneInvalidText: "Enter a Bangladeshi mobile number (01XXXXXXXXX).",
  phoneCountryNotAcceptedText: "This store does not accept phone numbers from that country.",
  nameRequiredText: "Enter your full name.",
  addressRequiredText: "Enter your delivery address.",
  addressIncompleteText: "Enter a complete delivery address (at least {minimum} characters).",
  cityZoneRequiredText: "Choose a city and thana to continue.",
  zoneRequiredText: "Choose a thana to continue.",
  cityUnavailableText: "That city is no longer available. Choose another.",
  thanaUnavailableText: "That thana is no longer available. Choose another.",
  areaUnavailableText: "That area is no longer available. Choose another.",
  deliveryRequiredText: "Choose a delivery option.",
  checkingAvailableQuantityText: "Checking available quantity for {item}",
  maximumAvailableQuantityText: "Maximum available quantity reached for {item}",
  increaseQuantityText: "Increase {item} quantity",
  decreaseQuantityText: "Decrease {item} quantity",
  removeFromCartText: "Remove {item} from cart",
  cartLoadingText: "Loading your cart",
  cartAttentionText: "Some cart items need attention",
  cartEmptyErrorText: "Add items to your cart before placing an order.",
  quickBuyStorageBlockedText: "This browser blocked temporary cart storage, so the item could not be added. Allow site storage and add it again.",
  orderProcessingFailedText: "Could not process the order. Try again.",
  unexpectedErrorText: "An unexpected error occurred.",
  cartItemsNeedAttentionText: "{count} cart items need attention before checkout.",
  orderPlacedSuccessText: "Your order was placed successfully. Order ID: {orderId}",
  checkingAccountText: "Checking account…",
  accountUnavailableText: "We could not verify your account right now. Please try again.",
  checkingCartText: "Checking cart…",
  reviewCartItemsText: "Review the highlighted cart items before checkout.",
  redirectingToPaymentText: "Redirecting to payment…",
  openingPaymentOptionsTitle: "Opening payment options",
  openingPaymentOptionsMessage: "Confirming your total and available payment methods.",
  checkoutDetailsMissingText: "Checkout details were not found. Return to your cart and try again.",
  checkoutDetailsUnreadableText: "Checkout details could not be read. Return to your cart and try again.",
  returnToCartText: "Return to cart",
  quantityShortText: "Qty {quantity}",
  eachText: "each",
  includedText: "included",
  dueNowText: "Due now",
  dueOnDeliveryText: "Due on delivery",
  dueAtPickupText: "Due at pickup",
  dueAtServiceText: "Due when the service is done",
  continueText: "Continue",
  continueAsGuestText: "Continue as guest",
  sessionExpiredText:
    "Your sign-in session expired. Your checkout details are safe. Continue as a guest, or sign in again.",
  checkoutConflictText: "This checkout was already submitted or changed in another tab. Review your cart and try again.",
  totalChangedReviewText:
    "Your order total or checkout terms changed. Review the refreshed total, then confirm the order again.",
  tooManyCheckoutAttemptsText: "Too many checkout attempts. Wait a moment and try again.",
  paymentFailedText: "Payment failed",
  noPaymentMethodsText:
    "No available payment method can accept this order total. Return to your cart.",
  preparingPaymentText: "Preparing payment…",
  paymentMethodUnavailableText: "Payment method unavailable",
  paymentMethodUnavailableMessage: "This payment method is not available. Choose another method.",
  retryPaymentFormText: "Retry payment form",
  processingPaymentTitle: "Processing payment",
  processingPaymentMessage: "Confirming your order and payment details.",
  placingOrderTitle: "Placing your order",
  placingOrderMessage: "Confirming item availability and delivery.",
  openingSecurePaymentTitle: "Opening secure payment",
  openingSecurePaymentMessage: "You'll continue with the selected payment provider.",
  unknownPaymentMethodText: "Unknown payment method selected.",
  unsafeRedirectText: "Payment could not open because the gateway returned an unsafe redirect URL.",
  genericErrorText: "An error occurred. Please try again.",
  totalVerificationFailedText:
    "We could not verify the current taxes and order total. Return to your cart and try again.",
  totalUnavailableText: "Total unavailable",
  continueToProviderText: "Continue to {provider}",
  payAmountNowText: "Pay {amount} now",
  payAmountText: "Pay {amount}",
  providerRedirectText: "You'll be redirected to {provider} to complete your payment.",
  creditDebitCardText: "Credit or debit card",
  paySecurelyByCardText: "Pay securely by card",
  onlinePaymentText: "Pay online",
  onlinePaymentDescriptionText: "bKash, Nagad, cards and more",
  completeWithProviderText: "Complete payment with {provider}",
  cashOnDeliveryText: "Cash on delivery",
  payOnDeliveryText: "Pay when you receive your order",
  enterDiscountCodeText: "Enter a discount code.",
  discountAppliedText: "{code} applied",
  invalidDiscountCodeText: "We couldn't find that code. Check it and try again.",
  discountApplyFailedText: "Could not apply the discount. Try again.",
  discountAlreadyAppliedText: "You already entered {code}.",
  removeDiscountCodeText: "Remove {code}",
  discountMinimumSubtotalText: "Add {amount} more to use {code}.",
  discountMinimumQuantityText: "Add {count} more items to use {code}.",
  discountMinimumQuantityOneText: "Add 1 more item to use {code}.",
  discountGetFreeText: "Add {item} to get it free.",
  discountGetPercentText: "Add {item} to get {percent}% off it.",
  discountBuyMoreText: "Add {count} more {item} to use {code}.",
  discountSpendMoreText: "Spend {amount} more on {item} to use {code}.",
  discountNotCombinableText: "{code} can't be combined with {other}.",
  discountLowerSavingsText: "Your cart already gets an equal or better discount.",
  discountLowerSavingsThanText: "{other} gives an equal or bigger discount, so {other} is applied.",
  discountReplacesText: "{code} gives a bigger discount than {other}, so {code} is applied.",
  discountNeedsPhoneText: "Enter your phone number to use {code}.",
  offerAddItemText: "Add",
  offerChooseOptionsText: "Choose options",
  contactHeadingText: "Contact",
  deliveryHeadingText: "Delivery",
  nameTooShortText: "Enter your full name (at least 3 letters).",
  emailInvalidText: "Enter an email like name@example.com.",
  zoneSearchPlaceholder: "Type to find your thana",
  retryText: "Try again",
  undoText: "Undo",
  itemRemovedText: "{item} removed",
  cartClearedText: "Cart cleared",
  changeText: "Change",
  contactReviewText: "Contact",
  shipToReviewText: "Ship to",
  deliveryReviewText: "Delivery",
  pickupFromText: "Pick up from {address}",
  saleOfferGetText: "Buy {quantity} {item}, get this {benefit}",
  saleOfferGetSpendText: "Spend {amount} on {item}, get this {benefit}",
  orderReceiptNoteText: "Your note",
  phoneIntlInvalidText: "Enter a valid phone number with its country code.",
  deliveryFeeChangedText: "Delivery fee changed from {old} to {new}. Check your total, then place your order.",
  deliveryOptionReplacedText: "{old} is no longer available here, so {new} is selected. Delivery was {oldFee}, now {newFee}. Check your total.",
  deliveryOptionReplacedSameFeeText: "{old} is no longer available for this address, so {new} ({fee}) is selected. Check your total, then place your order.",
  deliveryOptionGoneText: "{old} is no longer available for this address. Choose another delivery option.",
  freeDeliveryProgressText: "Add {amount} more for free delivery.",
  discountNeedsDeliveryText: "Choose your city and thana to use {code}.",
  discountOneDeliveryText: "Only one delivery discount can be used. {other} already applies to delivery.",
  freeOverText: "Free over {amount}",
  chooseAddressForDeliveryText: "Choose your city and thana to see delivery options.",
  noDeliveryToAddressText: "We don't deliver to this address yet.",
  deliveryOptionsFailedText: "We couldn't load delivery options. Check your connection and try again.",
  orderAlreadyPlacedText: "This order was already placed.",
  viewOrderText: "View order",
  addToCartText: "Add to cart",
  buyNowText: "Buy now",
  chooseOptionText: "Choose a {option}",
  fromPriceText: "From {price}",
  quantityLabelText: "Quantity",
  quantityLimitText: "You can buy up to {count} at a time.",
  saleOfferText: "Buy {quantity}, get {item} {benefit}",
  saleOfferSpendText: "Spend {amount}, get {item} {benefit}",
  freeBenefitText: "free",
  percentBenefitText: "{percent}% off",
  orderStatusTitleText: "Order {orderNumber}",
  orderTrackingUpdatesText: "Updates",
  orderTrackingStepDoneText: "done",
  orderTrackingIdText: "Tracking ID",
  orderTrackWithCourierText: "Track with courier",
  // Delivery method: ship, pick up, or nothing to deliver (Wave A §2.7, §8.2).
  deliveryMethodLegendText: "Delivery method",
  deliveryModeShipText: "Delivery",
  deliveryModePickupText: "Pickup",
  pickupLocationLabel: "Choose a pickup location",
  pickupLocationRequiredText: "Choose a pickup location.",
  pickupHoursText: "Open {hours}",
  noDeliveryNeededText: "No delivery needed — we'll send updates to your phone.",
  pickupReviewText: "Pick up at",
  payAtPickupText: "Pay when you pick up your order",
  payAtServiceText: "Pay when the service is done",
  // Buyer inputs on the product page and the cart line (Wave A §3).
  editLineText: "Edit",
  editLineLabelText: "Edit {item}",
  updateCartItemText: "Update cart",
  customizationRequiredText: "Fill in {field}.",
  customizationRequiredChoiceText: "Choose {field}.",
  customizationRequiredCheckText: "Tick {field} to continue.",
  customizationTooLongText: "Use at most {max} characters.",
  customizationCounterText: "{count}/{max}",
  customizationSurchargeText: "+{price}",
  customizationOptionalText: "optional",
  customizationChoosePlaceholderText: "Choose…",
  customizationUnavailableText: "This product can't be ordered right now.",
  customizationNeededText: "Fill in your details below, then add it to your cart.",
  customizationInvalidText: "Some of your details can't be used. Check them below, then add it to your cart.",
  pickupAvailableText: "Pickup available",
  noDeliveryNeededBadgeText: "No delivery needed",
  // Receipt, account order and tracking: lines grouped by how they reach the buyer.
  orderLineGroupShipText: "Delivery",
  orderLineGroupPickupText: "Pickup",
  orderLineGroupServiceText: "Services",
  orderLineGroupDigitalText: "Digital items",
  orderLineGroupGiftCardText: "Gift cards",
  orderLinePreparingText: "Preparing",
  orderLineSentText: "Sent",
  orderLineDeliveredText: "Delivered",
  orderLineReadyForPickupText: "Ready for pickup",
  orderLinePickedUpText: "Picked up",
  orderLineServiceDoneText: "Service done",
  orderLineFulfilledCountText: "{done} of {total}",
  orderPickupHeadingText: "Pickup",
  orderPickupAddressText: "Pick up at {address}",
  orderPickupReadyText: "Ready for pickup at {address}",
  orderPickupNotReadyText: "We'll let you know when your order is ready to collect.",
  orderPickupHoursLabelText: "Hours",
  orderNoDeliveryText: "No delivery needed",
  orderReceiptPickedUpTitleText: "Order picked up",
  orderReceiptPickedUpMessageText: "Order #{orderId} has been picked up.",
  orderReceiptFulfilledMessageText: "Order #{orderId} is complete.",
  // Gift cards as a tender (Wave B §4.3): the payment step's field, chips and amount due.
  giftCardTitleText: "Gift card",
  giftCardCodeLabelText: "Gift card code",
  giftCardApplyText: "Apply",
  giftCardApplyingText: "Applying…",
  giftCardRemoveText: "Remove gift card {card}",
  giftCardAppliedText: "Gift card {card} applied.",
  giftCardRemovedText: "Gift card {card} removed.",
  giftCardEnterCodeText: "Enter the 16-character code from your gift card.",
  giftCardUnusableText: "This gift card can't be used.",
  giftCardDuplicateText: "This gift card is already applied.",
  giftCardNotNeededText: "Your other gift cards already cover this order, so this one wasn't used.",
  giftCardLimitText: "You can use up to 5 gift cards on one order.",
  giftCardChangedText: "Your gift card balance changed; review and place the order again.",
  giftCardRateLimitedText: "Too many tries. Wait a minute, then try again.",
  giftCardUnavailableText: "Gift cards can't be used right now. Try again later.",
  giftCardLineText: "Gift card {card}",
  amountDueText: "Amount due",
  paidWithGiftCardText: "Paid with gift card",
  paidWithGiftCardDescriptionText: "Your gift cards cover the whole order.",
  giftCardPayOnDeliveryText: "Pay {amount} when you receive your order",
  giftCardCheckoutStepText: "Have a gift card? Use it on the payment step",
} as const;

export type CheckoutLanguageData = {
  -readonly [Key in keyof typeof ENGLISH_CHECKOUT_LANGUAGE_DATA]: string;
};

export type CheckoutLanguageKey = keyof CheckoutLanguageData;

export const BANGLA_CHECKOUT_LANGUAGE_DATA: CheckoutLanguageData = {
  pageTitle: "কার্ট ও চেকআউট",
  checkoutSectionTitle: "চেকআউটের তথ্য",
  cartSectionTitle: "শপিং কার্ট",
  customerNameLabel: "পুরো নাম",
  customerNamePlaceholder: "আপনার পুরো নাম লিখুন",
  customerPhoneLabel: "ফোন নম্বর",
  customerPhonePlaceholder: "01712-345678",
  customerPhoneHelp: "০১ দিয়ে শুরু ১১ সংখ্যার মোবাইল নম্বর। কুরিয়ার এই নম্বরে কল করবে।",
  phoneCountryLabelText: "ফোন নম্বরের দেশ",
  customerEmailLabel: "ইমেইল (ঐচ্ছিক)",
  customerEmailPlaceholder: "আপনার ইমেইল ঠিকানা লিখুন",
  shippingAddressLabel: "ডেলিভারির ঠিকানা",
  shippingAddressPlaceholder: "আপনার সম্পূর্ণ ডেলিভারির ঠিকানা লিখুন",
  cityLabel: "শহর",
  zoneLabel: "থানা",
  areaLabel: "উপ-এলাকা (ঐচ্ছিক)",
  shippingMethodLabel: "ডেলিভারি পদ্ধতি বেছে নিন",
  orderNotesLabel: "অর্ডার নোট (ঐচ্ছিক)",
  orderNotesPlaceholder: "অর্ডার সম্পর্কে বিশেষ কোনো নির্দেশনা আছে?",
  continueShoppingText: "কেনাকাটা চালিয়ে যান",
  subtotalText: "পণ্যের মোট",
  shippingText: "ডেলিভারি চার্জ",
  discountText: "ছাড়",
  totalText: "সর্বমোট",
  discountCodePlaceholder: "ডিসকাউন্ট কোড",
  applyDiscountText: "প্রয়োগ করুন",
  removeDiscountText: "সরান",
  placeOrderText: "অর্ডার করুন",
  processingText: "প্রক্রিয়া চলছে…",
  emptyCartText: "আপনার কার্ট খালি",
  emptyCartDescriptionText: "আপনি এখনো কার্টে কোনো পণ্য যোগ করেননি।",
  paymentRecoveryMessageText:
    "পেমেন্ট পেজ খোলার আগেই আপনার অর্ডারটি তৈরি হয়েছে। নতুন করে চেকআউট শুরু করার আগে পেমেন্টের অবস্থা দেখুন।",
  viewPaymentStatusText: "পেমেন্টের অবস্থা দেখুন",
  paymentRecoveryPageTitleText: "পেমেন্ট পুনরুদ্ধার",
  paymentRecoveryEyebrowText: "নিরাপদ পেমেন্ট পুনরুদ্ধার",
  paymentRecoveryHeadingText: "অর্ডারটি যাচাই করুন",
  paymentRecoveryIntroText:
    "এই লিংকটি নিজে থেকে ব্যক্তিগত রসিদের তথ্য খোলে না। এই ব্রাউজার থেকে পেমেন্ট চালিয়ে যেতে ক্রেতার যোগাযোগের মাধ্যম যাচাই করুন।",
  paymentRecoverySmsChannelText: "অর্ডারের ফোনে SMS",
  paymentRecoveryWhatsappChannelText: "অর্ডারের ফোনে WhatsApp",
  paymentRecoveryEmailChannelText: "অর্ডারের ইমেইলে",
  paymentRecoveryOrderReferenceText: "অর্ডার রেফারেন্স",
  paymentRecoveryVerificationChannelText: "যাচাইকরণের মাধ্যম",
  paymentRecoverySendCodeText: "কোড পাঠান",
  paymentRecoveryVerificationCodeText: "যাচাইকরণ কোড",
  paymentRecoveryContinueToReceiptText: "রসিদে এগিয়ে যান",
  paymentRecoveryUnavailableText:
    "এই মুহূর্তে পেমেন্ট পুনরুদ্ধার করা যাচ্ছে না। অ্যাকাউন্টের অর্ডার দেখতে সাইন ইন করুন।",
  paymentRecoveryMissingOrderText:
    "এই পুনরুদ্ধার লিংকে অর্ডার রেফারেন্স নেই। দোকানের কাছে নতুন পেমেন্ট পুনরুদ্ধার লিংক চান।",
  paymentRecoveryViewAccountOrdersText: "অ্যাকাউন্টের অর্ডার দেখুন",
  paymentRecoverySendingCodeText: "যাচাইকরণ কোড পাঠানো হচ্ছে…",
  paymentRecoveryCodeSentText:
    "অর্ডারটি পেমেন্ট পুনরুদ্ধারের উপযোগী হলে ক্রেতার যোগাযোগের মাধ্যমে যাচাইকরণ কোড পাঠানো হবে।",
  paymentRecoverySendFailedText: "যাচাইকরণ কোড পাঠানো যায়নি। আবার চেষ্টা করুন।",
  paymentRecoveryEnterCodeText: "এগিয়ে যেতে যাচাইকরণ কোড লিখুন।",
  paymentRecoveryVerifyingCodeText: "কোড যাচাই করা হচ্ছে…",
  paymentRecoveryVerificationFailedText:
    "যাচাইকরণ ব্যর্থ হয়েছে। নতুন কোড নিয়ে আবার চেষ্টা করুন।",
  paymentRecoveryRateLimitedText:
    "খুব বেশি যাচাইয়ের চেষ্টা হয়েছে। কিছুক্ষণ অপেক্ষা করে আবার চেষ্টা করুন।",
  orderReceiptPageTitleText: "অর্ডারের রসিদ",
  orderReceiptMissingTitleText: "রসিদটি খোলা যায়নি",
  orderReceiptBrowserRecoveryMessageText:
    "রসিদটি শুধু চেকআউট করা ব্রাউজারেই খোলা যাবে। পেমেন্ট চালিয়ে যেতে আপনার যোগাযোগের মাধ্যম যাচাই করুন।",
  orderReceiptBrowserOnlyMessageText:
    "রসিদটি শুধু চেকআউট করা ব্রাউজারেই খোলা যাবে। অর্ডার দেখতে সাইন ইন করুন অথবা চেকআউট করা ব্রাউজারে ফিরে যান।",
  orderReceiptUnavailableTitleText: "রসিদটি সাময়িকভাবে পাওয়া যাচ্ছে না",
  orderReceiptPrivateUnavailableMessageText:
    "ব্যক্তিগত অর্ডার লিংক থেকে রসিদটি লোড করা যায়নি। অর্ডারটি হয়ে থাকলে সেটি আপনার অ্যাকাউন্টের অর্ডারে দেখা যেতে পারে।",
  orderReceiptExpiredTitleText: "রসিদের প্রবেশাধিকার শেষ হয়েছে",
  orderReceiptExpiredMessageText:
    "এই ব্রাউজারে ব্যক্তিগত রসিদটি আর পাওয়া যাচ্ছে না। অ্যাকাউন্টের অর্ডার দেখতে সাইন ইন করুন।",
  orderReceiptUnavailableMessageText:
    "রসিদটি এখন লোড করা যায়নি। আবার চেষ্টা করুন অথবা অ্যাকাউন্টের অর্ডার দেখুন।",
  orderReceiptReferenceText: "রেফারেন্স",
  orderReceiptVerifyRecoveryText: "পেমেন্ট পুনরুদ্ধার যাচাই করুন",
  orderReceiptRetryText: "রসিদ আবার লোড করুন",
  orderReceiptOrderDetailsText: "অর্ডারের তথ্য",
  orderReceiptOrderNumberText: "অর্ডার নম্বর",
  orderReceiptPlacedText: "অর্ডারের সময়",
  orderReceiptStatusText: "অর্ডারের অবস্থা",
  orderReceiptPaymentText: "পেমেন্ট পদ্ধতি",
  orderReceiptPaymentStatusText: "পেমেন্টের অবস্থা",
  orderReceiptDeliveryText: "ডেলিভারি",
  orderReceiptDeliveryWithMethodText: "ডেলিভারি · {method}",
  orderReceiptDeliveryNotRecordedText: "এই অর্ডারের ডেলিভারি পদ্ধতি সংরক্ষণ করা হয়নি।",
  orderReceiptFeeWaivedText: "{fee} চার্জ মওকুফ হয়েছে",
  orderReceiptPaidText: "পরিশোধিত",
  orderReceiptBalanceDueText: "বাকি টাকা",
  orderReceiptDeliveryDetailsText: "ডেলিভারির তথ্য",
  orderReceiptItemsText: "পণ্যসমূহ",
  orderReceiptProductUnavailableText: "পণ্যটি পাওয়া যাচ্ছে না",
  orderReceiptQuantityText: "পরিমাণ: {quantity}",
  orderReceiptItemDiscountText: "পণ্যে ছাড়: −{amount}",
  orderReceiptTaxIncludedText: "{label} অন্তর্ভুক্ত: {amount}",
  orderReceiptTaxAddedText: "{label} যোগ হয়েছে: {amount}",
  orderReceiptLineTotalText: "পণ্যটির মোট",
  orderReceiptPrintText: "রসিদ প্রিন্ট করুন",
  orderReceiptCheckingPaymentText: "পেমেন্টের অবস্থা যাচাই করা হচ্ছে…",
  orderReceiptCheckPaymentText: "পেমেন্টের অবস্থা যাচাই করুন",
  orderReceiptStripePaymentMethodRequiredText:
    "Stripe-এ নতুন কার্ডের তথ্য প্রয়োজন। চালিয়ে যেতে নিচের Stripe-এর মাধ্যমে পেমেন্ট সম্পন্ন করুন বেছে নিন।",
  orderReceiptStripeAuthenticationRequiredText:
    "এই পেমেন্টের জন্য Stripe-এ অতিরিক্ত যাচাই প্রয়োজন। চালিয়ে যেতে নিচের Stripe-এর মাধ্যমে পেমেন্ট সম্পন্ন করুন বেছে নিন।",
  orderReceiptConfirmationDelayedText:
    "পেমেন্ট নিশ্চিত হতে স্বাভাবিকের চেয়ে বেশি সময় লাগছে। আপনি নিরাপদে এই রসিদ থেকে বের হয়ে পরে আবার দেখতে পারেন।",
  orderReceiptStatusUpdatedText: "পেমেন্টের অবস্থা হালনাগাদ হয়েছে। রসিদ রিফ্রেশ হচ্ছে…",
  orderReceiptRetryWithProviderText: "{provider} দিয়ে আবার পেমেন্ট করুন",
  orderReceiptRetryPaymentText: "আবার পেমেন্ট করুন",
  orderReceiptOpeningPaymentText: "পেমেন্ট খোলা হচ্ছে…",
  orderReceiptRetryUnavailableText: "এই অর্ডারের পেমেন্ট আবার চেষ্টা করা যাচ্ছে না।",
  orderReceiptCardUnavailableText: "এই অর্ডারে কার্ড পেমেন্ট পাওয়া যাচ্ছে না।",
  orderReceiptLoadingCardText: "নিরাপদ কার্ড ফর্ম লোড হচ্ছে…",
  orderReceiptEnterCardText: "এই অর্ডারটি চালিয়ে যেতে কার্ডের তথ্য লিখুন।",
  orderReceiptCardLoadFailedText: "নিরাপদ কার্ড ফর্ম লোড করা যায়নি। অন্য পেমেন্ট পদ্ধতি চেষ্টা করুন।",
  orderReceiptPaymentProcessingRetryText: "পেমেন্ট এখনো প্রক্রিয়াধীন। {seconds} সেকেন্ড পর আবার চেষ্টা করা হবে…",
  orderReceiptStartPaymentFailedText: "পেমেন্ট শুরু করা যায়নি। আবার চেষ্টা করুন।",
  orderReceiptGatewayRedirectFailedText: "পেমেন্ট সেবা নিরাপদ পেমেন্ট পেজ দেয়নি।",
  orderReceiptConfirmingCardText: "আপনার বর্তমান অর্ডারের কার্ড পেমেন্ট নিশ্চিত করা হচ্ছে…",
  orderReceiptCardPaymentFailedText: "কার্ড পেমেন্ট সম্পন্ন করা যায়নি। আপনার অর্ডারটি সংরক্ষিত আছে।",
  orderReceiptExistingOrderCardHelpText:
    "আপনার বর্তমান অর্ডারটিই হালনাগাদ হবে। নতুন কোনো অর্ডার তৈরি হবে না।",
  orderReceiptPaymentIssueTitleText: "পেমেন্ট সম্পন্ন হয়নি",
  orderReceiptPaymentIssueMessageText:
    "অর্ডার #{orderId} সংরক্ষিত আছে। পেমেন্ট পদ্ধতি বেছে নিন।",
  orderReceiptPaymentPendingTitleText: "পেমেন্ট অপেক্ষমাণ",
  orderReceiptPaymentPendingMessageText:
    "অর্ডার #{orderId} সংরক্ষিত আছে।",
  orderReceiptConfirmedTitleText: "অর্ডার নিশ্চিত হয়েছে",
  orderReceiptConfirmedMessageText: "অর্ডার #{orderId} নিশ্চিত হয়েছে এবং প্রস্তুত করা হচ্ছে।",
  orderReceiptProcessingTitleText: "অর্ডার প্রস্তুত করা হচ্ছে",
  orderReceiptProcessingMessageText: "অর্ডার #{orderId} প্রস্তুত করা হচ্ছে।",
  orderReceiptShippedTitleText: "অর্ডার পাঠানো হয়েছে",
  orderReceiptShippedMessageText: "অর্ডার #{orderId} আপনার পথে আছে।",
  orderReceiptDeliveredTitleText: "অর্ডার ডেলিভারি হয়েছে",
  orderReceiptDeliveredMessageText: "অর্ডার #{orderId} ডেলিভারি করা হয়েছে।",
  orderReceiptCompletedTitleText: "অর্ডার সম্পন্ন হয়েছে",
  orderReceiptCompletedMessageText: "অর্ডার #{orderId} সম্পন্ন হয়েছে।",
  orderReceiptCancelledTitleText: "অর্ডার বাতিল হয়েছে",
  orderReceiptCancelledMessageText: "অর্ডার #{orderId} বাতিল করা হয়েছে।",
  orderReceiptRefundedTitleText: "অর্ডারের টাকা ফেরত হয়েছে",
  orderReceiptRefundedMessageText: "অর্ডার #{orderId}-এর টাকা ফেরত দেওয়া নথিভুক্ত হয়েছে।",
  orderReceiptReturnedTitleText: "অর্ডার ফেরত এসেছে",
  orderReceiptReturnedMessageText: "অর্ডার #{orderId} ফেরত দেওয়া নথিভুক্ত হয়েছে।",
  orderReceiptPartiallyRefundedTitleText: "অর্ডারের কিছু টাকা ফেরত হয়েছে",
  orderReceiptPartiallyRefundedMessageText:
    "অর্ডার #{orderId}-এর কিছু টাকা ফেরত দেওয়া নথিভুক্ত হয়েছে।",
  orderReceiptUpdatedTitleText: "অর্ডার হালনাগাদ হয়েছে",
  orderReceiptUpdatedMessageText: "অর্ডার #{orderId} হালনাগাদ হয়েছে।",
  orderReceiptPlacedTitleText: "অর্ডার দেওয়া হয়েছে",
  orderReceiptPlacedMessageText: "আমরা অর্ডার #{orderId} পেয়েছি।",
  orderReceiptStatusNotAvailableText: "পাওয়া যাচ্ছে না",
  orderReceiptStatusPendingText: "অপেক্ষমাণ",
  orderReceiptStatusIncompleteText: "অসম্পূর্ণ",
  orderReceiptStatusConfirmedText: "নিশ্চিত",
  orderReceiptStatusProcessingText: "প্রক্রিয়াধীন",
  orderReceiptStatusShippedText: "পাঠানো হয়েছে",
  orderReceiptStatusDeliveredText: "ডেলিভারি হয়েছে",
  orderReceiptStatusCompletedText: "সম্পন্ন",
  orderReceiptStatusCancelledText: "বাতিল",
  orderReceiptStatusRefundedText: "টাকা ফেরত হয়েছে",
  orderReceiptStatusReturnedText: "ফেরত এসেছে",
  orderReceiptStatusPartiallyRefundedText: "আংশিক টাকা ফেরত হয়েছে",
  orderReceiptStatusFailedText: "ব্যর্থ",
  orderReceiptPaymentStatusPaidText: "পরিশোধিত",
  orderReceiptPaymentStatusPartialText: "আংশিক পরিশোধিত",
  orderReceiptPaymentStatusUnpaidText: "অপরিশোধিত",
  orderReceiptPaymentStatusNoPaymentDueText: "কোনো পেমেন্ট বাকি নেই",
  orderReceiptPaymentMethodCardText: "কার্ড (Stripe)",
  orderReceiptPaymentMethodSslcommerzText: "অনলাইন পেমেন্ট (SSLCommerz)",
  orderReceiptSaveAccountTitleText: "এই অর্ডারটি আপনার অ্যাকাউন্টে সংরক্ষণ করুন",
  orderReceiptSavedAccountTitleText: "অর্ডারটি আপনার অ্যাকাউন্টে সংরক্ষিত হয়েছে",
  orderReceiptSaveAccountHelpText:
    "এই অর্ডারে দেওয়া ফোন নম্বর দিয়ে অ্যাকাউন্ট তৈরি করুন অথবা একই ফোন বা ইমেইল দিয়ে সাইন ইন করুন।",
  orderReceiptViewInAccountText: "অ্যাকাউন্টে দেখুন",
  orderReceiptSaveToAccountText: "আমার অ্যাকাউন্টে সংরক্ষণ করুন",
  orderReceiptSavingText: "সংরক্ষণ করা হচ্ছে…",
  orderReceiptCreateAccountText: "অ্যাকাউন্ট তৈরি করুন",
  orderReceiptSignInText: "সাইন ইন করুন",
  orderReceiptMissingReferenceText: "এই রসিদে অর্ডার রেফারেন্স নেই।",
  orderReceiptSavingToAccountText: "অর্ডারটি আপনার অ্যাকাউন্টে সংরক্ষণ করা হচ্ছে…",
  orderReceiptSaveFailedText: "অর্ডারটি সংরক্ষণ করা যায়নি। আবার চেষ্টা করুন।",
  orderReceiptAlreadySavedText: "অর্ডারটি ইতিমধ্যে আপনার অ্যাকাউন্টে আছে।",
  orderReceiptSavedText: "অর্ডারটি সংরক্ষিত হয়েছে। এখন যেকোনো সাইন-ইন করা ডিভাইস থেকে এটি দেখতে পারবেন।",
  orderReceiptCreateAccountPromptText: "এই অর্ডারে দেওয়া ফোন নম্বর দিয়ে আপনার অ্যাকাউন্ট তৈরি করুন।",
  orderReceiptSignInPromptText: "এই অর্ডারের সঙ্গে মেলে এমন ফোন নম্বর বা ইমেইল দিয়ে সাইন ইন করুন।",
  orderReceiptHelpText: "সাহায্য প্রয়োজন?",
  orderReceiptCancelRequestActionText: "বাতিলের অনুরোধ করুন",
  orderReceiptCancelRequestDescriptionText: "অর্ডারটি পাঠানোর আগে দোকানকে পর্যালোচনা করতে বলুন।",
  orderReceiptCancelRequestPickupDescriptionText: "অর্ডারটি সংগ্রহের আগে দোকানকে পর্যালোচনা করতে বলুন।",
  orderReceiptCancelRequestServiceDescriptionText: "সেবা সম্পন্ন হওয়ার আগে দোকানকে অর্ডারটি পর্যালোচনা করতে বলুন।",
  orderReceiptReturnRequestActionText: "ফেরতের অনুরোধ করুন",
  orderReceiptRefundRequestActionText: "টাকা ফেরতের অনুরোধ করুন",
  orderReceiptRequestSubmittedText: "দোকান আপনার অনুরোধ পেয়েছে এবং পরিবর্তনের আগে এটি পর্যালোচনা করবে।",
  orderReceiptRequestUnderReviewText: "দোকানের দল অনুরোধটি পর্যালোচনা করছে।",
  orderReceiptRequestApprovedText: "দোকান অনুরোধটি গ্রহণ করেছে। অগ্রগতি জানতে অর্ডারের অবস্থা দেখুন।",
  orderReceiptRequestRejectedText: "দোকান অনুরোধটি গ্রহণ করতে পারেনি।",
  orderReceiptRequestWithdrawnText: "অনুরোধটি প্রত্যাহার করা হয়েছে।",
  orderReceiptRequestCompletedText: "অনুরোধটি সম্পন্ন হয়েছে।",
  orderReceiptRequestSettledText: "অনুরোধটি নিষ্পত্তি হয়েছে।",
  orderReceiptRequestStatusSubmittedText: "জমা হয়েছে",
  orderReceiptRequestStatusUnderReviewText: "পর্যালোচনাধীন",
  orderReceiptRequestStatusApprovedText: "গৃহীত",
  orderReceiptRequestStatusRejectedText: "প্রত্যাখ্যাত",
  orderReceiptRequestStatusWithdrawnText: "প্রত্যাহার করা হয়েছে",
  orderReceiptRequestStatusCompletedText: "সম্পন্ন",
  orderReceiptRequestLabelText: "{action} · {status}",
  orderReceiptReasonText: "কারণ",
  orderReceiptReasonAriaText: "সহায়তার অনুরোধের কারণ",
  orderReceiptReasonPlaceholderText: "আপনি কেন এই অনুরোধ করছেন?",
  orderReceiptCancelText: "বাতিল করুন",
  orderReceiptSendRequestText: "অনুরোধ পাঠান",
  orderReceiptMissingProofText: "অনুরোধ পাঠানোর জন্য প্রয়োজনীয় ব্রাউজার প্রমাণ এই রসিদে নেই।",
  orderReceiptReasonRequiredText: "অনুরোধ পাঠানোর আগে সংক্ষিপ্ত কারণ লিখুন।",
  orderReceiptSupportFailedText: "সহায়তার অনুরোধ পাঠানো যায়নি। আবার চেষ্টা করুন।",
  orderReceiptRequestSentText: "অনুরোধ পাঠানো হয়েছে। দোকানের দল এখন অর্ডার থেকে এটি পর্যালোচনা করতে পারবে।",
  orderReceiptSupportUnavailableText: "এই অর্ডারের জন্য এখন সহায়তার অনুরোধ পাওয়া যাচ্ছে না।",
  orderReceiptNextStepsTitleText: "এরপর কী হবে",
  orderReceiptNextStepsCodText: "অর্ডারটি নিশ্চিত করতে আমরা আপনাকে ফোন করব, তারপর কুরিয়ারে পাঠিয়ে দেব।",
  orderReceiptNextStepsPaidText: "আপনার পেমেন্ট নিশ্চিত হয়েছে। আমরা অর্ডারটি প্যাক করে কুরিয়ারে পাঠিয়ে দেব।",
  orderReceiptNextStepsPickupCodText: "অর্ডার নিশ্চিত করতে আমরা আপনাকে কল করব, তারপর সংগ্রহের জন্য প্রস্তুত হলে জানাব।",
  orderReceiptNextStepsPickupPaidText: "আপনার পেমেন্ট নিশ্চিত হয়েছে। অর্ডার সংগ্রহের জন্য প্রস্তুত হলে আমরা জানাব।",
  orderReceiptNextStepsServiceCodText: "অর্ডার নিশ্চিত করতে ও সেবার সময় ঠিক করতে আমরা আপনাকে কল করব।",
  orderReceiptNextStepsServicePaidText: "আপনার পেমেন্ট নিশ্চিত হয়েছে। সেবার সময় ঠিক করতে আমরা যোগাযোগ করব।",
  orderReceiptDeliveryEstimateText: "ডেলিভারিতে সাধারণত {estimate} লাগে।",
  orderReceiptAccountSavedText: "আপনার অ্যাকাউন্টে সংরক্ষিত",
  orderReceiptViewOrderText: "অর্ডার দেখুন",
  orderReceiptAccountSignInText: "অ্যাকাউন্টে এই অর্ডারটি দেখতে সাইন ইন করুন",
  orderReceiptAccountCreateText: "এই অর্ডারটি ট্র্যাক করতে একটি অ্যাকাউন্ট খুলুন",
  orderReceiptIncompleteTitleText: "রসিদের লিংকটি অসম্পূর্ণ",
  orderReceiptTrackOrderHelpText: "অর্ডার নম্বর ও অর্ডারে দেওয়া ফোন নম্বর দিয়ে যেকোনো ডিভাইস থেকে আপনার অর্ডারটি দেখতে পারবেন।",
  trackOrderText: "অর্ডার ট্র্যাক করুন",
  trackOrderIntroText: "আপনার অর্ডার নম্বর এবং অর্ডারে দেওয়া ফোন নম্বরটি লিখুন।",
  trackOrderCodeSentText: "তথ্যগুলো কোনো অর্ডারের সাথে মিললে, সেই অর্ডারে সংরক্ষিত ফোন নম্বর বা ইমেইলে একটি কোড পাঠানো হয়েছে।",
  trackOrderNumberInvalidText: "আপনার অর্ডার নম্বর লিখুন, যেমন #1001।",
  trackOrderPhoneInvalidText: "অর্ডারে দেওয়া ফোন নম্বরটি লিখুন।",
  trackOrderUnavailableText: "এই মুহূর্তে অর্ডার ট্র্যাক করা যাচ্ছে না।",
  storeContactLabelText: "দোকানের সঙ্গে যোগাযোগ:",
  orderCodeResendInText: "{time} পরে নতুন কোড পাঠান",
  orderCodeSendNewText: "নতুন কোড পাঠান",
  orderCodeTryAgainInText: "{time} পরে আবার চেষ্টা করুন",
  orderCodeWrongOneAttemptText: "কোডটি সঠিক নয়। আর ১ বার চেষ্টা করতে পারবেন।",
  orderCodeWrongAttemptsText: "কোডটি সঠিক নয়। আর {count} বার চেষ্টা করতে পারবেন।",
  orderCodeExpiredText: "এই কোডটি আর ব্যবহার করা যাবে না। নতুন কোড পাঠান।",
  paymentRecoveryFinishTitleText: "আপনার অর্ডারের পেমেন্ট সম্পন্ন করুন",
  paymentRecoveryCodeIntroText: "এই অর্ডারে সংরক্ষিত ফোন নম্বর বা ইমেইলে আমরা একটি কোড পাঠাব।",
  paymentRecoveryCodeRequestedText: "অর্ডারটির পেমেন্ট এখনো অনলাইনে করা গেলে, এতে সংরক্ষিত ফোন নম্বর বা ইমেইলে একটি কোড পাঠানো হয়েছে।",
  paymentRecoveryContinueToPaymentText: "পেমেন্টে এগিয়ে যান",
  paymentRecoveryLinkIncompleteText: "পেমেন্ট লিংকটি অসম্পূর্ণ। দোকানকে লিংকটি আবার পাঠাতে বলুন।",
  paymentRecoveryCodesUnavailableText: "এই মুহূর্তে কোড পাঠানো যাচ্ছে না।",
  paymentRecoverySendCodeByText: "কোড পাঠানোর মাধ্যম",
  termsText: "অর্ডারটি নিশ্চিত করলে আপনি আমাদের {terms} ও {privacy}-তে সম্মত হচ্ছেন।",
  termsLinkText: "পরিষেবার শর্তাবলি",
  privacyLinkText: "গোপনীয়তা নীতি",
  processingOrderTitle: "আপনার অর্ডার প্রক্রিয়া করা হচ্ছে",
  processingOrderMessage: "আপনার অর্ডারটি প্রক্রিয়া করা পর্যন্ত অনুগ্রহ করে অপেক্ষা করুন।",
  requiredFieldIndicator: "*",
  homeAriaLabel: "হোমপেজে যান",
  secureCheckoutText: "নিরাপদ চেকআউট",
  checkoutProgressLabel: "চেকআউটের অগ্রগতি",
  informationStepText: "তথ্য",
  paymentStepText: "পেমেন্ট",
  confirmationStepText: "নিশ্চিতকরণ",
  estimatedTotalText: "আনুমানিক সর্বমোট",
  taxText: "কর",
  freeText: "ফ্রি",
  calculatingText: "হিসাব করা হচ্ছে…",
  unavailableText: "স্টক শেষ",
  taxVerificationFailedText: "সর্বমোট আপডেট করা যায়নি। ইন্টারনেট সংযোগ দেখে আবার চেষ্টা করুন।",
  cartItemChangedText: "চেকআউটের আগে কার্টের একটি পণ্য যাচাই করা দরকার।",
  cartAvailabilityFailedText: "কার্টের পণ্য যাচাই করা যায়নি। পেজ রিফ্রেশ করে আবার চেষ্টা করুন।",
  cartItemsChangedText: "পেমেন্টের আগে কার্টের {count}টি পণ্য পরিবর্তিত হয়েছে। চেকআউটের আগে সেগুলো দেখুন।",
  oneCartItemChangedText: "পেমেন্টের আগে কার্টের একটি পণ্য পরিবর্তিত হয়েছে। চেকআউটের আগে সেটি দেখুন।",
  cartAvailabilityReviewText: "কার্টের পণ্য যাচাই করা যায়নি। চেকআউটের আগে কার্টটি দেখুন।",
  orderSummaryText: "অর্ডারের সারাংশ",
  paymentPageTitle: "পেমেন্ট",
  paymentMethodsText: "পেমেন্ট পদ্ধতিগুলো",
  paymentMethodText: "পেমেন্ট পদ্ধতি",
  loadingPaymentMethodsText: "পেমেন্ট পদ্ধতি লোড হচ্ছে",
  testModeNoticeText: "টেস্ট মোড — কোনো প্রকৃত পেমেন্ট নেওয়া হবে না।",
  cardDetailsText: "কার্ডের তথ্য",
  selectPaymentMethodText: "একটি পেমেন্ট পদ্ধতি বেছে নিন",
  continueToPaymentText: "পেমেন্টে এগিয়ে যান",
  checkoutUnavailableText: "চেকআউট বন্ধ আছে",
  checkoutUnavailableMessage: "চেকআউট সাময়িকভাবে বন্ধ আছে। কিছুক্ষণ পর আবার চেষ্টা করুন।",
  errorPrefixText: "সমস্যা:",
  successPrefixText: "সফল!",
  existingCheckoutTitle: "আপনার একটি চেকআউট ইতিমধ্যে চলছে",
  existingCheckoutMessage:
    "{orderId} নম্বর অর্ডারটির পেমেন্ট বাকি আছে। নতুন চেকআউট শুরুর আগে এটি দেখুন।",
  reviewExistingCheckoutText: "চলমান চেকআউট দেখুন",
  signInToCheckoutText: "সাইন ইন করে চেকআউট করুন",
  signInPromptText: "আগে থেকেই অ্যাকাউন্ট আছে? দ্রুত চেকআউট করতে সাইন ইন করুন",
  noScriptText: "চেকআউটের আগে কার্ট হালনাগাদ করতে JavaScript প্রয়োজন।",
  selectCityPlaceholder: "শহর বেছে নিন",
  selectZonePlaceholder: "থানা বেছে নিন",
  selectAreaPlaceholder: "উপ-এলাকা বেছে নিন (ঐচ্ছিক)",
  loadingText: "লোড হচ্ছে…",
  zonesLoadFailedText: "থানাগুলো লোড করা যায়নি। আবার চেষ্টা করুন",
  areasLoadFailedText: "উপ-এলাকাগুলো লোড করা যায়নি। আবার চেষ্টা করুন",
  noShippingMethodsText: "এই মুহূর্তে কোনো ডেলিভারি পদ্ধতি পাওয়া যাচ্ছে না।",
  waivedShippingFeeText: "সাধারণত {fee}; কার্টের একটি পণ্যের কারণে চার্জটি মওকুফ হয়েছে।",
  phoneRequiredText: "আপনার ফোন নম্বর লিখুন।",
  phoneInvalidText: "বাংলাদেশি মোবাইল নম্বর লিখুন (01XXXXXXXXX)।",
  phoneCountryNotAcceptedText: "এই দোকান ওই দেশের ফোন নম্বর গ্রহণ করে না।",
  nameRequiredText: "আপনার পুরো নাম লিখুন।",
  addressRequiredText: "আপনার ডেলিভারির ঠিকানা লিখুন।",
  addressIncompleteText: "সম্পূর্ণ ডেলিভারির ঠিকানা লিখুন (কমপক্ষে {minimum} অক্ষর)।",
  cityZoneRequiredText: "এগিয়ে যেতে শহর ও থানা বেছে নিন।",
  zoneRequiredText: "এগিয়ে যেতে একটি থানা বেছে নিন।",
  cityUnavailableText: "এই শহরটি আর পাওয়া যাচ্ছে না। অন্য একটি বেছে নিন।",
  thanaUnavailableText: "এই থানাটি আর পাওয়া যাচ্ছে না। অন্য একটি বেছে নিন।",
  areaUnavailableText: "এই এলাকাটি আর পাওয়া যাচ্ছে না। অন্য একটি বেছে নিন।",
  deliveryRequiredText: "একটি ডেলিভারি পদ্ধতি বেছে নিন।",
  checkingAvailableQuantityText: "{item}-এর উপলভ্য পরিমাণ যাচাই করা হচ্ছে",
  maximumAvailableQuantityText: "{item}-এর সর্বোচ্চ উপলভ্য পরিমাণ কার্টে আছে",
  increaseQuantityText: "{item}-এর পরিমাণ বাড়ান",
  decreaseQuantityText: "{item}-এর পরিমাণ কমান",
  removeFromCartText: "কার্ট থেকে {item} সরান",
  cartLoadingText: "আপনার কার্ট লোড হচ্ছে",
  cartAttentionText: "কার্টের কিছু পণ্য যাচাই করা দরকার",
  cartEmptyErrorText: "অর্ডার করার আগে কার্টে পণ্য যোগ করুন।",
  quickBuyStorageBlockedText: "ব্রাউজারটি সাময়িক কার্ট স্টোরেজ বন্ধ রাখায় পণ্যটি যোগ করা যায়নি। সাইট স্টোরেজ চালু করে আবার যোগ করুন।",
  orderProcessingFailedText: "অর্ডারটি প্রক্রিয়া করা যায়নি। আবার চেষ্টা করুন।",
  unexpectedErrorText: "একটি অপ্রত্যাশিত সমস্যা হয়েছে।",
  cartItemsNeedAttentionText: "চেকআউটের আগে কার্টের {count}টি পণ্য যাচাই করা দরকার।",
  orderPlacedSuccessText: "আপনার অর্ডারটি সফলভাবে দেওয়া হয়েছে। অর্ডার আইডি: {orderId}",
  checkingAccountText: "অ্যাকাউন্ট যাচাই করা হচ্ছে…",
  accountUnavailableText: "এখন আপনার অ্যাকাউন্ট যাচাই করা যায়নি। আবার চেষ্টা করুন।",
  checkingCartText: "কার্ট যাচাই করা হচ্ছে…",
  reviewCartItemsText: "চেকআউটের আগে চিহ্নিত পণ্যগুলো দেখুন।",
  redirectingToPaymentText: "পেমেন্টে নেওয়া হচ্ছে…",
  openingPaymentOptionsTitle: "পেমেন্টের বিকল্প খোলা হচ্ছে",
  openingPaymentOptionsMessage: "আপনার সর্বমোট এবং উপলভ্য পেমেন্ট পদ্ধতি নিশ্চিত করা হচ্ছে।",
  checkoutDetailsMissingText: "চেকআউটের তথ্য পাওয়া যায়নি। কার্টে ফিরে আবার চেষ্টা করুন।",
  checkoutDetailsUnreadableText: "চেকআউটের তথ্য পড়া যায়নি। কার্টে ফিরে আবার চেষ্টা করুন।",
  returnToCartText: "কার্টে ফিরুন",
  quantityShortText: "পরিমাণ {quantity}",
  eachText: "প্রতিটি",
  includedText: "অন্তর্ভুক্ত",
  dueNowText: "এখন পরিশোধযোগ্য",
  dueOnDeliveryText: "ডেলিভারির সময় পরিশোধযোগ্য",
  dueAtPickupText: "সংগ্রহের সময় পরিশোধযোগ্য",
  dueAtServiceText: "সেবা শেষে পরিশোধযোগ্য",
  continueText: "এগিয়ে যান",
  continueAsGuestText: "অতিথি হিসেবে এগিয়ে যান",
  sessionExpiredText:
    "আপনার সাইন-ইন সেশন শেষ হয়েছে। চেকআউটের তথ্য নিরাপদ আছে। অতিথি হিসেবে এগিয়ে যান অথবা আবার সাইন ইন করুন।",
  checkoutConflictText: "এই চেকআউটটি ইতিমধ্যে জমা হয়েছে অথবা অন্য ট্যাবে পরিবর্তিত হয়েছে। কার্ট দেখে আবার চেষ্টা করুন।",
  totalChangedReviewText:
    "আপনার অর্ডারের মোট টাকা বা চেকআউটের শর্ত বদলেছে। হালনাগাদ মোট টাকা দেখে অর্ডারটি আবার নিশ্চিত করুন।",
  tooManyCheckoutAttemptsText: "খুব বেশি চেকআউট চেষ্টা হয়েছে। কিছুক্ষণ অপেক্ষা করে আবার চেষ্টা করুন।",
  paymentFailedText: "পেমেন্ট ব্যর্থ হয়েছে",
  noPaymentMethodsText:
    "এই অর্ডারের মোট টাকার জন্য কোনো পেমেন্ট পদ্ধতি পাওয়া যাচ্ছে না। কার্টে ফিরুন।",
  preparingPaymentText: "পেমেন্ট প্রস্তুত হচ্ছে…",
  paymentMethodUnavailableText: "পেমেন্ট পদ্ধতি পাওয়া যাচ্ছে না",
  paymentMethodUnavailableMessage: "এই পেমেন্ট পদ্ধতিটি পাওয়া যাচ্ছে না। অন্য একটি পদ্ধতি বেছে নিন।",
  retryPaymentFormText: "পেমেন্ট ফর্ম আবার চেষ্টা করুন",
  processingPaymentTitle: "পেমেন্ট প্রক্রিয়া করা হচ্ছে",
  processingPaymentMessage: "আপনার অর্ডার ও পেমেন্টের তথ্য নিশ্চিত করা হচ্ছে।",
  placingOrderTitle: "আপনার অর্ডার দেওয়া হচ্ছে",
  placingOrderMessage: "পণ্যের প্রাপ্যতা ও ডেলিভারি নিশ্চিত করা হচ্ছে।",
  openingSecurePaymentTitle: "নিরাপদ পেমেন্ট খোলা হচ্ছে",
  openingSecurePaymentMessage: "বেছে নেওয়া পেমেন্ট সেবায় আপনাকে নিয়ে যাওয়া হবে।",
  unknownPaymentMethodText: "অজানা পেমেন্ট পদ্ধতি বেছে নেওয়া হয়েছে।",
  unsafeRedirectText: "পেমেন্ট সেবা নিরাপদ ঠিকানা না দেওয়ায় পেমেন্ট খোলা যায়নি।",
  genericErrorText: "একটি সমস্যা হয়েছে। আবার চেষ্টা করুন।",
  totalVerificationFailedText:
    "বর্তমান কর ও অর্ডারের সর্বমোট যাচাই করা যায়নি। কার্টে ফিরে আবার চেষ্টা করুন।",
  totalUnavailableText: "সর্বমোট পাওয়া যাচ্ছে না",
  continueToProviderText: "{provider}-এ এগিয়ে যান",
  payAmountNowText: "এখন {amount} পরিশোধ করুন",
  payAmountText: "{amount} পরিশোধ করুন",
  providerRedirectText: "পেমেন্ট সম্পন্ন করতে আপনাকে {provider}-এ নেওয়া হবে।",
  creditDebitCardText: "ক্রেডিট বা ডেবিট কার্ড",
  paySecurelyByCardText: "কার্ড দিয়ে নিরাপদে পেমেন্ট করুন",
  onlinePaymentText: "অনলাইনে পেমেন্ট করুন",
  onlinePaymentDescriptionText: "বিকাশ, নগদ, কার্ড ও আরও অনেক পদ্ধতি",
  completeWithProviderText: "{provider}-এর মাধ্যমে পেমেন্ট সম্পন্ন করুন",
  cashOnDeliveryText: "ক্যাশ অন ডেলিভারি",
  payOnDeliveryText: "অর্ডার পাওয়ার সময় মূল্য পরিশোধ করুন",
  enterDiscountCodeText: "একটি ডিসকাউন্ট কোড লিখুন।",
  discountAppliedText: "{code} প্রয়োগ হয়েছে",
  invalidDiscountCodeText: "এই কোডটি পাওয়া যায়নি। কোডটি দেখে আবার চেষ্টা করুন।",
  discountApplyFailedText: "ডিসকাউন্ট প্রয়োগ করা যায়নি। আবার চেষ্টা করুন।",
  discountAlreadyAppliedText: "{code} আগেই দেওয়া হয়েছে।",
  removeDiscountCodeText: "{code} সরান",
  discountMinimumSubtotalText: "{code} ব্যবহার করতে আরও {amount} কেনাকাটা করুন।",
  discountMinimumQuantityText: "{code} ব্যবহার করতে আরও {count}টি পণ্য যোগ করুন।",
  discountMinimumQuantityOneText: "{code} ব্যবহার করতে আরও ১টি পণ্য যোগ করুন।",
  discountGetFreeText: "{item} কার্টে যোগ করলে ফ্রি পাবেন।",
  discountGetPercentText: "{item} কার্টে যোগ করলে {percent}% ছাড় পাবেন।",
  discountBuyMoreText: "{code} ব্যবহার করতে আরও {count}টি {item} যোগ করুন।",
  discountSpendMoreText: "{code} ব্যবহার করতে {item} থেকে আরও {amount} কেনাকাটা করুন।",
  discountNotCombinableText: "{code} এর সাথে {other} একসাথে ব্যবহার করা যাবে না।",
  discountLowerSavingsText: "আপনার কার্টে এর সমান বা এর চেয়ে বেশি ছাড় আগেই আছে।",
  discountLowerSavingsThanText: "{other}-এ সমান বা বেশি ছাড়, তাই {other} দেওয়া হয়েছে।",
  discountReplacesText: "{code}-এ {other}-এর চেয়ে বেশি ছাড়, তাই {code} দেওয়া হয়েছে।",
  discountNeedsPhoneText: "{code} ব্যবহার করতে আপনার ফোন নম্বর দিন।",
  offerAddItemText: "যোগ করুন",
  offerChooseOptionsText: "অপশন বেছে নিন",
  contactHeadingText: "যোগাযোগ",
  deliveryHeadingText: "ডেলিভারি",
  nameTooShortText: "পুরো নাম লিখুন (অন্তত ৩ অক্ষর)।",
  emailInvalidText: "name@example.com এর মতো একটি ইমেইল দিন।",
  zoneSearchPlaceholder: "থানা খুঁজতে লিখুন",
  retryText: "আবার চেষ্টা করুন",
  undoText: "ফিরিয়ে আনুন",
  itemRemovedText: "{item} সরানো হয়েছে",
  cartClearedText: "কার্ট খালি করা হয়েছে",
  changeText: "পরিবর্তন",
  contactReviewText: "যোগাযোগ",
  shipToReviewText: "পাঠানো হবে",
  deliveryReviewText: "ডেলিভারি",
  pickupFromText: "{address} থেকে সংগ্রহ করুন",
  saleOfferGetText: "{item} {quantity}টি কিনলে এটি {benefit}",
  saleOfferGetSpendText: "{item}-এ {amount} কিনলে এটি {benefit}",
  orderReceiptNoteText: "আপনার নোট",
  phoneIntlInvalidText: "কান্ট্রি কোডসহ সঠিক ফোন নম্বর লিখুন।",
  deliveryFeeChangedText: "ডেলিভারি চার্জ {old} থেকে {new} হয়েছে। মোট টাকা দেখে অর্ডার করুন।",
  deliveryOptionReplacedText: "{old} এখানে আর পাওয়া যাচ্ছে না, তাই {new} বেছে নেওয়া হয়েছে। ডেলিভারি চার্জ {oldFee} থেকে {newFee}। মোট টাকা দেখুন।",
  deliveryOptionReplacedSameFeeText: "{old} এই ঠিকানায় আর পাওয়া যাচ্ছে না, তাই {new} ({fee}) বেছে নেওয়া হয়েছে। মোট টাকা দেখে অর্ডার করুন।",
  deliveryOptionGoneText: "{old} এই ঠিকানায় আর পাওয়া যাচ্ছে না। অন্য একটি ডেলিভারি অপশন বেছে নিন।",
  freeDeliveryProgressText: "ফ্রি ডেলিভারির জন্য আরও {amount} যোগ করুন।",
  discountNeedsDeliveryText: "{code} ব্যবহার করতে শহর ও থানা বেছে নিন।",
  discountOneDeliveryText: "একটি ডেলিভারি ডিসকাউন্টই ব্যবহার করা যায়। {other} ইতিমধ্যে ডেলিভারিতে প্রযোজ্য।",
  freeOverText: "{amount}-এর বেশি কিনলে ফ্রি",
  chooseAddressForDeliveryText: "ডেলিভারি অপশন দেখতে শহর ও থানা বেছে নিন।",
  noDeliveryToAddressText: "এই ঠিকানায় এখনো আমরা ডেলিভারি করি না।",
  deliveryOptionsFailedText: "ডেলিভারি অপশন লোড করা যায়নি। ইন্টারনেট সংযোগ দেখে আবার চেষ্টা করুন।",
  orderAlreadyPlacedText: "এই অর্ডারটি আগেই দেওয়া হয়েছে।",
  viewOrderText: "অর্ডার দেখুন",
  addToCartText: "কার্টে যোগ করুন",
  buyNowText: "এখনই কিনুন",
  chooseOptionText: "{option} বেছে নিন",
  fromPriceText: "{price} থেকে শুরু",
  quantityLabelText: "পরিমাণ",
  quantityLimitText: "একবারে সর্বোচ্চ {count}টি কেনা যাবে।",
  saleOfferText: "{quantity}টি কিনলে {item} {benefit}",
  saleOfferSpendText: "{amount} কেনাকাটায় {item} {benefit}",
  freeBenefitText: "ফ্রি",
  percentBenefitText: "{percent}% ছাড়ে",
  orderStatusTitleText: "অর্ডার {orderNumber}",
  orderTrackingUpdatesText: "আপডেট",
  orderTrackingStepDoneText: "সম্পন্ন",
  orderTrackingIdText: "ট্র্যাকিং আইডি",
  orderTrackWithCourierText: "কুরিয়ারের সাইটে ট্র্যাক করুন",
  deliveryMethodLegendText: "ডেলিভারি পদ্ধতি",
  deliveryModeShipText: "হোম ডেলিভারি",
  deliveryModePickupText: "দোকান থেকে সংগ্রহ",
  pickupLocationLabel: "সংগ্রহের স্থান বেছে নিন",
  pickupLocationRequiredText: "একটি সংগ্রহের স্থান বেছে নিন।",
  pickupHoursText: "খোলা থাকে {hours}",
  noDeliveryNeededText: "ডেলিভারির প্রয়োজন নেই — আপডেট আপনার ফোনে পাঠানো হবে।",
  pickupReviewText: "সংগ্রহ করবেন",
  payAtPickupText: "অর্ডার সংগ্রহের সময় মূল্য পরিশোধ করুন",
  payAtServiceText: "সেবা শেষ হলে মূল্য পরিশোধ করুন",
  editLineText: "সম্পাদনা",
  editLineLabelText: "{item} সম্পাদনা করুন",
  updateCartItemText: "কার্ট আপডেট করুন",
  customizationRequiredText: "{field} লিখুন।",
  customizationRequiredChoiceText: "{field} বেছে নিন।",
  customizationRequiredCheckText: "এগিয়ে যেতে {field} টিক দিন।",
  customizationTooLongText: "সর্বোচ্চ {max} অক্ষর লিখুন।",
  customizationCounterText: "{count}/{max}",
  customizationSurchargeText: "+{price}",
  customizationOptionalText: "ঐচ্ছিক",
  customizationChoosePlaceholderText: "বেছে নিন…",
  customizationUnavailableText: "এই পণ্যটি এখন অর্ডার করা যাচ্ছে না।",
  customizationNeededText: "নিচে আপনার তথ্য দিন, তারপর কার্টে যোগ করুন।",
  customizationInvalidText: "আপনার দেওয়া কিছু তথ্য গ্রহণ করা যাচ্ছে না। নিচে দেখে নিন, তারপর কার্টে যোগ করুন।",
  pickupAvailableText: "দোকান থেকে সংগ্রহ করা যাবে",
  noDeliveryNeededBadgeText: "ডেলিভারির প্রয়োজন নেই",
  orderLineGroupShipText: "ডেলিভারি",
  orderLineGroupPickupText: "সংগ্রহ",
  orderLineGroupServiceText: "সেবা",
  orderLineGroupDigitalText: "ডিজিটাল পণ্য",
  orderLineGroupGiftCardText: "গিফট কার্ড",
  orderLinePreparingText: "প্রস্তুত হচ্ছে",
  orderLineSentText: "পাঠানো হয়েছে",
  orderLineDeliveredText: "ডেলিভারি হয়েছে",
  orderLineReadyForPickupText: "সংগ্রহের জন্য প্রস্তুত",
  orderLinePickedUpText: "সংগ্রহ করা হয়েছে",
  orderLineServiceDoneText: "সেবা সম্পন্ন",
  orderLineFulfilledCountText: "{total}টির মধ্যে {done}টি",
  orderPickupHeadingText: "সংগ্রহ",
  orderPickupAddressText: "{address} থেকে সংগ্রহ করুন",
  orderPickupReadyText: "{address}-এ সংগ্রহের জন্য প্রস্তুত",
  orderPickupNotReadyText: "অর্ডার সংগ্রহের জন্য প্রস্তুত হলে আমরা জানাব।",
  orderPickupHoursLabelText: "সময়",
  orderNoDeliveryText: "ডেলিভারির প্রয়োজন নেই",
  orderReceiptPickedUpTitleText: "অর্ডার সংগ্রহ করা হয়েছে",
  orderReceiptPickedUpMessageText: "অর্ডার #{orderId} সংগ্রহ করা হয়েছে।",
  orderReceiptFulfilledMessageText: "অর্ডার #{orderId} সম্পন্ন হয়েছে।",
  giftCardTitleText: "গিফট কার্ড",
  giftCardCodeLabelText: "গিফট কার্ডের কোড",
  giftCardApplyText: "প্রয়োগ করুন",
  giftCardApplyingText: "প্রয়োগ করা হচ্ছে…",
  giftCardRemoveText: "গিফট কার্ড {card} সরান",
  giftCardAppliedText: "গিফট কার্ড {card} যোগ হয়েছে।",
  giftCardRemovedText: "গিফট কার্ড {card} সরানো হয়েছে।",
  giftCardEnterCodeText: "গিফট কার্ডের ১৬ অক্ষরের কোডটি লিখুন।",
  giftCardUnusableText: "এই গিফট কার্ডটি ব্যবহার করা যাচ্ছে না।",
  giftCardDuplicateText: "এই গিফট কার্ডটি আগেই যোগ করা হয়েছে।",
  giftCardNotNeededText: "আপনার অন্য গিফট কার্ডেই পুরো অর্ডারের দাম পরিশোধ হচ্ছে, তাই এটি ব্যবহার করা হয়নি।",
  giftCardLimitText: "একটি অর্ডারে সর্বোচ্চ ৫টি গিফট কার্ড ব্যবহার করা যায়।",
  giftCardChangedText: "আপনার গিফট কার্ডের ব্যালেন্স বদলে গেছে; দেখে নিয়ে আবার অর্ডার করুন।",
  giftCardRateLimitedText: "অনেকবার চেষ্টা করা হয়েছে। এক মিনিট অপেক্ষা করে আবার চেষ্টা করুন।",
  giftCardUnavailableText: "এই মুহূর্তে গিফট কার্ড ব্যবহার করা যাচ্ছে না। পরে আবার চেষ্টা করুন।",
  giftCardLineText: "গিফট কার্ড {card}",
  amountDueText: "পরিশোধযোগ্য টাকা",
  paidWithGiftCardText: "গিফট কার্ডে পরিশোধিত",
  paidWithGiftCardDescriptionText: "আপনার গিফট কার্ডেই পুরো অর্ডারের দাম পরিশোধ হচ্ছে।",
  giftCardPayOnDeliveryText: "অর্ডার পাওয়ার সময় {amount} পরিশোধ করুন",
  giftCardCheckoutStepText: "গিফট কার্ড আছে? পেমেন্ট ধাপে ব্যবহার করুন",
};

export const CHECKOUT_LANGUAGE_KEYS = /* @__PURE__ */ Object.freeze(
  /* @__PURE__ */ Object.keys(ENGLISH_CHECKOUT_LANGUAGE_DATA) as CheckoutLanguageKey[],
);

/**
 * The checkout-language copy the product page uses, delivered with the
 * layout (`storefrontCopy`) so merchant edits reach cached product pages
 * without a second read: buy buttons and offers, buyer inputs (Wave A §3)
 * and the fulfilment facts beside the buy box. One list for the core
 * resolver, the API contract and the storefront type.
 */
export const PRODUCT_PAGE_COPY_KEYS = [
  "addToCartText",
  "buyNowText",
  "unavailableText",
  "chooseOptionText",
  "fromPriceText",
  "quantityLabelText",
  "quantityLimitText",
  "saleOfferText",
  "saleOfferSpendText",
  "saleOfferGetText",
  "saleOfferGetSpendText",
  "freeBenefitText",
  "percentBenefitText",
  "customizationRequiredText",
  "customizationRequiredChoiceText",
  "customizationRequiredCheckText",
  "customizationTooLongText",
  "customizationCounterText",
  "customizationSurchargeText",
  "customizationOptionalText",
  "customizationChoosePlaceholderText",
  "customizationUnavailableText",
  "customizationNeededText",
  "customizationInvalidText",
  "updateCartItemText",
  "pickupAvailableText",
  "noDeliveryNeededBadgeText",
  "payAtServiceText",
] as const satisfies readonly CheckoutLanguageKey[];

export type ProductPageCopyKey = (typeof PRODUCT_PAGE_COPY_KEYS)[number];
export type ProductPageCopy = Pick<CheckoutLanguageData, ProductPageCopyKey> & {
  /** Base code of the active checkout language ("en", "bn"). */
  languageCode: string;
};

/** The product page's copy from a resolved checkout language. */
export function pickProductPageCopy(code: unknown, copy: CheckoutLanguageData): ProductPageCopy {
  const picked = Object.fromEntries(PRODUCT_PAGE_COPY_KEYS.map((key) => [key, copy[key]])) as Pick<
    CheckoutLanguageData,
    ProductPageCopyKey
  >;
  return { languageCode: checkoutLanguageBaseCode(code), ...picked };
}

export const CHECKOUT_LANGUAGE_LONG_TEXT_KEYS =/* @__PURE__ */ new Set<CheckoutLanguageKey>([
  "termsText",
  "emptyCartDescriptionText",
  "paymentRecoveryMessageText",
  "paymentRecoveryIntroText",
  "paymentRecoveryUnavailableText",
  "paymentRecoveryMissingOrderText",
  "paymentRecoveryCodeSentText",
  "paymentRecoveryVerificationFailedText",
  "orderReceiptBrowserRecoveryMessageText",
  "orderReceiptBrowserOnlyMessageText",
  "orderReceiptPrivateUnavailableMessageText",
  "orderReceiptExpiredMessageText",
  "orderReceiptUnavailableMessageText",
  "orderReceiptDeliveryNotRecordedText",
  "orderReceiptStripePaymentMethodRequiredText",
  "orderReceiptStripeAuthenticationRequiredText",
  "orderReceiptConfirmationDelayedText",
  "orderReceiptCardLoadFailedText",
  "orderReceiptPaymentIssueMessageText",
  "orderReceiptPaymentPendingMessageText",
  "orderReceiptConfirmedMessageText",
  "orderReceiptProcessingMessageText",
  "orderReceiptShippedMessageText",
  "orderReceiptDeliveredMessageText",
  "orderReceiptPickedUpMessageText",
  "orderReceiptFulfilledMessageText",
  "noDeliveryNeededText",
  "orderPickupNotReadyText",
  "orderReceiptCompletedMessageText",
  "orderReceiptCancelledMessageText",
  "orderReceiptRefundedMessageText",
  "orderReceiptReturnedMessageText",
  "orderReceiptPartiallyRefundedMessageText",
  "orderReceiptUpdatedMessageText",
  "orderReceiptPlacedMessageText",
  "orderReceiptSaveAccountHelpText",
  "orderReceiptSavedText",
  "orderReceiptRequestSubmittedText",
  "orderReceiptRequestApprovedText",
  "orderReceiptRequestRejectedText",
  "orderReceiptRequestSettledText",
  "orderReceiptMissingProofText",
  "checkoutUnavailableMessage",
  "existingCheckoutMessage",
  "noScriptText",
  "accountUnavailableText",
  "openingPaymentOptionsMessage",
  "checkoutDetailsMissingText",
  "checkoutDetailsUnreadableText",
  "sessionExpiredText",
  "noPaymentMethodsText",
  "paymentMethodUnavailableMessage",
  "processingPaymentMessage",
  "placingOrderMessage",
  "openingSecurePaymentMessage",
  "unsafeRedirectText",
  "totalVerificationFailedText",
]);

const CHECKOUT_LANGUAGE_PRESETS: Record<string, CheckoutLanguageData> = {
  en: ENGLISH_CHECKOUT_LANGUAGE_DATA,
  bn: BANGLA_CHECKOUT_LANGUAGE_DATA,
};

function parseStoredLanguageData(value: unknown): Record<string, unknown> {
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }
  if (typeof value !== "string") return {};
  try {
    const parsed = JSON.parse(value) as unknown;
    return parsed && typeof parsed === "object" && !Array.isArray(parsed)
      ? (parsed as Record<string, unknown>)
      : {};
  } catch {
    return {};
  }
}

export function checkoutLanguageBaseCode(code: unknown): string {
  if (typeof code !== "string") return "en";
  return code.trim().toLowerCase().split(/[-_]/, 1)[0] || "en";
}

export function getCheckoutLanguagePreset(code: unknown): CheckoutLanguageData {
  const preset = CHECKOUT_LANGUAGE_PRESETS[checkoutLanguageBaseCode(code)];
  return { ...(preset ?? ENGLISH_CHECKOUT_LANGUAGE_DATA) };
}

function comparableDefaultText(value: string): string {
  return value
    .trim()
    .toLocaleLowerCase("en")
    .replaceAll("…", "...")
    .replace(/[.!]+$/u, "")
    .replace(/\s+/g, " ");
}

/**
 * Earlier built-in wording. A saved language still holding one of these was
 * never edited by the merchant, so it follows the current default instead.
 */
const RETIRED_DEFAULT_TEXT: Partial<Record<CheckoutLanguageKey, readonly string[]>> = {
  deliveryOptionReplacedText: ["{old} is no longer available for this address, so {new} is selected. Check your total, then place your order.", "{old} এই ঠিকানায় আর পাওয়া যাচ্ছে না, তাই {new} বেছে নেওয়া হয়েছে। মোট টাকা দেখে অর্ডার করুন।"],
  discountMinimumQuantityText: ["Add {count} more to use {code}."],
  addToCartText: ["Add to Cart"],
  buyNowText: ["Buy Now"],
  chooseAddressForDeliveryText: ["Choose your city and zone to see delivery options.", "ডেলিভারি অপশন দেখতে শহর ও জোন বেছে নিন।"],
  cityZoneRequiredText: ["Choose a city and zone to continue.", "এগিয়ে যেতে শহর ও এলাকা বেছে নিন।"],
  customerPhoneHelp: ["Enter your phone number with country code", "কান্ট্রি কোডসহ আপনার ফোন নম্বর লিখুন"],
  customerPhonePlaceholder: ["Phone number", "ফোন নম্বর"],
  discountAppliedText: ["Discount applied successfully!", "ডিসকাউন্ট সফলভাবে প্রয়োগ হয়েছে!"],
  enterDiscountCodeText: ["Enter a discount code", "একটি ডিসকাউন্ট কোড লিখুন"],
  invalidDiscountCodeText: ["Invalid discount code", "ডিসকাউন্ট কোডটি সঠিক নয়"],
  noPaymentMethodsText: ["No available payment method can accept this order total. Return to your cart or contact the store.", "এই অর্ডারের মোট টাকার জন্য কোনো পেমেন্ট পদ্ধতি পাওয়া যাচ্ছে না। কার্টে ফিরুন অথবা দোকানের সঙ্গে যোগাযোগ করুন।"],
  orderReceiptExpiredMessageText: ["This private receipt is no longer available in this browser. Sign in to check account orders, or contact the store if you still need help.", "এই ব্রাউজারে ব্যক্তিগত রসিদটি আর পাওয়া যাচ্ছে না। অ্যাকাউন্টের অর্ডার দেখতে সাইন ইন করুন অথবা সাহায্যের জন্য দোকানের সঙ্গে যোগাযোগ করুন।"],
  orderReceiptPaymentIssueMessageText: ["Order #{orderId} is saved. Retry payment below instead of placing another order.", "অর্ডার #{orderId} সংরক্ষিত আছে। নতুন অর্ডার না করে নিচে থেকে আবার পেমেন্ট করুন।"],
  orderReceiptPaymentPendingMessageText: ["Order #{orderId} is saved. Do not place it again while we check the payment.", "অর্ডার #{orderId} সংরক্ষিত আছে। পেমেন্ট যাচাই করার সময় অর্ডারটি আবার দেবেন না।"],
  orderReceiptPaymentPendingTitleText: ["Confirming payment", "পেমেন্ট নিশ্চিত করা হচ্ছে"],
  orderReceiptRequestRejectedText: ["The store could not accept this request. Contact the store if you still need help.", "দোকান অনুরোধটি গ্রহণ করতে পারেনি। আরও সাহায্য লাগলে দোকানের সঙ্গে যোগাযোগ করুন।"],
  orderReceiptRequestSettledText: ["This request is settled. Contact the store if you still need help.", "অনুরোধটি নিষ্পত্তি হয়েছে। আরও সাহায্য লাগলে দোকানের সঙ্গে যোগাযোগ করুন।"],
  paymentRecoveryCodesUnavailableText: ["We can't send codes right now. Contact the store to finish paying.", "এই মুহূর্তে কোড পাঠানো যাচ্ছে না। পেমেন্ট সম্পন্ন করতে দোকানের সাথে যোগাযোগ করুন।"],
  paymentRecoveryUnavailableText: ["Payment recovery is not available right now. Sign in to check account orders or contact the store.", "এই মুহূর্তে পেমেন্ট পুনরুদ্ধার করা যাচ্ছে না। অ্যাকাউন্টের অর্ডার দেখতে সাইন ইন করুন অথবা দোকানের সঙ্গে যোগাযোগ করুন।"],
  phoneInvalidText: ["Enter a valid phone number.", "সঠিক ফোন নম্বর লিখুন।", "Enter an 11-digit mobile number starting with 01.", "০১ দিয়ে শুরু ১১ সংখ্যার মোবাইল নম্বর লিখুন।"],
  selectZonePlaceholder: ["Select a zone", "এলাকা বেছে নিন"],
  taxVerificationFailedText: ["We could not verify tax. Change the destination or try again.", "কর যাচাই করা যায়নি। গন্তব্য পরিবর্তন করুন অথবা আবার চেষ্টা করুন।"],
  termsText: ["By placing this order, you agree to our Terms of Service and Privacy Policy.", "অর্ডারটি নিশ্চিত করলে আপনি আমাদের পরিষেবার শর্তাবলি ও গোপনীয়তা নীতিতে সম্মত হচ্ছেন।"],
  trackOrderUnavailableText: ["Order tracking isn't available right now. Contact the store.", "এই মুহূর্তে অর্ডার ট্র্যাক করা যাচ্ছে না। দোকানের সাথে যোগাযোগ করুন।"],
  unavailableText: ["Unavailable", "পাওয়া যাচ্ছে না"],
  zoneLabel: ["Zone", "এলাকা"],
  zoneRequiredText: ["Choose a zone to continue.", "এগিয়ে যেতে একটি এলাকা বেছে নিন।"],
  zoneSearchPlaceholder: ["Type to find your zone", "জোন খুঁজতে লিখুন"],
  zonesLoadFailedText: ["Could not load zones. Try again", "এলাকাগুলো লোড করা যায়নি। আবার চেষ্টা করুন"],
};

/**
 * Stored values are merchant overrides. Older records persisted the English
 * defaults even for non-English locale codes, so an unchanged English value
 * must not shadow a built-in locale preset. Genuine custom values are kept.
 */
export function resolveCheckoutLanguageData(
  code: unknown,
  storedValue: unknown,
): CheckoutLanguageData {
  const baseCode = checkoutLanguageBaseCode(code);
  const resolved = getCheckoutLanguagePreset(baseCode);
  const stored = parseStoredLanguageData(storedValue);

  for (const key of CHECKOUT_LANGUAGE_KEYS) {
    const value = stored[key];
    if (typeof value !== "string" || value.trim() === "") continue;
    if (RETIRED_DEFAULT_TEXT[key]?.some((retired) => comparableDefaultText(retired) === comparableDefaultText(value))) {
      continue;
    }
    // "Phone Number" saved from an older default is the default in sentence case.
    if (comparableDefaultText(value) === comparableDefaultText(resolved[key])) continue;
    if (
      baseCode !== "en" &&
      comparableDefaultText(value) ===
        comparableDefaultText(ENGLISH_CHECKOUT_LANGUAGE_DATA[key])
    ) {
      continue;
    }
    resolved[key] = value;
  }

  return resolved;
}

// Separate module so browser bundles can format copy without the presets.
export { formatCheckoutLanguageText } from "./checkout-language-format";
