export const ENGLISH_CHECKOUT_LANGUAGE_DATA = {
  pageTitle: "Cart & Checkout",
  checkoutSectionTitle: "Checkout information",
  cartSectionTitle: "Shopping cart",
  customerNameLabel: "Full name",
  customerNamePlaceholder: "Enter your full name",
  customerPhoneLabel: "Phone number",
  customerPhonePlaceholder: "Phone number",
  customerPhoneHelp: "Enter your phone number with country code",
  phoneCountryLabelText: "Phone number country",
  customerEmailLabel: "Email (optional)",
  customerEmailPlaceholder: "Enter your email address",
  shippingAddressLabel: "Delivery address",
  shippingAddressPlaceholder: "Enter your full delivery address",
  cityLabel: "City",
  zoneLabel: "Zone",
  areaLabel: "Area (optional)",
  shippingMethodLabel: "Choose delivery option",
  orderNotesLabel: "Order notes (optional)",
  orderNotesPlaceholder: "Any special instructions for your order?",
  continueShoppingText: "Continue shopping",
  subtotalText: "Subtotal",
  shippingText: "Shipping",
  discountText: "Discount",
  totalText: "Total",
  discountCodePlaceholder: "Discount code",
  applyDiscountText: "Apply",
  removeDiscountText: "Remove",
  placeOrderText: "Place order",
  processingText: "Processing…",
  emptyCartText: "Your cart is empty",
  emptyCartDescriptionText: "You haven't added anything to your cart yet.",
  paymentRecoveryMessageText:
    "Your order was created before payment opened. Review its payment status before starting another checkout.",
  viewPaymentStatusText: "View payment status",
  paymentRecoveryPageTitleText: "Payment recovery",
  paymentRecoveryEyebrowText: "Hosted payment recovery",
  paymentRecoveryHeadingText: "Verify this order",
  paymentRecoveryIntroText:
    "This link does not open private receipt details by itself. Verify the buyer contact to continue payment from this browser.",
  paymentRecoverySmsChannelText: "SMS to order phone",
  paymentRecoveryWhatsappChannelText: "WhatsApp to order phone",
  paymentRecoveryEmailChannelText: "Email on order",
  paymentRecoveryOrderReferenceText: "Order reference",
  paymentRecoveryVerificationChannelText: "Verification channel",
  paymentRecoverySendCodeText: "Send code",
  paymentRecoveryVerificationCodeText: "Verification code",
  paymentRecoveryContinueToReceiptText: "Continue to receipt",
  paymentRecoveryUnavailableText:
    "Payment recovery is not available right now. Sign in to check account orders or contact the store.",
  paymentRecoveryMissingOrderText:
    "This recovery link is missing an order reference. Ask the store to send a fresh payment recovery link.",
  paymentRecoveryViewAccountOrdersText: "View account orders",
  paymentRecoverySendingCodeText: "Sending verification code…",
  paymentRecoveryCodeSentText:
    "If this order is eligible for payment recovery, a verification code will be sent to the buyer contact.",
  paymentRecoverySendFailedText: "Could not send a verification code. Please try again.",
  paymentRecoveryEnterCodeText: "Enter the verification code to continue.",
  paymentRecoveryVerifyingCodeText: "Verifying code…",
  paymentRecoveryVerificationFailedText:
    "Verification failed. Please request a new code and try again.",
  paymentRecoveryRateLimitedText:
    "Too many verification attempts. Wait a moment and try again.",
  orderReceiptPageTitleText: "Order receipt",
  orderReceiptMissingTitleText: "We could not open this receipt",
  orderReceiptBrowserRecoveryMessageText:
    "This receipt can only be opened in the browser used at checkout. Verify your contact to recover payment.",
  orderReceiptBrowserOnlyMessageText:
    "This receipt can only be opened in the browser used at checkout. Sign in to view your orders, or return to the checkout browser.",
  orderReceiptUnavailableTitleText: "Receipt temporarily unavailable",
  orderReceiptPrivateUnavailableMessageText:
    "We could not load this receipt from the private order link. If the order was placed, it may still appear in your account history.",
  orderReceiptExpiredTitleText: "Receipt access expired",
  orderReceiptExpiredMessageText:
    "This private receipt is no longer available in this browser. Sign in to check account orders, or contact the store if you still need help.",
  orderReceiptUnavailableMessageText:
    "We could not load this receipt right now. Please retry or check your account order history.",
  orderReceiptReferenceText: "Reference",
  orderReceiptVerifyRecoveryText: "Verify payment recovery",
  orderReceiptRetryText: "Retry receipt",
  orderReceiptOrderDetailsText: "Order details",
  orderReceiptOrderNumberText: "Order number",
  orderReceiptPlacedText: "Placed",
  orderReceiptStatusText: "Status",
  orderReceiptPaymentText: "Payment",
  orderReceiptPaymentStatusText: "Payment status",
  orderReceiptDeliveryText: "Delivery",
  orderReceiptDeliveryWithMethodText: "Delivery · {method}",
  orderReceiptDeliveryNotRecordedText: "Delivery method was not recorded for this order.",
  orderReceiptFeeWaivedText: "{fee} fee waived",
  orderReceiptPaidText: "Paid",
  orderReceiptBalanceDueText: "Balance due",
  orderReceiptDeliveryDetailsText: "Delivery details",
  orderReceiptItemsText: "Items",
  orderReceiptProductUnavailableText: "Product unavailable",
  orderReceiptQuantityText: "Quantity: {quantity}",
  orderReceiptItemDiscountText: "Item discount: −{amount}",
  orderReceiptTaxIncludedText: "{label} included: {amount}",
  orderReceiptTaxAddedText: "{label} added: {amount}",
  orderReceiptLineTotalText: "Line total",
  orderReceiptPrintText: "Print receipt",
  orderReceiptCheckingPaymentText: "Checking payment status…",
  orderReceiptCheckPaymentText: "Check payment status",
  orderReceiptConfirmationDelayedText:
    "Confirmation is taking longer than usual. You can safely leave this receipt and return later.",
  orderReceiptStatusUpdatedText: "Payment status updated. Refreshing your receipt…",
  orderReceiptRetryWithProviderText: "Retry payment with {provider}",
  orderReceiptRetryPaymentText: "Retry payment",
  orderReceiptOpeningPaymentText: "Opening payment…",
  orderReceiptRetryUnavailableText: "Payment retry is unavailable for this order.",
  orderReceiptCardUnavailableText: "Card payment is unavailable for this order.",
  orderReceiptLoadingCardText: "Loading secure card fields…",
  orderReceiptEnterCardText: "Enter your card details to continue with this order.",
  orderReceiptCardLoadFailedText: "Could not load the secure card form. Please try another payment method.",
  orderReceiptPaymentProcessingRetryText: "Payment is still processing. Retrying in {seconds}s…",
  orderReceiptStartPaymentFailedText: "Could not start payment. Please try again.",
  orderReceiptGatewayRedirectFailedText: "The payment service did not return a safe payment page.",
  orderReceiptConfirmingCardText: "Confirming card payment for your existing order…",
  orderReceiptCardPaymentFailedText: "Card payment could not be completed. Your order is still saved.",
  orderReceiptExistingOrderCardHelpText:
    "Your existing order will be updated. This will not create another order.",
  orderReceiptPaymentIssueTitleText: "Payment not completed",
  orderReceiptPaymentIssueMessageText:
    "Order #{orderId} is saved. Choose a payment method.",
  orderReceiptPaymentPendingTitleText: "Payment pending",
  orderReceiptPaymentPendingMessageText:
    "Order #{orderId} is saved.",
  orderReceiptConfirmedTitleText: "Order confirmed",
  orderReceiptConfirmedMessageText: "Order #{orderId} is confirmed and being prepared.",
  orderReceiptProcessingTitleText: "Order processing",
  orderReceiptProcessingMessageText: "Order #{orderId} is being prepared.",
  orderReceiptShippedTitleText: "Order shipped",
  orderReceiptShippedMessageText: "Order #{orderId} is on the way.",
  orderReceiptDeliveredTitleText: "Order delivered",
  orderReceiptDeliveredMessageText: "Order #{orderId} has been delivered.",
  orderReceiptCompletedTitleText: "Order completed",
  orderReceiptCompletedMessageText: "Order #{orderId} is complete.",
  orderReceiptCancelledTitleText: "Order cancelled",
  orderReceiptCancelledMessageText: "Order #{orderId} was cancelled.",
  orderReceiptRefundedTitleText: "Order refunded",
  orderReceiptRefundedMessageText: "The refund for order #{orderId} has been recorded.",
  orderReceiptReturnedTitleText: "Order returned",
  orderReceiptReturnedMessageText: "The return for order #{orderId} has been recorded.",
  orderReceiptPartiallyRefundedTitleText: "Order partially refunded",
  orderReceiptPartiallyRefundedMessageText:
    "A partial refund for order #{orderId} has been recorded.",
  orderReceiptUpdatedTitleText: "Order updated",
  orderReceiptUpdatedMessageText: "Order #{orderId} has been updated.",
  orderReceiptPlacedTitleText: "Order placed",
  orderReceiptPlacedMessageText: "We received order #{orderId}.",
  orderReceiptStatusNotAvailableText: "Not available",
  orderReceiptStatusPendingText: "Pending",
  orderReceiptStatusIncompleteText: "Incomplete",
  orderReceiptStatusConfirmedText: "Confirmed",
  orderReceiptStatusProcessingText: "Processing",
  orderReceiptStatusShippedText: "Shipped",
  orderReceiptStatusDeliveredText: "Delivered",
  orderReceiptStatusCompletedText: "Completed",
  orderReceiptStatusCancelledText: "Cancelled",
  orderReceiptStatusRefundedText: "Refunded",
  orderReceiptStatusReturnedText: "Returned",
  orderReceiptStatusPartiallyRefundedText: "Partially refunded",
  orderReceiptStatusFailedText: "Failed",
  orderReceiptPaymentStatusPaidText: "Paid",
  orderReceiptPaymentStatusPartialText: "Partially paid",
  orderReceiptPaymentStatusUnpaidText: "Unpaid",
  orderReceiptPaymentStatusNoPaymentDueText: "No payment due",
  orderReceiptPaymentMethodCardText: "Card (Stripe)",
  orderReceiptPaymentMethodSslcommerzText: "Online payment (SSLCommerz)",
  orderReceiptPaymentMethodPolarText: "Online payment (Polar)",
  orderReceiptSaveAccountTitleText: "Save this order to your account",
  orderReceiptSavedAccountTitleText: "Order saved to your account",
  orderReceiptSaveAccountHelpText:
    "Create an account with the phone saved on this order, or sign in with a matching phone or email.",
  orderReceiptViewInAccountText: "View in account",
  orderReceiptSaveToAccountText: "Save to my account",
  orderReceiptSavingText: "Saving…",
  orderReceiptCreateAccountText: "Create account",
  orderReceiptSignInText: "Sign in",
  orderReceiptMissingReferenceText: "This receipt is missing its order reference.",
  orderReceiptSavingToAccountText: "Saving this order to your account…",
  orderReceiptSaveFailedText: "This order could not be saved. Please try again.",
  orderReceiptAlreadySavedText: "This order is already in your account.",
  orderReceiptSavedText: "Order saved. You can now track it from any signed-in device.",
  orderReceiptCreateAccountPromptText: "Create your account with the phone number saved on this order.",
  orderReceiptSignInPromptText: "Sign in with a phone number or email that matches this order.",
  orderReceiptHelpText: "Need help?",
  orderReceiptCancelRequestActionText: "Request cancellation",
  orderReceiptReturnRequestActionText: "Request return",
  orderReceiptRefundRequestActionText: "Request refund",
  orderReceiptRequestSubmittedText:
    "The store received your request and will review it before making changes.",
  orderReceiptRequestUnderReviewText: "The store team is reviewing this request.",
  orderReceiptRequestApprovedText: "The store accepted this request. Check the order status for progress.",
  orderReceiptRequestRejectedText:
    "The store could not accept this request. Contact the store if you still need help.",
  orderReceiptRequestWithdrawnText: "This request was withdrawn.",
  orderReceiptRequestCompletedText: "This request is complete.",
  orderReceiptRequestSettledText: "This request is settled. Contact the store if you still need help.",
  orderReceiptRequestStatusSubmittedText: "Submitted",
  orderReceiptRequestStatusUnderReviewText: "Under review",
  orderReceiptRequestStatusApprovedText: "Approved",
  orderReceiptRequestStatusRejectedText: "Rejected",
  orderReceiptRequestStatusWithdrawnText: "Withdrawn",
  orderReceiptRequestStatusCompletedText: "Completed",
  orderReceiptRequestLabelText: "{action} · {status}",
  orderReceiptReasonText: "Reason",
  orderReceiptReasonAriaText: "Support request reason",
  orderReceiptReasonPlaceholderText: "Why are you requesting this?",
  orderReceiptCancelText: "Cancel",
  orderReceiptSendRequestText: "Send request",
  orderReceiptMissingProofText: "This receipt is missing the browser proof needed to send a request.",
  orderReceiptReasonRequiredText: "Add a short reason before sending the request.",
  orderReceiptSupportFailedText: "Support request failed. Please try again.",
  orderReceiptRequestSentText: "Request sent. The store team can now review it from the order.",
  orderReceiptSupportUnavailableText: "Support requests are not available for this order right now.",
  termsText:
    "By placing this order, you agree to our Terms of Service and Privacy Policy.",
  processingOrderTitle: "Processing your order",
  processingOrderMessage: "Please wait while we process your order.",
  requiredFieldIndicator: "*",
  homeAriaLabel: "Go to homepage",
  secureCheckoutText: "Secure checkout",
  checkoutProgressLabel: "Checkout progress",
  informationStepText: "Information",
  paymentStepText: "Payment",
  confirmationStepText: "Confirmation",
  estimatedTotalText: "Estimated total",
  taxText: "Tax",
  freeText: "Free",
  calculatingText: "Calculating…",
  unavailableText: "Unavailable",
  taxVerificationFailedText: "We could not verify tax. Change the destination or try again.",
  cartItemChangedText: "One cart item needs attention before checkout.",
  cartAvailabilityFailedText: "Could not verify cart availability. Refresh and try again.",
  cartItemsChangedText: "{count} cart items changed before payment. Review them before checkout.",
  oneCartItemChangedText: "One cart item changed before payment. Please review it before checkout.",
  cartAvailabilityReviewText: "Could not verify cart availability. Review your cart before checkout.",
  orderSummaryText: "Order summary",
  paymentPageTitle: "Payment",
  paymentMethodsText: "Payment methods",
  paymentMethodText: "Payment method",
  loadingPaymentMethodsText: "Loading payment methods",
  testModeNoticeText: "Test mode — no real payments will be processed.",
  cardDetailsText: "Card details",
  selectPaymentMethodText: "Select a payment method",
  continueToPaymentText: "Continue to payment",
  checkoutUnavailableText: "Checkout unavailable",
  checkoutUnavailableMessage:
    "Checkout is temporarily unavailable. Please try again shortly.",
  errorPrefixText: "Error:",
  successPrefixText: "Success!",
  existingCheckoutTitle: "You already have a checkout in progress",
  existingCheckoutMessage:
    "Order {orderId} is waiting for payment. Review it before starting another checkout.",
  reviewExistingCheckoutText: "Review existing checkout",
  signInToCheckoutText: "Sign in to checkout",
  signInPromptText: "Already have an account? Sign in for faster checkout",
  noScriptText: "JavaScript is required to update your cart before checkout.",
  selectCityPlaceholder: "Select a city",
  selectZonePlaceholder: "Select a zone",
  selectAreaPlaceholder: "Select an area (optional)",
  loadingText: "Loading…",
  zonesLoadFailedText: "Could not load zones. Try again",
  areasLoadFailedText: "Could not load areas. Try again",
  noShippingMethodsText: "No shipping methods are available at this time.",
  waivedShippingFeeText: "Normally {fee}; waived by an item in your cart.",
  phoneRequiredText: "Enter your phone number.",
  phoneInvalidText: "Enter a valid phone number.",
  phoneCountryNotAcceptedText: "This store does not accept phone numbers from that country.",
  nameRequiredText: "Enter your full name.",
  addressRequiredText: "Enter your delivery address.",
  addressIncompleteText: "Enter a complete delivery address (at least {minimum} characters).",
  cityZoneRequiredText: "Choose a city and zone to continue.",
  zoneRequiredText: "Choose a zone to continue.",
  deliveryRequiredText: "Choose a delivery option.",
  checkingAvailableQuantityText: "Checking available quantity for {item}",
  maximumAvailableQuantityText: "Maximum available quantity reached for {item}",
  increaseQuantityText: "Increase {item} quantity",
  decreaseQuantityText: "Decrease {item} quantity",
  removeFromCartText: "Remove {item} from cart",
  cartLoadingText: "Loading your cart",
  cartAttentionText: "Some cart items need attention",
  cartEmptyErrorText: "Add items to your cart before placing an order.",
  quickBuyStorageBlockedText: "This browser blocked temporary cart storage, so the item could not be added. Allow site storage and add it again.",
  orderProcessingFailedText: "Could not process the order. Try again.",
  unexpectedErrorText: "An unexpected error occurred.",
  cartItemsNeedAttentionText: "{count} cart items need attention before checkout.",
  orderPlacedSuccessText: "Your order was placed successfully. Order ID: {orderId}",
  checkingAccountText: "Checking account…",
  accountUnavailableText: "We could not verify your account right now. Please try again.",
  checkingCartText: "Checking cart…",
  reviewCartItemsText: "Review the highlighted cart items before checkout.",
  redirectingToPaymentText: "Redirecting to payment…",
  openingPaymentOptionsTitle: "Opening payment options",
  openingPaymentOptionsMessage: "Confirming your total and available payment methods.",
  checkoutDetailsMissingText: "Checkout details were not found. Return to your cart and try again.",
  checkoutDetailsUnreadableText: "Checkout details could not be read. Return to your cart and try again.",
  returnToCartText: "Return to cart",
  quantityShortText: "Qty {quantity}",
  eachText: "each",
  includedText: "included",
  dueNowText: "Due now",
  dueOnDeliveryText: "Due on delivery",
  continueText: "Continue",
  continueAsGuestText: "Continue as guest",
  sessionExpiredText:
    "Your sign-in session expired. Your checkout details are safe. Continue as a guest, or sign in again.",
  checkoutConflictText: "This checkout was already submitted or changed in another tab. Review your cart and try again.",
  totalChangedReviewText:
    "Your order total or checkout terms changed. Review the refreshed total, then confirm the order again.",
  tooManyCheckoutAttemptsText: "Too many checkout attempts. Wait a moment and try again.",
  paymentFailedText: "Payment failed",
  noPaymentMethodsText:
    "No available payment method can accept this order total. Return to your cart or contact the store.",
  preparingPaymentText: "Preparing payment…",
  paymentMethodUnavailableText: "Payment method unavailable",
  paymentMethodUnavailableMessage: "This payment method is not available. Choose another method.",
  retryPaymentFormText: "Retry payment form",
  processingPaymentTitle: "Processing payment",
  processingPaymentMessage: "Confirming your order and payment details.",
  placingOrderTitle: "Placing your order",
  placingOrderMessage: "Confirming item availability and delivery.",
  openingSecurePaymentTitle: "Opening secure payment",
  openingSecurePaymentMessage: "You'll continue with the selected payment provider.",
  unknownPaymentMethodText: "Unknown payment method selected.",
  unsafeRedirectText: "Payment could not open because the gateway returned an unsafe redirect URL.",
  genericErrorText: "An error occurred. Please try again.",
  totalVerificationFailedText:
    "We could not verify the current taxes and order total. Return to your cart and try again.",
  totalUnavailableText: "Total unavailable",
  continueToProviderText: "Continue to {provider}",
  payAmountNowText: "Pay {amount} now",
  payAmountText: "Pay {amount}",
  providerRedirectText: "You'll be redirected to {provider} to complete your payment.",
  creditDebitCardText: "Credit or debit card",
  paySecurelyByCardText: "Pay securely by card",
  onlinePaymentText: "Pay online",
  onlinePaymentDescriptionText: "bKash, Nagad, cards and more",
  cardOrWalletText: "Card or digital wallet",
  completeWithProviderText: "Complete payment with {provider}",
  cashOnDeliveryText: "Cash on delivery",
  payOnDeliveryText: "Pay when you receive your order",
  enterDiscountCodeText: "Enter a discount code",
  removeCurrentDiscountText: "Remove the current discount first.",
  discountAppliedText: "Discount applied successfully!",
  invalidDiscountCodeText: "Invalid discount code",
  discountApplyFailedText: "Could not apply the discount. Try again.",
  discountRemovedText: "Discount removed.",
} as const;

export type CheckoutLanguageData = {
  -readonly [Key in keyof typeof ENGLISH_CHECKOUT_LANGUAGE_DATA]: string;
};

export type CheckoutLanguageKey = keyof CheckoutLanguageData;

export const BANGLA_CHECKOUT_LANGUAGE_DATA: CheckoutLanguageData = {
  pageTitle: "কার্ট ও চেকআউট",
  checkoutSectionTitle: "চেকআউটের তথ্য",
  cartSectionTitle: "শপিং কার্ট",
  customerNameLabel: "পুরো নাম",
  customerNamePlaceholder: "আপনার পুরো নাম লিখুন",
  customerPhoneLabel: "ফোন নম্বর",
  customerPhonePlaceholder: "ফোন নম্বর",
  customerPhoneHelp: "কান্ট্রি কোডসহ আপনার ফোন নম্বর লিখুন",
  phoneCountryLabelText: "ফোন নম্বরের দেশ",
  customerEmailLabel: "ইমেইল (ঐচ্ছিক)",
  customerEmailPlaceholder: "আপনার ইমেইল ঠিকানা লিখুন",
  shippingAddressLabel: "ডেলিভারির ঠিকানা",
  shippingAddressPlaceholder: "আপনার সম্পূর্ণ ডেলিভারির ঠিকানা লিখুন",
  cityLabel: "শহর",
  zoneLabel: "এলাকা",
  areaLabel: "উপ-এলাকা (ঐচ্ছিক)",
  shippingMethodLabel: "ডেলিভারি পদ্ধতি বেছে নিন",
  orderNotesLabel: "অর্ডার নোট (ঐচ্ছিক)",
  orderNotesPlaceholder: "অর্ডার সম্পর্কে বিশেষ কোনো নির্দেশনা আছে?",
  continueShoppingText: "কেনাকাটা চালিয়ে যান",
  subtotalText: "পণ্যের মোট",
  shippingText: "ডেলিভারি চার্জ",
  discountText: "ছাড়",
  totalText: "সর্বমোট",
  discountCodePlaceholder: "ডিসকাউন্ট কোড",
  applyDiscountText: "প্রয়োগ করুন",
  removeDiscountText: "সরান",
  placeOrderText: "অর্ডার করুন",
  processingText: "প্রক্রিয়া চলছে…",
  emptyCartText: "আপনার কার্ট খালি",
  emptyCartDescriptionText: "আপনি এখনো কার্টে কোনো পণ্য যোগ করেননি।",
  paymentRecoveryMessageText:
    "পেমেন্ট পেজ খোলার আগেই আপনার অর্ডারটি তৈরি হয়েছে। নতুন করে চেকআউট শুরু করার আগে পেমেন্টের অবস্থা দেখুন।",
  viewPaymentStatusText: "পেমেন্টের অবস্থা দেখুন",
  paymentRecoveryPageTitleText: "পেমেন্ট পুনরুদ্ধার",
  paymentRecoveryEyebrowText: "নিরাপদ পেমেন্ট পুনরুদ্ধার",
  paymentRecoveryHeadingText: "অর্ডারটি যাচাই করুন",
  paymentRecoveryIntroText:
    "এই লিংকটি নিজে থেকে ব্যক্তিগত রসিদের তথ্য খোলে না। এই ব্রাউজার থেকে পেমেন্ট চালিয়ে যেতে ক্রেতার যোগাযোগের মাধ্যম যাচাই করুন।",
  paymentRecoverySmsChannelText: "অর্ডারের ফোনে SMS",
  paymentRecoveryWhatsappChannelText: "অর্ডারের ফোনে WhatsApp",
  paymentRecoveryEmailChannelText: "অর্ডারের ইমেইলে",
  paymentRecoveryOrderReferenceText: "অর্ডার রেফারেন্স",
  paymentRecoveryVerificationChannelText: "যাচাইকরণের মাধ্যম",
  paymentRecoverySendCodeText: "কোড পাঠান",
  paymentRecoveryVerificationCodeText: "যাচাইকরণ কোড",
  paymentRecoveryContinueToReceiptText: "রসিদে এগিয়ে যান",
  paymentRecoveryUnavailableText:
    "এই মুহূর্তে পেমেন্ট পুনরুদ্ধার করা যাচ্ছে না। অ্যাকাউন্টের অর্ডার দেখতে সাইন ইন করুন অথবা দোকানের সঙ্গে যোগাযোগ করুন।",
  paymentRecoveryMissingOrderText:
    "এই পুনরুদ্ধার লিংকে অর্ডার রেফারেন্স নেই। দোকানের কাছে নতুন পেমেন্ট পুনরুদ্ধার লিংক চান।",
  paymentRecoveryViewAccountOrdersText: "অ্যাকাউন্টের অর্ডার দেখুন",
  paymentRecoverySendingCodeText: "যাচাইকরণ কোড পাঠানো হচ্ছে…",
  paymentRecoveryCodeSentText:
    "অর্ডারটি পেমেন্ট পুনরুদ্ধারের উপযোগী হলে ক্রেতার যোগাযোগের মাধ্যমে যাচাইকরণ কোড পাঠানো হবে।",
  paymentRecoverySendFailedText: "যাচাইকরণ কোড পাঠানো যায়নি। আবার চেষ্টা করুন।",
  paymentRecoveryEnterCodeText: "এগিয়ে যেতে যাচাইকরণ কোড লিখুন।",
  paymentRecoveryVerifyingCodeText: "কোড যাচাই করা হচ্ছে…",
  paymentRecoveryVerificationFailedText:
    "যাচাইকরণ ব্যর্থ হয়েছে। নতুন কোড নিয়ে আবার চেষ্টা করুন।",
  paymentRecoveryRateLimitedText:
    "খুব বেশি যাচাইয়ের চেষ্টা হয়েছে। কিছুক্ষণ অপেক্ষা করে আবার চেষ্টা করুন।",
  orderReceiptPageTitleText: "অর্ডারের রসিদ",
  orderReceiptMissingTitleText: "রসিদটি খোলা যায়নি",
  orderReceiptBrowserRecoveryMessageText:
    "রসিদটি শুধু চেকআউট করা ব্রাউজারেই খোলা যাবে। পেমেন্ট চালিয়ে যেতে আপনার যোগাযোগের মাধ্যম যাচাই করুন।",
  orderReceiptBrowserOnlyMessageText:
    "রসিদটি শুধু চেকআউট করা ব্রাউজারেই খোলা যাবে। অর্ডার দেখতে সাইন ইন করুন অথবা চেকআউট করা ব্রাউজারে ফিরে যান।",
  orderReceiptUnavailableTitleText: "রসিদটি সাময়িকভাবে পাওয়া যাচ্ছে না",
  orderReceiptPrivateUnavailableMessageText:
    "ব্যক্তিগত অর্ডার লিংক থেকে রসিদটি লোড করা যায়নি। অর্ডারটি হয়ে থাকলে সেটি আপনার অ্যাকাউন্টের অর্ডারে দেখা যেতে পারে।",
  orderReceiptExpiredTitleText: "রসিদের প্রবেশাধিকার শেষ হয়েছে",
  orderReceiptExpiredMessageText:
    "এই ব্রাউজারে ব্যক্তিগত রসিদটি আর পাওয়া যাচ্ছে না। অ্যাকাউন্টের অর্ডার দেখতে সাইন ইন করুন অথবা সাহায্যের জন্য দোকানের সঙ্গে যোগাযোগ করুন।",
  orderReceiptUnavailableMessageText:
    "রসিদটি এখন লোড করা যায়নি। আবার চেষ্টা করুন অথবা অ্যাকাউন্টের অর্ডার দেখুন।",
  orderReceiptReferenceText: "রেফারেন্স",
  orderReceiptVerifyRecoveryText: "পেমেন্ট পুনরুদ্ধার যাচাই করুন",
  orderReceiptRetryText: "রসিদ আবার লোড করুন",
  orderReceiptOrderDetailsText: "অর্ডারের তথ্য",
  orderReceiptOrderNumberText: "অর্ডার নম্বর",
  orderReceiptPlacedText: "অর্ডারের সময়",
  orderReceiptStatusText: "অর্ডারের অবস্থা",
  orderReceiptPaymentText: "পেমেন্ট পদ্ধতি",
  orderReceiptPaymentStatusText: "পেমেন্টের অবস্থা",
  orderReceiptDeliveryText: "ডেলিভারি",
  orderReceiptDeliveryWithMethodText: "ডেলিভারি · {method}",
  orderReceiptDeliveryNotRecordedText: "এই অর্ডারের ডেলিভারি পদ্ধতি সংরক্ষণ করা হয়নি।",
  orderReceiptFeeWaivedText: "{fee} চার্জ মওকুফ হয়েছে",
  orderReceiptPaidText: "পরিশোধিত",
  orderReceiptBalanceDueText: "বাকি টাকা",
  orderReceiptDeliveryDetailsText: "ডেলিভারির তথ্য",
  orderReceiptItemsText: "পণ্যসমূহ",
  orderReceiptProductUnavailableText: "পণ্যটি পাওয়া যাচ্ছে না",
  orderReceiptQuantityText: "পরিমাণ: {quantity}",
  orderReceiptItemDiscountText: "পণ্যে ছাড়: −{amount}",
  orderReceiptTaxIncludedText: "{label} অন্তর্ভুক্ত: {amount}",
  orderReceiptTaxAddedText: "{label} যোগ হয়েছে: {amount}",
  orderReceiptLineTotalText: "পণ্যটির মোট",
  orderReceiptPrintText: "রসিদ প্রিন্ট করুন",
  orderReceiptCheckingPaymentText: "পেমেন্টের অবস্থা যাচাই করা হচ্ছে…",
  orderReceiptCheckPaymentText: "পেমেন্টের অবস্থা যাচাই করুন",
  orderReceiptConfirmationDelayedText:
    "পেমেন্ট নিশ্চিত হতে স্বাভাবিকের চেয়ে বেশি সময় লাগছে। আপনি নিরাপদে এই রসিদ থেকে বের হয়ে পরে আবার দেখতে পারেন।",
  orderReceiptStatusUpdatedText: "পেমেন্টের অবস্থা হালনাগাদ হয়েছে। রসিদ রিফ্রেশ হচ্ছে…",
  orderReceiptRetryWithProviderText: "{provider} দিয়ে আবার পেমেন্ট করুন",
  orderReceiptRetryPaymentText: "আবার পেমেন্ট করুন",
  orderReceiptOpeningPaymentText: "পেমেন্ট খোলা হচ্ছে…",
  orderReceiptRetryUnavailableText: "এই অর্ডারের পেমেন্ট আবার চেষ্টা করা যাচ্ছে না।",
  orderReceiptCardUnavailableText: "এই অর্ডারে কার্ড পেমেন্ট পাওয়া যাচ্ছে না।",
  orderReceiptLoadingCardText: "নিরাপদ কার্ড ফর্ম লোড হচ্ছে…",
  orderReceiptEnterCardText: "এই অর্ডারটি চালিয়ে যেতে কার্ডের তথ্য লিখুন।",
  orderReceiptCardLoadFailedText: "নিরাপদ কার্ড ফর্ম লোড করা যায়নি। অন্য পেমেন্ট পদ্ধতি চেষ্টা করুন।",
  orderReceiptPaymentProcessingRetryText: "পেমেন্ট এখনো প্রক্রিয়াধীন। {seconds} সেকেন্ড পর আবার চেষ্টা করা হবে…",
  orderReceiptStartPaymentFailedText: "পেমেন্ট শুরু করা যায়নি। আবার চেষ্টা করুন।",
  orderReceiptGatewayRedirectFailedText: "পেমেন্ট সেবা নিরাপদ পেমেন্ট পেজ দেয়নি।",
  orderReceiptConfirmingCardText: "আপনার বর্তমান অর্ডারের কার্ড পেমেন্ট নিশ্চিত করা হচ্ছে…",
  orderReceiptCardPaymentFailedText: "কার্ড পেমেন্ট সম্পন্ন করা যায়নি। আপনার অর্ডারটি সংরক্ষিত আছে।",
  orderReceiptExistingOrderCardHelpText:
    "আপনার বর্তমান অর্ডারটিই হালনাগাদ হবে। নতুন কোনো অর্ডার তৈরি হবে না।",
  orderReceiptPaymentIssueTitleText: "পেমেন্ট সম্পন্ন হয়নি",
  orderReceiptPaymentIssueMessageText:
    "অর্ডার #{orderId} সংরক্ষিত আছে। পেমেন্ট পদ্ধতি বেছে নিন।",
  orderReceiptPaymentPendingTitleText: "পেমেন্ট অপেক্ষমাণ",
  orderReceiptPaymentPendingMessageText:
    "অর্ডার #{orderId} সংরক্ষিত আছে।",
  orderReceiptConfirmedTitleText: "অর্ডার নিশ্চিত হয়েছে",
  orderReceiptConfirmedMessageText: "অর্ডার #{orderId} নিশ্চিত হয়েছে এবং প্রস্তুত করা হচ্ছে।",
  orderReceiptProcessingTitleText: "অর্ডার প্রস্তুত করা হচ্ছে",
  orderReceiptProcessingMessageText: "অর্ডার #{orderId} প্রস্তুত করা হচ্ছে।",
  orderReceiptShippedTitleText: "অর্ডার পাঠানো হয়েছে",
  orderReceiptShippedMessageText: "অর্ডার #{orderId} আপনার পথে আছে।",
  orderReceiptDeliveredTitleText: "অর্ডার ডেলিভারি হয়েছে",
  orderReceiptDeliveredMessageText: "অর্ডার #{orderId} ডেলিভারি করা হয়েছে।",
  orderReceiptCompletedTitleText: "অর্ডার সম্পন্ন হয়েছে",
  orderReceiptCompletedMessageText: "অর্ডার #{orderId} সম্পন্ন হয়েছে।",
  orderReceiptCancelledTitleText: "অর্ডার বাতিল হয়েছে",
  orderReceiptCancelledMessageText: "অর্ডার #{orderId} বাতিল করা হয়েছে।",
  orderReceiptRefundedTitleText: "অর্ডারের টাকা ফেরত হয়েছে",
  orderReceiptRefundedMessageText: "অর্ডার #{orderId}-এর টাকা ফেরত দেওয়া নথিভুক্ত হয়েছে।",
  orderReceiptReturnedTitleText: "অর্ডার ফেরত এসেছে",
  orderReceiptReturnedMessageText: "অর্ডার #{orderId} ফেরত দেওয়া নথিভুক্ত হয়েছে।",
  orderReceiptPartiallyRefundedTitleText: "অর্ডারের কিছু টাকা ফেরত হয়েছে",
  orderReceiptPartiallyRefundedMessageText:
    "অর্ডার #{orderId}-এর কিছু টাকা ফেরত দেওয়া নথিভুক্ত হয়েছে।",
  orderReceiptUpdatedTitleText: "অর্ডার হালনাগাদ হয়েছে",
  orderReceiptUpdatedMessageText: "অর্ডার #{orderId} হালনাগাদ হয়েছে।",
  orderReceiptPlacedTitleText: "অর্ডার দেওয়া হয়েছে",
  orderReceiptPlacedMessageText: "আমরা অর্ডার #{orderId} পেয়েছি।",
  orderReceiptStatusNotAvailableText: "পাওয়া যাচ্ছে না",
  orderReceiptStatusPendingText: "অপেক্ষমাণ",
  orderReceiptStatusIncompleteText: "অসম্পূর্ণ",
  orderReceiptStatusConfirmedText: "নিশ্চিত",
  orderReceiptStatusProcessingText: "প্রক্রিয়াধীন",
  orderReceiptStatusShippedText: "পাঠানো হয়েছে",
  orderReceiptStatusDeliveredText: "ডেলিভারি হয়েছে",
  orderReceiptStatusCompletedText: "সম্পন্ন",
  orderReceiptStatusCancelledText: "বাতিল",
  orderReceiptStatusRefundedText: "টাকা ফেরত হয়েছে",
  orderReceiptStatusReturnedText: "ফেরত এসেছে",
  orderReceiptStatusPartiallyRefundedText: "আংশিক টাকা ফেরত হয়েছে",
  orderReceiptStatusFailedText: "ব্যর্থ",
  orderReceiptPaymentStatusPaidText: "পরিশোধিত",
  orderReceiptPaymentStatusPartialText: "আংশিক পরিশোধিত",
  orderReceiptPaymentStatusUnpaidText: "অপরিশোধিত",
  orderReceiptPaymentStatusNoPaymentDueText: "কোনো পেমেন্ট বাকি নেই",
  orderReceiptPaymentMethodCardText: "কার্ড (Stripe)",
  orderReceiptPaymentMethodSslcommerzText: "অনলাইন পেমেন্ট (SSLCommerz)",
  orderReceiptPaymentMethodPolarText: "অনলাইন পেমেন্ট (Polar)",
  orderReceiptSaveAccountTitleText: "এই অর্ডারটি আপনার অ্যাকাউন্টে সংরক্ষণ করুন",
  orderReceiptSavedAccountTitleText: "অর্ডারটি আপনার অ্যাকাউন্টে সংরক্ষিত হয়েছে",
  orderReceiptSaveAccountHelpText:
    "এই অর্ডারে দেওয়া ফোন নম্বর দিয়ে অ্যাকাউন্ট তৈরি করুন অথবা একই ফোন বা ইমেইল দিয়ে সাইন ইন করুন।",
  orderReceiptViewInAccountText: "অ্যাকাউন্টে দেখুন",
  orderReceiptSaveToAccountText: "আমার অ্যাকাউন্টে সংরক্ষণ করুন",
  orderReceiptSavingText: "সংরক্ষণ করা হচ্ছে…",
  orderReceiptCreateAccountText: "অ্যাকাউন্ট তৈরি করুন",
  orderReceiptSignInText: "সাইন ইন করুন",
  orderReceiptMissingReferenceText: "এই রসিদে অর্ডার রেফারেন্স নেই।",
  orderReceiptSavingToAccountText: "অর্ডারটি আপনার অ্যাকাউন্টে সংরক্ষণ করা হচ্ছে…",
  orderReceiptSaveFailedText: "অর্ডারটি সংরক্ষণ করা যায়নি। আবার চেষ্টা করুন।",
  orderReceiptAlreadySavedText: "অর্ডারটি ইতিমধ্যে আপনার অ্যাকাউন্টে আছে।",
  orderReceiptSavedText: "অর্ডারটি সংরক্ষিত হয়েছে। এখন যেকোনো সাইন-ইন করা ডিভাইস থেকে এটি দেখতে পারবেন।",
  orderReceiptCreateAccountPromptText: "এই অর্ডারে দেওয়া ফোন নম্বর দিয়ে আপনার অ্যাকাউন্ট তৈরি করুন।",
  orderReceiptSignInPromptText: "এই অর্ডারের সঙ্গে মেলে এমন ফোন নম্বর বা ইমেইল দিয়ে সাইন ইন করুন।",
  orderReceiptHelpText: "সাহায্য প্রয়োজন?",
  orderReceiptCancelRequestActionText: "বাতিলের অনুরোধ করুন",
  orderReceiptReturnRequestActionText: "ফেরতের অনুরোধ করুন",
  orderReceiptRefundRequestActionText: "টাকা ফেরতের অনুরোধ করুন",
  orderReceiptRequestSubmittedText: "দোকান আপনার অনুরোধ পেয়েছে এবং পরিবর্তনের আগে এটি পর্যালোচনা করবে।",
  orderReceiptRequestUnderReviewText: "দোকানের দল অনুরোধটি পর্যালোচনা করছে।",
  orderReceiptRequestApprovedText: "দোকান অনুরোধটি গ্রহণ করেছে। অগ্রগতি জানতে অর্ডারের অবস্থা দেখুন।",
  orderReceiptRequestRejectedText: "দোকান অনুরোধটি গ্রহণ করতে পারেনি। আরও সাহায্য লাগলে দোকানের সঙ্গে যোগাযোগ করুন।",
  orderReceiptRequestWithdrawnText: "অনুরোধটি প্রত্যাহার করা হয়েছে।",
  orderReceiptRequestCompletedText: "অনুরোধটি সম্পন্ন হয়েছে।",
  orderReceiptRequestSettledText: "অনুরোধটি নিষ্পত্তি হয়েছে। আরও সাহায্য লাগলে দোকানের সঙ্গে যোগাযোগ করুন।",
  orderReceiptRequestStatusSubmittedText: "জমা হয়েছে",
  orderReceiptRequestStatusUnderReviewText: "পর্যালোচনাধীন",
  orderReceiptRequestStatusApprovedText: "গৃহীত",
  orderReceiptRequestStatusRejectedText: "প্রত্যাখ্যাত",
  orderReceiptRequestStatusWithdrawnText: "প্রত্যাহার করা হয়েছে",
  orderReceiptRequestStatusCompletedText: "সম্পন্ন",
  orderReceiptRequestLabelText: "{action} · {status}",
  orderReceiptReasonText: "কারণ",
  orderReceiptReasonAriaText: "সহায়তার অনুরোধের কারণ",
  orderReceiptReasonPlaceholderText: "আপনি কেন এই অনুরোধ করছেন?",
  orderReceiptCancelText: "বাতিল করুন",
  orderReceiptSendRequestText: "অনুরোধ পাঠান",
  orderReceiptMissingProofText: "অনুরোধ পাঠানোর জন্য প্রয়োজনীয় ব্রাউজার প্রমাণ এই রসিদে নেই।",
  orderReceiptReasonRequiredText: "অনুরোধ পাঠানোর আগে সংক্ষিপ্ত কারণ লিখুন।",
  orderReceiptSupportFailedText: "সহায়তার অনুরোধ পাঠানো যায়নি। আবার চেষ্টা করুন।",
  orderReceiptRequestSentText: "অনুরোধ পাঠানো হয়েছে। দোকানের দল এখন অর্ডার থেকে এটি পর্যালোচনা করতে পারবে।",
  orderReceiptSupportUnavailableText: "এই অর্ডারের জন্য এখন সহায়তার অনুরোধ পাওয়া যাচ্ছে না।",
  termsText:
    "অর্ডারটি নিশ্চিত করলে আপনি আমাদের পরিষেবার শর্তাবলি ও গোপনীয়তা নীতিতে সম্মত হচ্ছেন।",
  processingOrderTitle: "আপনার অর্ডার প্রক্রিয়া করা হচ্ছে",
  processingOrderMessage: "আপনার অর্ডারটি প্রক্রিয়া করা পর্যন্ত অনুগ্রহ করে অপেক্ষা করুন।",
  requiredFieldIndicator: "*",
  homeAriaLabel: "হোমপেজে যান",
  secureCheckoutText: "নিরাপদ চেকআউট",
  checkoutProgressLabel: "চেকআউটের অগ্রগতি",
  informationStepText: "তথ্য",
  paymentStepText: "পেমেন্ট",
  confirmationStepText: "নিশ্চিতকরণ",
  estimatedTotalText: "আনুমানিক সর্বমোট",
  taxText: "কর",
  freeText: "ফ্রি",
  calculatingText: "হিসাব করা হচ্ছে…",
  unavailableText: "পাওয়া যাচ্ছে না",
  taxVerificationFailedText: "কর যাচাই করা যায়নি। গন্তব্য পরিবর্তন করুন অথবা আবার চেষ্টা করুন।",
  cartItemChangedText: "চেকআউটের আগে কার্টের একটি পণ্য যাচাই করা দরকার।",
  cartAvailabilityFailedText: "কার্টের পণ্য যাচাই করা যায়নি। পেজ রিফ্রেশ করে আবার চেষ্টা করুন।",
  cartItemsChangedText: "পেমেন্টের আগে কার্টের {count}টি পণ্য পরিবর্তিত হয়েছে। চেকআউটের আগে সেগুলো দেখুন।",
  oneCartItemChangedText: "পেমেন্টের আগে কার্টের একটি পণ্য পরিবর্তিত হয়েছে। চেকআউটের আগে সেটি দেখুন।",
  cartAvailabilityReviewText: "কার্টের পণ্য যাচাই করা যায়নি। চেকআউটের আগে কার্টটি দেখুন।",
  orderSummaryText: "অর্ডারের সারাংশ",
  paymentPageTitle: "পেমেন্ট",
  paymentMethodsText: "পেমেন্ট পদ্ধতিগুলো",
  paymentMethodText: "পেমেন্ট পদ্ধতি",
  loadingPaymentMethodsText: "পেমেন্ট পদ্ধতি লোড হচ্ছে",
  testModeNoticeText: "টেস্ট মোড — কোনো প্রকৃত পেমেন্ট নেওয়া হবে না।",
  cardDetailsText: "কার্ডের তথ্য",
  selectPaymentMethodText: "একটি পেমেন্ট পদ্ধতি বেছে নিন",
  continueToPaymentText: "পেমেন্টে এগিয়ে যান",
  checkoutUnavailableText: "চেকআউট বন্ধ আছে",
  checkoutUnavailableMessage: "চেকআউট সাময়িকভাবে বন্ধ আছে। কিছুক্ষণ পর আবার চেষ্টা করুন।",
  errorPrefixText: "সমস্যা:",
  successPrefixText: "সফল!",
  existingCheckoutTitle: "আপনার একটি চেকআউট ইতিমধ্যে চলছে",
  existingCheckoutMessage:
    "{orderId} নম্বর অর্ডারটির পেমেন্ট বাকি আছে। নতুন চেকআউট শুরুর আগে এটি দেখুন।",
  reviewExistingCheckoutText: "চলমান চেকআউট দেখুন",
  signInToCheckoutText: "সাইন ইন করে চেকআউট করুন",
  signInPromptText: "আগে থেকেই অ্যাকাউন্ট আছে? দ্রুত চেকআউট করতে সাইন ইন করুন",
  noScriptText: "চেকআউটের আগে কার্ট হালনাগাদ করতে JavaScript প্রয়োজন।",
  selectCityPlaceholder: "শহর বেছে নিন",
  selectZonePlaceholder: "এলাকা বেছে নিন",
  selectAreaPlaceholder: "উপ-এলাকা বেছে নিন (ঐচ্ছিক)",
  loadingText: "লোড হচ্ছে…",
  zonesLoadFailedText: "এলাকাগুলো লোড করা যায়নি। আবার চেষ্টা করুন",
  areasLoadFailedText: "উপ-এলাকাগুলো লোড করা যায়নি। আবার চেষ্টা করুন",
  noShippingMethodsText: "এই মুহূর্তে কোনো ডেলিভারি পদ্ধতি পাওয়া যাচ্ছে না।",
  waivedShippingFeeText: "সাধারণত {fee}; কার্টের একটি পণ্যের কারণে চার্জটি মওকুফ হয়েছে।",
  phoneRequiredText: "আপনার ফোন নম্বর লিখুন।",
  phoneInvalidText: "সঠিক ফোন নম্বর লিখুন।",
  phoneCountryNotAcceptedText: "এই দোকান ওই দেশের ফোন নম্বর গ্রহণ করে না।",
  nameRequiredText: "আপনার পুরো নাম লিখুন।",
  addressRequiredText: "আপনার ডেলিভারির ঠিকানা লিখুন।",
  addressIncompleteText: "সম্পূর্ণ ডেলিভারির ঠিকানা লিখুন (কমপক্ষে {minimum} অক্ষর)।",
  cityZoneRequiredText: "এগিয়ে যেতে শহর ও এলাকা বেছে নিন।",
  zoneRequiredText: "এগিয়ে যেতে একটি এলাকা বেছে নিন।",
  deliveryRequiredText: "একটি ডেলিভারি পদ্ধতি বেছে নিন।",
  checkingAvailableQuantityText: "{item}-এর উপলভ্য পরিমাণ যাচাই করা হচ্ছে",
  maximumAvailableQuantityText: "{item}-এর সর্বোচ্চ উপলভ্য পরিমাণ কার্টে আছে",
  increaseQuantityText: "{item}-এর পরিমাণ বাড়ান",
  decreaseQuantityText: "{item}-এর পরিমাণ কমান",
  removeFromCartText: "কার্ট থেকে {item} সরান",
  cartLoadingText: "আপনার কার্ট লোড হচ্ছে",
  cartAttentionText: "কার্টের কিছু পণ্য যাচাই করা দরকার",
  cartEmptyErrorText: "অর্ডার করার আগে কার্টে পণ্য যোগ করুন।",
  quickBuyStorageBlockedText: "ব্রাউজারটি সাময়িক কার্ট স্টোরেজ বন্ধ রাখায় পণ্যটি যোগ করা যায়নি। সাইট স্টোরেজ চালু করে আবার যোগ করুন।",
  orderProcessingFailedText: "অর্ডারটি প্রক্রিয়া করা যায়নি। আবার চেষ্টা করুন।",
  unexpectedErrorText: "একটি অপ্রত্যাশিত সমস্যা হয়েছে।",
  cartItemsNeedAttentionText: "চেকআউটের আগে কার্টের {count}টি পণ্য যাচাই করা দরকার।",
  orderPlacedSuccessText: "আপনার অর্ডারটি সফলভাবে দেওয়া হয়েছে। অর্ডার আইডি: {orderId}",
  checkingAccountText: "অ্যাকাউন্ট যাচাই করা হচ্ছে…",
  accountUnavailableText: "এখন আপনার অ্যাকাউন্ট যাচাই করা যায়নি। আবার চেষ্টা করুন।",
  checkingCartText: "কার্ট যাচাই করা হচ্ছে…",
  reviewCartItemsText: "চেকআউটের আগে চিহ্নিত পণ্যগুলো দেখুন।",
  redirectingToPaymentText: "পেমেন্টে নেওয়া হচ্ছে…",
  openingPaymentOptionsTitle: "পেমেন্টের বিকল্প খোলা হচ্ছে",
  openingPaymentOptionsMessage: "আপনার সর্বমোট এবং উপলভ্য পেমেন্ট পদ্ধতি নিশ্চিত করা হচ্ছে।",
  checkoutDetailsMissingText: "চেকআউটের তথ্য পাওয়া যায়নি। কার্টে ফিরে আবার চেষ্টা করুন।",
  checkoutDetailsUnreadableText: "চেকআউটের তথ্য পড়া যায়নি। কার্টে ফিরে আবার চেষ্টা করুন।",
  returnToCartText: "কার্টে ফিরুন",
  quantityShortText: "পরিমাণ {quantity}",
  eachText: "প্রতিটি",
  includedText: "অন্তর্ভুক্ত",
  dueNowText: "এখন পরিশোধযোগ্য",
  dueOnDeliveryText: "ডেলিভারির সময় পরিশোধযোগ্য",
  continueText: "এগিয়ে যান",
  continueAsGuestText: "অতিথি হিসেবে এগিয়ে যান",
  sessionExpiredText:
    "আপনার সাইন-ইন সেশন শেষ হয়েছে। চেকআউটের তথ্য নিরাপদ আছে। অতিথি হিসেবে এগিয়ে যান অথবা আবার সাইন ইন করুন।",
  checkoutConflictText: "এই চেকআউটটি ইতিমধ্যে জমা হয়েছে অথবা অন্য ট্যাবে পরিবর্তিত হয়েছে। কার্ট দেখে আবার চেষ্টা করুন।",
  totalChangedReviewText:
    "আপনার অর্ডারের মোট টাকা বা চেকআউটের শর্ত বদলেছে। হালনাগাদ মোট টাকা দেখে অর্ডারটি আবার নিশ্চিত করুন।",
  tooManyCheckoutAttemptsText: "খুব বেশি চেকআউট চেষ্টা হয়েছে। কিছুক্ষণ অপেক্ষা করে আবার চেষ্টা করুন।",
  paymentFailedText: "পেমেন্ট ব্যর্থ হয়েছে",
  noPaymentMethodsText:
    "এই অর্ডারের মোট টাকার জন্য কোনো পেমেন্ট পদ্ধতি পাওয়া যাচ্ছে না। কার্টে ফিরুন অথবা দোকানের সঙ্গে যোগাযোগ করুন।",
  preparingPaymentText: "পেমেন্ট প্রস্তুত হচ্ছে…",
  paymentMethodUnavailableText: "পেমেন্ট পদ্ধতি পাওয়া যাচ্ছে না",
  paymentMethodUnavailableMessage: "এই পেমেন্ট পদ্ধতিটি পাওয়া যাচ্ছে না। অন্য একটি পদ্ধতি বেছে নিন।",
  retryPaymentFormText: "পেমেন্ট ফর্ম আবার চেষ্টা করুন",
  processingPaymentTitle: "পেমেন্ট প্রক্রিয়া করা হচ্ছে",
  processingPaymentMessage: "আপনার অর্ডার ও পেমেন্টের তথ্য নিশ্চিত করা হচ্ছে।",
  placingOrderTitle: "আপনার অর্ডার দেওয়া হচ্ছে",
  placingOrderMessage: "পণ্যের প্রাপ্যতা ও ডেলিভারি নিশ্চিত করা হচ্ছে।",
  openingSecurePaymentTitle: "নিরাপদ পেমেন্ট খোলা হচ্ছে",
  openingSecurePaymentMessage: "বেছে নেওয়া পেমেন্ট সেবায় আপনাকে নিয়ে যাওয়া হবে।",
  unknownPaymentMethodText: "অজানা পেমেন্ট পদ্ধতি বেছে নেওয়া হয়েছে।",
  unsafeRedirectText: "পেমেন্ট সেবা নিরাপদ ঠিকানা না দেওয়ায় পেমেন্ট খোলা যায়নি।",
  genericErrorText: "একটি সমস্যা হয়েছে। আবার চেষ্টা করুন।",
  totalVerificationFailedText:
    "বর্তমান কর ও অর্ডারের সর্বমোট যাচাই করা যায়নি। কার্টে ফিরে আবার চেষ্টা করুন।",
  totalUnavailableText: "সর্বমোট পাওয়া যাচ্ছে না",
  continueToProviderText: "{provider}-এ এগিয়ে যান",
  payAmountNowText: "এখন {amount} পরিশোধ করুন",
  payAmountText: "{amount} পরিশোধ করুন",
  providerRedirectText: "পেমেন্ট সম্পন্ন করতে আপনাকে {provider}-এ নেওয়া হবে।",
  creditDebitCardText: "ক্রেডিট বা ডেবিট কার্ড",
  paySecurelyByCardText: "কার্ড দিয়ে নিরাপদে পেমেন্ট করুন",
  onlinePaymentText: "অনলাইনে পেমেন্ট করুন",
  onlinePaymentDescriptionText: "বিকাশ, নগদ, কার্ড ও আরও অনেক পদ্ধতি",
  cardOrWalletText: "কার্ড বা ডিজিটাল ওয়ালেট",
  completeWithProviderText: "{provider}-এর মাধ্যমে পেমেন্ট সম্পন্ন করুন",
  cashOnDeliveryText: "ক্যাশ অন ডেলিভারি",
  payOnDeliveryText: "অর্ডার পাওয়ার সময় মূল্য পরিশোধ করুন",
  enterDiscountCodeText: "একটি ডিসকাউন্ট কোড লিখুন",
  removeCurrentDiscountText: "আগে বর্তমান ডিসকাউন্টটি সরান।",
  discountAppliedText: "ডিসকাউন্ট সফলভাবে প্রয়োগ হয়েছে!",
  invalidDiscountCodeText: "ডিসকাউন্ট কোডটি সঠিক নয়",
  discountApplyFailedText: "ডিসকাউন্ট প্রয়োগ করা যায়নি। আবার চেষ্টা করুন।",
  discountRemovedText: "ডিসকাউন্ট সরানো হয়েছে।",
};

export const CHECKOUT_LANGUAGE_KEYS = Object.freeze(
  Object.keys(ENGLISH_CHECKOUT_LANGUAGE_DATA) as CheckoutLanguageKey[],
);

export const CHECKOUT_LANGUAGE_LONG_TEXT_KEYS = new Set<CheckoutLanguageKey>([
  "termsText",
  "emptyCartDescriptionText",
  "paymentRecoveryMessageText",
  "paymentRecoveryIntroText",
  "paymentRecoveryUnavailableText",
  "paymentRecoveryMissingOrderText",
  "paymentRecoveryCodeSentText",
  "paymentRecoveryVerificationFailedText",
  "orderReceiptBrowserRecoveryMessageText",
  "orderReceiptBrowserOnlyMessageText",
  "orderReceiptPrivateUnavailableMessageText",
  "orderReceiptExpiredMessageText",
  "orderReceiptUnavailableMessageText",
  "orderReceiptDeliveryNotRecordedText",
  "orderReceiptConfirmationDelayedText",
  "orderReceiptCardLoadFailedText",
  "orderReceiptPaymentIssueMessageText",
  "orderReceiptPaymentPendingMessageText",
  "orderReceiptConfirmedMessageText",
  "orderReceiptProcessingMessageText",
  "orderReceiptShippedMessageText",
  "orderReceiptDeliveredMessageText",
  "orderReceiptCompletedMessageText",
  "orderReceiptCancelledMessageText",
  "orderReceiptRefundedMessageText",
  "orderReceiptReturnedMessageText",
  "orderReceiptPartiallyRefundedMessageText",
  "orderReceiptUpdatedMessageText",
  "orderReceiptPlacedMessageText",
  "orderReceiptSaveAccountHelpText",
  "orderReceiptSavedText",
  "orderReceiptRequestSubmittedText",
  "orderReceiptRequestApprovedText",
  "orderReceiptRequestRejectedText",
  "orderReceiptRequestSettledText",
  "orderReceiptMissingProofText",
  "checkoutUnavailableMessage",
  "existingCheckoutMessage",
  "noScriptText",
  "accountUnavailableText",
  "openingPaymentOptionsMessage",
  "checkoutDetailsMissingText",
  "checkoutDetailsUnreadableText",
  "sessionExpiredText",
  "noPaymentMethodsText",
  "paymentMethodUnavailableMessage",
  "processingPaymentMessage",
  "placingOrderMessage",
  "openingSecurePaymentMessage",
  "unsafeRedirectText",
  "totalVerificationFailedText",
]);

const CHECKOUT_LANGUAGE_PRESETS: Record<string, CheckoutLanguageData> = {
  en: { ...ENGLISH_CHECKOUT_LANGUAGE_DATA },
  bn: BANGLA_CHECKOUT_LANGUAGE_DATA,
};

function parseStoredLanguageData(value: unknown): Record<string, unknown> {
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }
  if (typeof value !== "string") return {};
  try {
    const parsed = JSON.parse(value) as unknown;
    return parsed && typeof parsed === "object" && !Array.isArray(parsed)
      ? (parsed as Record<string, unknown>)
      : {};
  } catch {
    return {};
  }
}

export function checkoutLanguageBaseCode(code: unknown): string {
  if (typeof code !== "string") return "en";
  return code.trim().toLowerCase().split(/[-_]/, 1)[0] || "en";
}

export function getCheckoutLanguagePreset(code: unknown): CheckoutLanguageData {
  const preset = CHECKOUT_LANGUAGE_PRESETS[checkoutLanguageBaseCode(code)];
  return { ...(preset ?? ENGLISH_CHECKOUT_LANGUAGE_DATA) };
}

function comparableDefaultText(value: string): string {
  return value
    .trim()
    .toLocaleLowerCase("en")
    .replaceAll("…", "...")
    .replace(/[.!]+$/u, "")
    .replace(/\s+/g, " ");
}

/**
 * Stored values are merchant overrides. Older records persisted the English
 * defaults even for non-English locale codes, so an unchanged English value
 * must not shadow a built-in locale preset. Genuine custom values are kept.
 */
export function resolveCheckoutLanguageData(
  code: unknown,
  storedValue: unknown,
): CheckoutLanguageData {
  const baseCode = checkoutLanguageBaseCode(code);
  const resolved = getCheckoutLanguagePreset(baseCode);
  const stored = parseStoredLanguageData(storedValue);

  for (const key of CHECKOUT_LANGUAGE_KEYS) {
    const value = stored[key];
    if (typeof value !== "string" || value.trim() === "") continue;
    if (
      baseCode !== "en" &&
      comparableDefaultText(value) ===
        comparableDefaultText(ENGLISH_CHECKOUT_LANGUAGE_DATA[key])
    ) {
      continue;
    }
    resolved[key] = value;
  }

  return resolved;
}

export function formatCheckoutLanguageText(
  template: string,
  values: Readonly<Record<string, string | number>>,
): string {
  return template.replace(/\{([a-zA-Z][a-zA-Z0-9]*)\}/g, (match, key: string) =>
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : match,
  );
}
