import { describe, expect, it } from "vitest";
import { chmodSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { tmpdir } from "os";
import {
  CREDENTIAL_ENCRYPTION_KEY_BYTES,
  MASTER_SECRET_MIN_LENGTH,
  RETIRED_LOCAL_ENV_KEYS,
  assertLocalSecretSync,
  assertSafeLocalMutationUrl,
  classifyMutationTarget,
  collectLocalSecretSyncIssues,
  collectStaleLocalEnvIssues,
  generateCredentialEncryptionKey,
  generateMasterSecret,
  getArgValue,
  isUsableCredentialEncryptionKey,
  isUsableMasterSecret,
  parseEnvFileContent,
  resolvePnpmExecutable,
  resolveLocalStatePath,
  resolveSharedLocalSecrets,
} from "./dev-local-utils.mjs";

const VALID_MASTER_SECRET = "m".repeat(MASTER_SECRET_MIN_LENGTH);
const VALID_AES_KEY = Buffer.alloc(CREDENTIAL_ENCRYPTION_KEY_BYTES, 7).toString("base64");

describe("local dev script helpers", () => {
  it("parses simple .dev.vars files without leaking comments into values", () => {
    expect(parseEnvFileContent(`
      # comment
      export SCALIUS_SECRET=master-secret # trailing note
      CREDENTIAL_ENCRYPTION_KEY="aes-key"
      EMPTY=
    `)).toEqual({
      SCALIUS_SECRET: "master-secret",
      CREDENTIAL_ENCRYPTION_KEY: "aes-key",
      EMPTY: "",
    });
  });

  it("generates a master secret and an AES-256 key in the installed formats", () => {
    const master = generateMasterSecret();
    const aesKey = generateCredentialEncryptionKey();

    expect(master).toHaveLength(64);
    expect(isUsableMasterSecret(master)).toBe(true);
    expect(aesKey).toHaveLength(44);
    expect(Buffer.from(aesKey, "base64")).toHaveLength(CREDENTIAL_ENCRYPTION_KEY_BYTES);
    expect(isUsableCredentialEncryptionKey(aesKey)).toBe(true);
    expect(generateMasterSecret()).not.toBe(master);
  });

  it("rejects placeholder, short, and non-AES-256 secret values", () => {
    expect(isUsableMasterSecret("<auto-generated>")).toBe(false);
    expect(isUsableMasterSecret("")).toBe(false);
    expect(isUsableMasterSecret("s".repeat(MASTER_SECRET_MIN_LENGTH - 1))).toBe(false);
    expect(isUsableMasterSecret(` ${VALID_MASTER_SECRET} `)).toBe(true);

    expect(isUsableCredentialEncryptionKey("<auto-generated>")).toBe(false);
    expect(isUsableCredentialEncryptionKey("not base64!")).toBe(false);
    expect(isUsableCredentialEncryptionKey(Buffer.alloc(16).toString("base64"))).toBe(false);
    expect(isUsableCredentialEncryptionKey(Buffer.alloc(48).toString("base64"))).toBe(false);
    expect(isUsableCredentialEncryptionKey(VALID_AES_KEY)).toBe(true);
  });

  it("reuses existing API secrets when generating missing local env files", () => {
    const secrets = resolveSharedLocalSecrets({
      apiVars: {
        SCALIUS_SECRET: VALID_MASTER_SECRET,
        CREDENTIAL_ENCRYPTION_KEY: VALID_AES_KEY,
      },
      env: {},
    });

    expect(secrets).toEqual({
      scaliusSecret: VALID_MASTER_SECRET,
      credentialEncryptionKey: VALID_AES_KEY,
    });
  });

  it("prefers the environment, then API, admin, and storefront files for the master secret", () => {
    const envSecret = "e".repeat(MASTER_SECRET_MIN_LENGTH);
    const adminSecret = "a".repeat(MASTER_SECRET_MIN_LENGTH);
    const storefrontSecret = "s".repeat(MASTER_SECRET_MIN_LENGTH);

    expect(resolveSharedLocalSecrets({
      apiVars: { SCALIUS_SECRET: "<auto-generated>" },
      adminVars: { SCALIUS_SECRET: adminSecret },
      storefrontVars: { SCALIUS_SECRET: storefrontSecret },
      env: { SCALIUS_SECRET: envSecret },
    }).scaliusSecret).toBe(envSecret);

    expect(resolveSharedLocalSecrets({
      apiVars: { SCALIUS_SECRET: "too-short" },
      adminVars: { SCALIUS_SECRET: adminSecret },
      storefrontVars: { SCALIUS_SECRET: storefrontSecret },
      env: {},
    }).scaliusSecret).toBe(adminSecret);

    expect(resolveSharedLocalSecrets({
      storefrontVars: { SCALIUS_SECRET: storefrontSecret },
      env: {},
    }).scaliusSecret).toBe(storefrontSecret);
  });

  it("never reuses an unusable credential encryption key", () => {
    const secrets = resolveSharedLocalSecrets({
      apiVars: { CREDENTIAL_ENCRYPTION_KEY: "legacy-non-base64-value" },
      adminVars: { CREDENTIAL_ENCRYPTION_KEY: Buffer.alloc(16).toString("base64") },
      env: {},
    });

    expect(secrets.credentialEncryptionKey).not.toBe("legacy-non-base64-value");
    expect(isUsableCredentialEncryptionKey(secrets.credentialEncryptionKey)).toBe(true);
  });

  it("regenerates both secrets when forced", () => {
    const secrets = resolveSharedLocalSecrets({
      forceRegenerate: true,
      apiVars: {
        SCALIUS_SECRET: VALID_MASTER_SECRET,
        CREDENTIAL_ENCRYPTION_KEY: VALID_AES_KEY,
      },
      env: {},
    });

    expect(secrets.scaliusSecret).not.toBe(VALID_MASTER_SECRET);
    expect(secrets.credentialEncryptionKey).not.toBe(VALID_AES_KEY);
    expect(isUsableMasterSecret(secrets.scaliusSecret)).toBe(true);
    expect(isUsableCredentialEncryptionKey(secrets.credentialEncryptionKey)).toBe(true);
  });

  it("reports shared-secret drift without including secret values", () => {
    const apiSecret = "p".repeat(MASTER_SECRET_MIN_LENGTH);
    const adminSecret = "q".repeat(MASTER_SECRET_MIN_LENGTH);
    const issues = collectLocalSecretSyncIssues({
      apiVars: { SCALIUS_SECRET: apiSecret, CREDENTIAL_ENCRYPTION_KEY: VALID_AES_KEY },
      adminVars: { SCALIUS_SECRET: adminSecret, CREDENTIAL_ENCRYPTION_KEY: VALID_AES_KEY },
      storefrontVars: { SCALIUS_SECRET: apiSecret },
    });

    expect(issues).toEqual(["SCALIUS_SECRET differs between local .dev.vars files"]);
    expect(issues.join("\n")).not.toContain(apiSecret);
    expect(issues.join("\n")).not.toContain(adminSecret);
    expect(issues.join("\n")).not.toContain(VALID_AES_KEY);
  });

  it("requires the master secret in every Worker and the AES key only on API and admin", () => {
    expect(collectLocalSecretSyncIssues({
      apiVars: { SCALIUS_SECRET: VALID_MASTER_SECRET, CREDENTIAL_ENCRYPTION_KEY: VALID_AES_KEY },
      adminVars: { SCALIUS_SECRET: VALID_MASTER_SECRET, CREDENTIAL_ENCRYPTION_KEY: VALID_AES_KEY },
      storefrontVars: { SCALIUS_SECRET: VALID_MASTER_SECRET },
    })).toEqual([]);

    expect(collectLocalSecretSyncIssues({
      apiVars: { SCALIUS_SECRET: VALID_MASTER_SECRET },
      adminVars: { CREDENTIAL_ENCRYPTION_KEY: VALID_AES_KEY },
      storefrontVars: { SCALIUS_SECRET: "<auto-generated>" },
    })).toEqual([
      "SCALIUS_SECRET is missing from apps/admin-v2/.dev.vars, apps/storefront/.dev.vars",
      "CREDENTIAL_ENCRYPTION_KEY is missing from apps/api/.dev.vars",
    ]);
  });

  it("flags short master secrets and malformed AES keys per file", () => {
    const issues = collectLocalSecretSyncIssues({
      apiVars: { SCALIUS_SECRET: "short", CREDENTIAL_ENCRYPTION_KEY: "not-a-key" },
      adminVars: { SCALIUS_SECRET: VALID_MASTER_SECRET, CREDENTIAL_ENCRYPTION_KEY: VALID_AES_KEY },
      storefrontVars: { SCALIUS_SECRET: VALID_MASTER_SECRET },
    });

    expect(issues).toContain(
      `SCALIUS_SECRET must be at least ${MASTER_SECRET_MIN_LENGTH} characters in apps/api/.dev.vars`,
    );
    expect(issues).toContain(
      `CREDENTIAL_ENCRYPTION_KEY must be base64 of exactly ${CREDENTIAL_ENCRYPTION_KEY_BYTES} bytes in apps/api/.dev.vars`,
    );
    expect(issues.join("\n")).not.toContain("not-a-key");
  });

  it("does not compare secrets to files that never carry them", () => {
    expect(collectLocalSecretSyncIssues({
      apiVars: { SCALIUS_SECRET: VALID_MASTER_SECRET, CREDENTIAL_ENCRYPTION_KEY: VALID_AES_KEY },
      adminVars: { SCALIUS_SECRET: VALID_MASTER_SECRET, CREDENTIAL_ENCRYPTION_KEY: VALID_AES_KEY },
      storefrontVars: {
        SCALIUS_SECRET: VALID_MASTER_SECRET,
        CREDENTIAL_ENCRYPTION_KEY: Buffer.alloc(CREDENTIAL_ENCRYPTION_KEY_BYTES, 9).toString("base64"),
      },
    })).toEqual([]);
  });

  it("lists retired per-purpose secrets and URL keys still present in local env files", () => {
    expect(RETIRED_LOCAL_ENV_KEYS).toEqual(expect.arrayContaining([
      "BETTER_AUTH_SECRET",
      "JWT_SECRET",
      "API_TOKEN",
      "PURGE_TOKEN",
      "PUBLIC_API_URL",
      "PUBLIC_API_BASE_URL",
      "STOREFRONT_URL",
      "BETTER_AUTH_URL",
      "R2_PUBLIC_URL",
      "CDN_DOMAIN_URL",
      "PURGE_URL",
      "DASHBOARD_URL",
      "CACHE_NAMESPACE",
    ]));
    expect(RETIRED_LOCAL_ENV_KEYS).not.toContain("SCALIUS_SECRET");
    expect(RETIRED_LOCAL_ENV_KEYS).not.toContain("CREDENTIAL_ENCRYPTION_KEY");

    const issues = collectStaleLocalEnvIssues({
      apiVars: { SCALIUS_SECRET: VALID_MASTER_SECRET, JWT_SECRET: "old-jwt", PURGE_URL: "http://localhost:4322/api/purge-cache" },
      adminVars: { SCALIUS_SECRET: VALID_MASTER_SECRET },
      storefrontVars: { SCALIUS_SECRET: VALID_MASTER_SECRET, PUBLIC_API_URL: "" },
    });

    expect(issues).toEqual([
      "apps/api/.dev.vars still defines retired keys: JWT_SECRET, PURGE_URL",
      "apps/storefront/.dev.vars still defines retired keys: PUBLIC_API_URL",
    ]);
    expect(issues.join("\n")).not.toContain("old-jwt");
    expect(collectStaleLocalEnvIssues({ apiVars: null, adminVars: null, storefrontVars: null })).toEqual([]);
  });

  it("resolves relative Wrangler state paths from the repo root", () => {
    expect(resolveLocalStatePath("/repo", "tmp/state")).toBe("/repo/tmp/state");
    expect(resolveLocalStatePath("/repo", "/tmp/state")).toBe("/tmp/state");
  });

  it("rejects missing values for value-style CLI flags", () => {
    expect(() => getArgValue(["--admin-password"], "--admin-password")).toThrow(
      /requires a value/,
    );
    expect(() =>
      getArgValue(["--admin-password", "--skip-admin"], "--admin-password"),
    ).toThrow(/requires a value/);
  });

  it("points shared-secret drift repair at env-only setup", () => {
    expect(() => assertLocalSecretSync({
      apiVars: { SCALIUS_SECRET: "a".repeat(MASTER_SECRET_MIN_LENGTH) },
      adminVars: { SCALIUS_SECRET: "b".repeat(MASTER_SECRET_MIN_LENGTH) },
      storefrontVars: { SCALIUS_SECRET: "a".repeat(MASTER_SECRET_MIN_LENGTH) },
    })).toThrow(/pnpm dev:setup --force --env-only/);
  });

  it("classifies mutation targets without treating production as safe", () => {
    expect(classifyMutationTarget("http://localhost:8787/api/v1")).toMatchObject({
      origin: "http://localhost:8787",
      hostname: "localhost",
      isLocal: true,
      isKnownProduction: false,
    });
    expect(classifyMutationTarget("https://api.scalius.com/api/v1")).toMatchObject({
      origin: "https://api.scalius.com",
      hostname: "api.scalius.com",
      isLocal: false,
      isKnownProduction: true,
    });
  });

  it("allows mutation helpers only on loopback URLs", () => {
    expect(() => assertSafeLocalMutationUrl("http://127.0.0.1:8787")).not.toThrow();
    expect(() => assertSafeLocalMutationUrl("https://api.scalius.com")).toThrow(/known production/);
    expect(() => assertSafeLocalMutationUrl("https://staging.example.com")).toThrow(/non-local/);
  });

  it("resolves pnpm from the current Node Corepack shim when PATH is bare", () => {
    const tempRoot = mkdtempSync(join(tmpdir(), "scalius-pnpm-resolve-"));
    try {
      const nodeBin = join(tempRoot, "bin", "node");
      const corepackPnpm = join(tempRoot, "lib", "node_modules", "corepack", "shims", "pnpm");
      mkdirSync(dirname(nodeBin), { recursive: true });
      mkdirSync(dirname(corepackPnpm), { recursive: true });
      writeFileSync(nodeBin, "");
      writeFileSync(corepackPnpm, "#!/bin/sh\n");
      chmodSync(corepackPnpm, 0o755);

      expect(resolvePnpmExecutable({
        env: { PATH: "/missing", HOME: join(tempRoot, "home") },
        nodeExecPath: nodeBin,
      })).toBe(corepackPnpm);
    } finally {
      rmSync(tempRoot, { recursive: true, force: true });
    }
  });

  it("prefers the pnpm executable beside a Corepack pnpm.mjs npm_execpath", () => {
    const tempRoot = mkdtempSync(join(tmpdir(), "scalius-pnpm-execpath-"));
    try {
      const pnpmMjs = join(tempRoot, "bin", "pnpm.mjs");
      const pnpmExecutable = join(tempRoot, "bin", "pnpm");
      mkdirSync(dirname(pnpmMjs), { recursive: true });
      writeFileSync(pnpmMjs, "");
      writeFileSync(pnpmExecutable, "#!/bin/sh\n");
      chmodSync(pnpmExecutable, 0o755);

      expect(resolvePnpmExecutable({
        env: {
          PATH: "/missing",
          HOME: join(tempRoot, "home"),
          npm_execpath: pnpmMjs,
        },
        nodeExecPath: join(tempRoot, "node"),
      })).toBe(pnpmExecutable);
    } finally {
      rmSync(tempRoot, { recursive: true, force: true });
    }
  });

  it("normalizes explicit SCALIUS_PNPM_BIN when it points at Corepack pnpm.mjs", () => {
    const tempRoot = mkdtempSync(join(tmpdir(), "scalius-pnpm-explicit-"));
    try {
      const pnpmMjs = join(tempRoot, "bin", "pnpm.mjs");
      const pnpmExecutable = join(tempRoot, "bin", "pnpm");
      mkdirSync(dirname(pnpmMjs), { recursive: true });
      writeFileSync(pnpmMjs, "");
      writeFileSync(pnpmExecutable, "#!/bin/sh\n");
      chmodSync(pnpmExecutable, 0o755);

      expect(resolvePnpmExecutable({
        env: {
          PATH: "/missing",
          SCALIUS_PNPM_BIN: pnpmMjs,
        },
        nodeExecPath: join(tempRoot, "node"),
      })).toBe(pnpmExecutable);
    } finally {
      rmSync(tempRoot, { recursive: true, force: true });
    }
  });
});
