#!/usr/bin/env node
/**
 * dev-setup.mjs — One-command local development setup
 *
 * Usage: pnpm dev:setup
 *
 * 1. Installs dependencies
 * 2. Generates the two installed secrets and creates .dev.vars for both
 *    Workers (SCALIUS_SECRET on API + storefront; CREDENTIAL_ENCRYPTION_KEY on API)
 * 3. Applies local D1 migrations
 * 4. Creates the default local admin account unless --skip-admin is passed
 *
 * No URL is written anywhere: Workers read platform URLs from the dashboard
 * (Settings -> System -> Platform via GET /api/v1/platform) and local
 * development falls back to localhost:8787 (API), :4322 (storefront), and
 * :4323 (dashboard) automatically in code.
 */

import { execSync } from "child_process";
import { appendFileSync, existsSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import {
  assertLocalSecretSync,
  assertPassword,
  collectStaleLocalEnvIssues,
  getArgValue,
  readEnvVarsIfExists,
  pnpmShellCommand,
  resolveLocalStatePath,
  resolveSharedLocalSecrets,
  shellQuote,
} from "./dev-local-utils.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const pnpm = pnpmShellCommand();
const adminDir = resolve(root, "apps", "admin-v2");
const apiDir = resolve(root, "apps", "api");
const storefrontDir = resolve(root, "apps", "storefront");
const args = process.argv.slice(2);
const forceRegenerate = args.includes("--force");
const skipInstall = args.includes("--skip-install");
const skipAdmin = args.includes("--skip-admin");
const envOnly = args.includes("--env-only") || args.includes("--repair-env");
const showHelp = args.includes("--help") || args.includes("-h");

let wranglerState;
let localAdminEmail;
let localAdminPassword;
let localAdminName;
try {
  wranglerState = getArgValue(args, "--state") || process.env.SCALIUS_WRANGLER_STATE;
  localAdminEmail = getArgValue(args, "--admin-email") || process.env.LOCAL_ADMIN_EMAIL || "admin@local.scalius.test";
  localAdminPassword = getArgValue(args, "--admin-password") || process.env.LOCAL_ADMIN_PASSWORD || "ScaliusLocal123!";
  localAdminName = getArgValue(args, "--admin-name") || process.env.LOCAL_ADMIN_NAME || "Local Admin";
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}

const resolvedWranglerState = wranglerState ? resolveLocalStatePath(root, wranglerState) : null;

if (resolvedWranglerState) {
  process.env.SCALIUS_WRANGLER_STATE = resolvedWranglerState;
}

const apiDevVarsPath = resolve(apiDir, ".dev.vars");
const storefrontDevVarsPath = resolve(storefrontDir, ".dev.vars");
const existingApiVars = readEnvVarsIfExists(apiDevVarsPath);
const existingStorefrontVars = readEnvVarsIfExists(storefrontDevVarsPath);
const { scaliusSecret, credentialEncryptionKey } = resolveSharedLocalSecrets({
  forceRegenerate,
  apiVars: existingApiVars,
  storefrontVars: existingStorefrontVars,
});

const apiDevVars = {
  SCALIUS_SECRET: scaliusSecret,
  CREDENTIAL_ENCRYPTION_KEY: credentialEncryptionKey,
};

const storefrontDevVars = {
  SCALIUS_SECRET: scaliusSecret,
};

if (showHelp) {
  console.log(`
Usage: pnpm dev:setup [options]

Options:
  --force                    Regenerate local .dev.vars files (new secrets)
  --env-only                 Create/repair .dev.vars files only; skip install, migrations, admin
  --skip-install             Do not run pnpm install
  --skip-admin               Do not create the default local admin
  --admin-email <email>      Local admin email (default: ${localAdminEmail})
  --admin-password <value>   Local admin password, 12+ chars (or LOCAL_ADMIN_PASSWORD)
  --admin-name <name>        Local admin name (default: ${localAdminName})
  --state <path>             Wrangler local state path; relative paths resolve from repo root
`);
  process.exit(0);
}

if (!skipAdmin && !envOnly) {
  try {
    assertPassword(localAdminPassword);
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}

function run(cmd, label, options = {}) {
  console.log(`\n▶ ${label}`);
  console.log(`  $ ${options.displayCommand ?? cmd}\n`);
  execSync(cmd, {
    cwd: root,
    stdio: "inherit",
    env: { ...process.env, ...options.env },
  });
}

function appendMissingEnvVars(filePath, expectedValues, label) {
  const currentValues = readEnvVarsIfExists(filePath);
  if (!currentValues) return;

  const missingEntries = Object.entries(expectedValues).filter(([key]) => {
    const current = currentValues[key];
    return !current || current.trim() === "" || current.trim() === "<auto-generated>";
  });
  if (missingEntries.length === 0) return;

  const block = [
    "",
    "# Added by pnpm dev:setup to repair local development env.",
    ...missingEntries.map(([key, value]) => `${key}=${value}`),
    "",
  ].join("\n");
  appendFileSync(filePath, block);
  console.log(`  ✓ Added missing ${missingEntries.map(([key]) => key).join(", ")} to ${label}`);
}

function writeDevVarsFile({ path, label, workerLabel, values, secretNotes }) {
  if (existsSync(path) && !forceRegenerate) {
    console.log(`\n⚡ ${label} already exists — skipping (use --force to regenerate)`);
  } else {
    console.log(`\n▶ Generating secrets and creating ${label}`);
    const lines = [
      "# Auto-generated by: pnpm dev:setup",
      `# Installed secrets for local development (${workerLabel}).`,
      "# URLs are never configured here: Workers read them from the dashboard",
      "# (Settings -> System -> Platform) and fall back to localhost ports in dev.",
      "",
      ...Object.entries(values).flatMap(([key, value]) => [
        `# ${secretNotes[key]}`,
        `${key}=${value}`,
      ]),
      "",
    ];
    writeFileSync(path, lines.join("\n"));
    console.log(`  ✓ Created ${label}`);
  }
  appendMissingEnvVars(path, values, label);
}

const secretNotes = {
  SCALIUS_SECRET: "Master secret; identical across API and storefront (>= 32 chars).",
  CREDENTIAL_ENCRYPTION_KEY: "AES-256 key for merchant credentials at rest (API only).",
};

console.log("\n🚀 Scalius Commerce — Local Development Setup\n");
console.log("=".repeat(55));

// 1. Install dependencies
if (skipInstall || envOnly) {
  console.log("\n⚡ Skipping dependency install");
} else {
  run(`${pnpm} install`, "Installing dependencies");
}

// 2. Create .dev.vars for all Workers. Existing usable secrets are reused so
// partially missing local env files do not desynchronize API/storefront.
writeDevVarsFile({
  path: apiDevVarsPath,
  label: "apps/api/.dev.vars",
  workerLabel: "API Worker",
  values: apiDevVars,
  secretNotes,
});
writeDevVarsFile({
  path: storefrontDevVarsPath,
  label: "apps/storefront/.dev.vars",
  workerLabel: "Storefront Worker",
  values: storefrontDevVars,
  secretNotes,
});

const writtenApiVars = readEnvVarsIfExists(apiDevVarsPath);
const writtenStorefrontVars = readEnvVarsIfExists(storefrontDevVarsPath);

assertLocalSecretSync({
  apiVars: writtenApiVars,
  storefrontVars: writtenStorefrontVars,
});

// Earlier setups wrote per-purpose secrets and localhost URLs. Workers no
// longer read them; they are harmless but confusing, so say so once.
const staleIssues = collectStaleLocalEnvIssues({
  apiVars: writtenApiVars,
  storefrontVars: writtenStorefrontVars,
});
// The dashboard is a static SPA served by the API Worker; it reads no env.
const staleBuildEnvFiles = [
  ["apps/admin-v2/.dev.vars", resolve(adminDir, ".dev.vars")],
  ["apps/admin-v2/.env.development", resolve(adminDir, ".env.development")],
  ["apps/storefront/.env.development", resolve(storefrontDir, ".env.development")],
].filter(([, path]) => existsSync(path)).map(([label]) => label);
if (staleIssues.length > 0 || staleBuildEnvFiles.length > 0) {
  console.log("\n⚠ Retired local env entries detected (no Worker reads them any more):");
  for (const issue of staleIssues) console.log(`  - ${issue}`);
  for (const label of staleBuildEnvFiles) {
    console.log(`  - ${label} is no longer generated or read; delete it`);
  }
  console.log("  Run pnpm dev:setup --force --env-only to rewrite .dev.vars with only the installed secrets.");
}

if (envOnly) {
  console.log("\n⚡ Env-only mode: skipping local D1 migrations and admin creation");
} else {
  // 3. Apply local D1 migrations (via API worker's wrangler config)
  run(
    "node scripts/deploy.mjs --migrate-only --local",
    "Applying local D1 migrations"
  );
}

// 4. Create default local admin through the same setup endpoint used by the UI.
if (envOnly) {
  // Already handled above.
} else if (skipAdmin) {
  console.log("\n⚡ Skipping local admin creation");
} else {
  run(
    [
      "node scripts/dev-admin.mjs create",
      "--skip-migrations",
      ...(resolvedWranglerState ? [`--state ${shellQuote(resolvedWranglerState)}`] : []),
    ].join(" "),
    "Creating default local admin if needed",
    {
      displayCommand: "node scripts/dev-admin.mjs create --skip-migrations (credentials via environment)",
      env: {
        LOCAL_ADMIN_EMAIL: localAdminEmail,
        LOCAL_ADMIN_PASSWORD: localAdminPassword,
        LOCAL_ADMIN_NAME: localAdminName,
      },
    },
  );
}

console.log("\n" + "=".repeat(55));
console.log(envOnly ? "✅ Env repair complete!\n" : "✅ Setup complete!\n");
console.log("Next steps:");
if (envOnly) {
  console.log("  1. pnpm dev:doctor   — Re-check local readiness");
  console.log("  2. pnpm dev:setup    — Apply migrations and create local admin if needed");
  console.log("  3. pnpm dev          — Start API + admin + storefront\n");
} else {
  console.log("  1. pnpm dev          — Start API + admin + storefront");
  console.log("  2. http://localhost:4323/admin");
  if (!skipAdmin) {
    console.log(`  3. Sign in as ${localAdminEmail} with the configured local admin password.\n`);
  } else {
    console.log("  3. Create the first admin in the browser or run pnpm dev:admin:create\n");
  }
}
