#!/usr/bin/env node
/**
 * dev-setup.mjs — One-command local development setup
 *
 * Usage: pnpm dev:setup
 *
 * 1. Installs dependencies
 * 2. Generates secrets and creates .dev.vars (Cloudflare runtime bindings)
 * 3. Creates .env.development (Vite/Astro build-time vars)
 * 4. Applies local D1 migrations
 */

import { execSync } from "child_process";
import { existsSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import crypto from "crypto";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const args = process.argv.slice(2);
const forceRegenerate = args.includes("--force");

function run(cmd, label) {
  console.log(`\n▶ ${label}`);
  console.log(`  $ ${cmd}\n`);
  execSync(cmd, { cwd: root, stdio: "inherit" });
}

function generateSecret() {
  return crypto.randomBytes(32).toString("base64");
}

console.log("\n🚀 Scalius Commerce Lite — Local Development Setup\n");
console.log("=".repeat(55));

// 1. Install dependencies
run("pnpm install", "Installing dependencies");

// 2. Create .dev.vars (Cloudflare runtime bindings / secrets)
//    These override the production values in wrangler.jsonc for local dev.
const devVarsPath = resolve(root, ".dev.vars");
if (existsSync(devVarsPath) && !forceRegenerate) {
  console.log(
    "\n⚡ .dev.vars already exists — skipping (use --force to regenerate)"
  );
} else {
  console.log("\n▶ Generating secrets and creating .dev.vars");
  const betterAuthSecret = generateSecret();
  const jwtSecret = generateSecret();
  const apiToken = generateSecret();

  const devVars = [
    "# Auto-generated by: pnpm dev:setup",
    "# Cloudflare runtime bindings for local development.",
    "# These override the production values in wrangler.jsonc.",
    "",
    "# ── Secrets ──",
    `BETTER_AUTH_SECRET=${betterAuthSecret}`,
    `JWT_SECRET=${jwtSecret}`,
    `API_TOKEN=${apiToken}`,
    "",
    "# ── Local overrides (override wrangler.jsonc production URLs) ──",
    "BETTER_AUTH_URL=http://localhost:4321",
    "PUBLIC_API_BASE_URL=http://localhost:4321",
    "STOREFRONT_URL=http://localhost:4322",
    "",
  ].join("\n");

  writeFileSync(devVarsPath, devVars);
  console.log("  ✓ Created .dev.vars with generated secrets");
}

// 3. Create .env.development (Vite/Astro build-time vars)
//    .dev.vars handles Cloudflare runtime bindings (accessible via env.VAR_NAME in Workers).
//    .env.development handles Vite build-time vars (accessible via import.meta.env.VAR_NAME).
//    Both are needed because Vite does NOT read .dev.vars.
const envDevPath = resolve(root, ".env.development");
if (existsSync(envDevPath) && !forceRegenerate) {
  console.log(
    "\n⚡ .env.development already exists — skipping (use --force to regenerate)"
  );
} else {
  console.log("\n▶ Creating .env.development for Vite/Astro build-time vars");
  const envDev = [
    "# Auto-generated by: pnpm dev:setup",
    "# Vite/Astro build-time variables (available via import.meta.env.*)",
    "# .dev.vars handles Cloudflare runtime bindings; this file handles Vite.",
    "PUBLIC_API_BASE_URL=http://localhost:4321",
    "",
  ].join("\n");

  writeFileSync(envDevPath, envDev);
  console.log("  ✓ Created .env.development");
}

// 4. Apply local D1 migrations
run(
  "node scripts/deploy.mjs --migrate-only --local",
  "Applying local D1 migrations"
);

console.log("\n" + "=".repeat(55));
console.log("✅ Setup complete! Run:\n");
console.log(
  "   pnpm dev          → Start dev server (http://localhost:4321)"
);
console.log(
  "   pnpm dev:reset    → Reset local database to a clean state"
);
console.log("   pnpm db:studio    → Open Drizzle Studio (DB browser)\n");
