#!/usr/bin/env node
/**
 * dev-setup.mjs — One-command local development setup
 *
 * Usage: pnpm dev:setup
 *
 * 1. Installs dependencies
 * 2. Generates secrets and creates .dev.vars for all three apps
 * 3. Creates .env.development for admin + storefront (Vite/Astro build-time vars)
 * 4. Applies local D1 migrations
 * 5. Creates the default local admin account unless --skip-admin is passed
 */

import { execSync } from "child_process";
import { existsSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import crypto from "crypto";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const adminDir = resolve(root, "apps", "admin-v2");
const apiDir = resolve(root, "apps", "api");
const storefrontDir = resolve(root, "apps", "storefront");
const args = process.argv.slice(2);
const forceRegenerate = args.includes("--force");
const skipInstall = args.includes("--skip-install");
const skipAdmin = args.includes("--skip-admin");
const showHelp = args.includes("--help") || args.includes("-h");

const localAdminEmail = getArgValue("--admin-email") || process.env.LOCAL_ADMIN_EMAIL || "admin@local.scalius.test";
const localAdminPassword = getArgValue("--admin-password") || process.env.LOCAL_ADMIN_PASSWORD || "ScaliusLocal123!";
const localAdminName = getArgValue("--admin-name") || process.env.LOCAL_ADMIN_NAME || "Local Admin";

if (showHelp) {
  console.log(`
Usage: pnpm dev:setup [options]

Options:
  --force                    Regenerate local env files
  --skip-install             Do not run pnpm install
  --skip-admin               Do not create the default local admin
  --admin-email <email>      Local admin email (default: ${localAdminEmail})
  --admin-password <value>   Local admin password, 12+ chars (default: ${localAdminPassword})
  --admin-name <name>        Local admin name (default: ${localAdminName})
`);
  process.exit(0);
}

function run(cmd, label) {
  console.log(`\n▶ ${label}`);
  console.log(`  $ ${cmd}\n`);
  execSync(cmd, { cwd: root, stdio: "inherit" });
}

function generateSecret() {
  return crypto.randomBytes(32).toString("base64");
}

function getArgValue(name) {
  const inline = args.find((arg) => arg.startsWith(`${name}=`));
  if (inline) return inline.slice(name.length + 1);
  const index = args.indexOf(name);
  if (index >= 0) return args[index + 1];
  return undefined;
}

function shellQuote(value) {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

console.log("\n🚀 Scalius Commerce — Local Development Setup\n");
console.log("=".repeat(55));

// 1. Install dependencies
if (skipInstall) {
  console.log("\n⚡ Skipping dependency install");
} else {
  run("pnpm install", "Installing dependencies");
}

// 2. Create .dev.vars for both apps
const betterAuthSecret = generateSecret();
const jwtSecret = generateSecret();
const apiToken = generateSecret();
const purgeToken = generateSecret();
const credentialEncryptionKey = generateSecret();

// API Worker .dev.vars
const apiDevVarsPath = resolve(apiDir, ".dev.vars");
if (existsSync(apiDevVarsPath) && !forceRegenerate) {
  console.log(
    "\n⚡ apps/api/.dev.vars already exists — skipping (use --force to regenerate)"
  );
} else {
  console.log("\n▶ Generating secrets and creating apps/api/.dev.vars");
  const devVars = [
    "# Auto-generated by: pnpm dev:setup",
    "# Cloudflare runtime bindings for local development (API Worker).",
    "",
    "# ── Secrets ──",
    `BETTER_AUTH_SECRET=${betterAuthSecret}`,
    `JWT_SECRET=${jwtSecret}`,
    `API_TOKEN=${apiToken}`,
    `CREDENTIAL_ENCRYPTION_KEY=${credentialEncryptionKey}`,
    "",
    "# ── Local overrides ──",
    "BETTER_AUTH_URL=http://localhost:4323",
    "PUBLIC_API_BASE_URL=http://localhost:8787",
    "STOREFRONT_URL=http://localhost:4322",
    "R2_PUBLIC_URL=http://localhost:8787/api/v1/media",
    "",
  ].join("\n");
  writeFileSync(apiDevVarsPath, devVars);
  console.log("  ✓ Created apps/api/.dev.vars");
}

// Admin Worker .dev.vars
const adminDevVarsPath = resolve(adminDir, ".dev.vars");
if (existsSync(adminDevVarsPath) && !forceRegenerate) {
  console.log(
    "\n⚡ apps/admin-v2/.dev.vars already exists — skipping (use --force to regenerate)"
  );
} else {
  console.log("\n▶ Generating secrets and creating apps/admin-v2/.dev.vars");
  // Use the SAME secrets as API so both workers can validate tokens
  const devVars = [
    "# Auto-generated by: pnpm dev:setup",
    "# Cloudflare runtime bindings for local development (Admin V2 Worker).",
    "",
    "# ── Secrets (must match API worker) ──",
    `BETTER_AUTH_SECRET=${betterAuthSecret}`,
    `JWT_SECRET=${jwtSecret}`,
    `API_TOKEN=${apiToken}`,
    `CREDENTIAL_ENCRYPTION_KEY=${credentialEncryptionKey}`,
    "",
    "# ── Local overrides ──",
    "BETTER_AUTH_URL=http://localhost:4323",
    "PUBLIC_API_BASE_URL=http://localhost:8787",
    "STOREFRONT_URL=http://localhost:4322",
    "R2_PUBLIC_URL=http://localhost:8787/api/v1/media",
    "",
  ].join("\n");
  writeFileSync(adminDevVarsPath, devVars);
  console.log("  ✓ Created apps/admin-v2/.dev.vars");
}

// Storefront Worker .dev.vars
const storefrontDevVarsPath = resolve(storefrontDir, ".dev.vars");
if (existsSync(storefrontDevVarsPath) && !forceRegenerate) {
  console.log(
    "\n⚡ apps/storefront/.dev.vars already exists — skipping (use --force to regenerate)"
  );
} else {
  console.log("\n▶ Generating secrets and creating apps/storefront/.dev.vars");
  const devVars = [
    "# Auto-generated by: pnpm dev:setup",
    "# Cloudflare runtime bindings for local development (Storefront Worker).",
    "",
    "# ── Secrets (must match API worker) ──",
    `API_TOKEN=${apiToken}`,
    `JWT_SECRET=${jwtSecret}`,
    `PURGE_TOKEN=${purgeToken}`,
    "",
    "# ── Local overrides ──",
    'PUBLIC_API_URL=http://localhost:8787/api/v1',
    'PUBLIC_API_BASE_URL=http://localhost:8787',
    'STOREFRONT_URL=http://localhost:4322',
    "",
  ].join("\n");
  writeFileSync(storefrontDevVarsPath, devVars);
  console.log("  ✓ Created apps/storefront/.dev.vars");
}

// 3. Create .env.development for admin-v2 app (Vite build-time vars)
const envDevPath = resolve(adminDir, ".env.development");
if (existsSync(envDevPath) && !forceRegenerate) {
  console.log(
    "\n⚡ apps/admin-v2/.env.development already exists — skipping (use --force to regenerate)"
  );
} else {
  console.log("\n▶ Creating apps/admin-v2/.env.development");
  const envDev = [
    "# Auto-generated by: pnpm dev:setup",
    "# Vite build-time variables (available via import.meta.env.*)",
    "PUBLIC_API_BASE_URL=http://localhost:8787",
    "",
  ].join("\n");
  writeFileSync(envDevPath, envDev);
  console.log("  ✓ Created apps/admin-v2/.env.development");
}

// Storefront .env.development (Vite/Astro build-time vars)
const storefrontEnvDevPath = resolve(storefrontDir, ".env.development");
if (existsSync(storefrontEnvDevPath) && !forceRegenerate) {
  console.log(
    "\n⚡ apps/storefront/.env.development already exists — skipping (use --force to regenerate)"
  );
} else {
  console.log("\n▶ Creating apps/storefront/.env.development");
  const envDev = [
    "# Auto-generated by: pnpm dev:setup",
    "# Vite/Astro build-time variables (available via import.meta.env.*)",
    "PUBLIC_API_URL=http://localhost:8787/api/v1",
    "PUBLIC_API_BASE_URL=http://localhost:8787",
    "STOREFRONT_URL=http://localhost:4322",
    "",
  ].join("\n");
  writeFileSync(storefrontEnvDevPath, envDev);
  console.log("  ✓ Created apps/storefront/.env.development");
}

// 4. Apply local D1 migrations (via API worker's wrangler config)
run(
  "node scripts/deploy.mjs --migrate-only --local",
  "Applying local D1 migrations"
);

// 5. Create default local admin through the same setup endpoint used by the UI.
if (skipAdmin) {
  console.log("\n⚡ Skipping local admin creation");
} else {
  run(
    [
      "node scripts/dev-admin.mjs create",
      `--email ${shellQuote(localAdminEmail)}`,
      `--password ${shellQuote(localAdminPassword)}`,
      `--name ${shellQuote(localAdminName)}`,
    ].join(" "),
    "Creating default local admin if needed",
  );
}

console.log("\n" + "=".repeat(55));
console.log("✅ Setup complete!\n");
console.log("Next steps:");
console.log("  1. pnpm dev          — Start API + admin + storefront");
console.log("  2. http://localhost:4323/admin");
if (!skipAdmin) {
  console.log(`  3. Sign in with ${localAdminEmail} / ${localAdminPassword}\n`);
} else {
  console.log("  3. Create the first admin in the browser or run pnpm dev:admin:create\n");
}
