/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccessDeniedRouteImport } from './routes/admin/access-denied'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as AdminAttributesRouteImport } from './routes/admin/attributes'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminSettingsRouteRouteImport } from './routes/admin/settings/route'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSetupRouteImport } from './routes/auth/setup'
import { Route as AuthSetup2faRouteImport } from './routes/auth/setup-2fa'
import { Route as AuthTwoFactorRouteImport } from './routes/auth/two-factor'
import { Route as InvoiceOrderIdRouteImport } from './routes/invoice.$orderId'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin/articles/index'
import { Route as AdminArticlesNewRouteImport } from './routes/admin/articles/new'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AdminCategoriesNewRouteImport } from './routes/admin/categories/new'
import { Route as AdminCollectionsIndexRouteImport } from './routes/admin/collections/index'
import { Route as AdminCollectionsNewRouteImport } from './routes/admin/collections/new'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AdminCustomersNewRouteImport } from './routes/admin/customers/new'
import { Route as AdminDiscountsIndexRouteImport } from './routes/admin/discounts/index'
import { Route as AdminDiscountsDiscountIdRouteImport } from './routes/admin/discounts/$discountId'
import { Route as AdminDiscountsNewRouteImport } from './routes/admin/discounts/new'
import { Route as AdminInventoryIndexRouteImport } from './routes/admin/inventory/index'
import { Route as AdminInventoryLabelsRouteImport } from './routes/admin/inventory/labels'
import { Route as AdminOnlineStoreBannersRouteImport } from './routes/admin/online-store/banners'
import { Route as AdminOnlineStorePreferencesRouteImport } from './routes/admin/online-store/preferences'
import { Route as AdminOnlineStoreThemeRouteImport } from './routes/admin/online-store/theme'
import { Route as AdminOrdersListRouteImport } from './routes/admin/orders/_list'
import { Route as AdminOrdersNewRouteImport } from './routes/admin/orders/new'
import { Route as AdminPagesIndexRouteImport } from './routes/admin/pages/index'
import { Route as AdminPagesNewRouteImport } from './routes/admin/pages/new'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminSettingsAdvancedRouteImport } from './routes/admin/settings/advanced'
import { Route as AdminSettingsAppsRouteImport } from './routes/admin/settings/apps'
import { Route as AdminSettingsCheckoutRouteImport } from './routes/admin/settings/checkout'
import { Route as AdminSettingsCustomerAccountsRouteImport } from './routes/admin/settings/customer-accounts'
import { Route as AdminSettingsNotificationsRouteImport } from './routes/admin/settings/notifications'
import { Route as AdminSettingsPaymentsRouteImport } from './routes/admin/settings/payments'
import { Route as AdminSettingsPoliciesRouteImport } from './routes/admin/settings/policies'
import { Route as AdminSettingsShippingRouteImport } from './routes/admin/settings/shipping'
import { Route as AdminSettingsStoreRouteImport } from './routes/admin/settings/store'
import { Route as AdminSettingsTaxesRouteImport } from './routes/admin/settings/taxes'
import { Route as AdminSettingsUsersRouteImport } from './routes/admin/settings/users'
import { Route as AdminArticlesArticleIdEditRouteImport } from './routes/admin/articles/$articleId/edit'
import { Route as AdminCategoriesCategoryIdEditRouteImport } from './routes/admin/categories/$categoryId/edit'
import { Route as AdminCollectionsCollectionIdEditRouteImport } from './routes/admin/collections/$collectionId/edit'
import { Route as AdminCustomersCustomerIdEditRouteImport } from './routes/admin/customers/$customerId/edit'
import { Route as AdminOnlineStoreNavigationIndexRouteImport } from './routes/admin/online-store/navigation/index'
import { Route as AdminOnlineStoreNavigationMenuIdRouteImport } from './routes/admin/online-store/navigation/$menuId'
import { Route as AdminOrdersOrderIdIndexRouteImport } from './routes/admin/orders/$orderId/index'
import { Route as AdminOrdersOrderIdEditRouteImport } from './routes/admin/orders/$orderId/edit'
import { Route as AdminOrdersListIndexRouteImport } from './routes/admin/orders/_list/index'
import { Route as AdminOrdersListAbandonedRouteImport } from './routes/admin/orders/_list/abandoned'
import { Route as AdminPagesPageIdEditRouteImport } from './routes/admin/pages/$pageId/edit'
import { Route as AdminProductsProductIdEditRouteImport } from './routes/admin/products/$productId/edit'
import { Route as AdminSettingsNotificationsEventRouteImport } from './routes/admin/settings/notifications_.$event'
import { Route as AdminSettingsShippingAreasRouteImport } from './routes/admin/settings/shipping_.areas'
import { Route as AdminSettingsUsersUserIdRouteImport } from './routes/admin/settings/users_.$userId'
import { Route as AdminOrdersListAbandonedCheckoutIdRouteImport } from './routes/admin/orders/_list/abandoned.$checkoutId'
import { Route as AdminSettingsAgentAccessAuthorizeRequestIdRouteImport } from './routes/admin/settings/agent-access.authorize.$requestId'
import { Route as AdminSettingsAgentAccessContinueHandoffIdRouteImport } from './routes/admin/settings/agent-access.continue.$handoffId'
import { Route as AdminSettingsUsersRolesRoleIdRouteImport } from './routes/admin/settings/users_.roles.$roleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessDeniedRoute = AdminAccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttributesRoute = AdminAttributesRouteImport.update({
  id: '/attributes',
  path: '/attributes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetup2faRoute = AuthSetup2faRouteImport.update({
  id: '/setup-2fa',
  path: '/setup-2fa',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthRoute,
} as any)
const InvoiceOrderIdRoute = InvoiceOrderIdRouteImport.update({
  id: '/invoice/$orderId',
  path: '/invoice/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesNewRoute = AdminCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsIndexRoute = AdminCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsNewRoute = AdminCollectionsNewRouteImport.update({
  id: '/collections/new',
  path: '/collections/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersNewRoute = AdminCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsIndexRoute = AdminDiscountsIndexRouteImport.update({
  id: '/discounts/',
  path: '/discounts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsDiscountIdRoute =
  AdminDiscountsDiscountIdRouteImport.update({
    id: '/discounts/$discountId',
    path: '/discounts/$discountId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDiscountsNewRoute = AdminDiscountsNewRouteImport.update({
  id: '/discounts/new',
  path: '/discounts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryIndexRoute = AdminInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryLabelsRoute = AdminInventoryLabelsRouteImport.update({
  id: '/inventory/labels',
  path: '/inventory/labels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnlineStoreBannersRoute = AdminOnlineStoreBannersRouteImport.update({
  id: '/online-store/banners',
  path: '/online-store/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnlineStorePreferencesRoute =
  AdminOnlineStorePreferencesRouteImport.update({
    id: '/online-store/preferences',
    path: '/online-store/preferences',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOnlineStoreThemeRoute = AdminOnlineStoreThemeRouteImport.update({
  id: '/online-store/theme',
  path: '/online-store/theme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersListRoute = AdminOrdersListRouteImport.update({
  id: '/orders/_list',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersNewRoute = AdminOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesNewRoute = AdminPagesNewRouteImport.update({
  id: '/pages/new',
  path: '/pages/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsAdvancedRoute = AdminSettingsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsAppsRoute = AdminSettingsAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsCheckoutRoute = AdminSettingsCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsCustomerAccountsRoute =
  AdminSettingsCustomerAccountsRouteImport.update({
    id: '/customer-accounts',
    path: '/customer-accounts',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsNotificationsRoute =
  AdminSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsPaymentsRoute = AdminSettingsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsPoliciesRoute = AdminSettingsPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsShippingRoute = AdminSettingsShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsStoreRoute = AdminSettingsStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsTaxesRoute = AdminSettingsTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsUsersRoute = AdminSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminArticlesArticleIdEditRoute =
  AdminArticlesArticleIdEditRouteImport.update({
    id: '/articles/$articleId/edit',
    path: '/articles/$articleId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCategoriesCategoryIdEditRoute =
  AdminCategoriesCategoryIdEditRouteImport.update({
    id: '/categories/$categoryId/edit',
    path: '/categories/$categoryId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCollectionsCollectionIdEditRoute =
  AdminCollectionsCollectionIdEditRouteImport.update({
    id: '/collections/$collectionId/edit',
    path: '/collections/$collectionId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCustomersCustomerIdEditRoute =
  AdminCustomersCustomerIdEditRouteImport.update({
    id: '/customers/$customerId/edit',
    path: '/customers/$customerId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOnlineStoreNavigationIndexRoute =
  AdminOnlineStoreNavigationIndexRouteImport.update({
    id: '/online-store/navigation/',
    path: '/online-store/navigation/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOnlineStoreNavigationMenuIdRoute =
  AdminOnlineStoreNavigationMenuIdRouteImport.update({
    id: '/online-store/navigation/$menuId',
    path: '/online-store/navigation/$menuId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrdersOrderIdIndexRoute = AdminOrdersOrderIdIndexRouteImport.update({
  id: '/orders/$orderId/',
  path: '/orders/$orderId/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersOrderIdEditRoute = AdminOrdersOrderIdEditRouteImport.update({
  id: '/orders/$orderId/edit',
  path: '/orders/$orderId/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersListIndexRoute = AdminOrdersListIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrdersListRoute,
} as any)
const AdminOrdersListAbandonedRoute =
  AdminOrdersListAbandonedRouteImport.update({
    id: '/abandoned',
    path: '/abandoned',
    getParentRoute: () => AdminOrdersListRoute,
  } as any)
const AdminPagesPageIdEditRoute = AdminPagesPageIdEditRouteImport.update({
  id: '/pages/$pageId/edit',
  path: '/pages/$pageId/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsProductIdEditRoute =
  AdminProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSettingsNotificationsEventRoute =
  AdminSettingsNotificationsEventRouteImport.update({
    id: '/notifications_/$event',
    path: '/notifications/$event',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsShippingAreasRoute =
  AdminSettingsShippingAreasRouteImport.update({
    id: '/shipping_/areas',
    path: '/shipping/areas',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsUsersUserIdRoute =
  AdminSettingsUsersUserIdRouteImport.update({
    id: '/users_/$userId',
    path: '/users/$userId',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminOrdersListAbandonedCheckoutIdRoute =
  AdminOrdersListAbandonedCheckoutIdRouteImport.update({
    id: '/$checkoutId',
    path: '/$checkoutId',
    getParentRoute: () => AdminOrdersListAbandonedRoute,
  } as any)
const AdminSettingsAgentAccessAuthorizeRequestIdRoute =
  AdminSettingsAgentAccessAuthorizeRequestIdRouteImport.update({
    id: '/agent-access/authorize/$requestId',
    path: '/agent-access/authorize/$requestId',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsAgentAccessContinueHandoffIdRoute =
  AdminSettingsAgentAccessContinueHandoffIdRouteImport.update({
    id: '/agent-access/continue/$handoffId',
    path: '/agent-access/continue/$handoffId',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsUsersRolesRoleIdRoute =
  AdminSettingsUsersRolesRoleIdRouteImport.update({
    id: '/users_/roles/$roleId',
    path: '/users/roles/$roleId',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/connect': typeof ConnectRoute
  '/invoices': typeof InvoicesRoute
  '/scanner': typeof ScannerRoute
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/admin/access-denied': typeof AdminAccessDeniedRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/attributes': typeof AdminAttributesRoute
  '/admin/media': typeof AdminMediaRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup': typeof AuthSetupRoute
  '/auth/setup-2fa': typeof AuthSetup2faRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/invoice/$orderId': typeof InvoiceOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/discounts/$discountId': typeof AdminDiscountsDiscountIdRoute
  '/admin/discounts/new': typeof AdminDiscountsNewRoute
  '/admin/inventory/labels': typeof AdminInventoryLabelsRoute
  '/admin/online-store/banners': typeof AdminOnlineStoreBannersRoute
  '/admin/online-store/preferences': typeof AdminOnlineStorePreferencesRoute
  '/admin/online-store/theme': typeof AdminOnlineStoreThemeRoute
  '/admin/orders': typeof AdminOrdersListRouteWithChildren
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/settings/advanced': typeof AdminSettingsAdvancedRoute
  '/admin/settings/apps': typeof AdminSettingsAppsRoute
  '/admin/settings/checkout': typeof AdminSettingsCheckoutRoute
  '/admin/settings/customer-accounts': typeof AdminSettingsCustomerAccountsRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/payments': typeof AdminSettingsPaymentsRoute
  '/admin/settings/policies': typeof AdminSettingsPoliciesRoute
  '/admin/settings/shipping': typeof AdminSettingsShippingRoute
  '/admin/settings/store': typeof AdminSettingsStoreRoute
  '/admin/settings/taxes': typeof AdminSettingsTaxesRoute
  '/admin/settings/users': typeof AdminSettingsUsersRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/discounts/': typeof AdminDiscountsIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/articles/$articleId/edit': typeof AdminArticlesArticleIdEditRoute
  '/admin/categories/$categoryId/edit': typeof AdminCategoriesCategoryIdEditRoute
  '/admin/collections/$collectionId/edit': typeof AdminCollectionsCollectionIdEditRoute
  '/admin/customers/$customerId/edit': typeof AdminCustomersCustomerIdEditRoute
  '/admin/online-store/navigation/$menuId': typeof AdminOnlineStoreNavigationMenuIdRoute
  '/admin/orders/$orderId/edit': typeof AdminOrdersOrderIdEditRoute
  '/admin/orders/abandoned': typeof AdminOrdersListAbandonedRouteWithChildren
  '/admin/pages/$pageId/edit': typeof AdminPagesPageIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/admin/settings/notifications/$event': typeof AdminSettingsNotificationsEventRoute
  '/admin/settings/shipping/areas': typeof AdminSettingsShippingAreasRoute
  '/admin/settings/users/$userId': typeof AdminSettingsUsersUserIdRoute
  '/admin/online-store/navigation/': typeof AdminOnlineStoreNavigationIndexRoute
  '/admin/orders/$orderId/': typeof AdminOrdersOrderIdIndexRoute
  '/admin/orders/': typeof AdminOrdersListIndexRoute
  '/admin/orders/abandoned/$checkoutId': typeof AdminOrdersListAbandonedCheckoutIdRoute
  '/admin/settings/agent-access/authorize/$requestId': typeof AdminSettingsAgentAccessAuthorizeRequestIdRoute
  '/admin/settings/agent-access/continue/$handoffId': typeof AdminSettingsAgentAccessContinueHandoffIdRoute
  '/admin/settings/users/roles/$roleId': typeof AdminSettingsUsersRolesRoleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/connect': typeof ConnectRoute
  '/invoices': typeof InvoicesRoute
  '/scanner': typeof ScannerRoute
  '/admin/access-denied': typeof AdminAccessDeniedRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/attributes': typeof AdminAttributesRoute
  '/admin/media': typeof AdminMediaRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup': typeof AuthSetupRoute
  '/auth/setup-2fa': typeof AuthSetup2faRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/invoice/$orderId': typeof InvoiceOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/discounts/$discountId': typeof AdminDiscountsDiscountIdRoute
  '/admin/discounts/new': typeof AdminDiscountsNewRoute
  '/admin/inventory/labels': typeof AdminInventoryLabelsRoute
  '/admin/online-store/banners': typeof AdminOnlineStoreBannersRoute
  '/admin/online-store/preferences': typeof AdminOnlineStorePreferencesRoute
  '/admin/online-store/theme': typeof AdminOnlineStoreThemeRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/settings/advanced': typeof AdminSettingsAdvancedRoute
  '/admin/settings/apps': typeof AdminSettingsAppsRoute
  '/admin/settings/checkout': typeof AdminSettingsCheckoutRoute
  '/admin/settings/customer-accounts': typeof AdminSettingsCustomerAccountsRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/payments': typeof AdminSettingsPaymentsRoute
  '/admin/settings/policies': typeof AdminSettingsPoliciesRoute
  '/admin/settings/shipping': typeof AdminSettingsShippingRoute
  '/admin/settings/store': typeof AdminSettingsStoreRoute
  '/admin/settings/taxes': typeof AdminSettingsTaxesRoute
  '/admin/settings/users': typeof AdminSettingsUsersRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/collections': typeof AdminCollectionsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/discounts': typeof AdminDiscountsIndexRoute
  '/admin/inventory': typeof AdminInventoryIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/articles/$articleId/edit': typeof AdminArticlesArticleIdEditRoute
  '/admin/categories/$categoryId/edit': typeof AdminCategoriesCategoryIdEditRoute
  '/admin/collections/$collectionId/edit': typeof AdminCollectionsCollectionIdEditRoute
  '/admin/customers/$customerId/edit': typeof AdminCustomersCustomerIdEditRoute
  '/admin/online-store/navigation/$menuId': typeof AdminOnlineStoreNavigationMenuIdRoute
  '/admin/orders/$orderId/edit': typeof AdminOrdersOrderIdEditRoute
  '/admin/orders/abandoned': typeof AdminOrdersListAbandonedRouteWithChildren
  '/admin/pages/$pageId/edit': typeof AdminPagesPageIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/admin/settings/notifications/$event': typeof AdminSettingsNotificationsEventRoute
  '/admin/settings/shipping/areas': typeof AdminSettingsShippingAreasRoute
  '/admin/settings/users/$userId': typeof AdminSettingsUsersUserIdRoute
  '/admin/online-store/navigation': typeof AdminOnlineStoreNavigationIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdIndexRoute
  '/admin/orders': typeof AdminOrdersListIndexRoute
  '/admin/orders/abandoned/$checkoutId': typeof AdminOrdersListAbandonedCheckoutIdRoute
  '/admin/settings/agent-access/authorize/$requestId': typeof AdminSettingsAgentAccessAuthorizeRequestIdRoute
  '/admin/settings/agent-access/continue/$handoffId': typeof AdminSettingsAgentAccessContinueHandoffIdRoute
  '/admin/settings/users/roles/$roleId': typeof AdminSettingsUsersRolesRoleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/connect': typeof ConnectRoute
  '/invoices': typeof InvoicesRoute
  '/scanner': typeof ScannerRoute
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/admin/access-denied': typeof AdminAccessDeniedRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/attributes': typeof AdminAttributesRoute
  '/admin/media': typeof AdminMediaRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup': typeof AuthSetupRoute
  '/auth/setup-2fa': typeof AuthSetup2faRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/invoice/$orderId': typeof InvoiceOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/discounts/$discountId': typeof AdminDiscountsDiscountIdRoute
  '/admin/discounts/new': typeof AdminDiscountsNewRoute
  '/admin/inventory/labels': typeof AdminInventoryLabelsRoute
  '/admin/online-store/banners': typeof AdminOnlineStoreBannersRoute
  '/admin/online-store/preferences': typeof AdminOnlineStorePreferencesRoute
  '/admin/online-store/theme': typeof AdminOnlineStoreThemeRoute
  '/admin/orders/_list': typeof AdminOrdersListRouteWithChildren
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/settings/advanced': typeof AdminSettingsAdvancedRoute
  '/admin/settings/apps': typeof AdminSettingsAppsRoute
  '/admin/settings/checkout': typeof AdminSettingsCheckoutRoute
  '/admin/settings/customer-accounts': typeof AdminSettingsCustomerAccountsRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/payments': typeof AdminSettingsPaymentsRoute
  '/admin/settings/policies': typeof AdminSettingsPoliciesRoute
  '/admin/settings/shipping': typeof AdminSettingsShippingRoute
  '/admin/settings/store': typeof AdminSettingsStoreRoute
  '/admin/settings/taxes': typeof AdminSettingsTaxesRoute
  '/admin/settings/users': typeof AdminSettingsUsersRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/discounts/': typeof AdminDiscountsIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/articles/$articleId/edit': typeof AdminArticlesArticleIdEditRoute
  '/admin/categories/$categoryId/edit': typeof AdminCategoriesCategoryIdEditRoute
  '/admin/collections/$collectionId/edit': typeof AdminCollectionsCollectionIdEditRoute
  '/admin/customers/$customerId/edit': typeof AdminCustomersCustomerIdEditRoute
  '/admin/online-store/navigation/$menuId': typeof AdminOnlineStoreNavigationMenuIdRoute
  '/admin/orders/$orderId/edit': typeof AdminOrdersOrderIdEditRoute
  '/admin/orders/_list/abandoned': typeof AdminOrdersListAbandonedRouteWithChildren
  '/admin/pages/$pageId/edit': typeof AdminPagesPageIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/admin/settings/notifications_/$event': typeof AdminSettingsNotificationsEventRoute
  '/admin/settings/shipping_/areas': typeof AdminSettingsShippingAreasRoute
  '/admin/settings/users_/$userId': typeof AdminSettingsUsersUserIdRoute
  '/admin/online-store/navigation/': typeof AdminOnlineStoreNavigationIndexRoute
  '/admin/orders/$orderId/': typeof AdminOrdersOrderIdIndexRoute
  '/admin/orders/_list/': typeof AdminOrdersListIndexRoute
  '/admin/orders/_list/abandoned/$checkoutId': typeof AdminOrdersListAbandonedCheckoutIdRoute
  '/admin/settings/agent-access/authorize/$requestId': typeof AdminSettingsAgentAccessAuthorizeRequestIdRoute
  '/admin/settings/agent-access/continue/$handoffId': typeof AdminSettingsAgentAccessContinueHandoffIdRoute
  '/admin/settings/users_/roles/$roleId': typeof AdminSettingsUsersRolesRoleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/connect'
    | '/invoices'
    | '/scanner'
    | '/admin/settings'
    | '/admin/access-denied'
    | '/admin/account'
    | '/admin/attributes'
    | '/admin/media'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/setup'
    | '/auth/setup-2fa'
    | '/auth/two-factor'
    | '/invoice/$orderId'
    | '/admin/'
    | '/admin/articles/new'
    | '/admin/categories/new'
    | '/admin/collections/new'
    | '/admin/customers/new'
    | '/admin/discounts/$discountId'
    | '/admin/discounts/new'
    | '/admin/inventory/labels'
    | '/admin/online-store/banners'
    | '/admin/online-store/preferences'
    | '/admin/online-store/theme'
    | '/admin/orders'
    | '/admin/orders/new'
    | '/admin/pages/new'
    | '/admin/products/new'
    | '/admin/settings/advanced'
    | '/admin/settings/apps'
    | '/admin/settings/checkout'
    | '/admin/settings/customer-accounts'
    | '/admin/settings/notifications'
    | '/admin/settings/payments'
    | '/admin/settings/policies'
    | '/admin/settings/shipping'
    | '/admin/settings/store'
    | '/admin/settings/taxes'
    | '/admin/settings/users'
    | '/admin/articles/'
    | '/admin/categories/'
    | '/admin/collections/'
    | '/admin/customers/'
    | '/admin/discounts/'
    | '/admin/inventory/'
    | '/admin/pages/'
    | '/admin/products/'
    | '/admin/settings/'
    | '/admin/articles/$articleId/edit'
    | '/admin/categories/$categoryId/edit'
    | '/admin/collections/$collectionId/edit'
    | '/admin/customers/$customerId/edit'
    | '/admin/online-store/navigation/$menuId'
    | '/admin/orders/$orderId/edit'
    | '/admin/orders/abandoned'
    | '/admin/pages/$pageId/edit'
    | '/admin/products/$productId/edit'
    | '/admin/settings/notifications/$event'
    | '/admin/settings/shipping/areas'
    | '/admin/settings/users/$userId'
    | '/admin/online-store/navigation/'
    | '/admin/orders/$orderId/'
    | '/admin/orders/'
    | '/admin/orders/abandoned/$checkoutId'
    | '/admin/settings/agent-access/authorize/$requestId'
    | '/admin/settings/agent-access/continue/$handoffId'
    | '/admin/settings/users/roles/$roleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/connect'
    | '/invoices'
    | '/scanner'
    | '/admin/access-denied'
    | '/admin/account'
    | '/admin/attributes'
    | '/admin/media'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/setup'
    | '/auth/setup-2fa'
    | '/auth/two-factor'
    | '/invoice/$orderId'
    | '/admin'
    | '/admin/articles/new'
    | '/admin/categories/new'
    | '/admin/collections/new'
    | '/admin/customers/new'
    | '/admin/discounts/$discountId'
    | '/admin/discounts/new'
    | '/admin/inventory/labels'
    | '/admin/online-store/banners'
    | '/admin/online-store/preferences'
    | '/admin/online-store/theme'
    | '/admin/orders/new'
    | '/admin/pages/new'
    | '/admin/products/new'
    | '/admin/settings/advanced'
    | '/admin/settings/apps'
    | '/admin/settings/checkout'
    | '/admin/settings/customer-accounts'
    | '/admin/settings/notifications'
    | '/admin/settings/payments'
    | '/admin/settings/policies'
    | '/admin/settings/shipping'
    | '/admin/settings/store'
    | '/admin/settings/taxes'
    | '/admin/settings/users'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/inventory'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/articles/$articleId/edit'
    | '/admin/categories/$categoryId/edit'
    | '/admin/collections/$collectionId/edit'
    | '/admin/customers/$customerId/edit'
    | '/admin/online-store/navigation/$menuId'
    | '/admin/orders/$orderId/edit'
    | '/admin/orders/abandoned'
    | '/admin/pages/$pageId/edit'
    | '/admin/products/$productId/edit'
    | '/admin/settings/notifications/$event'
    | '/admin/settings/shipping/areas'
    | '/admin/settings/users/$userId'
    | '/admin/online-store/navigation'
    | '/admin/orders/$orderId'
    | '/admin/orders'
    | '/admin/orders/abandoned/$checkoutId'
    | '/admin/settings/agent-access/authorize/$requestId'
    | '/admin/settings/agent-access/continue/$handoffId'
    | '/admin/settings/users/roles/$roleId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/connect'
    | '/invoices'
    | '/scanner'
    | '/admin/settings'
    | '/admin/access-denied'
    | '/admin/account'
    | '/admin/attributes'
    | '/admin/media'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/setup'
    | '/auth/setup-2fa'
    | '/auth/two-factor'
    | '/invoice/$orderId'
    | '/admin/'
    | '/admin/articles/new'
    | '/admin/categories/new'
    | '/admin/collections/new'
    | '/admin/customers/new'
    | '/admin/discounts/$discountId'
    | '/admin/discounts/new'
    | '/admin/inventory/labels'
    | '/admin/online-store/banners'
    | '/admin/online-store/preferences'
    | '/admin/online-store/theme'
    | '/admin/orders/_list'
    | '/admin/orders/new'
    | '/admin/pages/new'
    | '/admin/products/new'
    | '/admin/settings/advanced'
    | '/admin/settings/apps'
    | '/admin/settings/checkout'
    | '/admin/settings/customer-accounts'
    | '/admin/settings/notifications'
    | '/admin/settings/payments'
    | '/admin/settings/policies'
    | '/admin/settings/shipping'
    | '/admin/settings/store'
    | '/admin/settings/taxes'
    | '/admin/settings/users'
    | '/admin/articles/'
    | '/admin/categories/'
    | '/admin/collections/'
    | '/admin/customers/'
    | '/admin/discounts/'
    | '/admin/inventory/'
    | '/admin/pages/'
    | '/admin/products/'
    | '/admin/settings/'
    | '/admin/articles/$articleId/edit'
    | '/admin/categories/$categoryId/edit'
    | '/admin/collections/$collectionId/edit'
    | '/admin/customers/$customerId/edit'
    | '/admin/online-store/navigation/$menuId'
    | '/admin/orders/$orderId/edit'
    | '/admin/orders/_list/abandoned'
    | '/admin/pages/$pageId/edit'
    | '/admin/products/$productId/edit'
    | '/admin/settings/notifications_/$event'
    | '/admin/settings/shipping_/areas'
    | '/admin/settings/users_/$userId'
    | '/admin/online-store/navigation/'
    | '/admin/orders/$orderId/'
    | '/admin/orders/_list/'
    | '/admin/orders/_list/abandoned/$checkoutId'
    | '/admin/settings/agent-access/authorize/$requestId'
    | '/admin/settings/agent-access/continue/$handoffId'
    | '/admin/settings/users_/roles/$roleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  InvoicesRoute: typeof InvoicesRoute
  ScannerRoute: typeof ScannerRoute
  InvoiceOrderIdRoute: typeof InvoiceOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access-denied': {
      id: '/admin/access-denied'
      path: '/access-denied'
      fullPath: '/admin/access-denied'
      preLoaderRoute: typeof AdminAccessDeniedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attributes': {
      id: '/admin/attributes'
      path: '/attributes'
      fullPath: '/admin/attributes'
      preLoaderRoute: typeof AdminAttributesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/setup': {
      id: '/auth/setup'
      path: '/setup'
      fullPath: '/auth/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/setup-2fa': {
      id: '/auth/setup-2fa'
      path: '/setup-2fa'
      fullPath: '/auth/setup-2fa'
      preLoaderRoute: typeof AuthSetup2faRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/two-factor': {
      id: '/auth/two-factor'
      path: '/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/invoice/$orderId': {
      id: '/invoice/$orderId'
      path: '/invoice/$orderId'
      fullPath: '/invoice/$orderId'
      preLoaderRoute: typeof InvoiceOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/new': {
      id: '/admin/categories/new'
      path: '/categories/new'
      fullPath: '/admin/categories/new'
      preLoaderRoute: typeof AdminCategoriesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections/': {
      id: '/admin/collections/'
      path: '/collections'
      fullPath: '/admin/collections/'
      preLoaderRoute: typeof AdminCollectionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections/new': {
      id: '/admin/collections/new'
      path: '/collections/new'
      fullPath: '/admin/collections/new'
      preLoaderRoute: typeof AdminCollectionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/new': {
      id: '/admin/customers/new'
      path: '/customers/new'
      fullPath: '/admin/customers/new'
      preLoaderRoute: typeof AdminCustomersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/': {
      id: '/admin/discounts/'
      path: '/discounts'
      fullPath: '/admin/discounts/'
      preLoaderRoute: typeof AdminDiscountsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/$discountId': {
      id: '/admin/discounts/$discountId'
      path: '/discounts/$discountId'
      fullPath: '/admin/discounts/$discountId'
      preLoaderRoute: typeof AdminDiscountsDiscountIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/new': {
      id: '/admin/discounts/new'
      path: '/discounts/new'
      fullPath: '/admin/discounts/new'
      preLoaderRoute: typeof AdminDiscountsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory/': {
      id: '/admin/inventory/'
      path: '/inventory'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AdminInventoryIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory/labels': {
      id: '/admin/inventory/labels'
      path: '/inventory/labels'
      fullPath: '/admin/inventory/labels'
      preLoaderRoute: typeof AdminInventoryLabelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/online-store/banners': {
      id: '/admin/online-store/banners'
      path: '/online-store/banners'
      fullPath: '/admin/online-store/banners'
      preLoaderRoute: typeof AdminOnlineStoreBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/online-store/preferences': {
      id: '/admin/online-store/preferences'
      path: '/online-store/preferences'
      fullPath: '/admin/online-store/preferences'
      preLoaderRoute: typeof AdminOnlineStorePreferencesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/online-store/theme': {
      id: '/admin/online-store/theme'
      path: '/online-store/theme'
      fullPath: '/admin/online-store/theme'
      preLoaderRoute: typeof AdminOnlineStoreThemeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/_list': {
      id: '/admin/orders/_list'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersListRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/new': {
      id: '/admin/orders/new'
      path: '/orders/new'
      fullPath: '/admin/orders/new'
      preLoaderRoute: typeof AdminOrdersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/new': {
      id: '/admin/pages/new'
      path: '/pages/new'
      fullPath: '/admin/pages/new'
      preLoaderRoute: typeof AdminPagesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/advanced': {
      id: '/admin/settings/advanced'
      path: '/advanced'
      fullPath: '/admin/settings/advanced'
      preLoaderRoute: typeof AdminSettingsAdvancedRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/apps': {
      id: '/admin/settings/apps'
      path: '/apps'
      fullPath: '/admin/settings/apps'
      preLoaderRoute: typeof AdminSettingsAppsRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/checkout': {
      id: '/admin/settings/checkout'
      path: '/checkout'
      fullPath: '/admin/settings/checkout'
      preLoaderRoute: typeof AdminSettingsCheckoutRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/customer-accounts': {
      id: '/admin/settings/customer-accounts'
      path: '/customer-accounts'
      fullPath: '/admin/settings/customer-accounts'
      preLoaderRoute: typeof AdminSettingsCustomerAccountsRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/notifications': {
      id: '/admin/settings/notifications'
      path: '/notifications'
      fullPath: '/admin/settings/notifications'
      preLoaderRoute: typeof AdminSettingsNotificationsRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/payments': {
      id: '/admin/settings/payments'
      path: '/payments'
      fullPath: '/admin/settings/payments'
      preLoaderRoute: typeof AdminSettingsPaymentsRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/policies': {
      id: '/admin/settings/policies'
      path: '/policies'
      fullPath: '/admin/settings/policies'
      preLoaderRoute: typeof AdminSettingsPoliciesRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/shipping': {
      id: '/admin/settings/shipping'
      path: '/shipping'
      fullPath: '/admin/settings/shipping'
      preLoaderRoute: typeof AdminSettingsShippingRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/store': {
      id: '/admin/settings/store'
      path: '/store'
      fullPath: '/admin/settings/store'
      preLoaderRoute: typeof AdminSettingsStoreRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/taxes': {
      id: '/admin/settings/taxes'
      path: '/taxes'
      fullPath: '/admin/settings/taxes'
      preLoaderRoute: typeof AdminSettingsTaxesRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/users': {
      id: '/admin/settings/users'
      path: '/users'
      fullPath: '/admin/settings/users'
      preLoaderRoute: typeof AdminSettingsUsersRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/articles/$articleId/edit': {
      id: '/admin/articles/$articleId/edit'
      path: '/articles/$articleId/edit'
      fullPath: '/admin/articles/$articleId/edit'
      preLoaderRoute: typeof AdminArticlesArticleIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/$categoryId/edit': {
      id: '/admin/categories/$categoryId/edit'
      path: '/categories/$categoryId/edit'
      fullPath: '/admin/categories/$categoryId/edit'
      preLoaderRoute: typeof AdminCategoriesCategoryIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections/$collectionId/edit': {
      id: '/admin/collections/$collectionId/edit'
      path: '/collections/$collectionId/edit'
      fullPath: '/admin/collections/$collectionId/edit'
      preLoaderRoute: typeof AdminCollectionsCollectionIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$customerId/edit': {
      id: '/admin/customers/$customerId/edit'
      path: '/customers/$customerId/edit'
      fullPath: '/admin/customers/$customerId/edit'
      preLoaderRoute: typeof AdminCustomersCustomerIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/online-store/navigation/': {
      id: '/admin/online-store/navigation/'
      path: '/online-store/navigation'
      fullPath: '/admin/online-store/navigation/'
      preLoaderRoute: typeof AdminOnlineStoreNavigationIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/online-store/navigation/$menuId': {
      id: '/admin/online-store/navigation/$menuId'
      path: '/online-store/navigation/$menuId'
      fullPath: '/admin/online-store/navigation/$menuId'
      preLoaderRoute: typeof AdminOnlineStoreNavigationMenuIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$orderId/': {
      id: '/admin/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId/'
      preLoaderRoute: typeof AdminOrdersOrderIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$orderId/edit': {
      id: '/admin/orders/$orderId/edit'
      path: '/orders/$orderId/edit'
      fullPath: '/admin/orders/$orderId/edit'
      preLoaderRoute: typeof AdminOrdersOrderIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/_list/': {
      id: '/admin/orders/_list/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersListIndexRouteImport
      parentRoute: typeof AdminOrdersListRoute
    }
    '/admin/orders/_list/abandoned': {
      id: '/admin/orders/_list/abandoned'
      path: '/abandoned'
      fullPath: '/admin/orders/abandoned'
      preLoaderRoute: typeof AdminOrdersListAbandonedRouteImport
      parentRoute: typeof AdminOrdersListRoute
    }
    '/admin/pages/$pageId/edit': {
      id: '/admin/pages/$pageId/edit'
      path: '/pages/$pageId/edit'
      fullPath: '/admin/pages/$pageId/edit'
      preLoaderRoute: typeof AdminPagesPageIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$productId/edit': {
      id: '/admin/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/admin/products/$productId/edit'
      preLoaderRoute: typeof AdminProductsProductIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/notifications_/$event': {
      id: '/admin/settings/notifications_/$event'
      path: '/notifications/$event'
      fullPath: '/admin/settings/notifications/$event'
      preLoaderRoute: typeof AdminSettingsNotificationsEventRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/shipping_/areas': {
      id: '/admin/settings/shipping_/areas'
      path: '/shipping/areas'
      fullPath: '/admin/settings/shipping/areas'
      preLoaderRoute: typeof AdminSettingsShippingAreasRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/users_/$userId': {
      id: '/admin/settings/users_/$userId'
      path: '/users/$userId'
      fullPath: '/admin/settings/users/$userId'
      preLoaderRoute: typeof AdminSettingsUsersUserIdRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/orders/_list/abandoned/$checkoutId': {
      id: '/admin/orders/_list/abandoned/$checkoutId'
      path: '/$checkoutId'
      fullPath: '/admin/orders/abandoned/$checkoutId'
      preLoaderRoute: typeof AdminOrdersListAbandonedCheckoutIdRouteImport
      parentRoute: typeof AdminOrdersListAbandonedRoute
    }
    '/admin/settings/agent-access/authorize/$requestId': {
      id: '/admin/settings/agent-access/authorize/$requestId'
      path: '/agent-access/authorize/$requestId'
      fullPath: '/admin/settings/agent-access/authorize/$requestId'
      preLoaderRoute: typeof AdminSettingsAgentAccessAuthorizeRequestIdRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/agent-access/continue/$handoffId': {
      id: '/admin/settings/agent-access/continue/$handoffId'
      path: '/agent-access/continue/$handoffId'
      fullPath: '/admin/settings/agent-access/continue/$handoffId'
      preLoaderRoute: typeof AdminSettingsAgentAccessContinueHandoffIdRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/users_/roles/$roleId': {
      id: '/admin/settings/users_/roles/$roleId'
      path: '/users/roles/$roleId'
      fullPath: '/admin/settings/users/roles/$roleId'
      preLoaderRoute: typeof AdminSettingsUsersRolesRoleIdRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
  }
}

interface AdminSettingsRouteRouteChildren {
  AdminSettingsAdvancedRoute: typeof AdminSettingsAdvancedRoute
  AdminSettingsAppsRoute: typeof AdminSettingsAppsRoute
  AdminSettingsCheckoutRoute: typeof AdminSettingsCheckoutRoute
  AdminSettingsCustomerAccountsRoute: typeof AdminSettingsCustomerAccountsRoute
  AdminSettingsNotificationsRoute: typeof AdminSettingsNotificationsRoute
  AdminSettingsPaymentsRoute: typeof AdminSettingsPaymentsRoute
  AdminSettingsPoliciesRoute: typeof AdminSettingsPoliciesRoute
  AdminSettingsShippingRoute: typeof AdminSettingsShippingRoute
  AdminSettingsStoreRoute: typeof AdminSettingsStoreRoute
  AdminSettingsTaxesRoute: typeof AdminSettingsTaxesRoute
  AdminSettingsUsersRoute: typeof AdminSettingsUsersRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminSettingsNotificationsEventRoute: typeof AdminSettingsNotificationsEventRoute
  AdminSettingsShippingAreasRoute: typeof AdminSettingsShippingAreasRoute
  AdminSettingsUsersUserIdRoute: typeof AdminSettingsUsersUserIdRoute
  AdminSettingsAgentAccessAuthorizeRequestIdRoute: typeof AdminSettingsAgentAccessAuthorizeRequestIdRoute
  AdminSettingsAgentAccessContinueHandoffIdRoute: typeof AdminSettingsAgentAccessContinueHandoffIdRoute
  AdminSettingsUsersRolesRoleIdRoute: typeof AdminSettingsUsersRolesRoleIdRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsAdvancedRoute: AdminSettingsAdvancedRoute,
  AdminSettingsAppsRoute: AdminSettingsAppsRoute,
  AdminSettingsCheckoutRoute: AdminSettingsCheckoutRoute,
  AdminSettingsCustomerAccountsRoute: AdminSettingsCustomerAccountsRoute,
  AdminSettingsNotificationsRoute: AdminSettingsNotificationsRoute,
  AdminSettingsPaymentsRoute: AdminSettingsPaymentsRoute,
  AdminSettingsPoliciesRoute: AdminSettingsPoliciesRoute,
  AdminSettingsShippingRoute: AdminSettingsShippingRoute,
  AdminSettingsStoreRoute: AdminSettingsStoreRoute,
  AdminSettingsTaxesRoute: AdminSettingsTaxesRoute,
  AdminSettingsUsersRoute: AdminSettingsUsersRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminSettingsNotificationsEventRoute: AdminSettingsNotificationsEventRoute,
  AdminSettingsShippingAreasRoute: AdminSettingsShippingAreasRoute,
  AdminSettingsUsersUserIdRoute: AdminSettingsUsersUserIdRoute,
  AdminSettingsAgentAccessAuthorizeRequestIdRoute:
    AdminSettingsAgentAccessAuthorizeRequestIdRoute,
  AdminSettingsAgentAccessContinueHandoffIdRoute:
    AdminSettingsAgentAccessContinueHandoffIdRoute,
  AdminSettingsUsersRolesRoleIdRoute: AdminSettingsUsersRolesRoleIdRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminOrdersListAbandonedRouteChildren {
  AdminOrdersListAbandonedCheckoutIdRoute: typeof AdminOrdersListAbandonedCheckoutIdRoute
}

const AdminOrdersListAbandonedRouteChildren: AdminOrdersListAbandonedRouteChildren =
  {
    AdminOrdersListAbandonedCheckoutIdRoute:
      AdminOrdersListAbandonedCheckoutIdRoute,
  }

const AdminOrdersListAbandonedRouteWithChildren =
  AdminOrdersListAbandonedRoute._addFileChildren(
    AdminOrdersListAbandonedRouteChildren,
  )

interface AdminOrdersListRouteChildren {
  AdminOrdersListAbandonedRoute: typeof AdminOrdersListAbandonedRouteWithChildren
  AdminOrdersListIndexRoute: typeof AdminOrdersListIndexRoute
}

const AdminOrdersListRouteChildren: AdminOrdersListRouteChildren = {
  AdminOrdersListAbandonedRoute: AdminOrdersListAbandonedRouteWithChildren,
  AdminOrdersListIndexRoute: AdminOrdersListIndexRoute,
}

const AdminOrdersListRouteWithChildren = AdminOrdersListRoute._addFileChildren(
  AdminOrdersListRouteChildren,
)

interface AdminRouteChildren {
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminAccessDeniedRoute: typeof AdminAccessDeniedRoute
  AdminAccountRoute: typeof AdminAccountRoute
  AdminAttributesRoute: typeof AdminAttributesRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminCategoriesNewRoute: typeof AdminCategoriesNewRoute
  AdminCollectionsNewRoute: typeof AdminCollectionsNewRoute
  AdminCustomersNewRoute: typeof AdminCustomersNewRoute
  AdminDiscountsDiscountIdRoute: typeof AdminDiscountsDiscountIdRoute
  AdminDiscountsNewRoute: typeof AdminDiscountsNewRoute
  AdminInventoryLabelsRoute: typeof AdminInventoryLabelsRoute
  AdminOnlineStoreBannersRoute: typeof AdminOnlineStoreBannersRoute
  AdminOnlineStorePreferencesRoute: typeof AdminOnlineStorePreferencesRoute
  AdminOnlineStoreThemeRoute: typeof AdminOnlineStoreThemeRoute
  AdminOrdersListRoute: typeof AdminOrdersListRouteWithChildren
  AdminOrdersNewRoute: typeof AdminOrdersNewRoute
  AdminPagesNewRoute: typeof AdminPagesNewRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminCollectionsIndexRoute: typeof AdminCollectionsIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminDiscountsIndexRoute: typeof AdminDiscountsIndexRoute
  AdminInventoryIndexRoute: typeof AdminInventoryIndexRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminArticlesArticleIdEditRoute: typeof AdminArticlesArticleIdEditRoute
  AdminCategoriesCategoryIdEditRoute: typeof AdminCategoriesCategoryIdEditRoute
  AdminCollectionsCollectionIdEditRoute: typeof AdminCollectionsCollectionIdEditRoute
  AdminCustomersCustomerIdEditRoute: typeof AdminCustomersCustomerIdEditRoute
  AdminOnlineStoreNavigationMenuIdRoute: typeof AdminOnlineStoreNavigationMenuIdRoute
  AdminOrdersOrderIdEditRoute: typeof AdminOrdersOrderIdEditRoute
  AdminPagesPageIdEditRoute: typeof AdminPagesPageIdEditRoute
  AdminProductsProductIdEditRoute: typeof AdminProductsProductIdEditRoute
  AdminOnlineStoreNavigationIndexRoute: typeof AdminOnlineStoreNavigationIndexRoute
  AdminOrdersOrderIdIndexRoute: typeof AdminOrdersOrderIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminAccessDeniedRoute: AdminAccessDeniedRoute,
  AdminAccountRoute: AdminAccountRoute,
  AdminAttributesRoute: AdminAttributesRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminCategoriesNewRoute: AdminCategoriesNewRoute,
  AdminCollectionsNewRoute: AdminCollectionsNewRoute,
  AdminCustomersNewRoute: AdminCustomersNewRoute,
  AdminDiscountsDiscountIdRoute: AdminDiscountsDiscountIdRoute,
  AdminDiscountsNewRoute: AdminDiscountsNewRoute,
  AdminInventoryLabelsRoute: AdminInventoryLabelsRoute,
  AdminOnlineStoreBannersRoute: AdminOnlineStoreBannersRoute,
  AdminOnlineStorePreferencesRoute: AdminOnlineStorePreferencesRoute,
  AdminOnlineStoreThemeRoute: AdminOnlineStoreThemeRoute,
  AdminOrdersListRoute: AdminOrdersListRouteWithChildren,
  AdminOrdersNewRoute: AdminOrdersNewRoute,
  AdminPagesNewRoute: AdminPagesNewRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminCollectionsIndexRoute: AdminCollectionsIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminDiscountsIndexRoute: AdminDiscountsIndexRoute,
  AdminInventoryIndexRoute: AdminInventoryIndexRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminArticlesArticleIdEditRoute: AdminArticlesArticleIdEditRoute,
  AdminCategoriesCategoryIdEditRoute: AdminCategoriesCategoryIdEditRoute,
  AdminCollectionsCollectionIdEditRoute: AdminCollectionsCollectionIdEditRoute,
  AdminCustomersCustomerIdEditRoute: AdminCustomersCustomerIdEditRoute,
  AdminOnlineStoreNavigationMenuIdRoute: AdminOnlineStoreNavigationMenuIdRoute,
  AdminOrdersOrderIdEditRoute: AdminOrdersOrderIdEditRoute,
  AdminPagesPageIdEditRoute: AdminPagesPageIdEditRoute,
  AdminProductsProductIdEditRoute: AdminProductsProductIdEditRoute,
  AdminOnlineStoreNavigationIndexRoute: AdminOnlineStoreNavigationIndexRoute,
  AdminOrdersOrderIdIndexRoute: AdminOrdersOrderIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetupRoute: typeof AuthSetupRoute
  AuthSetup2faRoute: typeof AuthSetup2faRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetupRoute: AuthSetupRoute,
  AuthSetup2faRoute: AuthSetup2faRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ConnectRoute: ConnectRoute,
  InvoicesRoute: InvoicesRoute,
  ScannerRoute: ScannerRoute,
  InvoiceOrderIdRoute: InvoiceOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
