import { createFileRoute } from "@tanstack/react-router";

interface CloudflareWorkerEnv {
  API?: { fetch: (url: string) => Promise<Response> };
  PUBLIC_API_BASE_URL?: string;
}

export const Route = createFileRoute("/firebase-messaging-sw.js")({
  server: {
    handlers: {
      GET: async () => {
        // 1. Fetch Firebase config from API using service binding or HTTP
        let publicConfig: Record<string, string> = {};
        try {
          const { env } = await import("cloudflare:workers");
          const cfEnv = env as CloudflareWorkerEnv;
          let response: Response;
          if (cfEnv?.API) {
            response = await cfEnv.API.fetch(
              new URL("/api/v1/auth/firebase-config", "http://api.internal").toString(),
            );
          } else {
            const apiBase = cfEnv?.PUBLIC_API_BASE_URL || "http://localhost:8787";
            response = await fetch(
              new URL("/api/v1/auth/firebase-config", apiBase).toString(),
            );
          }
          if (response.ok) {
            const body = (await response.json()) as { data?: Record<string, string> };
            publicConfig = body?.data || {};
          }
        } catch (e: unknown) {
          console.error("Error reading Firebase config from API for SW:", e);
        }

        // 2. If config unavailable, return no-op service worker
        if (!publicConfig.apiKey) {
          const noopScript = `// Firebase Cloud Messaging Service Worker — config unavailable
console.warn("[firebase-messaging-sw.js] Firebase config not available from API. Push notifications disabled.");
`;
          return new Response(noopScript, {
            status: 200,
            headers: {
              "Content-Type": "application/javascript",
              "Cache-Control": "no-cache, no-store, must-revalidate",
            },
          });
        }

        // 3. Construct the script
        const scriptContent = `// Firebase Cloud Messaging Service Worker
// Dynamically generated by /firebase-messaging-sw.js server route

importScripts("https://www.gstatic.com/firebasejs/9.15.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/9.15.0/firebase-messaging-compat.js");

const firebaseConfig = ${JSON.stringify(publicConfig, null, 2)};

firebase.initializeApp(firebaseConfig);

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  console.log("[firebase-messaging-sw.js] Received background message", payload);

  const notificationTitle = payload.data?.customerName
    ? \`\${payload.data.customerName} placed a new order\`
    : payload.notification?.title || "New Order Received";

  const notificationOptions = {
    body: payload.data?.orderId
      ? \`Order ID: \${payload.data.orderId}. Click to view.\`
      : payload.notification?.body || "A new order has been placed on your store.",
    icon: "/favicon.svg",
    badge: "/favicon.svg",
    tag: "order-notification",
    requireInteraction: true,
    data: {
      url: payload.data?.link || "/admin/orders",
    },
  };

  self.registration.showNotification(notificationTitle, notificationOptions);
});

self.addEventListener("notificationclick", (event) => {
  console.log("[firebase-messaging-sw.js] Notification click received.");
  event.notification.close();

  const urlToOpen = event.notification.data?.url || "/admin/orders";

  event.waitUntil(
    clients
      .matchAll({
        type: "window",
        includeUncontrolled: true,
      })
      .then((clientList) => {
        for (const client of clientList) {
          if (client.url.includes("/admin") && "focus" in client) {
            return client.focus();
          }
        }
        if (clients.openWindow) {
          return clients.openWindow(urlToOpen);
        }
      }),
  );
});
`;

        return new Response(scriptContent, {
          status: 200,
          headers: {
            "Content-Type": "application/javascript",
            "Cache-Control": "no-cache, no-store, must-revalidate",
          },
        });
      },
    },
  },
});
